### ISSUE TITLE
Win32 Build-Test CMAKE_HAVE_LIBC_PTHREAD" failed

### ISSUE THREAD

**Issue by john0909** [ggerganov/whisper.cpp#101]
![image](https://user-images.githubusercontent.com/7496823/198210907-2b78c15e-4805-47dd-b4d5-894cf7b8e705.png)

**Comment by CHERTS** [comment]
it's okey, library pthreads no needed for Windows, in file ggml.c used native implementation threads and atomic functions

**Comment by ggerganov** [comment]
I am not able to maintain the Windows build because I don't have the OS. I recommend trying out WSL if problems persist.
Will close the issue now in favor of #5
