### ISSUE TITLE
Stream Application is missing

### ISSUE THREAD

**Issue by kojomensahonums** [ggerganov/whisper.cpp#1040]
I am trying to perform real-time transcription but can't find the stream application in the zip files after downloading. I am running on Windows and so far the only thing that has worked for me is using the main, bench and quantize commands directly (from the examples list). All the other features seem to be gone and I can't get a way to work.

This is all the files I get after unzipping the downloaded files. How do I get the others? What can I do to make the applications work on Windows?

![image](https://github.com/ggerganov/whisper.cpp/assets/92085084/d5e1517b-d872-43dc-9b95-46fac27829c0)

**Comment by Oheed911** [comment]
yes same issue, can anyone help?

**Comment by Oheed911** [comment]
Yes, I was using mingw for code compilation on windows, if you want the stream code to run on the windows, you need to install this library before "make stream" command:
`pacman -S mingw-w64-x86_64-SDL2`

**Comment by kojomensahonums** [comment]
I am still having a lot of issues after installing mingw and sdl. I get this error in the terminal when I run the make stream command. I probably am doing something wrong.

![image](https://github.com/ggerganov/whisper.cpp/assets/92085084/c34d7715-e47f-4685-9455-eff157eb5aa0)

**Comment by kojomensahonums** [comment]
Got it working with wsl. Issue resolved
