### ISSUE TITLE
Some Error，No module named 'torch'

### ISSUE THREAD

**Issue by xclidongbo** [ggerganov/whisper.cpp#1044]
❯ ./models/generate-coreml-model.sh base.en
Traceback (most recent call last):
  File "/Users/lidongbo/WorkBentch/Git/whisper.cpp/models/convert-whisper-to-coreml.py", line 2, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
coremlc: error: Model does not exist at models/coreml-encoder-base.en.mlpackage -- file:///Users/lidongbo/WorkBentch/Git/whisper.cpp/
mv: cannot stat 'models/coreml-encoder-base.en.mlmodelc': No such file or directory

**Comment by togume** [comment]
@xclidongbo I have the same issue. Were you able to resolve it? How?

**Comment by XZF0** [comment]
@togume : 
generate-coreml-model.sh invokes python as 'python3' (old habits, I imagine), which on my box bypasses the conda env and resolves to python 3.11, not the intended 3.10; and produces the ModuleNotFoundError.
Editing `python3` --> `python` allows the script to proceed.
