### ISSUE TITLE
whisper : add Metal support in the Decoder

### ISSUE THREAD

**Issue by ggerganov** [ggerganov/whisper.cpp#1047]
GPU inference on Apple Silicon via Metal backend was recently added to `llama.cpp`: https://github.com/ggerganov/llama.cpp/pull/1642

We should port the changes to `whisper.cpp` and allow the Decoder to run on the GPU in a similar way

**Comment by ggerganov** [comment]
Done via #whisper #1270

**Comment by aehlke** [comment]
What are the instructions for running this (Metal, or Metal + non-ANE OpenML)? Sorry, couldn't figure out from the changes whether the most performant config is now the default or how to configure it to run with this new addition. Thanks.
