### ISSUE TITLE
Compile in Vietnamese language error

### ISSUE THREAD

**Issue by nltoan** [ggerganov/whisper.cpp#1051]
Why do I compile in Vietnamese language, the text after compiling it keeps adding the following code: " Hãy subscribe cho kênh Ghiền Mì Gõ Để không bỏ  lỡ những video hấp dẫn"

<img width="702" alt="image" src="https://github.com/ggerganov/whisper.cpp/assets/42729172/54c558e8-605f-4642-a95f-e39fe8018b9e">
<img width="526" alt="image" src="https://github.com/ggerganov/whisper.cpp/assets/42729172/0b3026ce-87d2-4cc3-97a8-ca3c83bcc827">

**Comment by bobqianic** [comment]
If you notice this issue at the end of the audio, it's probably because of the model's `hallucination`. Try using the `-pc` option, and you'll see that the probability scores for these words are quite low, indicated in red.
