### ISSUE TITLE
compile error under centos system

### ISSUE THREAD

**Issue by stoneLee81** [ggerganov/whisper.cpp#1052]
centosversion: CentOS Linux release 7.6.1810

use git clone to get the latest source from master, unzip it and run make command to compile, the error occurs as below:

I whisper.cpp build info:
I UNAME_S:  Linux
I UNAME_P:  x86_64
I UNAME_M:  x86_64
I CFLAGS:   -I.              -O3 -DNDEBUG -std=c11   -fPIC -D_XOPEN_SOURCE=600 -pthread -mavx2 -mfma -mf16c -mavx -msse3
I CXXFLAGS: -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -D_XOPEN_SOURCE=600 -pthread
I LDFLAGS:
I CC:       cc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
I CXX:      g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)

cc  -I.              -O3 -DNDEBUG -std=c11   -fPIC -D_XOPEN_SOURCE=600 -pthread -mavx2 -mfma -mf16c -mavx -msse3   -c ggml.c -o ggml.o
ggml.c:90:23: fatal error: stdatomic.h: No such file or directory
 #include <stdatomic.h>
                       ^
compilation terminated.

**Comment by zengyipuBaidu** [comment]
I also meet this problem. could you tell me hou you resolve it? Thank you very much!

**Comment by htranxp** [comment]
@stoneLee81 how did you solved this?
