### ISSUE TITLE
CUDA error 209, no kernel image is available for execution on the device error

### ISSUE THREAD

**Issue by stoneLee81** [ggerganov/whisper.cpp#1068]
gpu-arch
> [root@VM-1-11-centos ~]# nvcc --list-gpu-arch
compute_35
compute_37
compute_50
compute_52
compute_53
compute_60
compute_61
compute_62
compute_70
compute_72
compute_75
compute_80
compute_86

cuda version info 
> [root@VM-1-11-centos ~]# nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Feb_14_21:12:58_PST_2021
Cuda compilation tools, release 11.2, V11.2.152
Build cuda_11.2.r11.2/compiler.29618528_0

> [root@VM-1-11-centos ~]# nvidia-smi
Fri Jun 30 17:44:55 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.106.00   Driver Version: 460.106.00   CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:00:08.0 Off |                    0 |
| N/A   31C    P0    27W /  70W |    272MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     53141      C   ./main                            269MiB |
+-----------------------------------------------------------------------------+

I changed -arch = any to -arch=compute_86 in Makefile file, and run 
make clean 
WHISPER_CUBLAS=1 make -j
to compile main file, when successd, I run below cmd, and error occurs '**when running main cmd to test output.wav file, throws CUDA error 209** 

[root@VM-1-11-centos whisper.cpp-master]# ./main -m models/ggml-medium.bin -f output.wav
whisper_init_from_file_no_state: loading model from 'models/ggml-medium.bin'
whisper_model_load: loading model
whisper_model_load: n_vocab       = 51865
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 1024
whisper_model_load: n_audio_head  = 16
whisper_model_load: n_audio_layer = 24
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 1024
whisper_model_load: n_text_head   = 16
whisper_model_load: n_text_layer  = 24
whisper_model_load: n_mels        = 80
whisper_model_load: ftype         = 1
whisper_model_load: qntvr         = 0
whisper_model_load: type          = 4
whisper_model_load: mem required  = 1899.00 MB (+   43.00 MB per decoder)
whisper_model_load: adding 1608 extra tokens
whisper_model_load: model ctx     = 1462.58 MB
ggml_init_cublas: found 1 CUDA devices:
  Device 0: Tesla T4
whisper_model_load: model size    = 1462.12 MB
whisper_init_state: kv self size  =   42.00 MB
whisper_init_state: kv cross size =  140.62 MB

system_info: n_threads = 4 / 8 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 | COREML = 0 |

main: processing 'output.wav' (1062400 samples, 66.4 sec), 4 threads, 1 processors, lang = en, task = transcribe, timestamps = 1 ...

CUDA error 209 at ggml-cuda.cu:2221: no kernel image is available for execution on the device

**Comment by Azeirah** [comment]
Means the architecture you specified in `-arch=...` is not the correct one for your GPU.

In my case, I have a 1080 TI and I had to specify `-arch=compute_61`.

You can look up your GPU on this website, like I did. Works fine after.

https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/
