### ISSUE TITLE
[Feature Request] Model loading over HTTPS

### ISSUE THREAD

**Issue by erkkimon** [ggerganov/whisper.cpp#109]
I think it is not technically necessary to download the model and load it from the local disk. Could there be an option to hardcode and/or enter URL for model file?

**Comment by ggerganov** [comment]
Yes, it is possible.

By the way, I saw your other comment about Firefox being x5 faster compared to Chrome.
I just tried it and I observe similar performance on M1 Pro between the 2 browsers.

For example, it takes around 7.7 seconds to process `jfk.wav` with `base.en` with both browsers:

<img width="833" alt="image" src="https://user-images.githubusercontent.com/1991296/198707226-00254828-35a5-4af6-b9ca-018588371119.png">

- Chrome: Version 106.0.5249.119 (Official Build) (arm64)
- Firefox: 106.0.2 (64-bit)
