### ISSUE TITLE
CMake: OpenBLAS not detected

### ISSUE THREAD

**Issue by nico202** [ggerganov/whisper.cpp#1094]
Hi, I was having problem with openblas not being detected in whisper but it was getting detected in llama.cpp.

Seems my problem was with BLA_SIZEOF_INTEGER, which on llama is [conditional](https://github.com/ggerganov/llama.cpp/blob/1d1630996920f889cdc08de26cebf2415958540e/CMakeLists.txt#L163)  while on whisper it is [not](https://github.com/ggerganov/whisper.cpp/blob/4774d2feb01a772a15de81ffc34b34a1f294f020/CMakeLists.txt#L142).  Removing it started detecting openblas, should we add the same check here?

**Comment by bobqianic** [comment]
Use 64-bit version of `openblas` should solve this problem. `apt search openblas64`
