### ISSUE TITLE
ggml.c CACHE_LINE_SIZE error: initializer element is not constant

### ISSUE THREAD

**Issue by biemster** [ggerganov/whisper.cpp#11]
I get this on Ubuntu 18.04 gcc 7.5.0 (time to update, yes), and I don't immediately see how to fix it since I don't know `__cpp_lib_hardware_interference_size`. Otherwise a simple replacement with a `#define` would suffice.
```
gcc -pthread -O3 -mavx -mavx2 -mfma -mf16c -c ggml.c
ggml.c:183:36: error: initializer element is not constant
 const size_t CACHE_LINE_SIZE_F32 = CACHE_LINE_SIZE/sizeof(float);
```

**Comment by biemster** [comment]
Also a few
```
main.cpp:1349:62: sorry, unimplemented: non-trivial designated initializers not supported
             struct ggml_cgraph gf = { .n_threads = n_threads };
```
so it is really time to update. You can close this if you choose not to support old compilers (although to my defense this is not THAT old..)

**Comment by biemster** [comment]
Hold on, I'm being to quick here. The initial issue can actually be solved by replacing the `const size_t` with a `#define`.

**Comment by ggerganov** [comment]
Regarding `CACHE_LINE_SIZE` - we need this to be at least as big as the L1 cache line size to avoid false sharing between threads during computation. I don't see why gcc 7.5.0 thinks this is not constant, but I'm okay to replace it with `#define` if that solves the issue.

Regarding the designated initializers in the `.cpp` - just replace it with:

```c++
struct ggml_cgraph gf; gf.n_threads = n_threads;
```

Feel free to submit a PR with these changes and I will be happy to apply them

**Comment by biemster** [comment]
Thanks! That works.
