### ISSUE TITLE
How can I optimize the models?

### ISSUE THREAD

**Issue by GersomR-afk** [ggerganov/whisper.cpp#1103]
I'm sorry if this has been asked already, if that's the case please link me to that issue.
I'm in the process of implementing the project in my mobile application. Everything works as expected, but the model size too large. I can't ship a ~150MB model with my application. I'm getting bad results with the ``ggml-tiny`` model with non-English audio. I'd prefer to do audio transcriptions client-side, so I'm wondering how can I optimize the model's size. I'm not too keen on AI, so any help would be appreciated!

**Comment by mkiol** [comment]
To make models just smaller you might quantize them doing [this](https://github.com/ggerganov/whisper.cpp#quantization). The sizes after q5_0 quantization for instance are as follows:

```
ggml-large-q5_0.bin: 1.08 GB
ggml-medium-q5_0.bin: 587 MB
ggml-small-q5_0.bin: 190 MB
ggml-base-q5_0.bin: 59.7 MB
ggml-tiny-q5_0.bin: 32.2 MB
```

BTW, If you don't want to play with models conversions, here is [my repo](https://huggingface.co/mukowaty/ggml-whisper/tree/main/multilang) with already converted multi-lang models.

**Comment by GersomR-afk** [comment]
Thank you very much, this reduces the model size significantly. I'm sorry I didn't read the README correctly, I must have looked over it.

**Comment by mkiol** [comment]
Glad I could help :)
