### ISSUE TITLE
./models/generate-coreml-model.sh large time to convert??

### ISSUE THREAD

**Issue by dubefab** [ggerganov/whisper.cpp#1119]
I am trying to get the CoreML functionality but it's been running for 2-3h with ANECompilerService at 99.9% of my cpu.
Macbook pro M1 base model.
<img width="953" alt="image" src="https://github.com/ggerganov/whisper.cpp/assets/36094769/57db8501-f907-4561-bc9b-f48773cc37f8">

Should I just let it run or something is obviously wrong??

**Comment by mrfragger** [comment]
medium.en takes over 5 hours so yea gonna be quite some time till it starts processing wav / transcribing.  If your screen locks, then the entire process is paused so you could be waiting days.  On a macbook to prevent sleeping do from terminal `sudo pmset -a disablesleep 1` this way you can keep your lid closed.  To revert back `sudo pmset -a disablesleep 0`.  Although initially I would just keep it open for the initial run for each model.

**Comment by dubefab** [comment]
It ended up working but it has errors... seems like it did not create the folder, all I have is a 1.27GB coreml-encoder-large.mlpackage file.
I'm thinking maybe I made a mistake and typed something like control-c at some point and it caused it? I see a ^[[C .

Here is the output:

(py310-whisper) fab@Flying whisper.cpp %./models/generate-coreml-model.sh large     
/opt/homebrew/anaconda3/envs/py310-whisper/lib/python3.10/site-packages/whisper/timing.py:58: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def backtrace(trace: np.ndarray):
ModelDimensions(n_mels=80, n_audio_ctx=1500, n_audio_state=1280, n_audio_head=20, n_audio_layer=32, n_vocab=51865, n_text_ctx=448, n_text_state=1280, n_text_head=20, n_text_layer=32)
/opt/homebrew/anaconda3/envs/py310-whisper/lib/python3.10/site-packages/whisper/model.py:166: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert x.shape[1:] == self.positional_embedding.shape, "incorrect audio shape"
/opt/homebrew/anaconda3/envs/py310-whisper/lib/python3.10/site-packages/whisper/model.py:97: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  scale = (n_state // self.n_head) ** -0.25
Converting PyTorch Frontend ==> MIL Ops: 100%|██████████████████▉| 2611/2612 [00:00<00:00, 3250.55 ops/s]
Running MIL frontend_pytorch pipeline: 100%|██████████████████████████| 5/5 [00:00<00:00, 32.27 passes/s]
Running MIL default pipeline: 100%|█████████████████████████████████| 57/57 [00:14<00:00,  4.05 passes/s]
Running MIL backend_mlprogram pipeline: 100%|██████████████████████| 10/10 [00:00<00:00, 325.89 passes/s]
^[[C

done converting
xcrun: error: unable to find utility "coremlc", not a developer tool or in PATH
mv: rename models/coreml-encoder-large.mlmodelc to models/ggml-large-encoder.mlmodelc: No such file or directory
(py310-whisper) fab@Flying whisper.cpp %
(py310-whisper) fab@Flying whisper.cpp %
(py310-whisper) fab@Flying whisper.cpp %make clean
WHISPER_COREML=1 make -j
I whisper.cpp build info: 
I UNAME_S:  Darwin
I UNAME_P:  arm
I UNAME_M:  arm64
I CFLAGS:   -I.              -O3 -DNDEBUG -std=c11   -fPIC -D_DARWIN_C_SOURCE -pthread -DGGML_USE_ACCELERATE
I CXXFLAGS: -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -D_DARWIN_C_SOURCE -pthread
I LDFLAGS:   -framework Accelerate
I CC:       Apple clang version 14.0.3 (clang-1403.0.22.14.1)
I CXX:      Apple clang version 14.0.3 (clang-1403.0.22.14.1)

rm -f *.o main stream command talk talk-llama bench quantize libwhisper.a libwhisper.so
I whisper.cpp build info: 
I UNAME_S:  Darwin
I UNAME_P:  arm
I UNAME_M:  arm64
I CFLAGS:   -I.              -O3 -DNDEBUG -std=c11   -fPIC -D_DARWIN_C_SOURCE -pthread -DGGML_USE_ACCELERATE
I CXXFLAGS: -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -D_DARWIN_C_SOURCE -pthread -DWHISPER_USE_COREML
I LDFLAGS:   -framework Accelerate -framework Foundation -framework CoreML
I CC:       Apple clang version 14.0.3 (clang-1403.0.22.14.1)
I CXX:      Apple clang version 14.0.3 (clang-1403.0.22.14.1)

cc  -I.              -O3 -DNDEBUG -std=c11   -fPIC -D_DARWIN_C_SOURCE -pthread -DGGML_USE_ACCELERATE   -c ggml.c -o ggml.o
c++ -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -D_DARWIN_C_SOURCE -pthread -DWHISPER_USE_COREML -c whisper.cpp -o whisper.o
c++ -O3 -I . -fobjc-arc -c coreml/whisper-encoder.mm -o whisper-encoder.o
c++ -O3 -I . -fobjc-arc -c coreml/whisper-encoder-impl.m -o whisper-encoder-impl.o
c++ -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -D_DARWIN_C_SOURCE -pthread -DWHISPER_USE_COREML examples/main/main.cpp examples/common.cpp examples/common-ggml.cpp ggml.o whisper.o whisper-encoder.o whisper-encoder-impl.o -o main  -framework Accelerate -framework Foundation -framework CoreML
c++ -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -D_DARWIN_C_SOURCE -pthread -DWHISPER_USE_COREML examples/bench/bench.cpp ggml.o whisper.o whisper-encoder.o whisper-encoder-impl.o -o bench  -framework Accelerate -framework Foundation -framework CoreML
c++ -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -D_DARWIN_C_SOURCE -pthread -DWHISPER_USE_COREML examples/quantize/quantize.cpp examples/common.cpp examples/common-ggml.cpp ggml.o whisper.o whisper-encoder.o whisper-encoder-impl.o -o quantize  -framework Accelerate -framework Foundation -framework CoreML
./main -h

usage: ./main [options] file0.wav file1.wav ...

options:
  -h,        --help              [default] show this help message and exit
  -t N,      --threads N         [4      ] number of threads to use during computation
  -p N,      --processors N      [1      ] number of processors to use during computation
  -ot N,     --offset-t N        [0      ] time offset in milliseconds
  -on N,     --offset-n N        [0      ] segment index offset
  -d  N,     --duration N        [0      ] duration of audio to process in milliseconds
  -mc N,     --max-context N     [-1     ] maximum number of text context tokens to store
  -ml N,     --max-len N         [0      ] maximum segment length in characters
  -sow,      --split-on-word     [false  ] split on word rather than on token
  -bo N,     --best-of N         [2      ] number of best candidates to keep
  -bs N,     --beam-size N       [-1     ] beam size for beam search
  -wt N,     --word-thold N      [0.01   ] word timestamp probability threshold
  -et N,     --entropy-thold N   [2.40   ] entropy threshold for decoder fail
  -lpt N,    --logprob-thold N   [-1.00  ] log probability threshold for decoder fail
  -su,       --speed-up          [false  ] speed up audio by x2 (reduced accuracy)
  -tr,       --translate         [false  ] translate from source language to english
  -di,       --diarize           [false  ] stereo audio diarization
  -tdrz,     --tinydiarize       [false  ] enable tinydiarize (requires a tdrz model)
  -nf,       --no-fallback       [false  ] do not use temperature fallback while decoding
  -otxt,     --output-txt        [false  ] output result in a text file
  -ovtt,     --output-vtt        [false  ] output result in a vtt file
  -osrt,     --output-srt        [false  ] output result in a srt file
  -olrc,     --output-lrc        [false  ] output result in a lrc file
  -owts,     --output-words      [false  ] output script for generating karaoke video
  -fp,       --font-path         [/System/Library/Fonts/Supplemental/Courier New Bold.ttf] path to a monospace font for karaoke video
  -ocsv,     --output-csv        [false  ] output result in a CSV file
  -oj,       --output-json       [false  ] output result in a JSON file
  -of FNAME, --output-file FNAME [       ] output file path (without file extension)
  -ps,       --print-special     [false  ] print special tokens
  -pc,       --print-colors      [false  ] print colors
  -pp,       --print-progress    [false  ] print progress
  -nt,       --no-timestamps     [false  ] do not print timestamps
  -l LANG,   --language LANG     [en     ] spoken language ('auto' for auto-detect)
  -dl,       --detect-language   [false  ] exit after automatically detecting language
             --prompt PROMPT     [       ] initial prompt
  -m FNAME,  --model FNAME       [models/ggml-base.en.bin] model path
  -f FNAME,  --file FNAME        [       ] input WAV file path
  -oved D,   --ov-e-device DNAME [CPU    ] the OpenVINO device used for encode inference

**Comment by dubefab** [comment]
ok it happened to me again with small:

error is: xcrun: error: unable to find utility "coremlc", not a developer tool or in PATH


(py310-whisper) fab@Flying whisper.cpp %./models/generate-coreml-model.sh small     
/opt/homebrew/anaconda3/envs/py310-whisper/lib/python3.10/site-packages/whisper/timing.py:58: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def backtrace(trace: np.ndarray):
ModelDimensions(n_mels=80, n_audio_ctx=1500, n_audio_state=768, n_audio_head=12, n_audio_layer=12, n_vocab=51865, n_text_ctx=448, n_text_state=768, n_text_head=12, n_text_layer=12)
/opt/homebrew/anaconda3/envs/py310-whisper/lib/python3.10/site-packages/whisper/model.py:166: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert x.shape[1:] == self.positional_embedding.shape, "incorrect audio shape"
/opt/homebrew/anaconda3/envs/py310-whisper/lib/python3.10/site-packages/whisper/model.py:97: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  scale = (n_state // self.n_head) ** -0.25
Converting PyTorch Frontend ==> MIL Ops: 100%|████████████████████████████████████████████████████████████▉| 1011/1012 [00:00<00:00, 4924.02 ops/s]
Running MIL frontend_pytorch pipeline: 100%|███████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 181.50 passes/s]
Running MIL default pipeline: 100%|███████████████████████████████████████████████████████████████████████████| 57/57 [00:02<00:00, 22.80 passes/s]
Running MIL backend_mlprogram pipeline: 100%|████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 828.98 passes/s]
done converting
xcrun: error: unable to find utility "coremlc", not a developer tool or in PATH
mv: rename models/coreml-encoder-small.mlmodelc to models/ggml-small-encoder.mlmodelc: No such file or directory
