### ISSUE TITLE
[Feature Request] Real-time Streaming in WASM

### ISSUE THREAD

**Issue by jd3655** [ggerganov/whisper.cpp#112]
What you are doing with this project is amazing. The Web Assembly example works great.

Do you think it's possible to use your "Stream" example in Web Assembly? An example using Vosk is here: https://ccoreilly.github.io/vosk-browser/

You can choose real-time streaming or upload a file.

**Comment by ggerganov** [comment]
Hi, it's possible to port the stream example to WASM, but I doubt the performance is good enough for realtime transcription.

By the way, thanks for showing me Vosk - this looks like a very interesting project.
The quality and performance of the WASM demo that you linked is very good.

**Comment by ggerganov** [comment]
Just added this: https://whisper.ggerganov.com/stream/

The transcribe step is currently hardcoded at 5 seconds.
As expected, it's quite heavy in terms of computation, but it does run on a MacBook.
