### ISSUE TITLE
talk-llama: Is there a way to see token generation in real-time like in llama.cpp?

### ISSUE THREAD

**Issue by Jiminator** [ggerganov/whisper.cpp#1121]
As the title reads.

Currently, llama.cpp in interactive mode has real-time token generation, and this functionality is missing in the talk-llama module. I will update this issue, if I figure out a way to implement this.

**Comment by Jiminator** [comment]
I just realized that I can just fflush(stdout) after printing the tokens. Closing the Issue

**Comment by scalar27** [comment]
I'm pretty new to this, but I think your comment is what I would like help with: in talk-llama, there is a pause and then all the text appears at once, fully generated.  (Unlike in llama.cpp).  If it could stream out instead I'm hoping that it would help with making the audio generation faster.  I'm using piper at present.  Have you figure out how to do this?

**Comment by scalar27** [comment]
I appreciate the speedy update!  It certainly does what I asked.  However, what I would like would be for the piper tts to start doing its thing and then the play command starting to produce speech even while talk-llama is still generating text (especially for a long response.).  

In speak, I am doing:
echo "$2" | piper --model ...  --output-raw | play ... traw -  
(where ... is some various parameters).

Play is from the sox package which seems to work well on Mac OS.  This setup works great except that no speech starts until the generation is complete.  Might there be a workaround?

**Comment by ggerganov** [comment]
This is a more complicated change to make. It's possible, but you need some logic to chunk the response and then same thread to asynchronously pass the chunks to the tts. Probably not very suitable for an example since there are variety of ways to implement this with pros and cons

**Comment by scalar27** [comment]
I see.  Thank you for the info.  I tried to play with --max-tokens and --audio-ctx but they don't seem to be what I am looking for.
