### ISSUE TITLE
llama.cpp does not support llama-2

### ISSUE THREAD

**Issue by dimitar** [ggerganov/whisper.cpp#1125]
When trying to use whisper.cpp and talk-llama on llama-2, it fails with the following error:

llama.cpp: loading model from ../llama.cpp/models/llama-2-13b-chat/ggml-model-q4_0.bin
error loading model: unrecognized tensor type 14

**Comment by guranu** [comment]
wrong repo type your issue here: https://github.com/ggerganov/llama.cpp

**Comment by dimitar** [comment]
> wrong repo type your issue here: https://github.com/ggerganov/llama.cpp

The llama.cpp repo works fine. It's the implementation in talk-llama in this repo that is erroring.

**Comment by dereklll** [comment]
I'm having the same problem with a solution

**Comment by a-a-smirnov** [comment]
Tried to pull `llama.cpp`/`llama.h` from llama.cpp repo but it crashes with floating point exception in `llama_calc_tensor_size` when it tries to load llama-2 model.

**Comment by bobqianic** [comment]
Issue has been solved by the recent sync.
