### ISSUE TITLE
Speed Up option (-su) slower on Pi4

### ISSUE THREAD

**Issue by petercwallis** [ggerganov/whisper.cpp#1152]
I am trying to get the guided mode (command) to run on a pi4 in real time.  The recognition accuracy is great - even with the tiny model - but it is taking almost a second to process even the shortest sound sample. The -ac parameter seems to have no effect, and -su makes it takes twice as long.  I am compiling on the 64bit pi4  with 
-mabi=lp64 -march=armv8-a -mcpu=cortex-a72 -mtune=cortex-a72

Am I doing something obviously wrong?

**Comment by bobqianic** [comment]
Hey, have you had a chance to use OpenBLAS yet? The built-in matrix multiplication algorithm might not be the most efficient one compared to OpenBLAS or other BLAS libraries. If you haven't turned it on yet, I'd suggest giving it a try. You should see a noticeable improvement in performance.

**Comment by bobqianic** [comment]
I'm not entirely sure why enabling `speedup` would slow things down for you. As of now, this speedup mode is disabled by default because it has many bugs. Essentially, it doubles the speed of the audio input for Whisper, but there are numerous issues with its implementation. We're currently working on resolving these problems. You can check out the discussion in the pull request section. I wouldn't recommend using this mode at the moment.

**Comment by petercwallis** [comment]
No go I am afraid.  Adding openblas has made absolutely no difference, and it would seem I am missing something fundamental here. The actual call to whisper_full with 1028ms of data, is taking random amounts of time, anywhere from 867ms to 12085ms (or more).   That might be an over heating issue, but what parameters would I set to have whisper do effectively no processing? I feel I am running out of sensible explanations here..

**Comment by petercwallis** [comment]
It is not overheating. I swapped the pi to a cold one and ran the code immediately. Same random result. Any ideas on how to identify the problem most appreciated.

**Comment by petercwallis** [comment]
So yes, -su seems to be broken, and speed-up by reducing the audio context becomes unstable for very small numbers/samples.  See "Some Questions About Short Audio #1117".

I will close this - and any comments can go on #1117.
