### ISSUE TITLE
whisper.cpp error with flag --print-colors and cannot run with medium and large model.

### ISSUE THREAD

**Issue by tiennguyen12g** [ggerganov/whisper.cpp#1157]
Hello everyone,
Error 1: I can use whisper.cpp with base model, but when I try to use other model, it is not work and throw this error:
![2](https://github.com/ggerganov/whisper.cpp/assets/40747229/9f4b173a-d23e-4db8-8855-93a35b4ada43)

Error 2:
When I try to check high or low confidence of the word, I added the flag "--print-colors". But the character does not display correctly.
![1](https://github.com/ggerganov/whisper.cpp/assets/40747229/f92df53e-099d-4c67-b67b-2b26bb9550cd)

I am use windows 10. Intel i7-8700K CPU 3.7Ghz and Nvidia 1050Ti 4GB Ram 48GB
If you have experience about this, please help me. 
Thank you for your support.

**Comment by tiennguyen12g** [comment]
Updated:
Error 2: I used the command on VS code, it was worked perfect.

Has anyone know the error 1? Please help me

**Comment by tiennguyen12g** [comment]
Updated: 
Error 1: We have convert file when we download from https://ggml.ggerganov.com/.
Here is the article that help you to convert it
https://github.com/ggerganov/whisper.cpp/discussions/753

**Comment by bobqianic** [comment]
> Error 2:
> When I try to check high or low confidence of the word, I added the flag "--print-colors". But the character does not display correctly.

The main issue is the problematic support for Windows. It's not just that the colors aren't displaying correctly, but text other than English might also not display. llama.cpp has a more mature implementation, so we can simply port it over.
