### ISSUE TITLE
Can't build stream because of sdl.h

### ISSUE THREAD

**Issue by shellheim** [ggerganov/whisper.cpp#1161]
I saw a few issues on the same topic, on issue #50 installing sdl2 worked with :  

`brew install sdl2`  but I am on Fedora 38 and I already have the package `SDL2-2.26.3-1.fc38.x86_64` but when I run `make stream` I get the following error which ends in the termination of compilation : 

```gcc
make stream 
which: no nvcc in (/home/user/.local/share/go/bin:/home/user/.cargo/bin/:/home/user/.local/bin:/home/user/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin)
I whisper.cpp build info: 
I UNAME_S:  Linux
I UNAME_P:  unknown
I UNAME_M:  x86_64
I CFLAGS:   -I.              -O3 -DNDEBUG -std=c11   -fPIC -pthread -mavx2 -mfma -mf16c -mavx -msse3
I CXXFLAGS: -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -pthread
I LDFLAGS:  
I CC:       cc (GCC) 13.2.1 20230728 (Red Hat 13.2.1-1)
I CXX:      g++ (GCC) 13.2.1 20230728 (Red Hat 13.2.1-1)

g++ -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -pthread examples/stream/stream.cpp examples/common.cpp examples/common-ggml.cpp examples/common-sdl.cpp ggml.o whisper.o -o stream `sdl2-config --cflags --libs` 
/bin/sh: line 1: sdl2-config: command not found
In file included from examples/stream/stream.cpp:7:
./examples/common-sdl.h:3:10: fatal error: SDL.h: No such file or directory
    3 | #include <SDL.h>
      |          ^~~~~~~
compilation terminated.
In file included from examples/common-sdl.cpp:1:
examples/common-sdl.h:3:10: fatal error: SDL.h: No such file or directory
    3 | #include <SDL.h>
      |          ^~~~~~~
compilation terminated.
make: *** [Makefile:305: stream] Error 1
```
I saw that installing sdl2 from source worked in issue #139 but I just wanted to ask for advice first, thanks.

**Comment by alonfaraj** [comment]
Hi @shellheim,
I tested your scenario on fedora 38 docker image.
I installed `sdl2` using `dnf install SDL2-devel`. I have the same version like you mentioned - the build succeed.
In my case `sdl2-config` installed under `/usr/bin/`.
Maybe it installed in a different path on your machine and `make` couldn't find it?

**Comment by shellheim** [comment]
Thanks @alonfaraj, it's fixed! I really appreciate the time you took to test it yourself!  I didn't know I had to install the `SDL2-devel` package, I only had `SDL2`. Didn't know that sorry.  

Also, I was using the base model to stream and it gets most words wrong, the transcribing is spot on though! What do you think can improve the stream command, using it on better hardware or using a larger model? I think it would be better to upgrade to a new and more powerful cpu, currently this one only has 4 cores.

**Comment by alonfaraj** [comment]
Glad to hear!
I'm not sure about the other issue.. sorry.
Maybe it worth opening a new issue for this.

**Comment by LaptopDev** [comment]
How did you manage to compile 'stream' without a makefile? The documentation just says 'download SDL2-devel' and run 'make stream'. I am unfamiliar with build automation.

> Thanks @alonfaraj, it's fixed! I really appreciate the time you took to test it yourself! I didn't know I had to install the `SDL2-devel` package, I only had `SDL2`. Didn't know that sorry.

**Comment by shellheim** [comment]
I am not sure what you mean. There is a [makefile.](https://github.com/ggerganov/whisper.cpp/blob/master/Makefile) I don't know much about compilation of/or C/C++. I just followed the instructions in the [README](https://github.com/ggerganov/whisper.cpp/blob/master/Makefile)

**Comment by LaptopDev** [comment]
> I am not sure what you mean. There is a [makefile.](https://github.com/ggerganov/whisper.cpp/blob/master/Makefile) I don't know much about compilation of/or C/C++. I just followed the instructions in the [README](https://github.com/ggerganov/whisper.cpp/blob/master/Makefile)

Reading into the makefile, I realized 'make stream' should be run from the project root directory.

I believed 'make stream' needed to be run in /examples/stream and by default would use the Makefile in the root directory, but when I moved to the root directory and ran 'make stream' it compiled.

Just a misunderstanding how how make works. thank you.

**Comment by shellheim** [comment]
Oh, you're welcome.
