### ISSUE TITLE
How to calculate the probability value of a word?

### ISSUE THREAD

**Issue by tiennguyen12g** [ggerganov/whisper.cpp#1166]
Hi everyone, I am new here, so I do not know how authors can calculate the value of probability. I guess they use one of the following methods:

1. Comparing the audio of a word in audio with a lot of sample sounds. Then, they count how many times it's correct and calculate the percentage.
   Example: With 100 sample sounds, if the word in the audio matches 50 sample sounds, the probability value is 50%.
   
2. Comparing the syllables of the word.
   Example: For the word 'contribute' - /kənˈtrɪb.juːt/. They check if the phoneme sounds are correct. If /kən/ sounds like /kan/ or /kon/, the word will only get 66.6% probability.

If they are using the second approach, could you please explain how I can identify the incorrect phoneme?

I would like to receive results like:
- "birch": /bir/ may lack confidence, so its color is yellow, and /ch/ is the correct phoneme, so its color is green.
- "planks": /pl/ may lack confidence, so its color is green, and /anks/ is the correct phoneme, so its color is red.
I came across this picture in a discussion, but it doesn't have a solution.
![image](https://github.com/openai/whisper/assets/40747229/445b86ee-7dd0-460e-817e-5f7f2e2d6ffc)
Examples: "Agricultural," "depletion."
![whisperccp1](https://github.com/openai/whisper/assets/40747229/2b46fc04-9ec5-4b5f-a936-22abd828f36d)
I would greatly appreciate your assistance. Thank you so much.

I see the website name "apeuni" has this feature, you can see more example:

![ape1](https://github.com/ggerganov/whisper.cpp/assets/40747229/fd7a8fd8-1f7a-4c1d-9915-d80c4ced5734)
![ape2](https://github.com/ggerganov/whisper.cpp/assets/40747229/993cb812-ca8a-4d34-b85b-67753ba7bc75)

**Comment by bobqianic** [comment]
No, we simply use the output from the `softmax` function to determine the probability values. The model utilizes `softmax` to decide the next token. The `temperature` parameter modifies this probability distribution. A higher `temperature` leads to a more uniform distribution, making the probabilities more similar and introducing greater randomness.
