### ISSUE TITLE
Tutorial for Visual studio code on Windows11

### ISSUE THREAD

**Issue by MonicaArnaud** [ggerganov/whisper.cpp#117]
Hi, maybe it is a little stupid to ask, I used to run python files instead of C++, I would appreciate if someone could teach me how to run the scripts on the visual studio code on Windows 11. I tried to Terminal > Run Build task, but it shows the following errors. Please help. Thank you!

![sppech2textError](https://user-images.githubusercontent.com/58461368/198945441-86912340-4504-46d2-a3d1-dad55ca6091e.png)

**Comment by chidiwilliams** [comment]
@MonicaArnaud I set up mine using CMake with the CMake and CMake Tools extensions on VSCode (https://code.visualstudio.com/docs/cpp/cmake-linux)

**Comment by MonicaArnaud** [comment]
> @MonicaArnaud I set up mine using CMake with the CMake and CMake Tools extensions on VSCode (https://code.visualstudio.com/docs/cpp/cmake-linux)

Hi, I installed both the CMake and CMake Tools extensions, but it didn't work, same error. Thank you anyway. 

Do you know how to run this app on the browser? It seems someone run it on Chrome. Thanks

**Comment by ggerganov** [comment]
@MonicaArnaud 

Try following the steps here:

https://github.com/ggerganov/whisper.cpp/actions/runs/3517978497/workflow#L117-L144

Or directly download the latest executable from here (at the bottom):

https://github.com/ggerganov/whisper.cpp/actions/runs/3517978497
