### ISSUE TITLE
Does not load models

### ISSUE THREAD

**Issue by guranu** [ggerganov/whisper.cpp#1178]
When i try to use whisper i get an error "failed to initialize whisper context" this has never happened before i tried to re-compile it but it still gives me this error:
```
$./main -m models/ggml-large -f vfx_map_bahamas.wav
whisper_init_from_file_no_state: loading model from 'models/ggml-large'
whisper_init_from_file_no_state: failed to open 'models/ggml-large'
error: failed to initialize whisper context
```

**Comment by infinityp913** [comment]
Hi! I got the same error with my ggml-tiny.en.bin. Do you mind sharing how you fixed it?

**Comment by guranu** [comment]
You first type the path to the audio and then you type the the audio.

**Comment by ancre222** [comment]
Sorry, it still gives me this error: ./main -m models/ggml-large -f /Users/andre/Downloads/samples_jfk.wav 
whisper_init_from_file_with_params_no_state: loading model from 'models/ggml-large'
whisper_init_from_file_with_params_no_state: failed to open 'models/ggml-large'
error: failed to initialize whisper context
