### ISSUE TITLE
convert-pt-to-ggml.py run error

### ISSUE THREAD

**Issue by yjyz1011** [ggerganov/whisper.cpp#1183]
the error info:
Traceback (most recent call last):
  File "F:\convert-pt-to-ggml.py", line 296, in <module>
    data = list_vars[name].squeeze().numpy()
           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'squeeze'
how to solve it?please

**Comment by bobqianic** [comment]
You should use `pip` to install numpy first.
