### ISSUE TITLE
-p not working with -t > 1 on Raspberry Pi 4B (ARM64)

### ISSUE THREAD

**Issue by julianpoemp** [ggerganov/whisper.cpp#1184]
Hello,

I just tried whisper.cpp for the first time on my Raspberry Pi 4B (Ubuntu 23, ARM64) and it works like  a charm. The only issue: If I set -p to > 1 and -t to > 1 all 4 cores are being used for processing. I checked this with htop. The cores are only limited if I set -t to 1.

Example:

./main -m models/ggml-base.bin -f Bahnauskunft16k.wav -l de -p 2 -t 4
=> all 4 cores are processing

./main -m models/ggml-base.bin -f Bahnauskunft16k.wav -l de -p 2 -t 1
=> 2 cores are processing

Is this a bug or does the OS contribute the threads automatically on all cores?

**Comment by bobqianic** [comment]
This isn't a bug. whisper.cpp uses `p*t` threads in total. So, setting `p` to `2` and t to `1` gives you `2` threads. For shorter audio, I'd recommend using `-p 1 -t N`, as it's quicker.
