### ISSUE TITLE
Stop transcription Process

### ISSUE THREAD

**Issue by rahalmichel96** [ggerganov/whisper.cpp#1185]
Hi everyone,

I'm using your project for Android to make transcription with Whisper. I would like to know if you've already added a mechanism to stop the ongoing transcription process ?

Thank you for what you've done so far :)

**Comment by chidiwilliams** [comment]
You can pass a state variable to `new_segment_callback_user_data` to stop transcription before the next segment starts.

See an example here:
- https://github.com/chidiwilliams/buzz/blob/c498e60949e9fddd48d49355c2a05eb97407a6a7/buzz/transcriber.py#L202
- https://github.com/chidiwilliams/buzz/blob/c498e60949e9fddd48d49355c2a05eb97407a6a7/buzz/transcriber.py#L236

**Comment by rahalmichel96** [comment]
Ok thank you ! I'll check the code.

Very well done for your work 😃
