### ISSUE TITLE
After coverted to CoreML model, can the bin model file no longer be needed?

### ISSUE THREAD

**Issue by haozes** [ggerganov/whisper.cpp#1188]
Ideally, no bin file should be needed after convert model to CoreML model.

Currently this not only increases the file size of the app, but also increases memory consumption.

I know that CoreML for encoder is currently working fine,  but decode seems to still have problems.

Thanks

**Comment by ggerganov** [comment]
The `.bin` file is still necessary in order to run the Decoder.
If we implement CoreML for the Decoder, then we can remove the .bin file
