### ISSUE TITLE
Error: unknown type name '__m128'

### ISSUE THREAD

**Issue by alphafox02** [ggerganov/whisper.cpp#1192]
System Specs
Lubuntu 22.04 with GCC 11.4.0

Attempting to build WhisperCPP from source today results in Error: unknown type name '__m128' at various spots in ggml.c

**Comment by alphafox02** [comment]
Rolled back to git commit 4774d2f the issue does not exist. In the very next commit, 3998465, that's when it starts happening on my end (at least this PC I'm on).

**Comment by alphafox02** [comment]
I think it maybe due to the PC/VM not having avx/avx2 support? On another Pc that has it, the problem does not happen.

**Comment by bobqianic** [comment]
#1162

**Comment by alphafox02** [comment]
That fixed it. Thank you. I’ll close this since there’s a PR.
