### ISSUE TITLE
Whisper downloaded 2023 August  22 won't build (that of August 13 did) with many errors

### ISSUE THREAD

**Issue by ArthurPeabody** [ggerganov/whisper.cpp#1198]
I downloaded master.zip today.  It won't build, first complaining of no nvcc then a number of other errors.  I downloaded August 13, have been using that.
[errors.txt](https://github.com/ggerganov/whisper.cpp/files/12399186/errors.txt)

**Comment by bobqianic** [comment]
#1196

**Comment by bobqianic** [comment]
I've closed this issue because the PR is now merged. If you have any further questions, please don't hesitate to open a new issue and ask.
