### ISSUE TITLE
How to read/convert .wts to .srt?

### ISSUE THREAD

**Issue by moebiussurfing** [ggerganov/whisper.cpp#120]
Hello, 
I just tried the word level process, but the srt was generated as regular, by sentence scheme.

I see the generated .wts file but I don't know how to open it...
Could we maybe generate ths srt (or maybe both word/sentence versions)?

It looks like maybe you have a local mp4 video to merge the .wts into doing overlay?

Thanks for the repo and that new features!

**Comment by moebiussurfing** [comment]
... it looks like it's an FFmpeg script to generate a preview vide0 (?)...
it points to `"drawtext=fontfile='/System/Library/Fonts/Supplemental/Courier New Bold.ttf': ... 
Maybe macOs path for the fonts?
I am on Windows. Maybe it's macOS only?

```.bash
moebiussurfing@surfingMachine MINGW64 /d/_CODE/_AI/whisper.cpp
$ source ./HUXLEY2_16k.wav.wts
bash: !/bin/bash: No such file or directory
bash: ./HUXLEY2_16k.wav.wts: line 3: unexpected EOF while looking for matching `"'
bash: ./HUXLEY2_16k.wav.wts: line 4: syntax error: unexpected end of file
```

**Comment by ggerganov** [comment]
Yes, this option currently outputs a bash script that runs `ffmpeg` to generate karaoke-style video.

There will be a separate option added to output word timestamps to a file.
Additionally, we can now also control the length of generated subtitles so there will be another option to set the max line length for the subtitles.

**Comment by ggerganov** [comment]
This is now resolved - see https://github.com/ggerganov/whisper.cpp/issues/49#issuecomment-1301154359 for more info

**Comment by lucasbr15** [comment]
> This is now resolved - see [#49 (comment)](https://github.com/ggerganov/whisper.cpp/issues/49#issuecomment-1301154359) for more info

Can anyone else help with this? how do you create this transition? would it be possible to help with this?

**Comment by ggerganov** [comment]
@lucasbr15 
Which part is not clear?

Try to follow the steps described in the README:

- https://github.com/ggerganov/whisper.cpp#word-level-timestamp
- https://github.com/ggerganov/whisper.cpp#karaoke-style-movie-generation-experimental

**Comment by lucasbr15** [comment]
> @lucasbr15 Which part is not clear?
> 
> Try to follow the steps described in the README:
> 
> * https://github.com/ggerganov/whisper.cpp#word-level-timestamp
> * https://github.com/ggerganov/whisper.cpp#karaoke-style-movie-generation-experimental

I'm sorry for the late reply.

I was wondering if you could tell me what script you used to make it so that the words generated by the whisper are put together in sequential phrases in karaoke style, with each word being highlighted as it is spoken.

I've been trying to look everywhere for a script that does exactly what yours does, but I can't seem to find anything.

I'm using [Stabilizing Timestamps for Whisper](https://github.com/jianfch/stable-ts).

Do you think you could help me out? It would mean a lot, since I'm not the only one looking for a script like this. Thanks!
