### ISSUE TITLE
Difficulty compiling examples on windows

### ISSUE THREAD

**Issue by DraconInteractive** [ggerganov/whisper.cpp#1213]
I'm having a _significantly_ difficult time compiling these cpp's. 
My current setup didnt have mingw, cmake or make, so I installed these, setup path variables etc. I generally work with a lot of premade tools, so this was fairly new to me. 

I downloaded the base.en model by running ./models/download-ggml-model.sh, which worked fine. 

From here I tried a few different ways to build main, but kept hitting walls in building main. Most of them seemed to boil down to 'windows'. Running make anywhere in the project (root, examples, etc) has me hitting errors such as: 
`process_begin: CreateProcess(NULL, uname -s, ...) failed.
Makefile:4: pipe: No error
process_begin: CreateProcess(NULL, uname -p, ...) failed.
Makefile:8: pipe: No error
process_begin: CreateProcess(NULL, uname -m, ...) failed.
Makefile:12: pipe: No error
process_begin: CreateProcess(NULL, which nvcc, ...) failed.
Makefile:16: pipe: No error
'cc' is not recognized as an internal or external command,
operable program or batch file.
'head' is not recognized as an internal or external command,
operable program or batch file.`

I have tried running CMAKE at various areas too, no luck. I have recloned the repo many times to test making/cmaking with different inputs / orders and no success. 

Downloading the latest release and running the .exe was a good temporary boost, but I realised that if i wanted to do anything useful (like the stream or command examples) then I was going to need to master this build pipeline.

My highest amount of success came from me copying the files from ./examples (not the subfolders, just files) and placing them in root. Then I pulled the command.cpp and commands.txt from the examples/command and placed them in root too. 
Here, I found that i was getting errors for SDL.h, which I had assumed was contained in SDL2.dll. So I downloaded the dev files for SDL2 and placed them in root/SDL2. 

I'm then running the command g++ command.cpp -o command -I ./SDL2/

This got me past the missing references, but then gave me a bunch of undefined references (below):

I appreciate any help someone can provide for this! I think there is a core concept im not understanding about the use of make/cmake  but im kind of flailing in the dark hoping to strike gold somehow. 
 
````F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x120f): undefined reference to `whisper_full_default_params'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x1415): undefined reference to `whisper_full'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x148a): undefined reference to `whisper_full_n_segments'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x14b4): undefined reference to `whisper_full_get_segment_text'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x14e6): undefined reference to `whisper_full_n_tokens'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x151e): undefined reference to `whisper_full_get_token_data'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x16ef): undefined reference to `trim(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x1b98): undefined reference to `whisper_tokenize'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x1f8e): undefined reference to `whisper_tokenize'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x21db): undefined reference to `sdl_poll_events()'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x222e): undefined reference to `audio_async::get(int, std::vector<float, std::allocator<float> >&)'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x227b): undefined reference to `vad_simple(std::vector<float, std::allocator<float> >&, int, int, float, float, bool)'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x22ca): undefined reference to `whisper_full_default_params'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x24fb): undefined reference to `whisper_full'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x253f): undefined reference to `whisper_get_logits'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x2571): undefined reference to `whisper_n_vocab'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x2b97): undefined reference to `whisper_token_to_str'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x2dbd): undefined reference to `audio_async::clear()'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x304d): undefined reference to `sdl_poll_events()'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x313f): undefined reference to `audio_async::get(int, std::vector<float, std::allocator<float> >&)'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x3189): undefined reference to `vad_simple(std::vector<float, std::allocator<float> >&, int, int, float, float, bool)'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x31e0): undefined reference to `audio_async::get(int, std::vector<float, std::allocator<float> >&)'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x3226): undefined reference to `trim(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x334e): undefined reference to `similarity(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x340f): undefined reference to `audio_async::clear()'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x360c): undefined reference to `sdl_poll_events()'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x36fe): undefined reference to `audio_async::get(int, std::vector<float, std::allocator<float> >&)'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x3748): undefined reference to `vad_simple(std::vector<float, std::allocator<float> >&, int, int, float, float, bool)'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x37b1): undefined reference to `audio_async::get(int, std::vector<float, std::allocator<float> >&)'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x37f7): undefined reference to `trim(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x386e): undefined reference to `similarity(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x3aa6): undefined reference to `audio_async::get(int, std::vector<float, std::allocator<float> >&)'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x3b4c): undefined reference to `trim(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x3c13): undefined reference to `similarity(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x3cf3): undefined reference to `trim(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x3da1): undefined reference to `audio_async::clear()'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x3f2e): undefined reference to `whisper_lang_id'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x3fab): undefined reference to `whisper_init_from_file'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x3fe1): undefined reference to `whisper_is_multilingual'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x410d): undefined reference to `audio_async::audio_async(int)'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x4122): undefined reference to `audio_async::init(int, int)'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x4166): undefined reference to `audio_async::resume()'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x41a1): undefined reference to `audio_async::clear()'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x424d): undefined reference to `audio_async::pause()'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x425c): undefined reference to `whisper_print_timings'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x426b): undefined reference to `whisper_free'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x427d): undefined reference to `audio_async::~audio_async()'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\pmc10\AppData\Local\Temp\ccewAc2v.o:command.cpp:(.text+0x429c): undefined reference to `audio_async::~audio_async()'
F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: F:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/lib/../lib/libmingw32.a(lib64_libmingw32_a-crtexewin.o):crtexewin.c:(.text+0x130): undefined reference to `WinMain'
collect2.exe: error: ld returned 1 exit status````

**Comment by DraconInteractive** [comment]
After some more research, and a lot of help from chatgpt, i have a more thorough understanding of cmake. I have built the solution and I have main.exe, quantize.exe, bench.exe and whisper.dll. 

Now, I can see that WHISPER_BUILD_EXAMPLES is equal to ON, and I can see the examples folder propagated over to the solution directory, but im still not sure how to run a specific example. For instance, the command example. 

I apologise, as I work on this I can definitely see its a problem with my understanding of the systems, I'm just working through it as best I can.

**Comment by DraconInteractive** [comment]
Righto, WSL did the trick! At least I can run/edit the code now, and im working on converting it to .exe later (or, maybe not at all since my use-case might be cpp based). 

I'm going to close this now. I apologise for exposing you all to my steep learning curve, I am however very excited to start engaging with this properly! 

If anyone in the future runs into a similar problem, happy to expand on my steps to finally get it setup. Ciao

**Comment by gabrielmicko** [comment]
@DraconInteractive same issue, would you please share how you solved it?
