### ISSUE TITLE
v1.4.0 cannot be used with q5_1 model

### ISSUE THREAD

**Issue by wizardforcel** [ggerganov/whisper.cpp#1226]
It output nothing and then exits.

1.4.2 works but isn't released. Download links in the pipeline are invalid.

**Comment by bobqianic** [comment]
The new release is coming soon, packed with exciting new features and important bug fixes. If you can't wait and want to give it a try, just download the master branch and compile it.

**Comment by wizardforcel** [comment]
> The new release is coming soon, packed with exciting new features and important bug fixes. If you can't wait and want to give it a try, just download the master branch and compile it.

OK I'll have a try.
