### ISSUE TITLE
Support for Seamless-M4T models

### ISSUE THREAD

**Issue by aiaicode** [ggerganov/whisper.cpp#1236]
Not sure if its possible to support Seamless-M4T models with whisper.cpp but if its possible to run these models on CPU/GPU, would be nice.

**Comment by bobqianic** [comment]
I'd probably lean towards no, but since the backend `GGML` is pretty flexible, it's definitely possible to create a Seamless-M4T.cpp.

**Comment by ybeetle8** [comment]
SeamlessM4T's speech-to-speech is great, and it would be nice to have Seamless-M4T.cpp optimized to run on small devices...

**Comment by iHaagcom** [comment]
> SeamlessM4T's speech-to-speech is great, and it would be nice to have Seamless-M4T.cpp optimized to run on small devices...

I agree ☝️
