### ISSUE TITLE
main.exe hangs forever insteaf of failing with certain cmd arguments

### ISSUE THREAD

**Issue by emcodem** [ggerganov/whisper.cpp#1241]
Of course one should not start main.exe with wrong params but it is strange to see that we can easily cause a hang forever in some scenarios.
The reason was that i constructed paths wrong with a script, eg used single quotes around the input file but the filename itself contained a single quote too. For simplicity, i reproduced with a minimal version:

main.exe -m ggml-tiny.bin -f ' - '

Also, it does not seem to matter if -f is faulty input or -of is faulty.
I could only reproduce wen dash and ' is present

**Comment by bobqianic** [comment]
> The reason was that i constructed paths wrong with a script, eg used single quotes around the input file but the filename itself contained a single quote too. 

Can you give any examples?

> main.exe -m ggml-tiny.bin -f ' - '

So what is the filename?

**Comment by emcodem** [comment]
Well there is no file, the cmd has been wrongly calculated by my script. 
Here is another example that might make more sense:
```

whisper_init_from_file_no_state: loading model from 'C:\Users\emcod\Downloads\ggml-tiny.bin'
whisper_model_load: loading model
whisper_model_load: n_vocab       = 51865
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 384
whisper_model_load: n_audio_head  = 6
whisper_model_load: n_audio_layer = 4
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 384
whisper_model_load: n_text_head   = 6
whisper_model_load: n_text_layer  = 4
whisper_model_load: n_mels        = 80
whisper_model_load: ftype         = 1
whisper_model_load: qntvr         = 0
whisper_model_load: type          = 1
whisper_model_load: mem required  =  201.00 MB (+    3.00 MB per decoder)
whisper_model_load: adding 1608 extra tokens
whisper_model_load: model ctx     =   73.62 MB
whisper_model_load: model size    =   73.54 MB
whisper_init_state: kv self size  =    2.62 MB
whisper_init_state: kv cross size =    8.79 MB
error: failed to open ''' as WAV file
error: failed to read WAV file '''
```

From this moment on, the program "hangs" forever.

**Comment by bobqianic** [comment]
Got it, I'll take a look and see if I can fix it.

**Comment by bobqianic** [comment]
Actually, this behavior is intentional, not a bug. In the `read_wav` function within common.cpp, there's a setting that allows for reading WAV files through `stdin` when the file name is set to `-`. You can simply use double quotes **`"`** around your file path, and that should solve the problem.

https://github.com/ggerganov/whisper.cpp/blob/2f52783a080e8955e80e4324fed73e2f906bb80c/examples/common.cpp#L605-L628

**Comment by emcodem** [comment]
Thanks a lot for taking a look @bobqianic!
Just what i thought but kind of weird that fname is "-", isnt it " - " in my minimal example?
