### ISSUE TITLE
Whisper parameter tweaks for hallucinations / ghosting. Missing of parameter setting

### ISSUE THREAD

**Issue by Karrde1984** [ggerganov/whisper.cpp#1244]
Hi
There are some discussions about those ghost transcriptions with whisper and there are some parameter tweaks around, which reduces those hallucinations by ~90%. The most important parameter is called „**condition_on_previous_text**“. But that parameter is nowhere to see in whisper.net.
Can you include that parameter anytime soon? I think it is highly important it reduces those hallucinations heavily and we cant see any relevant negative side effects with other (but much slower Linux python) whisper projects.

**Comment by emcodem** [comment]
-mc 0 is equivalent to "condition_on_previous_text". It will remove "forever looping" output and also workaround other problems like counting up forever or lowercase forever. At the same time it will sometimes cause reduced transcribe quality.

**Comment by Karrde1984** [comment]
Thanks for your reply. Works great. everything i wished for. Case closed :-)
