### ISSUE TITLE
Could whisper.cpp use Meta's SeamlessM4T release?

### ISSUE THREAD

**Issue by dgm3333** [ggerganov/whisper.cpp#1245]
SeamlessM4T appears to be the meta alternative to Whisper with some enhancements.
Does anyone know if there is any crossover/compatability which would allow Whisper.cpp (or the Llama.cpp merge) to also utilise this engine?
https://github.com/facebookresearch/seamless_communication
https://ai.meta.com/resources/models-and-libraries/seamless-communication/

**Comment by bobqianic** [comment]
#1236

**Comment by dgm3333** [comment]
Oh thanks - I searched without the hyphen in the other post so didn't find it. Since Meta doesn't hyphenate the name then the other post is a typo but closing this one to avoid duplicate thread
