### ISSUE TITLE
complete Maven Central registration process

### ISSUE THREAD

**Issue by nalbion** [ggerganov/whisper.cpp#1246]
@ggerganov as you mentioned in [my PR](https://github.com/ggerganov/whisper.cpp/pull/944#issuecomment-1696075240) you still need to create an empty GitHub repository `OSSRH-94491` before we can publish the Java library.

**Comment by nalbion** [comment]
The jar file needs to be signed before it can be published.

https://docs.gradle.org/8.1/userguide/signing_plugin.html#sec:signatory_credentials

You will need to define project secrets:

GPG_PASSPHRASE
GPG_PRIVATE_KEY

**Comment by ggerganov** [comment]
GPG secrets have been added

**Comment by nalbion** [comment]
I think there's something wrong with the `JIRA_USER` and/or `JIRA_PASS`. I get exactly the same error below when I set either to the wrong value.

> Could not PUT 'https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/io/github/ggerganov/whispercpp/1.4.0/whispercpp-1.4.0.jar'. Received status code 401 from server: Unauthorized

**Comment by nalbion** [comment]
@ggerganov can you try generating the `PGP_SECRET` again using `gpg --armor --export` (or maybe `gpg --export-secret-keys -a -o secret-key.asc`)

**Comment by ggerganov** [comment]
I tried generating a new `PGP_SECRET` and re-runing the java workflow from master but it still fails.

![image](https://github.com/ggerganov/whisper.cpp/assets/1991296/a9c3c919-4003-4dae-9771-2858d73f30ee)

We currently have the following secrets:

![image](https://github.com/ggerganov/whisper.cpp/assets/1991296/16d8011d-2cea-4f7c-8385-0281c26c4000)

- `GPG_PRIVATE_KEY` and `GPG_PASSPHRASE` are my Github signing key data
- the `PGP_SECRET` I just generated a few minutes ago with the `gpg` command

Regarding the `PGP_SECRET` and `GPG_PRIVATE_KEY`, I'm not sure if they should include the ASCII prefix and suffix.
For example, the output of `gpg --armor --export` looks like this:

```
-----BEGIN PGP PRIVATE KEY BLOCK-----

[base64]
-----END PGP PRIVATE KEY BLOCK-----
```

Do I set the secret to be equal to just `[base64]` or also include the prefix and suffix?

**Comment by nalbion** [comment]
I think inlcude the `-----BEGIN PGP PRIVATE KEY BLOCK-----` and end block

**Comment by ggerganov** [comment]
Updated `PGP_SECRET` to include it

I think `GPG_PASSPHRASE` also includes it, but AFAICT it is not used by the workflow anyway.

What about `PGP_PASSPHRASE`:

https://github.com/ggerganov/whisper.cpp/blob/1d3e6683e6442cc0135a90b668b41e979c4440ed/.github/workflows/build.yml#L436-L442

I suppose it is optional, but I can also create an empty secret

**Comment by nalbion** [comment]
Let's try using secrets.GPG_PRIVATE_KEY and GPG_PASSPHRASE

**Comment by nalbion** [comment]
Should work now when we merge #1267.

**Comment by ggerganov** [comment]
Thank you! Should I remove the `PGP_SECRET` secret?

**Comment by nalbion** [comment]
<html>
<body>
<div>From <a href="https://s01.oss.sonatype.org/#stagingRepositories">https://s01.oss.sonatype.org/#stagingRepositories</a>
<br/>
<br/>
</div>



typeId | signature-staging
-- | --
failureMessage | No public key: Key with id: (449e073f9dc10735) was not able to be located on <a href="http://keyserver.ubuntu.com:11371/">http://keyserver.ubuntu.com:11371/</a>. Upload your public key and try the operation again.
failureMessage | No public key: Key with id: (449e073f9dc10735) was not able to be located on <a href="https://keys.openpgp.org/">https://keys.openpgp.org/</a>. Upload your public key and try the operation again.
failureMessage | No public key: Key with id: (449e073f9dc10735) was not able to be located on <a href="http://pgp.mit.edu:11371/">http://pgp.mit.edu:11371/</a>. Upload your public key and try the operation again.
failureMessage | No public key: Key with id: (449e073f9dc10735) was not able to be located on <a href="http://keyserver.ubuntu.com:11371/">http://keyserver.ubuntu.com:11371/</a>. Upload your public key and try the operation again.
failureMessage | No public key: Key with id: (449e073f9dc10735) was not able to be located on <a href="https://keys.openpgp.org/">https://keys.openpgp.org/</a>. Upload your public key and try the operation again.
failureMessage | No public key: Key with id: (449e073f9dc10735) was not able to be located on <a href="http://pgp.mit.edu:11371/">http://pgp.mit.edu:11371/</a>. Upload your public key and try the operation again.
failureMessage | No public key: Key with id: (449e073f9dc10735) was not able to be located on <a href="http://keyserver.ubuntu.com:11371/">http://keyserver.ubuntu.com:11371/</a>. Upload your public key and try the operation again.
failureMessage | No public key: Key with id: (449e073f9dc10735) was not able to be located on <a href="https://keys.openpgp.org/">https://keys.openpgp.org/</a>. Upload your public key and try the operation again.
failureMessage | No public key: Key with id: (449e073f9dc10735) was not able to be located on <a href="http://pgp.mit.edu:11371/">http://pgp.mit.edu:11371/</a>. Upload your public key and try the operation again.
failureMessage | No public key: Key with id: (449e073f9dc10735) was not able to be located on <a href="http://keyserver.ubuntu.com:11371/">http://keyserver.ubuntu.com:11371/</a>. Upload your public key and try the operation again.
failureMessage | No public key: Key with id: (449e073f9dc10735) was not able to be located on <a href="https://keys.openpgp.org/">https://keys.openpgp.org/</a>. Upload your public key and try the operation again.
failureMessage | No public key: Key with id: (449e073f9dc10735) was not able to be located on <a href="http://pgp.mit.edu:11371/">http://pgp.mit.edu:11371/</a>. Upload your public key and try the operation again.
failureMessage | No public key: Key with id: (449e073f9dc10735) was not able to be located on <a href="http://keyserver.ubuntu.com:11371/">http://keyserver.ubuntu.com:11371/</a>. Upload your public key and try the operation again.
failureMessage | No public key: Key with id: (449e073f9dc10735) was not able to be located on <a href="https://keys.openpgp.org/">https://keys.openpgp.org/</a>. Upload your public key and try the operation again.
failureMessage | No public key: Key with id: (449e073f9dc10735) was not able to be located on <a href="http://pgp.mit.edu:11371/">http://pgp.mit.edu:11371/</a>. Upload your public key and try the operation again.


</body>
</html>

**Comment by nalbion** [comment]
@ggerganov could you please publish your public key to https://keys.openpgp.org or http://pgp.mit.edu:11371

**Comment by ggerganov** [comment]
Yup, should be up ready now: https://keys.openpgp.org/search?q=C8948ECA6FBC3EAD4A7F9050449E073F9DC10735

**Comment by nalbion** [comment]
Great! It's released now, thanks @ggerganov!

![image](https://github.com/ggerganov/whisper.cpp/assets/1866161/6666af9d-da6d-4a4c-81ab-2ae1edd8aff8)
