### ISSUE TITLE
Does the openBlas option works？

### ISSUE THREAD

**Issue by xyx361100238** [ggerganov/whisper.cpp#125]
1、No Blas option：
```
     cmake ..  -DWHISPER_SUPPORT_OPENBLAS=OFF
     make
     ./bin/main -m ../models/ggml-base.en.bin -nt -t 1 -f ../samples/jfk.wav
```
 result:
![image](https://user-images.githubusercontent.com/19569322/199885914-155f80f9-51ee-403f-97aa-288e2b719e5d.png)

2、Have Blas option：
```
 cmake ..  -DWHISPER_SUPPORT_OPENBLAS=ON
 make
 ./bin/main -m ../models/ggml-base.en.bin -nt -t 1 -f ../samples/jfk.wav
```
result：
![image](https://user-images.githubusercontent.com/19569322/199886403-45af4b6c-af04-4fe5-8324-3dd867cefbaf.png)
![image](https://user-images.githubusercontent.com/19569322/199886525-a11b2352-b39d-4f8f-9233-85fb650ea537.png)

It's very close in total time，does it works？

**Comment by ArtyomZemlyak** [comment]
I had a mach slower results on i7-11800H

**Comment by ggerganov** [comment]
Yeah, I also didn't observe much benefit from using OpenBLAS when running FP16 mode: https://github.com/ggerganov/whisper.cpp/commit/fbd513b813ea42a500ba92be3dcfea0b6b6a4fa3

Likely, due to the extra FP16 -> FP32 conversion, since OpenBLAS does not support processing directly FP16.

**Comment by xyx361100238** [comment]
got it！
