### ISSUE TITLE
CoreML Support Installation Sequence

### ISSUE THREAD

**Issue by pudepiedj** [ggerganov/whisper.cpp#1260]
I am usually the one who has got something wrong, so I apologise if what follows is not the case, by the instructions given in [https://github.com/ggerganov/whisper.cpp/blob/master/models/README.md](url) do not work for me as stated. There is no reference here to **make <modelname>**; is that what is missing?

`$ ./download-ggml-model.sh base.en
Downloading ggml model base.en ...
models/ggml-base.en.bin          100%[=============================================>] 141.11M  5.41MB/s    in 22s
Done! Model 'base.en' saved in 'models/ggml-base.en.bin'
You can now use it like this:

  $ ./main -m models/ggml-base.en.bin -f samples/jfk.wav`

But I could not "use it like this" because although the binary is present, the **ggml-{modelname}-encoder.mlmodelc** file is missing. Should I have somehow acquired it from some other earlier process, or has the **make** step been omitted as in the main sequence README.MD?

This works for me:
`./models/generate-coreml-model.sh <modelname>`
This first downloads the binary, runs a python script, and then creates the **mlmodelc** file using **xcrun**. Then the "You can now use it like this" works.

**Comment by ggerganov** [comment]
You might want to check the latest version - it runs directly on the GPU using Metal and should be more performant than Core ML

**Comment by pudepiedj** [comment]
Thank you. I thought that was what I was doing - using the latest version - by using the command-line with **download-ggml-model.sh** as above that doesn't work. Where do I find the latest versions? What am I missing here?

**Comment by HenkPoley** [comment]
@ggerganov Does this mean models/download-coreml-model.sh is deprecated and can be removed?

I notice that the [Whisper.ccp CoreML HuggingFace repository](https://huggingface.co/datasets/ggerganov/whisper.cpp-coreml) is not available (either).

**Comment by chengyjonathan** [comment]
+1, should folks not be using the coreml support?
