### ISSUE TITLE
Any ways to generate japanese readings?

### ISSUE THREAD

**Issue by ganqqwerty** [ggerganov/whisper.cpp#1276]
In Japanese, there are chinese characters (Kanji, e.g. 日本, "nihon, nippon") and there's an alphabet (Hiragana, e.g. にほん, "ni-ho-n"). Kanji has more than one pronunciation and depends on context. When it's not clear how to read a particular Kanji, they put Hiragana near the word like that: 日本(にほん). 

Whisper.cpp generates the kanji version, but it has all pronunciation information to generate hiragana version. In fact, it should be easier to generate hiragana because it's purely pronunciation, whereas there's multiple kanjis for a given pronunciation.

Is it possible to implement the hiragana mode? Maybe it's possible to suppress certain tokens?

**Comment by bobqianic** [comment]
> Is it possible to implement the hiragana mode?

No, you might have to fine-tune the model to make that happen.
