### ISSUE TITLE
Issue with loading large model with CoreML support for PR: https://github.com/ggerganov/whisper.cpp/pull/1270

### ISSUE THREAD

**Issue by ramkumarkoppu** [ggerganov/whisper.cpp#1280]
Managed to load large model on Metal GPU and it works as per instructions in the PR.
But gets error when I tried to load large model by following CoreML instructions in the PR:

`whisper_init_from_file_no_state: loading model from './models/ggml-large.bin'
whisper_model_load: loading model
whisper_model_load: n_vocab       = 51865
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 1280
whisper_model_load: n_audio_head  = 20
whisper_model_load: n_audio_layer = 32
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 1280
whisper_model_load: n_text_head   = 20
whisper_model_load: n_text_layer  = 32
whisper_model_load: n_mels        = 80
whisper_model_load: ftype         = 1
whisper_model_load: qntvr         = 0
whisper_model_load: type          = 5
whisper_model_load: adding 1608 extra tokens
whisper_model_load: model ctx     = 2951.27 MB
whisper_model_load: model size    = 2950.66 MB
whisper_init_state: kv self size  =   70.00 MB
whisper_init_state: kv cross size =  234.38 MB
whisper_init_state: loading Core ML model from './models/ggml-large-encoder.mlmodelc'
whisper_init_state: first run on a device may take a while ...
**whisper_init_state: failed to load Core ML model from './models/ggml-large-encoder.mlmodelc'**
error: failed to initialize whisper context`

**Comment by ggerganov** [comment]
You have to generate the Core ML model with an extra step:

```
./models/generate-coreml-model.sh large
```

**Comment by ramkumarkoppu** [comment]
Worked, Thank you

**Comment by ramkumarkoppu** [comment]
Worked, Thank you

**Comment by warrenkc** [comment]
Could I get a little help?
I can get the base.en.bin to work: ./main -m models/ggml-base.en.bin -f samples/jfk.wav

But I get an error if I try to use the downloaded large model.
(bash ./models/download-ggml-model.sh large)
I can see the file downloaded as: ggml-large.bin
Then I run this command but get this error:
./main -m models/ggml-large.bin -f samples/jfk.wav             
whisper_init_from_file_with_params_no_state: loading model from 'models/ggml-large.bin'
whisper_model_load: loading model
whisper_model_load: n_vocab       = 51866
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 1280
whisper_model_load: n_audio_head  = 20
whisper_model_load: n_audio_layer = 32
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 1280
whisper_model_load: n_text_head   = 20
whisper_model_load: n_text_layer  = 32
whisper_model_load: n_mels        = 128
whisper_model_load: ftype         = 1
whisper_model_load: qntvr         = 0
whisper_model_load: type          = 5 (large v3)
whisper_model_load: adding 1609 extra tokens
whisper_model_load: n_langs       = 100
whisper_backend_init: using Metal backend
ggml_metal_init: allocating
ggml_metal_init: found device: Apple M1 Pro
ggml_metal_init: picking default device: Apple M1 Pro
ggml_metal_init: default.metallib not found, loading from source
ggml_metal_init: loading '/Users/warrenz/Temp/Testing Whsper Coreml/whisper.cpp/ggml-metal.metal'
ggml_metal_init: GPU name:   Apple M1 Pro
ggml_metal_init: GPU family: MTLGPUFamilyApple7 (1007)
ggml_metal_init: hasUnifiedMemory              = true
ggml_metal_init: recommendedMaxWorkingSetSize  = 10922.67 MB
ggml_metal_init: maxTransferRate               = built-in GPU
ggml_metal_add_buffer: allocated 'backend         ' buffer, size =  2973.44 MB, ( 2974.06 / 10922.67)
whisper_model_load:    Metal buffer size =  2973.43 MB
whisper_model_load: model size    = 2972.97 MB
whisper_backend_init: using Metal backend
ggml_metal_init: allocating
ggml_metal_init: found device: Apple M1 Pro
ggml_metal_init: picking default device: Apple M1 Pro
ggml_metal_init: default.metallib not found, loading from source
ggml_metal_init: loading '/Users/warrenz/Temp/Testing Whsper Coreml/whisper.cpp/ggml-metal.metal'
ggml_metal_init: GPU name:   Apple M1 Pro
ggml_metal_init: GPU family: MTLGPUFamilyApple7 (1007)
ggml_metal_init: hasUnifiedMemory              = true
ggml_metal_init: recommendedMaxWorkingSetSize  = 10922.67 MB
ggml_metal_init: maxTransferRate               = built-in GPU
ggml_metal_add_buffer: allocated 'backend         ' buffer, size =    70.00 MB, ( 3044.06 / 10922.67)
whisper_init_state: kv self size  =   70.00 MB
ggml_metal_add_buffer: allocated 'backend         ' buffer, size =   234.38 MB, ( 3278.44 / 10922.67)
whisper_init_state: kv cross size =  234.38 MB
whisper_init_state: loading Core ML model from 'models/ggml-large-encoder.mlmodelc'
whisper_init_state: first run on a device may take a while ...
whisper_init_state: failed to load Core ML model from 'models/ggml-large-encoder.mlmodelc'
ggml_metal_free: deallocating
error: failed to initialize whisper context
