### ISSUE TITLE
talk-llama segmentation fault with gguf

### ISSUE THREAD

**Issue by edwios** [ggerganov/whisper.cpp#1283]
Tried to use talk-llama and none of the gguf models worked, always ended up with segmentation fault: 11. Looks like llama part is not in sync with llama.cpp?

Was on a Mac M1 Max 64GB RAM, whisper.cpp commit 3fec2119e6b52d1381b02a0fbf281b1b34728c25

**Comment by ttunguz** [comment]
Same issue using a python wrapper around the whisper.cpp

**Comment by bobqianic** [comment]
It's quite normal since llama.cpp in this repository hasn't been updated for a long time. However, the latest commit has already synchronized llama.cpp, so there shouldn't be any issues. You can go ahead and try it out.

**Comment by ttunguz** [comment]
This version works much better. Thank you.

I'm trying to connect the stream_transcribe method to Python to be able to type on my computer while speaking to it. The current method prints the output of the transcription rather than passing it back as an object. Is it possible to receive the output as an object?

**Comment by bobqianic** [comment]
> Is it possible to receive the output as an object?

Yes, you can get the output as an object. This is because whisper.cpp allows for callback functions to handle results. If your Python interface lets you set up a special callback in whisper.cpp, then you can achieve what you want.

https://github.com/ggerganov/whisper.cpp/blob/951a1199265ff4424f938182542cf6bac9b36154/examples/main/main.cpp#L937-L945

**Comment by ttunguz** [comment]
Thanks, I came up with a very basic version. I appreciate the help!

from pynput.keyboard import Controller, Listener, Key
import subprocess
import threading
import re
import time
import os

# Initialize variables
typing_allowed = False
buffer = ""

def start_stream():
    subprocess.run(["./stream", "-f", "test.txt"])

def truncate_file(file_path):
    open(file_path, 'w').close()



def on_press(key):
    global typing_allowed
    if key == Key.alt_l:
        typing_allowed = True
        #truncate_file("test.txt")

def monitor_file(file_path, keyboard):
    global typing_allowed
    while True:
        if typing_allowed:
            time.sleep(4)  # Wait for 3 seconds before reading the text file
            if os.path.exists(file_path):
                with open(file_path, 'r') as f:
                    # Read all lines from the file
                    lines = f.readlines()

                # Check if there are any lines in the file
                if lines:
                    # Get the last line
                    last_line = lines[-1].strip()

                    # Remove text within brackets or parentheses
                    last_line = re.sub(r'\[.*?\]|\(.*?\)', '',
last_line).strip()

                    # Check if the filtered last line is not empty or just
whitespace
                    if last_line.strip():
                        # add a space to the end of last_line
                        last_line = last_line + " "
                        keyboard.type(last_line)

        time.sleep(1)

def on_release(key):
    global typing_allowed
    if key == Key.alt_l:
        typing_allowed = False

if __name__ == "__main__":
    keyboard = Controller()

    # Start the stream process in its own thread
    stream_thread = threading.Thread(target=start_stream)
    stream_thread.start()

    # Start the monitor_file function in its own thread
    monitor_thread = threading.Thread(target=monitor_file,
args=("test.txt", keyboard))
    monitor_thread.start()

    # Start listening to keyboard events
    with Listener(on_press=on_press, on_release=on_release) as listener:
        listener.join()
