### ISSUE TITLE
Significantly Less Accurate Results when Using Multiple Threads

### ISSUE THREAD

**Issue by DeveloperPaul123** [ggerganov/whisper.cpp#1284]
I'm aware that there is a warning for transcription accuracy when using multiple threads, but in my testing, even using something like 4 threads on a 30-40 second clip results in wildly different results from using a single thread. Is this expected? Is there any way to improve this with what `whisper.cpp` offers out of the box? 

I assume the issue is that the audio is split into even chunks which could be right in the middle of a sentence. One idea would be to try to auto detect "silence" in audio clips and split it into chunks based on that and then transcribe those chunks using multiple threads.

**Comment by bobqianic** [comment]
Which flag did you use to set the number of threads? `-p` or `-t`?

**Comment by DeveloperPaul123** [comment]
Yeah after some testing, if I set `whisper_params.n_threads = 4` and then run `whisper_full_parallel(..., 1)`, the output is correct, but I'm not sure how much of a performance benefit this gives, if at all.

**Comment by bobqianic** [comment]
> I'm currently setting this in code, not from a command line. Something like:
> 
> ```c++
> whisper_full_params whisper_params =
>                 whisper_full_default_params(WHISPER_SAMPLING_BEAM_SEARCH);
> whisper_params.n_threads = 4;
> ```

Could you let me know the value of `whisper_params.n_processors`? If this value is set to `1`, even when you invoke `whisper_full_parallel`, it should default to `whisper_full`. In this case, the audio shouldn't be split.

**Comment by DeveloperPaul123** [comment]
Yes you are correct. I did some more testing and looks like with a max thread count on 1 processor, there are some performance benefits. Sorry for the oversight on my part! And thanks for your help.

**Comment by DeveloperPaul123** [comment]
@bobqianic Do you know if the CLBlast backed is more effective than OpenBlas? It seems like there is no tensor offloading for whisper like in llama.cpp.

**Comment by bobqianic** [comment]
> @bobqianic Do you know if the CLBlast backed is more effective than OpenBlas? It seems like there is no tensor offloading for whisper like in llama.cpp.

I‘m not sure, but you can give it a try. Based on my experience with cuBLAS, there is a performance improvement, but it's not significant : )
