### ISSUE TITLE
OpenVINO on Windows does not work: cannot find whisper.dll

### ISSUE THREAD

**Issue by venkr** [ggerganov/whisper.cpp#1285]
I'm able to consistently get to a case where I'm able to build & run Whisper without OpenVINO, but when I attempt to build for OpenVINO, it cannot find the .dll. 

Here are the commands I've run to set up my env:
- Install OpenVINO (https://docs.openvino.ai/2023.0/openvino_docs_install_guides_installing_openvino_windows_header.html)
- Generate OpenVINO model (I've verified that it exists in the right spot)
```
cd models
python -m venv openvino_conv_env
openvino_conv_env\Scripts\activate
python -m pip install --upgrade pip
pip install -r openvino-conversion-requirements.txt
python convert-whisper-to-openvino.py --model base.en
```
- Run OpenVINO setup: `C:\Path\To\openvino\setupvars.bat`
- Add the right cmake dir `export OPENVINO_DIR='C:\Path\To\openvino\runtime\cmake'`

Then, I run the following flow to build and test without OpenVINO successfully:
- `cmake -B build`
- Open `build/whisper.cpp.sln` in Visual Studio 2022 and choose "Build Solution"
- Run `build/bin/Debug/main.exe -m models/ggml-base.en.bin -f samples/jfk.wav`

However, when I run the following to test with OpenVINO, I run into an error:
- `rm -rf build`
- `cmake -B build -DWHISPER_OPENVINO=1`
- Open `build/whisper.cpp.sln` in Visual Studio 2022 and choose "Build Solution"
- Run `build/bin/Debug/main.exe -m models/ggml-base.en.bin -f samples/jfk.wav`

The particular error is as follows:
`C:/Users/venki/source/whisper.cpp/build/bin/Debug/main.exe: error while loading shared libraries: whisper.dll: cannot open shared object file: No such file or directory`

**Comment by RyanMetcalfeInt8** [comment]
Hi @venkr, I just stumbled on this. Are you still having issues? whisper.dll should be present in ```C:/Users/venki/source/whisper.cpp/build/bin/Debug/ ```, so if you're not running from that directory you might need to add that folder to your ```Path``` environment var. For example, ```set Path=C:/Users/venki/source/whisper.cpp/build/bin/Debug/;%Path%```

The weird thing, of course, is that this shouldn't be specific to the OpenVINO-enabled build...

**Comment by venkr** [comment]
@RyanMetcalfeInt8 Looks like that resolves the error of not finding whisper.dll (ie: running from within the `bin/Debug` dir), but I end up getting a different error:
`C:/Users/venki/source/whisper.cpp/build/bin/Debug/main.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory`

Any idea how I could debug this further?

**Comment by RyanMetcalfeInt8** [comment]
hmm... it's not too clear which DLL's it is having trouble resolving. Can you try building  / running in Release mode? In Visual Studio change from 'Debug' to 'Release' at top of window, or if building from command line (running within ```C:/Users/venki/source/whisper.cpp/build/```):

```
cmake --build . --config Release
```

**Comment by venkr** [comment]
Resolved - this is just on me for using `Git Bash` - everything works fine as soon as I switch to using the regular command prompt.
