### ISSUE TITLE
Error while generating CoreML large model

### ISSUE THREAD

**Issue by xcottos** [ggerganov/whisper.cpp#1295]
Hi, 

I am trying to generate the CoreML model for large.

running the command: ./models/generate-coreml-model.sh large

after hours of compilation it raises an exception:

coremlc: error: compiler error:  Encountered an error while compiling a neural network model: in operation op_72: The operator (const) referenced by this operation does not match the operator defined by expected opset ios15. Is it an operator of the same name described by a different opset?

CPU: Apple M1 Max
OS: Ventura 13.3
xcode-select version 2397

any clue on how I can address it?

Thank you for this great project

Luca

**Comment by Sogl** [comment]
I have not experienced this error, but you can try to load an already converted `large` model: https://huggingface.co/chidiwilliams/whisper.cpp-coreml/blob/main/ggml-large-encoder.mlmodelc.zip

**Comment by xcottos** [comment]
thanks Sogl will try it now

**Comment by x4080** [comment]
> I have not experienced this error, but you can try to load an already converted `large` model: https://huggingface.co/chidiwilliams/whisper.cpp-coreml/blob/main/ggml-large-encoder.mlmodelc.zip

Hi, I downloaded the model from this location but its ggml-medium-encoder.mlmodelc.zip after extracting it and put inside models folder, I run :
```
cd whisper.cpp
make clean
WHISPER_COREML=1 make -j

./main -m models/ggml-medium-encoder.mlmodelc -f samples/jfk.wav
```

but the result is 
```
whisper_init_from_file_no_state: loading model from 'models/ggml-medium-encoder.mlmodelc'
whisper_model_load: loading model
whisper_model_load: invalid model data (bad magic)
whisper_init_no_state: failed to load model
error: failed to initialize whisper context
```

Did I miss something ?

Thanks for the help
