### ISSUE TITLE
No separate sentences, punctuation and capitalization

### ISSUE THREAD

**Issue by Sogl** [ggerganov/whisper.cpp#1309]
I use `large` model, command to start:
```
./main -m models/ggml-large.bin -f samples/name.wav -l ru -otxt -osrt -ocsv -oj
```

It happens that sentences, punctuation and capitalization in the text goes in parts, 20 minutes all spelled out, and then a large piece of solid text without sentences, then again normal.

What could it be?

**Comment by Sogl** [comment]
This hack helped me a little:  https://github.com/openai/whisper/discussions/194#discussioncomment-3766522 
But after 40 minutes the sentences started getting longer and losing capitalization. Is there any way to keep 100% punctuation?

**Comment by mrfragger** [comment]
I don't encounter it all that often anymore but to correct it you can use this sed script I came up with
https://github.com/ggerganov/whisper.cpp/discussions/957
