### ISSUE TITLE
Does ggml-whisper-small.bin support offloading to nvdia GPUs?  like llama.cpp models

### ISSUE THREAD

**Issue by dereklll** [ggerganov/whisper.cpp#1312]
During the test, talk-llama was found that ggml-whisper-small.bin heavily consumes CPU execution and the execution is more time consuming.

whisper_print_timings:     load time =  1192.69 ms
whisper_print_timings:     fallbacks =   0 p /   0 h
whisper_print_timings:      mel time =    35.52 ms
whisper_print_timings:   sample time =    70.64 ms /    65 runs (    1.09 ms per run)
**whisper_print_timings:   encode time =  6925.13 ms /     3 runs ( 2308.38 ms per run)**
whisper_print_timings:   decode time =   971.93 ms /    50 runs (   19.44 ms per run)
**whisper_print_timings:   prompt time =  1088.95 ms /     9 runs (  120.99 ms per run)**
whisper_print_timings:    total time = 37951.39 ms

llama_print_timings:        load time =  2508.08 ms
llama_print_timings:      sample time =   292.29 ms /    41 runs   (    7.13 ms per token,   140.27 tokens per second)
llama_print_timings: prompt eval time =  1575.87 ms /   274 tokens (    5.75 ms per token,   173.87 tokens per second)
llama_print_timings:        eval time =  1937.94 ms /    41 runs   (   47.27 ms per token,    21.16 tokens per second)
llama_print_timings:       total time = 36734.04 ms

![img_v2_3430782d-1ab3-42b4-a19b-85343975026g](https://github.com/ggerganov/whisper.cpp/assets/42927959/c3f40673-a4f9-44dd-a541-9a773eaaa78a)

hardware: orin 64G /arm64/ ubuntu

**Comment by bobqianic** [comment]
> Does ggml-whisper-small.bin support offloading to nvdia GPUs?

No, we haven't implemented CUDA offloading yet.

**Comment by dereklll** [comment]
> No, we've only implemented partial CUDA offloading so far, not full offloading.

Will there be plans to offload it all to gpu in the future?
The llama part is exceptionally well done and very much appreciated.
