### ISSUE TITLE
Does whisper.cpp needs much less memory than whisper.python?

### ISSUE THREAD

**Issue by playgithub** [ggerganov/whisper.cpp#1327]
For large model, whisper.python needs about 10GB memory while whisper.cpp needs only 3.3 GB memory, is it true?
Is it also true for GPU memory?

**Comment by mirek190** [comment]
if you are using cuda version then with the largest model takes 0.9 GB of Vram for me.

**Comment by playgithub** [comment]
Compared to whisper.python which take about 10GB vram, is it true that whisper.cpp only takes 0.9GB vram?

**Comment by playgithub** [comment]
I've tested whisper.cpp with large model v2 in GPU mode, it takes only 332MB of GPU memory.
