### ISSUE TITLE
'common-sdl.h' file not found — MacOS Sonoma

### ISSUE THREAD

**Issue by joshfarrant** [ggerganov/whisper.cpp#1336]
When trying to `make` any of the examples requiring `common-sdl.h` I run into

```
command.cpp:9:10: fatal error: 'common-sdl.h' file not found
```

I've installed `sdl2` using brew, and I've even tried building from source, but no joy.

Any suggestions appreciated, thanks

**Comment by DissonanceTK** [comment]
Same issue - MacOS Sonoma. Macbook Air M1.
`make stream
c++     stream.cpp   -o stream
stream.cpp:5:10: fatal error: 'common-sdl.h' file not found
#include "common-sdl.h"
         ^~~~~~~~~~~~~~
1 error generated.
make: *** [stream] Error 1`

**Comment by ai-at-home** [comment]
It seems likely that this error comes from not compiling in the root directory.  I am on Linux however if you attempt to compile from within the directory this is the error you get:

```
whisper.cpp/examples/stream$ make stream
g++     stream.cpp   -o stream
stream.cpp:6:10: fatal error: common/sdl.h: No such file or directory
    6 | #include "common/sdl.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: stream] Error 1
```

The solution is simply to `cd ../../` to go to the root dir then compile.

As such I don't think its a bug so much as perhaps a clarification needed in the docs.

**Comment by joyyang1215** [comment]
"The solution is simply to cd ../../ to go to the root dir then compile." --- it works
