### ISSUE TITLE
> which recognizes "Hey Google" very quickly and accurately

### ISSUE THREAD

**Issue by bobqianic** [ggerganov/whisper.cpp#1338]
> which recognizes "Hey Google" very quickly and accurately

In general, wake word detection is very different from general transcription and all of the big voice assistants use different models for each.

Wake word models are trained on many examples of the specific phrase for waking ("OK Google", "Siri", "Alexa", etc) and are trained to ignore everything else, whereas Whisper is trained to recognize anything. I wouldn't expect Whisper to perform well on wake word tasks; in general, I'd run a wake word specific model all the time and then only run Whisper on the command/spoken text.

If you're looking for efficient wake word engines, you can try https://picovoice.ai/platform/porcupine/ (commercial but free for personal use) and https://github.com/dscripka/openWakeWord (works particularly well and is very low powered).

There's also an interesting video from the Amazon Alexa team about this subject: https://www.youtube.com/watch?v=kYrw2cC9dvs

_Originally posted by @isaac-mcfadyen in https://github.com/ggerganov/whisper.cpp/issues/1232#issuecomment-1739732982_

**Comment by matijagrcic** [comment]
https://github.com/ggml-org/whisper.cpp/pull/1765
