### ISSUE TITLE
`--print-colors` output become garbled when the language is not English

### ISSUE THREAD

**Issue by AlifianK** [ggerganov/whisper.cpp#1339]
I'm sorry if this is a duplicate. This happened when I tried to input Japanese sound file together with `--print-colors` flag
![Screenshot 2023-10-01 202745](https://github.com/ggerganov/whisper.cpp/assets/50392169/4de94d72-fbeb-4e19-8655-964a0f485e97)
But the problem doesn't persist when I don't use the flag
![Screenshot 2023-10-01 202722](https://github.com/ggerganov/whisper.cpp/assets/50392169/762d2cf4-77e5-4f71-b0fe-7564cf86f01d)
I believe this is not an encoding issue with Windows since I activated the system-wide UTF-8 feature
![Screenshot 2023-10-01 204848](https://github.com/ggerganov/whisper.cpp/assets/50392169/5e8b84e3-c4fa-4af5-a127-eac581387a66)
It's interesting that the garbled characters are only some of the [Kanji](https://en.wikipedia.org/wiki/Kanji) but the [Hiragana](https://en.wikipedia.org/wiki/Hiragana) ones are not affected.

Whisper.cpp version is the latest git commit c76c11e59c65f5fe74aaf9d3951b8770b77b923b

**Comment by bobqianic** [comment]
Could you test PR #1313? I fixed the issue last week and need your feedback for merging.

**Comment by AlifianK** [comment]
PR #1313 solved the issue, thanks.
