### ISSUE TITLE
much worst transcription than official openai-whisper

### ISSUE THREAD

**Issue by piotr-sikora-v** [ggerganov/whisper.cpp#1366]
First thank for good work! Performance on my macbook is amazing!

But I have problem, maybe with some settings.
I try to use large model and on whisper.cpp i got much worst result than on official openai-whisper app.
now I only found that `-mc 0` give me little better result but still not same as openai-whisper.

which setting I should change?

Best regards!

**Comment by bobqianic** [comment]
whisper.cpp does not use beam search by default. If you want more accurate results, please adjust the `-bs` and `-bo` parameters.

**Comment by polvoazul** [comment]
Out of curiosity, why isn't that the default?

**Comment by bobqianic** [comment]
> Out of curiosity, why isn't that the default?

It's a balance between speed and accuracy. 
For most applications, greedy mode tends to be sufficient.
