### ISSUE TITLE
Java Binding - I can't build without whisper.dll

### ISSUE THREAD

**Issue by LosokosG** [ggerganov/whisper.cpp#1384]
### Discussed in https://github.com/ggerganov/whisper.cpp/discussions/1383

<div type='discussions-op-text'>

<sup>Originally posted by **LosokosG** October 21, 2023</sup>
I cannot build the project in order to get my required .jar file.
Both tests are failing.
Here is the error:
`java.lang.UnsatisfiedLinkError: Unable to load library 'whisper':
The specified module could not be found.

The specified module could not be found.

The specified module could not be found.`

I understand that it's because i don't have the whisper.dll file in the build/generated/resources, but paradoxically i can only get it by building the project.
I tried:
- re-installing gradle
- changing JDK version
- re-downloading
- using a different PC

If you need, here is the full build scan:
https://scans.gradle.com/s/umbpqzz5tb2hu</div>

**Comment by Clouke** [comment]
Try:
System.setProperty("jna.library.path", "path to your whisper.dll");

**Comment by yuvalkry** [comment]
There is a compatible Jar+DLL in the artifact
     https://github.com/ggerganov/whisper.cpp/actions/runs/6703965523
