### ISSUE TITLE
Does this do mp4 videos?

### ISSUE THREAD

**Issue by dazzng** [ggerganov/whisper.cpp#1385]
I am new to this sorry, I have some beginner questions.

Does this only suport Wav files with 16khz? I have videos that are mp4 files. Can I do them as well with this? I tired importing my mp4 videos but it gave the error, failed to read wav file.

Thanks

**Comment by bobqianic** [comment]
> Does this only suport Wav files with 16khz?

Yes, whisper models only support 16KHz `.wav` PCM audio.

> Can I do them as well with this?

Absolutely. Whisper.cpp itself cannot extract audio from `.mp4` videos and convert it to 16KHz `.wav` PCM audio, but you can achieve that by using `ffmpeg`.

**Comment by dazzng** [comment]
hey thanks for the answer. so I should use ffmpeg to convert mp4 video files to wav 16 khz audio files and then transcribe them?

**Comment by bobqianic** [comment]
> hey thanks for the answer. so I should use ffmpeg to convert mp4 video files to wav 16 khz audio files and then transcribe them?

Exactly.
