### ISSUE TITLE
ggml_metal_init fails on Intel Iris Graphics

### ISSUE THREAD

**Issue by ilya-lavrenov** [ggerganov/whisper.cpp#1393]
See https://github.com/conan-io/conan-center-index/pull/20774#issuecomment-1781921265

With 1.4.2 version simple test in Conan https://github.com/conan-io/conan-center-index/blob/49b151e872b2d4376097e35ed416f69c03090aba/recipes/whisper-cpp/all/test_package/test_package.cpp has passed, but with current master it fails with the following error on macOS:

```
ggml_metal_init: allocating
ggml_metal_init: found device: Intel Iris Graphics
ggml_metal_init: picking default device: Intel Iris Graphics
ggml_metal_init: loading '(null)'
ggml_metal_init: error: Error Domain=NSCocoaErrorDomain Code=258 "The file name is invalid."
whisper_init_state: ggml_metal_init() failed
```

I suppose Metal is not available on Intel iGPU? Should it be silently handled in whisper.cpp code?

**Comment by bobqianic** [comment]
See #1292 #1294
