### ISSUE TITLE
Large model differences?

### ISSUE THREAD

**Issue by chrisspen** [ggerganov/whisper.cpp#1396]
In `download-ggml-model.sh` is see three "large" models referenced, `large-v1`, `large`, and `large-q5_0`.

However, I can't find any documentation for these. What are their functional differences?

**Comment by bobqianic** [comment]
- large == large-v2
- large-v1 == large-v1
- large-q5_0 == quantized large-v2

**The difference between large-v1 and large-v2:**
https://github.com/openai/whisper/discussions/661

**WER (smaller is better):**
`large <= large-v1 < large-q5_0`

I find this quite confusing. I'm not sure why people name it like this : )

**Comment by chrisspen** [comment]
Ah, so you're saying I should use `large` for the best accuracy?

**Comment by bobqianic** [comment]
> Ah, so you're saying I should use `large` for the best accuracy?

Exactly.
