### ISSUE TITLE
Livestreaming audio in Python using pybind

### ISSUE THREAD

**Issue by NebilI** [ggerganov/whisper.cpp#140]
Are there any plans / would it be possible to use pybind11 to make a python library to enable easy use of live streaming audio in python? I was considering pursuing this but wanted to know the feasibility.

Great project btw!

**Comment by chidiwilliams** [comment]
I use ctypes to generate Python bindings and can attest that it works fine: 

https://github.com/chidiwilliams/buzz/blob/main/Makefile#L77

**Comment by NebilI** [comment]
Thank you! I @chidiwilliams still think it's worth pursuing pybind. Currently have most of the functions implemented but haven't started much testing yet I will keep you updated on the progress. @ggerganov

**Comment by ggerganov** [comment]
Closing this in favor of #9
