### ISSUE TITLE
Generate libwhisper.a for ios

### ISSUE THREAD

**Issue by Prateek0001** [ggerganov/whisper.cpp#1403]
I want to create a static library (libwhisper.a) so that i can use in my flutter project . Dynamic library for android libwhisper.so works fine in flutter app using ffi , i want to same for ios as well . Any suggestion ? File generated using make libwhisper.a gives error ggml.o is built for MacOS

**Comment by garyhai** [comment]
Memory map issue of iOS static library building is fixed in current release version 1.4.3.

**Comment by Prateek0001** [comment]
It will great if you can help me out in creating a static or dynamic library so that i can call using dart ffi , i have used both whisper cpp and llama cpp as a independent flutter project but i cant use it in same project as symbol collides for ggml and ggml-alloc files

**Comment by garyhai** [comment]
Compile and link are all passed on my side. whisper-rs with updated new version of whisper.cpp.

**Comment by Prateek0001** [comment]
hey @garyhai i want to use whisper.cpp swift package in my project , when i add this in my project i get "The package product 'whisper' cannot be used as a dependency of this target because it uses unsafe build flags" ..... I also commented .unsafeFlags(["-fno-objc-arc"]), .unsafeFlags(["-Wno-shorten-64-to-32", "-O3", "-DNDEBUG"]), .... but error is same .......... Previously i maked framework for whisper.cpp and it was working but it was not using gpu , i have taken pull from whisper.cpp and tried creating framework from latest files but it crash at runtime

**Comment by Prateek0001** [comment]
Yes @garyhai i have added Accelerate.framework

**Comment by Prateek0001** [comment]
I have created the framework for whisper cpp and its function can be called from dart , i am closing the issue.

**Comment by hfyydd** [comment]
> hey @garyhai i want to use whisper.cpp swift package in my project , when i add this in my project i get "The package product 'whisper' cannot be used as a dependency of this target because it uses unsafe build flags" ..... I also commented .unsafeFlags(["-fno-objc-arc"]), .unsafeFlags(["-Wno-shorten-64-to-32", "-O3", "-DNDEBUG"]), .... but error is same .......... Previously i maked framework for whisper.cpp and it was working but it was not using gpu , i have taken pull from whisper.cpp and tried creating framework from latest files but it crash at runtime

Please tell me how to solve it? Thanks

**Comment by maiqingqiang** [comment]
use specify the version with a commit hash
<img width="1065" alt="image" src="https://github.com/ggerganov/whisper.cpp/assets/1825679/1206947b-ed0e-4584-9e64-5e57b8b20f6f">

**Comment by metropol** [comment]
And remember to Clean Build Folder after changing the dependency rule to a specific commit hash.
