### ISSUE TITLE
Retrieve model version/identifier (string) at runtime?

### ISSUE THREAD

**Issue by damian0815** [ggerganov/whisper.cpp#1406]
Is there any way of retrieving any kind of model identifier metadata for the loaded whisper model, such as a version string? I could not find anything in what appeared to be any of the relevant structs, and a full repo search for the string "version" only returns GGML_QNT_VERSION which is the quantization format version, not the actual whisper model version.

**Comment by damian0815** [comment]
Ok, it seems the "official" version information is simply an SHA1 hash of the model .bin file so i guess this feature isn't necessary

**Comment by vade** [comment]
I was thinking we could use the release tag of whisper.cpp we are using?
