### ISSUE TITLE
command.wasm build - Aborted(OOM)

### ISSUE THREAD

**Issue by feuler** [ggerganov/whisper.cpp#1412]
Hi,

i've tried to build command.wasm like described in the instruction with:

mkdir build-em && cd build-em
emcmake cmake ..
make -j

Unfortunately when i try to use the generated files i get "Aborted(OOM)"

Any ideas why ?
Below are the error outputs.

emscripten version:
em++ --version
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.2 (a77b559a8b40b7e89fc8c17e41034128df9543e4)

cmake version: 3.25.1

command.wasm - html text box output:

storeFS: stored model: whisper.bin size: 147964211
whisper_init_from_file_no_state: loading model from 'whisper.bin'
whisper_model_load: loading model
whisper_model_load: n_vocab       = 51864
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 512
whisper_model_load: n_audio_head  = 8
whisper_model_load: n_audio_layer = 6
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 512
whisper_model_load: n_text_head   = 8
whisper_model_load: n_text_layer  = 6
whisper_model_load: n_mels        = 80
whisper_model_load: ftype         = 1
whisper_model_load: qntvr         = 0
whisper_model_load: type          = 2
whisper_model_load: adding 1607 extra tokens
whisper_model_load: model ctx     =  140.66 MB
whisper_model_load: model size    =  140.54 MB
whisper_init_state: kv self size  =    5.25 MB
whisper_init_state: kv cross size =   17.58 MB
Aborted(OOM)

Browser Console:

 Aborted(OOM)
command.js:1 Uncaught RuntimeError: Aborted(OOM). Build with -sASSERTIONS for more info.
    at abort (command.js:1:7240)
    at abortOnCannotGrowMemory (command.js:1:867752)
    at _emscripten_resize_heap (command.js:1:867855)
    at 0023533e:0xa2cb
    at 0023533e:0x25cb
    at 0023533e:0x50bd0
    at 0023533e:0x327d4
    at 0023533e:0x3fd7
    at 0023533e:0x2e8ef
    at 0023533e:0x7f10c

**Comment by feuler** [comment]
Solved issue by editing examples/command.wasm/CMakeLists.txt and changed INITIAL_MEMORY + TOTAL_MEMORY to 2048MB

**Comment by JayS0223** [comment]
> Solved issue by editing examples/command.wasm/CMakeLists.txt and changed INITIAL_MEMORY + TOTAL_MEMORY to 2048MB

where to find this file ??

**Comment by feuler** [comment]
> > Solved issue by editing examples/command.wasm/CMakeLists.txt and changed INITIAL_MEMORY + TOTAL_MEMORY to 2048MB
> 
> where to find this file ??

Here: https://github.com/ggerganov/whisper.cpp/tree/master/examples/command.wasm

**Comment by JayS0223** [comment]
CMakeLists.txt

i am not able to find the file

[image: image.png]
Also attached the Image that's there in my command.wasm file, if possible
can you guide me
And if possible we can have a google meet.
