### ISSUE TITLE
[Android] Issue with no translation results in Android Demo app

### ISSUE THREAD

**Issue by flitto-minjin-kim** [ggerganov/whisper.cpp#1421]
## Code
``` kotlin
    suspend fun transcribeData(data: FloatArray): String = withContext(scope.coroutineContext) {
        require(ptr != 0L)
        val numThreads = WhisperCpuConfig.preferredThreadCount
        Log.d(LOG_TAG, "Selecting $numThreads threads")
        WhisperLib.fullTranscribe(ptr, numThreads, data)
        val textCount = WhisperLib.getTextSegmentCount(ptr) // The result is always 0.
        return@withContext buildString {
            for (i in 0 until textCount) {
                append(WhisperLib.getTextSegment(ptr, i))
            }
        }
    }
```
<b>Calling that function always outputs an empty value.</b>

## ScreenShot
| App Ui | Sample Tree |
:-:|:-:
<img src="https://github.com/ggerganov/whisper.cpp/assets/141105397/48a597c7-1594-4287-b370-03df98d55ab8" width="250"/>| <image src="https://github.com/ggerganov/whisper.cpp/assets/141105397/111340de-a368-4ecb-90dd-823b8ee6fac2" width="250"/>

**Comment by ggerganov** [comment]
You are using a "test" model: `for-tests-ggml-base.bin`
These models are used only for tests and cannot be used for transcription

**Comment by aicareles** [comment]
> You are using a "test" model: `for-tests-ggml-base.bin` These models are used only for tests and cannot be used for transcription

if I want used for transcription, where is ggml-base.bin?

**Comment by Krulvis** [comment]
This page explains how to get a model https://github.com/ggerganov/whisper.cpp/tree/master/models
