### ISSUE TITLE
Extra newlines and text?

### ISSUE THREAD

**Issue by chrisspen** [ggerganov/whisper.cpp#1427]
Is there significance to the seemingly random newlines and extra text that Whisper inserts into its transcriptions?

It doesn't happen every time, but for certain audio clips, Whisper will break the transcription into multiple lines and sometimes even add extra text that is either redundant or not in the audio. Does this signify an "alternate" transcription or is it just an error?

For example, I have an audio file of a man saying, "Typhoid, did I tell you?" and Whispher's raw output is:

    Typhoid, did I tell you?
    tell you

So, pretty close, but it's adding that extra line in for some reason. Any idea why? I have a few other examples and their files to share if anyone's interested in debugging this.

**Comment by bobqianic** [comment]
This is simply an error, stemming from the model's hallucination. It's a widely discussed issue in the field of LLM.
