### ISSUE TITLE
Possible to update the release version?

### ISSUE THREAD

**Issue by magnusviri** [ggerganov/whisper.cpp#1433]
I am working with a package manager called [pkgx](https://github.com/pkgxdev) and it builds new packages when a new version is released. There is a [package for whisper](https://github.com/pkgxdev/pantry/blob/main/projects/github.com/ggerganov/whisper.cpp/package.yml) but it's stuck at 1.4.0 because that's [your last release](https://github.com/ggerganov/whisper.cpp/releases).

**Comment by Linux13524** [comment]
We also would need a new release version for updating the [Conan Center Index recipe](https://github.com/conan-io/conan-center-index/tree/master/recipes/whisper-cpp)  :wink:

**Comment by bobqianic** [comment]
> I'll try to make a minor 1.4.1 release tomorrow, before the new major release 1.5.0 that I'm aiming for this week

Actually, we've already progressed to Beta 1.4.2, so rolling out a new 1.4.1 release wouldn't make sense. You can see the latest version here: https://github.com/ggerganov/whisper.cpp/releases/tag/v1.4.2

<img width="869" alt="image" src="https://github.com/ggerganov/whisper.cpp/assets/129547291/29a4f836-74fd-49c1-8464-0484141e3602">
