### ISSUE TITLE
Shared library

### ISSUE THREAD

**Issue by mason-acronode** [ggerganov/whisper.cpp#144]
Hi，ggerganov.
I really appreciate for your effort.
I'd like to make .net application using the dynamic dll. I realized that whisper is compiled the static library when I built using makefile.
Is is enough to add the shared library compiling step in makefile?

**Comment by ggerganov** [comment]
I think yes. In any case you can use CMake - it already builds a shared library and it works.
Or you can directly build the latest `.dll` from the automated Github actions:

https://github.com/ggerganov/whisper.cpp/actions
