### ISSUE TITLE
Cannot build talk-llama. "error: use of undeclared identifier 'lcparams'"

### ISSUE THREAD

**Issue by johnmw** [ggerganov/whisper.cpp#1443]
I think this commit broke building talk-llama? (I'm on Mac silicon?)

https://github.com/ggerganov/whisper.cpp/commit/3989b29a9b0a2c0de92e848957d9a47635957f84

I get the error: "error: use of undeclared identifier 'lcparams'"

Version 1.4.2 builds.

**Comment by bobqianic** [comment]
The issue should be resolved in #1442.
