### ISSUE TITLE
Chinese Traditional to Simplified

### ISSUE THREAD

**Issue by summerHearts** [ggerganov/whisper.cpp#1450]
-dl,       --detect-language   [false  ] exit after automatically detecting language
             --prompt PROMPT     [以下是普通話的句子。] initial prompt

./main -m models/ggml-base.bin -f  demo.wav 

system_info: n_threads = 4 / 8 | AVX = 0 | AVX2 = 0 | AVX512 = 0 | FMA = 0 | NEON = 0 | ARM_FMA = 0 | METAL = 1 | F16C = 0 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | COREML = 0 | OPENVINO = 0 | 

main: processing '/Users/yaoyajie/Downloads/1699425251144.wav' (180800 samples, 11.3 sec), 4 threads, 1 processors, lang = zh, task = transcribe, timestamps = 1 ...

[00:00:00.000 --> 00:00:11.000]  公譽善其事,必先立其棄。進行開發工作時,利用並熟練使用恰當的工具可以讓工作效率得到大幅度提高。下邊。

How can i convert Traditional Chinese to Simplified Chinese?  Thanks

**Comment by Glowin** [comment]
`./main -m models/ggml-base.bin -f demo.wav --prompt "以下是普通话的句子"`

**Comment by markpopjason** [comment]
> failed for windows

如果你是用命令行的方式，可能是 windows 下命令行传参编码问题，可以试下用utf8 编码的文件方式传参，我试了下确实没有繁体字了

**Comment by tosinonikute** [comment]
Commenting to Bookmark issue!
