### ISSUE TITLE
talk-llama: say command not found

### ISSUE THREAD

**Issue by hbarnard** [ggerganov/whisper.cpp#1465]
Thanks for this work, highly appreciated. I'm getting quite good results on an orangepi5, using wizardLM-7B.ggmlv3.q4_0.bin that I've converted to gguf.

When I test talk-llama, I get this in the exchanges:
```
Georgi:./examples/talk-llama/speak: line 13: say: command not found
main: failed to speak
```
This isn't a big deal, but a little annoying.

**Comment by ggerganov** [comment]
You can edit the script `./examples/talk-llama/speak` to use any TTS you'd like. You can make it empty to disable speaking completely

**Comment by hbarnard** [comment]
Thanks, my bad, should have peeked into the script first. But hopefully will help someone else too.
