### ISSUE TITLE
[Regression?] OpenVINO GPU inference performance loss after v1.5.0

### ISSUE THREAD

**Issue by li-yifei** [ggerganov/whisper.cpp#1506]
Thank you for your great work that makes my intel mini pc running whisper medium model smoothly,
But I would like to report a performance issue after upgrading to v1.5.0

## Platform
Whisper.cpp: v1.5(bebf0da)
Hardware: Intel Core N305 iGPU
OS: Ubuntu 22.04
Compiler: GNU 12.3
OpenVINO: 2023.1.0

## Comparision
Sorry but I can't provide the voice file that is a private conversation.

Command: `build/bin/main -m models/ggml-medium.bin -l ja -f 16k.wav -oved GPU`
<details><summary>v1.4.3 output (total time = 205878.44 ms) </summary>
whisper_init_from_file_with_params_no_state: loading model from 'models/ggml-medium.bin'
whisper_model_load: loading model
whisper_model_load: n_vocab       = 51865
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 1024
whisper_model_load: n_audio_head  = 16
whisper_model_load: n_audio_layer = 24
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 1024
whisper_model_load: n_text_head   = 16
whisper_model_load: n_text_layer  = 24
whisper_model_load: n_mels        = 80
whisper_model_load: ftype         = 1
whisper_model_load: qntvr         = 0
whisper_model_load: type          = 4 (medium)
whisper_model_load: adding 1608 extra tokens
whisper_model_load: n_langs       = 99
whisper_model_load: model ctx     = 1462.58 MB
whisper_model_load: model size    = 1462.12 MB
whisper_init_state: kv self size  =   42.00 MB
whisper_init_state: kv cross size =  140.62 MB
whisper_init_state: compute buffer (conv)   =   33.15 MB
whisper_init_state: compute buffer (encode) =  162.33 MB
whisper_init_state: compute buffer (cross)  =    7.42 MB
whisper_init_state: compute buffer (decode) =   47.83 MB
whisper_ctx_init_openvino_encoder: loading OpenVINO model from 'models/ggml-medium-encoder-openvino.xml'
whisper_ctx_init_openvino_encoder: first run on a device may take a while ...
whisper_openvino_init: path_model = models/ggml-medium-encoder-openvino.xml, device = GPU, cache_dir = models/ggml-medium-encoder-openvino-cache
whisper_ctx_init_openvino_encoder: OpenVINO model loaded

system_info: n_threads = 4 / 8 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | METAL = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | COREML = 0 | OPENVINO = 1 |

main: processing '16k.wav' (3645347 samples, 227.8 sec), 4 threads, 1 processors, lang = ja, task = transcribe, timestamps = 1 ...
whisper_print_timings:     load time =   735.09 ms
whisper_print_timings:     fallbacks =   0 p /   0 h
whisper_print_timings:      mel time =   242.99 ms
whisper_print_timings:   sample time =  1018.15 ms /  1382 runs (    0.74 ms per run)
whisper_print_timings:   encode time = 83139.22 ms /     9 runs ( 9237.69 ms per run)
whisper_print_timings:   decode time = 69705.23 ms /  1369 runs (   50.92 ms per run)
whisper_print_timings:   prompt time = 47457.76 ms /    11 runs ( 4314.34 ms per run)
whisper_print_timings:    total time = 205878.44 ms
</details>

<details><summary>v1.5.0 output (total time = 409269.66 ms)</summary>
whisper_init_from_file_with_params_no_state: loading model from 'models/ggml-medium.bin'
whisper_model_load: loading model
whisper_model_load: n_vocab       = 51865
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 1024
whisper_model_load: n_audio_head  = 16
whisper_model_load: n_audio_layer = 24
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 1024
whisper_model_load: n_text_head   = 16
whisper_model_load: n_text_layer  = 24
whisper_model_load: n_mels        = 80
whisper_model_load: ftype         = 1
whisper_model_load: qntvr         = 0
whisper_model_load: type          = 4 (medium)
whisper_model_load: adding 1608 extra tokens
whisper_model_load: n_langs       = 99
whisper_model_load:      CPU buffer size =  1551.93 MB
whisper_model_load: model size    = 1551.57 MB
whisper_init_state: kv self size  =  132.12 MB
whisper_init_state: kv cross size =  147.46 MB
whisper_init_state: compute buffer (conv)   =   25.54 MB
whisper_init_state: compute buffer (encode) =  170.21 MB
whisper_init_state: compute buffer (cross)  =    7.78 MB
whisper_init_state: compute buffer (decode) =   98.25 MB
whisper_ctx_init_openvino_encoder: loading OpenVINO model from 'models/ggml-medium-encoder-openvino.xml'
whisper_ctx_init_openvino_encoder: first run on a device may take a while ...
whisper_openvino_init: path_model = models/ggml-medium-encoder-openvino.xml, device = GPU, cache_dir = models/ggml-medium-encoder-openvino-cache
whisper_ctx_init_openvino_encoder: OpenVINO model loaded

system_info: n_threads = 4 / 8 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | METAL = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | CUDA = 0 | COREML = 0 | OPENVINO = 1 |

main: processing '16k.wav' (3645347 samples, 227.8 sec), 4 threads, 1 processors, 5 beams + best of 5, lang = ja, task = transcribe, timestamps = 1 ...

whisper_print_timings:     load time =   684.52 ms
whisper_print_timings:     fallbacks =   0 p /   0 h
whisper_print_timings:      mel time =   221.28 ms
whisper_print_timings:   sample time =  4824.47 ms /  6679 runs (    0.72 ms per run)
whisper_print_timings:   encode time = 87423.93 ms /    10 runs ( 8742.39 ms per run)
whisper_print_timings:   decode time =  2272.87 ms /    38 runs (   59.81 ms per run)
whisper_print_timings:   batchd time = 260137.59 ms /  6590 runs (   39.47 ms per run)
whisper_print_timings:   prompt time = 52653.77 ms /  1496 runs (   35.20 ms per run)
whisper_print_timings:    total time = 409269.66 ms
</details>

## How to reproduce

1. download `l_openvino_toolkit_ubuntu22_2023.1.0.12185.47b736f63ed_x86_64` package
2. checkout whisper.cpp to current master (bebf0da)
3. convert models for openvino
4. build as tutorial 
``` Bash
cmake -B build -DWHISPER_OPENVINO=1 -DBUILD_SHARED_LIBS=OFF -DCMAKE_PREFIX_PATH=../l_openvino_toolkit_ubuntu22_2023.1.0.12185.47b736f63ed_x86_64/runtime .
cmake --build build --target main --config Release
``` 
5. run `build/bin/main -m models/ggml-medium.bin -l ja -f 16k.wav -oved GPU`
6. cleanup and checkout v1.4.3
7. build and run again

**Comment by ggerganov** [comment]
With v1.5.0, beam search is enabled by default which can result in more processing in the Decoder.
Add `-bs 1` to your command-line arguments to restore greedy / best-of sampling as in v1.4.3. With this, the performance should be similar as before
