### ISSUE TITLE
Generate a Core ML for fine-tuned Hugging Face model.

### ISSUE THREAD

**Issue by JRWSP** [ggerganov/whisper.cpp#1510]
Hello, 

I want to run a fine-tuned model on Core ML. For generating a Core ML model from `generate-coreml-model.sh`, I can only use for it for standard whisper models. How can I generate the Core ML model for the model from Hugging Face. E.g. [this small-jp model](https://huggingface.co/vumichien/whisper-small-ja)?

**Comment by ggerganov** [comment]
Rename the `ggml` fine-tuned model to `ggml-small.bin` and use `generate-coreml-model.sh` as usual

**Comment by JRWSP** [comment]
Wow, I did not think of this simple solution. Thanks!

**Comment by JRWSP** [comment]
Wow, I did not think of this simple solution. Thanks!
