### ISSUE TITLE
Option --cmd with main application

### ISSUE THREAD

**Issue by vansatchen** [ggerganov/whisper.cpp#1513]
Hi! Thanks for great stuff!
In my project i need to transcribe single words from an audio file, like "yes", "no", "may be" and other.
Is there any chance to use option like --cmd from application "command", with application "main", or use application "command" for transcribe audio files?
Thanks!

**Comment by felrock** [comment]
You could pipe the output from main into a script, you can use regex for extracting the individual words, like yes and no.

**Comment by vansatchen** [comment]
> You could pipe the output from main into a script, you can use regex for extracting the individual words, like yes and no.

At this time i use this method, but with --cmd i can rate possible options. I think this is the better way.

**Comment by vansatchen** [comment]
I think that in --cmd option used module like FuzzyWuzzy or Levenstein
So, using this modules, i get same results
>>> from fuzzywuzzy import process
>>> words = ["no", "no"]
>>> process.extractOne("not", words)
('no', 90)
