### ISSUE TITLE
Hullucinating issues

### ISSUE THREAD

**Issue by dubefab** [ggerganov/whisper.cpp#1515]
When I try transcribing (especially with large-v3) an English .wav that's about 60 minutes long. If there's a song somewhere in the video that repeats the same thing, it will start getting stuck in a loop of transcribing the same thing over and over again and won't even finish the transcription. Is there something I can do about this? Like options to enable? Thanks

**Comment by taivlam** [comment]
I've also noticed that `large-v3*` overall performs worse than `large-v2*`.

Either `large-v3*` works until it experiences a repetitive hallucination at some point into the audio file (some examples: 3 min into a 2 hr recording, and 40 min into a 1 hr recording); or `large-v3*` avoids a repetitive hallucination loop at the cost of performing overall worse than even `large-v1*`.

See the following for reference:

* GH issue #1507 from this repo
* Discussion from [openai/whisper#1762 (comment)](https://github.com/openai/whisper/discussions/1762#discussioncomment-7532295)
* GH discussion #1911 from this repo
