### ISSUE TITLE
Full GPU Support for Release.

### ISSUE THREAD

**Issue by AeneasZhu** [ggerganov/whisper.cpp#1517]
I am sorry, I don't much about coding. But Whisper.cpp helps me a lot in my life and work. The release versions seem not to support CUDA gpu by default, while users have to build on their own. However, I know few about stuff like "Make" or "CMake" and thus don't know how to build it on my Windows PC. Could you release a version with full GPU support? Thank you.

**Comment by Ajaja** [comment]
Just use artifact ```whisper-cublas-bin-x64```  from actions. But you also have to install CUDA Toolkit 12.1 from nvidia.com  or just extract  ```cublas64_12.dll```, ```cublasLt64_12.dll``` and  ```cudart64_12.dll``` libraries from the toolkit and put when into whisper.cpp folder.

**Comment by AeneasZhu** [comment]
> Just use artifact `whisper-cublas-bin-x64` from actions. But you also have to install CUDA Toolkit 12.1 from nvidia.com or just extract `cublas64_12.dll`, `cublasLt64_12.dll` and `cudart64_12.dll` libraries from the toolkit and put them into whisper.cpp folder.

I have installed the CUDA Toolkit. But I input `main` in terminal and nothing happens.

**Comment by Ajaja** [comment]
Strange. Maybe it needs ```cublas64_12.dll```, ```cublasLt64_12.dll``` and ```cudart64_12.dll``` in the folder with ```main.exe```. I have RTX 2060 and everything works well with ```whisper-cublas-bin-x64``` artifacts from ```master``` tree and those 3 dlls from CUDA toolkit.

**Comment by bobqianic** [comment]
> Maybe it needs cublas64_12.dll, cublasLt64_12.dll and cudart64_12.dll in the folder with main.exe

Yes.

We should add these `.dll` files to the release, for added convenience.
