### ISSUE TITLE
bug or feature by design when handle sdl callback?

### ISSUE THREAD

**Issue by yexiangyu** [ggerganov/whisper.cpp#1518]
file: examples/common-sdl.cpp, line: 156

`memcpy(&m_audio[0], &stream[n0], (n_samples - n0) * sizeof(float));`

should change to 

`memcpy(&m_audio[0], &stream[n0 * sizeof(float)], (n_samples - n0) * sizeof(float));`

https://github.com/ggerganov/whisper.cpp/blob/e2f0eba2d4dbe4ded5625cbd8a9c17e13f2482f6/examples/common-sdl.cpp#L156C1-L156C80

**Comment by bobqianic** [comment]
Indeed, you're correct. This appears to be a bug.
#1164

**Comment by bobqianic** [comment]
> `memcpy(&m_audio[0], &stream[n0 * sizeof(float)], (n_samples - n0) * sizeof(float));`

The logic in this case isn't entirely flawless. Consider a scenario where your `n_samples` unexpectedly grows to be much larger than `m_audio.size()` – for instance, ten times larger. This could result in undefined behavior, as it involves attempting to write data beyond the bounds of the array.

https://github.com/ggerganov/whisper.cpp/blob/e2f0eba2d4dbe4ded5625cbd8a9c17e13f2482f6/examples/common-sdl.cpp#L152-L165

**Comment by ggerganov** [comment]
Thank you for spotting this!

Could you check https://github.com/ggerganov/whisper.cpp/pull/1523 - I think it should fix the issues
