### ISSUE TITLE
whisper framework for ios 

### ISSUE THREAD

**Issue by Prateek0001** [ggerganov/whisper.cpp#1525]
Hey i want to create whisper cpp framework for ios which uses gpu for performance which functions can be called from dart ffi , i have added whisper swift package but its function are not visible from dart but i am sure framework will work.

**Comment by Prateek0001** [comment]
It will be great if you can provide all required files with flags so that i can create a framework @ggerganov

**Comment by ggerganov** [comment]
I have very basic ios development experience. If there is something that can be improved, please send a PR

**Comment by Prateek0001** [comment]
Thanks @ggerganov i have created the whisper framework for ios . I am closing the issue.
