### ISSUE TITLE
Why does whisper.cpp not support Chinese recognition

### ISSUE THREAD

**Issue by litongjava** [ggerganov/whisper.cpp#1531]
Whisper supports Chinese recognition. Whisper is an advanced speech recognition system developed by OpenAI, capable of recognizing and transcribing multiple languages, including Chinese. This means Whisper can recognize Chinese speech and convert it into Chinese text. Thanks to its advanced deep learning model, Whisper excels in handling a variety of languages and dialects. Why does whisper.cpp not support Chinese recognition?

**Comment by flameddd** [comment]
what's your issue ? you can indicate language with `-l` flag

```
 -l zh
```

**Comment by litongjava** [comment]
I tested it, it supports Chinese recognition, but the result is very bad.But Whipser recognizes it better than that.Why?

**Comment by yexiangyu** [comment]
> I tested it, it supports Chinese recognition, but the result is very bad.But Whipser recognizes it better than that.Why?

- please consider to use prompt like, `--prompt "请用简体中文输出"`
- use `-l zh`
- use larger model if tiny is used.

**Comment by litongjava** [comment]
thanks.

**Comment by sheng-di** [comment]
How to enable multiple language output?
