### ISSUE TITLE
i can't build WHISPER_CLBLAST

### ISSUE THREAD

**Issue by dyt06** [ggerganov/whisper.cpp#1566]
if (WHISPER_CLBLAST)
    find_package(CLBlast)
    if (CLBlast_FOUND)
        message(STATUS "CLBlast found")

        set(GGML_SOURCES_OPENCL ggml-opencl.cpp ggml-opencl.h)

        add_compile_definitions(GGML_USE_CLBLAST)

        set(WHISPER_EXTRA_LIBS ${WHISPER_EXTRA_LIBS} clblast)
    else()
        message(FATAL_ERROR "CLBlast not found")
    endif()
endif()

message(FATAL_ERROR "CLBlast not found")：i can't build WHISPER_CLBLAST。

**Comment by Theadmaster** [comment]
cmake -B build -DWHISPER_CLBLAST=ON -DCMAKE_PREFIX_PATH=${path_to_CLBlast}

**Comment by dyt06** [comment]
hank you everyone.

**Comment by dyt06** [comment]
Thank you everyone.
