### ISSUE TITLE
error occured when run code'make'

### ISSUE THREAD

**Issue by BearsEatLardCake** [ggerganov/whisper.cpp#1577]
$ make
which: no nvcc in (/c/Users/n/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/usr/bin:
/mingw64/bin:/usr/bin:/c/Users/n/bin:/c/Windows/system32:/c/Windows:/c/Windows/S
ystem32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Windows/System32/Open
SSH:/c/Users/n/anaconda3:/c/Users/n/anaconda3/Scripts:/c/Users/n/anaconda3/Libra
ry/bin:/c/Users/n/anaconda3/Library/mingw-w64/bin:/cmd:/c/Program Files/Cloudfla
re/Cloudflare WARP:/c/Python/Scripts:/c/Program Files/MySQL/MySQL Server 8.0/bin
:/c/Program Files/Docker/Docker/resources/bin:/c/Users/n/AppData/Roaming/Python/
Python39/Scripts:/c/Program Files/dotnet:/d/mingw64/bin:/c/Users/n/mingw64/bin:/
c/Users/n/AppData/Local/Microsoft/WindowsApps:/c/Users/n/AppData/Local/Programs/
Microsoft VS Code/bin:/d/PyCharm 2023.2/bin:/c/Python/Scripts:/d/mingw64/bin:/us
r/bin/vendor_perl:/usr/bin/core_perl)
I whisper.cpp build info:
I UNAME_S:  MINGW64_NT-10.0-19045
I UNAME_P:  unknown
I UNAME_M:  x86_64
I CFLAGS:   -I.              -O3 -DNDEBUG -std=c11   -fPIC -D_XOPEN_SOURCE=600 -
mavx -mavx2 -mfma -mf16c -msse3 -mssse3
I CXXFLAGS: -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -D_XOPEN_SOURCE=600 -
mavx -mavx2 -mfma -mf16c -msse3 -mssse3
I LDFLAGS:
I CC:       cc (x86_64-win32-seh-rev0, Built by MinGW-W64 project) 8.1.0
I CXX:      g++.exe (x86_64-win32-seh-rev0, Built by MinGW-W64 project) 8.1.0

g++ -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -D_XOPEN_SOURCE=600 -mavx -ma
vx2 -mfma -mf16c -msse3 -mssse3 -c whisper.cpp -o whisper.o
whisper.cpp: In function 'bool log_mel_spectrogram(whisper_state&, const float*,
 int, int, int, int, int, int, const whisper_filters&, bool, whisper_mel&)':
whisper.cpp:2882:26: error: 'thread' is not a member of 'std'
         std::vector<std::thread> workers(n_threads - 1);
                          ^~~~~~
whisper.cpp:2882:26: note: 'std::thread' is defined in header '<thread>'; did yo
u forget to '#include <thread>'?
whisper.cpp:40:1:
+#include <thread>

whisper.cpp:2882:26:
         std::vector<std::thread> workers(n_threads - 1);
                          ^~~~~~
whisper.cpp:2882:26: error: 'thread' is not a member of 'std'
whisper.cpp:2882:26: note: 'std::thread' is defined in header '<thread>'; did yo
u forget to '#include <thread>'?
whisper.cpp:2882:32: error: template argument 1 is invalid
         std::vector<std::thread> workers(n_threads - 1);
                                ^
whisper.cpp:2882:32: error: template argument 2 is invalid
whisper.cpp:2884:23: error: invalid types 'int[int]' for array subscript
             workers[iw] = std::thread(
                       ^
whisper.cpp:2884:32: error: 'thread' is not a member of 'std'
             workers[iw] = std::thread(
                                ^~~~~~
whisper.cpp:2884:32: note: 'std::thread' is defined in header '<thread>'; did yo
u forget to '#include <thread>'?
whisper.cpp:2894:23: error: invalid types 'int[int]' for array subscript
             workers[iw].join();
                       ^
whisper.cpp: In function 'whisper_full_params whisper_full_default_params(whispe
r_sampling_strategy)':
whisper.cpp:4357:61: error: 'std::thread' has not been declared
         /*.n_threads         =*/ std::min(4, (int32_t) std::thread::hardware_co
ncurrency()),
                                                             ^~~~~~
whisper.cpp: In function 'int whisper_full_with_state(whisper_context*, whisper_
state*, whisper_full_params, const float*, int)':
whisper.cpp:5387:42: error: 'thread' is not a member of 'std'
                         std::vector<std::thread> threads(n_threads - 1);
                                          ^~~~~~
whisper.cpp:5387:42: note: 'std::thread' is defined in header '<thread>'; did yo
u forget to '#include <thread>'?
whisper.cpp:5387:42: error: 'thread' is not a member of 'std'
whisper.cpp:5387:42: note: 'std::thread' is defined in header '<thread>'; did yo
u forget to '#include <thread>'?
whisper.cpp:5387:48: error: template argument 1 is invalid
                         std::vector<std::thread> threads(n_threads - 1);
                                                ^
whisper.cpp:5387:48: error: template argument 2 is invalid
whisper.cpp:5390:38: error: invalid types 'int[int]' for array subscript
                             threads[t] = std::thread(process);
                                      ^
whisper.cpp:5390:47: error: 'thread' is not a member of 'std'
                             threads[t] = std::thread(process);
                                               ^~~~~~
whisper.cpp:5390:47: note: 'std::thread' is defined in header '<thread>'; did yo
u forget to '#include <thread>'?
whisper.cpp:5396:38: error: invalid types 'int[int]' for array subscript
                             threads[t].join();
                                      ^
whisper.cpp:5630:46: error: 'thread' is not a member of 'std'
                             std::vector<std::thread> threads(n_threads - 1);
                                              ^~~~~~
whisper.cpp:5630:46: note: 'std::thread' is defined in header '<thread>'; did yo
u forget to '#include <thread>'?
whisper.cpp:5630:46: error: 'thread' is not a member of 'std'
whisper.cpp:5630:46: note: 'std::thread' is defined in header '<thread>'; did yo
u forget to '#include <thread>'?
whisper.cpp:5630:52: error: template argument 1 is invalid
                             std::vector<std::thread> threads(n_threads - 1);
                                                    ^
whisper.cpp:5630:52: error: template argument 2 is invalid
whisper.cpp:5633:42: error: invalid types 'int[int]' for array subscript
                                 threads[t] = std::thread(process);
                                          ^
whisper.cpp:5633:51: error: 'thread' is not a member of 'std'
                                 threads[t] = std::thread(process);
                                                   ^~~~~~
whisper.cpp:5633:51: note: 'std::thread' is defined in header '<thread>'; did yo
u forget to '#include <thread>'?
whisper.cpp:5639:42: error: invalid types 'int[int]' for array subscript
                                 threads[t].join();
                                          ^
whisper.cpp: In function 'int whisper_full_parallel(whisper_context*, whisper_fu
ll_params, const float*, int, int)':
whisper.cpp:5875:22: error: 'thread' is not a member of 'std'
     std::vector<std::thread> workers(n_processors - 1);
                      ^~~~~~
whisper.cpp:5875:22: note: 'std::thread' is defined in header '<thread>'; did yo
u forget to '#include <thread>'?
whisper.cpp:5875:22: error: 'thread' is not a member of 'std'
whisper.cpp:5875:22: note: 'std::thread' is defined in header '<thread>'; did yo
u forget to '#include <thread>'?
whisper.cpp:5875:28: error: template argument 1 is invalid
     std::vector<std::thread> workers(n_processors - 1);
                            ^
whisper.cpp:5875:28: error: template argument 2 is invalid
whisper.cpp:5895:18: error: invalid types 'int[int]' for array subscript
         workers[i] = std::thread(whisper_full_with_state, ctx, states[i], std::
move(params_cur), samples + start_samples, n_samples_cur);
                  ^
whisper.cpp:5895:27: error: 'thread' is not a member of 'std'
         workers[i] = std::thread(whisper_full_with_state, ctx, states[i], std::
move(params_cur), samples + start_samples, n_samples_cur);
                           ^~~~~~
whisper.cpp:5895:27: note: 'std::thread' is defined in header '<thread>'; did yo
u forget to '#include <thread>'?
whisper.cpp:5909:18: error: invalid types 'int[int]' for array subscript
         workers[i].join();
                  ^
whisper.cpp: In function 'const char* whisper_bench_memcpy_str(int)':
whisper.cpp:6180:26: error: 'thread' is not a member of 'std'
         std::vector<std::thread> threads(k - 1);
                          ^~~~~~
whisper.cpp:6180:26: note: 'std::thread' is defined in header '<thread>'; did yo
u forget to '#include <thread>'?
whisper.cpp:6180:26: error: 'thread' is not a member of 'std'
whisper.cpp:6180:26: note: 'std::thread' is defined in header '<thread>'; did yo
u forget to '#include <thread>'?
whisper.cpp:6180:32: error: template argument 1 is invalid
         std::vector<std::thread> threads(k - 1);
                                ^
whisper.cpp:6180:32: error: template argument 2 is invalid
whisper.cpp:6182:23: error: invalid types 'int[uint32_t {aka unsigned int}]' for
 array subscript
             threads[th] = std::thread(helper, th);
                       ^
whisper.cpp:6182:32: error: 'thread' is not a member of 'std'
             threads[th] = std::thread(helper, th);
                                ^~~~~~
whisper.cpp:6182:32: note: 'std::thread' is defined in header '<thread>'; did yo
u forget to '#include <thread>'?
whisper.cpp:6188:23: error: invalid types 'int[uint32_t {aka unsigned int}]' for
 array subscript
             threads[th].join();
                       ^
make: *** [Makefile:313: whisper.o] Error 1

**Comment by chujb** [comment]
> $ make which: no nvcc in (/c/Users/n/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/usr/bin: /mingw64/bin:/usr/bin:/c/Users/n/bin:/c/Windows/system32:/c/Windows:/c/Windows/S ystem32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Windows/System32/Open SSH:/c/Users/n/anaconda3:/c/Users/n/anaconda3/Scripts:/c/Users/n/anaconda3/Libra ry/bin:/c/Users/n/anaconda3/Library/mingw-w64/bin:/cmd:/c/Program Files/Cloudfla re/Cloudflare WARP:/c/Python/Scripts:/c/Program Files/MySQL/MySQL Server 8.0/bin :/c/Program Files/Docker/Docker/resources/bin:/c/Users/n/AppData/Roaming/Python/ Python39/Scripts:/c/Program Files/dotnet:/d/mingw64/bin:/c/Users/n/mingw64/bin:/ c/Users/n/AppData/Local/Microsoft/WindowsApps:/c/Users/n/AppData/Local/Programs/ Microsoft VS Code/bin:/d/PyCharm 2023.2/bin:/c/Python/Scripts:/d/mingw64/bin:/us r/bin/vendor_perl:/usr/bin/core_perl) I whisper.cpp build info: I UNAME_S: MINGW64_NT-10.0-19045 I UNAME_P: unknown I UNAME_M: x86_64 I CFLAGS: -I. -O3 -DNDEBUG -std=c11 -fPIC -D_XOPEN_SOURCE=600 - mavx -mavx2 -mfma -mf16c -msse3 -mssse3 I CXXFLAGS: -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -D_XOPEN_SOURCE=600 - mavx -mavx2 -mfma -mf16c -msse3 -mssse3 I LDFLAGS: I CC: cc (x86_64-win32-seh-rev0, Built by MinGW-W64 project) 8.1.0 I CXX: g++.exe (x86_64-win32-seh-rev0, Built by MinGW-W64 project) 8.1.0
> 
> g++ -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -D_XOPEN_SOURCE=600 -mavx -ma vx2 -mfma -mf16c -msse3 -mssse3 -c whisper.cpp -o whisper.o whisper.cpp: In function 'bool log_mel_spectrogram(whisper_state&, const float*, int, int, int, int, int, int, const whisper_filters&, bool, whisper_mel&)': whisper.cpp:2882:26: error: 'thread' is not a member of 'std' std::vectorstd::thread workers(n_threads - 1); ^~~~~~ whisper.cpp:2882:26: note: 'std::thread' is defined in header ''; did yo u forget to '#include '? whisper.cpp:40:1: +#include
> 
> whisper.cpp:2882:26: std::vectorstd::thread workers(n_threads - 1); ^~~~~~ whisper.cpp:2882:26: error: 'thread' is not a member of 'std' whisper.cpp:2882:26: note: 'std::thread' is defined in header ''; did yo u forget to '#include '? whisper.cpp:2882:32: error: template argument 1 is invalid std::vectorstd::thread workers(n_threads - 1); ^ whisper.cpp:2882:32: error: template argument 2 is invalid whisper.cpp:2884:23: error: invalid types 'int[int]' for array subscript workers[iw] = std::thread( ^ whisper.cpp:2884:32: error: 'thread' is not a member of 'std' workers[iw] = std::thread( ^~~~~~ whisper.cpp:2884:32: note: 'std::thread' is defined in header ''; did yo u forget to '#include '? whisper.cpp:2894:23: error: invalid types 'int[int]' for array subscript workers[iw].join(); ^ whisper.cpp: In function 'whisper_full_params whisper_full_default_params(whispe r_sampling_strategy)': whisper.cpp:4357:61: error: 'std::thread' has not been declared /_.n_threads =_/ std::min(4, (int32_t) std::thread::hardware_co ncurrency()), ^~~~~~ whisper.cpp: In function 'int whisper_full_with_state(whisper_context*, whisper_ state*, whisper_full_params, const float*, int)': whisper.cpp:5387:42: error: 'thread' is not a member of 'std' std::vectorstd::thread threads(n_threads - 1); ^~~~~~ whisper.cpp:5387:42: note: 'std::thread' is defined in header ''; did yo u forget to '#include '? whisper.cpp:5387:42: error: 'thread' is not a member of 'std' whisper.cpp:5387:42: note: 'std::thread' is defined in header ''; did yo u forget to '#include '? whisper.cpp:5387:48: error: template argument 1 is invalid std::vectorstd::thread threads(n_threads - 1); ^ whisper.cpp:5387:48: error: template argument 2 is invalid whisper.cpp:5390:38: error: invalid types 'int[int]' for array subscript threads[t] = std::thread(process); ^ whisper.cpp:5390:47: error: 'thread' is not a member of 'std' threads[t] = std::thread(process); ^~~~~~ whisper.cpp:5390:47: note: 'std::thread' is defined in header ''; did yo u forget to '#include '? whisper.cpp:5396:38: error: invalid types 'int[int]' for array subscript threads[t].join(); ^ whisper.cpp:5630:46: error: 'thread' is not a member of 'std' std::vectorstd::thread threads(n_threads - 1); ^~~~~~ whisper.cpp:5630:46: note: 'std::thread' is defined in header ''; did yo u forget to '#include '? whisper.cpp:5630:46: error: 'thread' is not a member of 'std' whisper.cpp:5630:46: note: 'std::thread' is defined in header ''; did yo u forget to '#include '? whisper.cpp:5630:52: error: template argument 1 is invalid std::vectorstd::thread threads(n_threads - 1); ^ whisper.cpp:5630:52: error: template argument 2 is invalid whisper.cpp:5633:42: error: invalid types 'int[int]' for array subscript threads[t] = std::thread(process); ^ whisper.cpp:5633:51: error: 'thread' is not a member of 'std' threads[t] = std::thread(process); ^~~~~~ whisper.cpp:5633:51: note: 'std::thread' is defined in header ''; did yo u forget to '#include '? whisper.cpp:5639:42: error: invalid types 'int[int]' for array subscript threads[t].join(); ^ whisper.cpp: In function 'int whisper_full_parallel(whisper_context*, whisper_fu ll_params, const float*, int, int)': whisper.cpp:5875:22: error: 'thread' is not a member of 'std' std::vectorstd::thread workers(n_processors - 1); ^~~~~~ whisper.cpp:5875:22: note: 'std::thread' is defined in header ''; did yo u forget to '#include '? whisper.cpp:5875:22: error: 'thread' is not a member of 'std' whisper.cpp:5875:22: note: 'std::thread' is defined in header ''; did yo u forget to '#include '? whisper.cpp:5875:28: error: template argument 1 is invalid std::vectorstd::thread workers(n_processors - 1); ^ whisper.cpp:5875:28: error: template argument 2 is invalid whisper.cpp:5895:18: error: invalid types 'int[int]' for array subscript workers[i] = std::thread(whisper_full_with_state, ctx, states[i], std:: move(params_cur), samples + start_samples, n_samples_cur); ^ whisper.cpp:5895:27: error: 'thread' is not a member of 'std' workers[i] = std::thread(whisper_full_with_state, ctx, states[i], std:: move(params_cur), samples + start_samples, n_samples_cur); ^~~~~~ whisper.cpp:5895:27: note: 'std::thread' is defined in header ''; did yo u forget to '#include '? whisper.cpp:5909:18: error: invalid types 'int[int]' for array subscript workers[i].join(); ^ whisper.cpp: In function 'const char* whisper_bench_memcpy_str(int)': whisper.cpp:6180:26: error: 'thread' is not a member of 'std' std::vectorstd::thread threads(k - 1); ^~~~~~ whisper.cpp:6180:26: note: 'std::thread' is defined in header ''; did yo u forget to '#include '? whisper.cpp:6180:26: error: 'thread' is not a member of 'std' whisper.cpp:6180:26: note: 'std::thread' is defined in header ''; did yo u forget to '#include '? whisper.cpp:6180:32: error: template argument 1 is invalid std::vectorstd::thread threads(k - 1); ^ whisper.cpp:6180:32: error: template argument 2 is invalid whisper.cpp:6182:23: error: invalid types 'int[uint32_t {aka unsigned int}]' for array subscript threads[th] = std::thread(helper, th); ^ whisper.cpp:6182:32: error: 'thread' is not a member of 'std' threads[th] = std::thread(helper, th); ^~~~~~ whisper.cpp:6182:32: note: 'std::thread' is defined in header ''; did yo u forget to '#include '? whisper.cpp:6188:23: error: invalid types 'int[uint32_t {aka unsigned int}]' for array subscript threads[th].join(); ^ make: *** [Makefile:313: whisper.o] Error 1

@BearsEatLardCake ，do you solve this problems?
