### ISSUE TITLE
GGML_OP_SOFT_MAX crash when using ggml metal code from latest llama.cpp

### ISSUE THREAD

**Issue by ptsochantaris** [ggerganov/whisper.cpp#1590]
First off, thank you for the truly amazing work on llama.cpp and whisper.cpp.

I am currently building a public domain voice prompt and response system for the Mac in Swift, and have been using both libraries, using the llama.* files and whisper.* files, together with the relevant ggml*.* files, running inference via Metal.

Everything was working fine until a view days ago, where improvements to llama.cpp meant that the `ggml-metal.Metal` file and related code that uses that shader is now out of sync with the equivalent in whisper.cpp.

This means that whisper.cpp and llama.cpp can't live in the same code-base because whisper.cpp will now break when trying to perform an GGML_OP_SOFT_MAX operation in the whisper model. I suspect the breaking change was part of this commit: https://github.com/ggerganov/llama.cpp/commit/ef47ec18da469423c276b683dd9b5741cee7023e

I have worked around this for now by using CoreML inference for whisper.cpp, but it would be nice to go back to the smaller overhead of being able to run inference in metal directly if possible. Please let me know if I can help in any way to diagnose or help fix this.

I hope this makes some sense, and/or this isn't me misunderstanding something (very possible, I am a llama.cpp newb!) Thanks for reading!

**Comment by ptsochantaris** [comment]
One good workaround I found, in case it helps others, was to build the two libraries as `dylib`s and include those in the project. In order for those to live nicely with each other, I did the following:
- Change the default metal shader lib name in the `ggml-metal.m` file from "default.metallib" to something different for whisper, and llama (in my case I did `whisper.metallib` and `llama.metallib`.
- Change the ObjC name of the "bundle hack" class in `ggml-metal.m` file from `GGMLMetalClass` to `GGMLMetalClassWhisper` so it doesn't conflict in the linked product.

Then I do something like this:
```
cd ~/whisper.cpp
make
xcrun -sdk macosx metal ggml-metal.metal -O3 -c -o whisper.air
xcrun -sdk macosx metallib whisper.air -o whisper.metallib
cp whisper.metallib libwhisper.dylib whisper.h ~/myProjectDir

cd ~/llama.cpp
make
xcrun -sdk macosx metal ggml-metal.metal -O3 -c -o llama.air
xcrun -sdk macosx metallib llama.air -o llama.metallib
cp llama.metallib libllama.dylib llama.h ~/myProjectDir
```

This keeps things tidy, and both frameworks can co-exist happily and run very well in the same binary without need to farm out to the CoreML encoder.

PS Ideally it would be nice if the `sgml-metal.m` files used different metal library and ObjC "bundle hack" classes so no editing of files was necessary. Happy to look into a PR for this if anyone else thinks this kind of fix makes sense.

**Comment by zshannon** [comment]
@ptsochantaris thanks for this! how're you generating the `*.dylib` files (prior to the `cp ..` command ^)?

**Comment by ptsochantaris** [comment]
@zshannon Ah, my bad for leaving that bit out, I didn't remember if the shared lib option was on by default in the makefile, it probably isn't.

So what I do is use the `ccmake` tool (I install it via HomeBrew) which has a nice curses-based interface. Just run it in the directory of the respective codebases like `ccmake .` and you can configure the various build options. One of the options is to create a shared lib, make sure it's on, the select "configure" and "generate" to update the makefiles. Then you can run `make` and you should have a `dylib` file in the directory right after.

I hope this makes more sense :)

<img width="584" alt="Screenshot 2023-12-08 at 11 28 02" src="https://github.com/ggerganov/whisper.cpp/assets/521581/2c67b19c-4559-48e0-a5f7-d05c162ad620">

**Comment by ptsochantaris** [comment]
This workaround seems to have broken after the latest round of GGML changes committed yesterday. Llama works fine but whisper blows up with that runtime error again. So bear in mind you may want to checkout the whisper repo just before the GGML changes on the 7th of Dec 2023. Will update if I learn more.

**Comment by ptsochantaris** [comment]
Yey, this was actually fixed with a commit one hour ago, so all is good. Since the metal shaders are no longer different in fact this whole issue can now be closed. At this point using the dylibs as-is from the repos should work fine! 👍

**Comment by ptsochantaris** [comment]
Closing this, as the bug that required this workaround has been fixed for a few days, so this info is probably redundant by now 👍

**Comment by thewh1teagle** [comment]
I experience the same issue when using latest whisper.cpp along with llama.cpp with https://github.com/utilityai/llama-cpp-rs and https://github.com/tazz4843/whisper-rs
