### ISSUE TITLE
custom streaming broken from 1.4.3 to 1.5.0

### ISSUE THREAD

**Issue by zobadaniel** [ggerganov/whisper.cpp#1591]
My custom streaming code, which is heavily inspired by the "stream" example, stopped working from this "last good" commit https://github.com/ggerganov/whisper.cpp/commit/ec7a6f04f9c32adec2e6b0995b8c728c5bf56f35 when updating to this commit https://github.com/ggerganov/whisper.cpp/commit/b0502836b82944d444f30ea1b5217f69ff6da71b and any later commit that I tried (1.5.0, 1.5.1 and https://github.com/ggerganov/whisper.cpp/commit/3c28d1a5712e4c06b0380166e6f482ca2b525970).

I'm building with WHISPER_CUBLAS=1 on Ubuntu 22.04, 64 bit Intel processor, using this card:
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1080        Off | 00000000:01:00.0 Off |                  N/A |
| 42%   47C    P0              35W / 180W |      0MiB /  8192MiB |      2%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

When doing the update to the mentioned commit, the call to "whisper_full()" does not return the transcript anymore, instead only one symbol (typically a capital letter) is returned. 

This is happening independent of whether I use a "full" whisper model or a quantized one.

The (hopefully) relevant part of the code is here: https://github.com/ZalozbaDev/docker_whisper_vosk/blob/1b0d92cb049fc57293a1c32ccc42d960e274bcd6/VoskRecognizer.cpp#L247 

Any idea what might be the cause? Any other info I could provide that would assist in finding out what's wrong? Please help me!

**Comment by zobadaniel** [comment]
Tested today commit https://github.com/ggerganov/whisper.cpp/commit/f9ca90256bf691642407e589db1a36562c461db7 and the issue is gone. Dunno which commit actually fixes it, but anyway, works again for me.

**Comment by ggerganov** [comment]
Thank you for reporting - there were some CUDA problems recently which should be resolved on latest `master`
