### ISSUE TITLE
cannot build talk-llama 

### ISSUE THREAD

**Issue by rohithbojja** [ggerganov/whisper.cpp#1611]
i built whisper.cpp via cmake and tried to run
E > Repos > whisper.cpp :  cmake -DWHISPER_CUBLAS=1 examples/talk-llama 
i got the following error:
CMake Error at CMakeLists.txt:30 (include):
  include could not find requested file
DefaultTargetOptions

CMake Error at main/CMakeLists.txt:4 (include):
include could not find requested file:
DefaultTargetOptions

CMake Error at server/CMakeLists.txt:4 (include):
include could not find requested file:
DefaultTargetOptions

CMake Error at bench/CMakeLists.txt:4 (include):
  include could not find requested file:

DefaultTargetOptions

CMake Error at quantize/CMakeLists.txt:4 (include):
  include could not find requested file:

DefaultTargetOptions

-- Configuring incomplete, errors occurred!

**Comment by bobqianic** [comment]
To construct Talk-Llama, you can follow these straightforward steps:

Start by downloading the source code for whisper.cpp from its main repository, commonly known as `whisper.cpp-master`. After acquiring the code, you'll need to prepare the build for Talk-Llama and any related examples that necessitate SDL2. This is achieved by executing the command:
```
cmake -S whisper.cpp-master -B [desired_build_directory] -DWHISPER_CUBLAS=1 -DWHISPER_SDL2=1
```
Replace `[desired_build_directory]` with the path where you want the build files to be placed. This command ensures all necessary configurations are set up. Following this, you can build the binary with this command:
```
cmake --build [desired_build_directory] --config release
```
Here, again, replace `[desired_build_directory]` with the path you specified earlier. This will compile and create the Talk-Llama application for you.

**Comment by rohithbojja** [comment]
SDL-2 isnt installing in windows! Help me

**Comment by bobqianic** [comment]
#1648
