### ISSUE TITLE
 "I need help on how to use 'whisper-cublas-12.2.0-bin-x64.zip' to transcribe audio files on 'Windows'."

### ISSUE THREAD

**Issue by peaceful610** [ggerganov/whisper.cpp#1613]
"I need help on how to use 'whisper-cublas-12.2.0-bin-x64.zip' to transcribe audio files on 'Windows'."

**Comment by peaceful610** [comment]
"I tried running it in CMD. The result was this, but it did not transcribe any text."
![Uploading 1111.png…]()

**Comment by peaceful610** [comment]
"I tried running it in CMD. The result was this, but it did not transcribe any text."
![1111](https://github.com/ggerganov/whisper.cpp/assets/129727914/faf90cdd-3bd0-401e-aa96-038ff79665d3)

E:\whisper-cublas-12.2.0-bin-x64>main.exe -f E:\example_model_audio\audio\jfk.wav -m E:\example_model_audio\model/for-tests-ggml-small.bin
whisper_init_from_file_with_params_no_state: loading model from 'E:\example_model_audio\model/for-tests-ggml-small.bin'
whisper_model_load: loading model
whisper_model_load: n_vocab       = 51865
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 768
whisper_model_load: n_audio_head  = 12
whisper_model_load: n_audio_layer = 12
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 768
whisper_model_load: n_text_head   = 12
whisper_model_load: n_text_layer  = 12
whisper_model_load: n_mels        = 80
whisper_model_load: ftype         = 1
whisper_model_load: qntvr         = 0
whisper_model_load: type          = 3 (small)
whisper_model_load: adding 1608 extra tokens
whisper_model_load: n_langs       = 99
ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   no
ggml_init_cublas: CUDA_USE_TENSOR_CORES: yes
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3060, compute capability 8.6
whisper_backend_init: using CUDA backend
whisper_model_load:     CUDA buffer size =   501.01 MB
whisper_model_load: model size    =    0.00 MB
whisper_model_load: WARN no tensors loaded from model file - assuming empty model for testing
whisper_backend_init: using CUDA backend
whisper_init_state: kv self size  =   49.55 MB
whisper_init_state: kv cross size =   55.30 MB
whisper_init_state: compute buffer (conv)   =   20.17 MB
whisper_init_state: compute buffer (encode) =  128.07 MB
whisper_init_state: compute buffer (cross)  =    6.25 MB
whisper_init_state: compute buffer (decode) =   97.33 MB

system_info: n_threads = 4 / 20 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | METAL = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 0 | VSX = 0 | CUDA = 1 | COREML = 0 | OPENVINO = 0 |

main: processing 'E:\example_model_audio\audio\jfk.wav' (176000 samples, 11.0 sec), 4 threads, 1 processors, 5 beams + best of 5, lang = en, task = transcribe, timestamps = 1 ...



whisper_print_timings:     load time =   109.66 ms
whisper_print_timings:     fallbacks =   5 p /   0 h
whisper_print_timings:      mel time =     9.31 ms
whisper_print_timings:   sample time =     3.38 ms /    30 runs (    0.11 ms per run)
whisper_print_timings:   encode time =   104.15 ms /     1 runs (  104.15 ms per run)
whisper_print_timings:   decode time =     0.00 ms /     1 runs (    0.00 ms per run)
whisper_print_timings:   batchd time =    51.82 ms /    18 runs (    2.88 ms per run)
whisper_print_timings:   prompt time =     0.00 ms /     1 runs (    0.00 ms per run)
whisper_print_timings:    total time =   290.23 ms

E:\whisper-cublas-12.2.0-bin-x64>

**Comment by bobqianic** [comment]
The reason it's not running is because you didn't provide a file path to whisper.cpp. You need to use the `-f` flag to pass the file path for it to work.

**Comment by peaceful610** [comment]
> 它未运行的原因是您没有提供 whisper .cpp 的文件路径。您需要使用该标志传递文件路径才能使其正常工作。`-f`

It's been resolved, thank you for your help.
