### ISSUE TITLE
Segmentation Fault Running on an old intel machine 7B Llama model

### ISSUE THREAD

**Issue by powerpower1232** [ggerganov/whisper.cpp#1623]
![Screenshot 2023-12-11 at 19 27 58](https://github.com/ggerganov/whisper.cpp/assets/152356484/25c02beb-52a6-46f0-b154-922aded45030)

7B Llama model

`./main -m ./models/7B/ggml-model-q4_0.gguf -n 128`

**Comment by petterreinholdtsen** [comment]
Any chance you can try to run the test using valgrind, to see why and where it segfaults?

**Comment by ggerganov** [comment]
This is not `whisper.cpp` related
