### ISSUE TITLE
cURL with PHP results different than command line

### ISSUE THREAD

**Issue by erturkkadir** [ggerganov/whisper.cpp#1624]
I don t know if it is php or some other issue, and hope someone helps me,

I have server with following command

```./server --host 0.0.0.0 --port 7863 -t 24 -l auto -m models/ggml-medium.bin --convert```

if i call it with  command line, 
```curl xxx.xxx.xxx.xxx:7863/inference -H "Content-Type: multipart/form-data" -F file="@./uploads/out.wav" -F temperature="0.2" -F response-format="json"```

if works perfectly.

But when I call from php with the following code
```
   $url = "xxx.xxx.xxx.xxx:7863/inference";
   $cFile = "@./uploads/out.wav";		         
   $postData = array(
	'file'=> $cFile,
	'temperature'=>'0.2',
	'response-format' => 'json'
   );

   ch = curl_init();
   curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
   curl_setopt($ch, CURLOPT_URL, $url);
   curl_setopt($ch, CURLOPT_POST, true);
   curl_setopt($ch, CURLOPT_POSTFIELDS, $postData);	
   $response = curl_exec($ch);
```

then I get {"error":"FFmpeg conversion failed."}

Any help appreciated.

Additional Note : I got following on server side when calling from php
```
whisper_server_temp_file.wav: Invalid data found when processing input
```

**Comment by felrock** [comment]
Could the issue be that you have --convert and still sending a .wav file? **{"error":"FFmpeg conversion failed."}** means ffmpeg failed with the convert command.

**Comment by erturkkadir** [comment]
Thanks @felrock  for your reply

I send same file with cURL command line, it converts and generates result.

**Comment by erturkkadir** [comment]
Finally I got it working with following (the issue with PHP 5.5+ and cUrl)

```
$data = array(
    'file'=> curl_file_create(realpath('uploads/out.wav')),
    'temperature'=>'0.2',
    'response-format' => 'json'
);
		
		
$ch = curl_init($url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, true);		
curl_setopt($ch, CURLOPT_POSTFIELDS, $data);	
curl_setopt($ch, CURLOPT_USERAGENT, 'Mozilla/4.0 (compatible; MSIE 5.01; Windows NT 5.0'); 
$response = curl_exec($ch);
```

I will close it.
