### ISSUE TITLE
SDL-2 isnt installing in windows! Help me

### ISSUE THREAD

**Issue by rohithbojja** [ggerganov/whisper.cpp#1648]
SDL-2 isnt installing in windows! Help me

**Comment by bobqianic** [comment]
```
cmake -S whisper.cpp-master -B [desired_build_directory] -DWHISPER_CUBLAS=1 -DWHISPER_SDL2=1 -DSDL2_DIR=[SDL2_devel_directory]\cmake
```

Go to https://github.com/libsdl-org/SDL and download the corresponding version of SDL2 for your compiler. Then, when using cmake, just pass the path to cmake using `-DSDL2_DIR=[SDL2_devel_directory]\cmake`

<img width="980" alt="image" src="https://github.com/ggerganov/whisper.cpp/assets/129547291/38c5a6ff-eb0b-4045-b097-c3503654dd22">
