### ISSUE TITLE
Can't compile with cuBLAS with non-standard CUDA setup on linux

### ISSUE THREAD

**Issue by pjuhasz** [ggerganov/whisper.cpp#1684]
I've installed CUDA packages from the Negativo17 repo on a Fedora 38 system (because I'm using their nvidia-driver on this Lenovo P50 laptop with its discrete Nvidia GPU, which used to be tricky to setup when I first got this machine, and this was the driver that worked), and I'm having problems compiling whisper.cpp with cuBLAS enabled. I get a barrage of weird errors like 

```
/usr/include/cuda/std/detail/libcxx/include/__cuda/atomic_prelude.h(29): error: identifier "ATOMIC_LLONG_LOCK_FREE" is undefined
      static_assert(ATOMIC_LLONG_LOCK_FREE == 2, "");
                    ^

/usr/include/cuda/std/detail/libcxx/include/__cuda/atomic_prelude.h(30): error: identifier "ATOMIC_POINTER_LOCK_FREE" is undefined
      static_assert(ATOMIC_POINTER_LOCK_FREE == 2, "");
                    ^

ggml-cuda.cu(6519): error: namespace "std" has no member "atomic_flag"
      std::atomic_flag& lock;
           ^

ggml-cuda.cu(6520): error: namespace "std" has no member "atomic_flag"
      scoped_spin_lock(std::atomic_flag& lock) : lock(lock) {
```

The problem seems to be that these packages install the CUDA headers and libraries under /usr/ instead of /usr/local/cuda (like the official cuda-toolkit from Nvidia does). Apart from whisper.cpp (and llama.cpp for that matter) the setup seems to be functional, e.g. I could compile and run the examples from cuda-samples.

Does anyone have any ideas or experience on how to fix this?

**Comment by bobqianic** [comment]
> The problem seems to be that these packages install the CUDA headers and libraries under /usr/ instead of /usr/local/cuda (like the official cuda-toolkit from Nvidia does). 

Try `CMake` and see if that helps.

`cmake -S [source] -B [build] -DWHISPER_CUBLAS=1`

`cmake --build [build] --config release`

**Comment by pjuhasz** [comment]
It didn't help:
```CMake Error at /usr/share/cmake/Modules/CMakeDetermineCUDACompiler.cmake:227 (message):
  Couldn't find CUDA library root.
```

**Comment by pjuhasz** [comment]
After reinstalling the machine with the official Nvidia driver packages, the errors went away and I could compile the program. So, PEBKAC, I guess.

**Comment by stevestorey** [comment]
Just for anyone else who gets here prior to something being changed in the negativo17 packaging - the current workaround is to comment the line `INCLUDES += "-I/usr/include/cuda"` from the `/usr/bin/nvcc.profile` file after which compilation works.
