### ISSUE TITLE
Option to suppress tokens

### ISSUE THREAD

**Issue by pprobst** [ggerganov/whisper.cpp#1697]
Hello. As far as I know, whispercpp does not support the option to suppress particular tokens / numerals during inference, like [WhisperX](https://github.com/m-bain/whisperX/) does. This is particularly useful, for example, if we want to [transcribe numbers literally](https://github.com/m-bain/whisperX/issues/300), e.g., "one" instead of "1".

Is there any interest in adding support for this feature?

**Comment by ggerganov** [comment]
Have you tried the grammar functionality: #1229 - could be useful

**Comment by pprobst** [comment]
No, I didn't know it was a thing. I will look into it. But if I understood it correctly from a brief reading, this is awesome; given a context-specific corpus, we can use it to "boost the weight" of certain words. There should be an example or something in the README to give more attention to this feature because it's a game-changer 👀

**Comment by pprobst** [comment]
Oh! I just found exactly what I needed in the source code (the grammar functionality will still be handy for me, though).

https://github.com/ggerganov/whisper.cpp/blob/2623640cd6b8e077ffb1fbe3c265208da3a0ca6d/whisper.cpp#L4473-L4478

And

https://github.com/ggerganov/whisper.cpp/blob/2623640cd6b8e077ffb1fbe3c265208da3a0ca6d/whisper.cpp#L4567-L4575

Very handy. Just need to add the tokens I won't use. I'm closing this issue now.

**Comment by flatsiedatsie** [comment]
Would it be possible to load such lists from an external file instead of having to recompile?

**Comment by josharian** [comment]
Seconded. I have the same use case (suppressing `0123456789%$£`, as in whisperx). It'd be nice to have this available in vanilla whisper.cpp via the command line. If there's openness, I'm game to try my hand at a PR. The main question is what the flags should be. (Should it be a simple `--suppress-digits`, like whisperx? Or take a string, which we split into tokens? Etc.)

**Comment by josharian** [comment]
Hmmm. It's more than what @pprobst found, because there are lots of all-numeric tokens, such as "500" (which is not just "5", "0", "0"). Grammars might indeed be a better choice here...

**Comment by josharian** [comment]
While I work on grammars, here's a quick patch folks can apply as desired:

```cpp
        // suppress tokens containing numbers
        static const std::string numbery = "0123456789%$£";
        for (int i = 0; i < n_logits; i++) {
            const std::string & token = vocab.id_to_token.at(i);
            // skip tokens starting with "[", lots of [_TT_NNNN] before calling find_first_of
            // this is important to avoid large performance regressions
            // as it is, this is still expensive
            if (!token.empty() && token.front() != '[' && token.find_first_of(numbery) != std::string::npos) {
                logits[i] = -INFINITY;
            }
        }
```

(This goes just after "suppress non-speech tokens".)

It appears to cost about 5% runtime, not inconsiderable.

If we wanted to add proper support for a simple "omit these ascii characters", without grammars, this could be made much cheaper by doing the `find_first_of` calcs once, not every time.

**Comment by wttdotm** [comment]
@josharian I just want to say thank you for this simple and goated patch. I was having a nightmare of a time dealing with word-level timestamps for dollar amounts (eg. "$45" being three different words but being treated as one by whisper) and after hours and hours of banging my head against unhelpful searches and repos this works perfectly.

**Comment by josharian** [comment]
Thanks. :)

If you want to get rid of the performance penalty for that patch, you can try pulling in this still-pretty-small commit, which I just rebased onto master: https://github.com/josharian/whisper.cpp/commit/c664398595bf598cc5aeb22062b716b70e49d198. (It worked months ago when I wrote it, but I haven't tested it since.)
