### ISSUE TITLE
Output file

### ISSUE THREAD

**Issue by Paveloom** [ggerganov/whisper.cpp#17]
Hello there. Seems like redirecting the standard output with either `>`, `>>` or `tee` doesn't work. Would be nice to have an option to save the output to a specific file.

**Comment by aufziehvogel** [comment]
I use redirection with `>` and for me it works without problems.

Maybe you're experiencing buffering? Shell redirection to my knowledge by default uses output buffering, i.e. you will not see data as it is written by the program. Instead, data will be written to the file whenever there (according to the buffering implementation) is enough data.

You can change the buffering with `stdbuf`. For example, to write to the file once per line you could call:

```
stdbuf -oL ./main -m models/ggml-large.bin -f input.wav > output.txt
```

**Comment by ggerganov** [comment]
You can now output the results to multiple file formats. For example:

```java
./main -m models/ggml-tiny.en.bin -f samples/jfk.wav -otxt -ovtt -osrt
```

will generate `.txt`, `.vtt` and `.srt` files.

Also, you can now redirect the results with `>`, as suggested by @aufziehvogel

**Comment by Paveloom** [comment]
Yeah, I thought it's related to buffering, too, @aufziehvogel. I think I've waited quite a while, though, and yet nothing showed up. Anyhow, thanks for letting me know about `stfbuf`, that fixed it!

Thanks, @ggerganov!

**Comment by CrispStrobe** [comment]
This is fully supported in CrispASR (our fork). Output to files via:

```bash
crispasr -m model.gguf -f audio.wav -otxt -osrt -ovtt
```

Stdout redirection also works — model loading info goes to stderr, transcription to stdout:

```bash
crispasr -m model.gguf -f audio.wav > transcript.txt
```

For buffering issues, use `stdbuf -oL` as suggested above. Closing as resolved.
