### ISSUE TITLE
Stops trancribing, yet still utilizing resources

### ISSUE THREAD

**Issue by Pocokk** [ggerganov/whisper.cpp#1705]
Using large-v3 model with basic settings (everything default), the program somewhat stuck/freezes/stops at a certain point (few minutes into a 90 minutes long audio), yet the GPU usage still at 80-90%, the fans are still spinning, there is activity in the background, yet the progress has been halted for some reason. 

How can I debug/test out/create logs during it to determine what's wrong it?

**Comment by bobqianic** [comment]
You could experiment with a different model, such as large-v2, to see if the issue continues. If the issue doesn't recur, it's likely that the program is getting stuck in the decoding process, possibly entering a loop because of temperature fallback.

**Comment by Pocokk** [comment]
The GPU temperature stayed in the mid 60s degrees during that 15 mins while I let it run.

**Comment by bobqianic** [comment]
> The GPU temperature stayed in the mid 60s degrees during that 15 mins while I let it run.

I'm referring to the temperature fallback in the sampling process, not the actual temperature of your GPU. LOL

**Comment by Pocokk** [comment]
Yeah I deleted that comment, sorry! (newbie here)

So what value should I set to that setting to avoid happening this again? (I also switch to v2 to see how that handles it)

**Comment by Pocokk** [comment]
Is there any way to manually increase the GPU usage? I sits in the 30% range, but don't know why.

**Comment by bobqianic** [comment]
> So what value should I set to that setting to avoid happening this again?

You can lower the `--entropy-thold`, which will enhance the likelihood of hallucinations but simultaneously decrease the risk of getting trapped in a loop.

**Comment by bobqianic** [comment]
> Is there any way to manually increase the GPU usage?

NO. However, you can transcribe multiple files at the same time.

**Comment by Pocokk** [comment]
Will try out "entropy-thold", appreciate the tip! 

So far, it seems v2 is more solid and it even uses various punctuations, while v3 was just a big wall of text, not even Uppercase letters at all.

I don't know, in theory, shouldn't v3 be more superior than v2 (or v1 or anything else)? 

Apologize for my lack of knowledge in this field, I just recently hopped in and being naive and not so tech-savvy is a bad combo in this hobby.

**Comment by bobqianic** [comment]
> I don't know, in theory, shouldn't v3 be more superior than v2 (or v1 or anything else)?

`v2 > v1 > v3`

v3 is generally a failure, and I hope they can solve these problems in v4

https://github.com/openai/whisper/discussions/1762

**Comment by Pocokk** [comment]
That sounds very bad.... so v2 it is for the time being, noted!

 Last question if you don't mind: are there definitive parameter values that would *always* booster the output (experience) without sacrificing other aspects?

**Comment by bobqianic** [comment]
> are there definitive parameter values that would always booster the output (experience) without sacrificing other aspects?

AFAIK, there aren't any parameters like that. If there were specific parameter values that consistently enhanced output quality, like you mentioned, we would have already set them as defaults. Take the beam size, for instance, it's preset to 5.

**Comment by Pocokk** [comment]
Just asking, because I've read somewhere that "beam size",  "best of being" and "patience" settings being set to higher/lower values can lead to various end results. All part of being a AI program I guess.

**Comment by bobqianic** [comment]
> Just asking, because I've read somewhere that "beam size", "best of being" and "patience" settings being set to higher/lower values can lead to various end results. All part of being a AI program I guess.
 
Absolutely. Additionally, there are various sampling strategies to explore, such as `top P` and `top K`. I'm sure you'll find the learning journey through the AI world to be quite fascinating.
