### ISSUE TITLE
Cannot find diarization model 

### ISSUE THREAD

**Issue by siddie** [ggerganov/whisper.cpp#1715]
As per the instructions, I try to download a diarization model. Using ./models/download-ggml-model.sh small.en-tdrz I get "Invalid model: small.en-tdrz"

The model is not present here:  https://huggingface.co/ggerganov/whisper.cpp/tree/main

Is there a way to download the diarization model?

**Comment by mrienstra** [comment]
That model is available here: https://huggingface.co/akashmjn/tinydiarize-whisper.cpp/tree/main

It can be downloaded within `whisper.cpp` with this command:

```bash
bash ./models/download-ggml-model.sh small.en-tdrz
```
... thanks to @akashmjn's PR (merged Jul 3, 2023): https://github.com/ggerganov/whisper.cpp/pull/1058

You can see `small.en-tdrz` in [`.models/download-ggml-model.sh`](https://github.com/ggerganov/whisper.cpp/blob/master/models/download-ggml-model.sh), at the moment, on line 34, and some related logic on lines 73-77 (line numbers subject to change, search the file for `tdrz` if necessary).

---

Perhaps your cloned copy of `whisper.cpp` is out of date? You can check your local copy of `.models/download-ggml-model.sh` and see if it contains references to `small.en-tdrz`. If that's not the issue, perhaps try again, and if you can reproduce the issue you reported, provide some more details about your setup to help others triage in case you've stumbled on an interesting bug! 🐛

**Comment by siddie** [comment]
Thanks, @mrienstra. I've been running the models on Windows PC. I believe, download-ggml-model.cmd used a different model repo and was not aware of tdrz. 

I ended up converting the original model to ggml and then moving on to language-independent diarization.
