### ISSUE TITLE
Doesn't t_batchd_us  need to be reset in whisper_reset_timings ? 

### ISSUE THREAD

**Issue by LVCSRer** [ggerganov/whisper.cpp#1721]
I found total time does not equal to the sum of above times (from mel time to prompt time), and I found batchd time increase for each utterance. 

Doesn't t_batchd_us  need to be reset in whisper_reset_timings ? 

Is it intentional that this number allowed increasing?

**Comment by ggerganov** [comment]
It's a bug - thanks for spotting this
