### ISSUE TITLE
issue to clone huggingface repo so I manually download distil large v2 and convert to ggml 

### ISSUE THREAD

**Issue by UniversalTechno** [ggerganov/whisper.cpp#1739]
issue to clone huggingface repo so I manually download distil large v2 and convert to ggml  , but i got the coversion to ggml very quickly and without showing any error is that normal or i have tocheck on the logs if there is something wrong 
also the generated ggml file has the same size as the original and i tested it on main program and it can made the speech to text without any issue 
please just need a confirmation

**Comment by bobqianic** [comment]
I'm not certain if there are any issues, but Hugging Face provides the converted Distil Large v2 model, which you can easily download.

> same size as the original

Perhaps you converted the FP32 version of the distilled model. OpenAI uses FP16, and the distilled model has half the number of parameters compared to the original model, so that would make sense.

**Comment by UniversalTechno** [comment]
I uploaded the new gmml into https://huggingface.co/saba1234/ggml-distil-large-v2
no i didnt use  FP32 i use the original distil large v2 model

**Comment by UniversalTechno** [comment]
I used the wget command is more helpful than git in the case of huggingface

**Comment by bobqianic** [comment]
> no i didnt use FP32 i use the original distil large v2 model

Ah, I understand now. This is expected because unless you quantize the model, ggml won't compress or quantize the weights. So, the size of the model before conversion should be almost the same as after. I mistakenly thought the original model you were referring to was the non-distilled one.
