### ISSUE TITLE
GGUF format and quantization support

### ISSUE THREAD

**Issue by HarrySoteriou** [ggerganov/whisper.cpp#1751]
Apologies if the question is silly but I am trying to quantize whisper.cpp in gguf format through llama.cpp because I need to test performance of various quantizations for a project I am working on. When trying to convert the model I get an error along the lines that the ctx is not provided in the configuration.json (because this is an audio to text model and doesnt have context like text-generation models).

Is there anyone that has successfully converted to gguf format and quantized the model? I have seen a couple of quantized whisper models in ggml format. Are they any different from ggml in terms of performance and portability?

**Comment by ggerganov** [comment]
`whisper.cpp` does not support GGUF format

You have to use the `quantize` tool in `whisper.cpp`

**Comment by HarrySoteriou** [comment]
Thank you for the quick reply and congrats on the great work you do
