### ISSUE TITLE
Docker on CUDA 12.1

### ISSUE THREAD

**Issue by MorphSeur** [ggerganov/whisper.cpp#1759]
It is great to use Whisper using Docker on CPU!

Docker using GPU can't work on my local machine as the CUDA version is 12.1.
For some reasons, I didn't update CUDA to 12.3.

Currently, I am trying to build a Docker for GPU support.
The CUDA versions mentioned in the main-cuda.Dockerfile were changed to 12.1.

After a build and a run, here is an error in the output (last line).
Do you have any suggestion?

`$ sudo docker run --gpus all -it --rm \
>   -v /home/test/environments/whisper/models:/models \
>   -v /home/test/environments/whisper/audios:/audios \
>   -v /home/test/environments/whisper/outputs:/outputs \
>    cuda-app:latest "./main -t 2 -p 10 -sow -pp -m /models/ggml-small.en.bin -f /audios/1.wav -otxt -of /outputs/1.small.en.txt"
whisper_init_from_file_with_params_no_state: loading model from '/models/ggml-small.en.bin'
whisper_model_load: loading model
whisper_model_load: n_vocab       = 51864
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 768
whisper_model_load: n_audio_head  = 12
whisper_model_load: n_audio_layer = 12
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 768
whisper_model_load: n_text_head   = 12
whisper_model_load: n_text_layer  = 12
whisper_model_load: n_mels        = 80
whisper_model_load: ftype         = 1
whisper_model_load: qntvr         = 0
whisper_model_load: type          = 3 (small)
whisper_model_load: adding 1607 extra tokens
whisper_model_load: n_langs       = 99
ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   no
ggml_init_cublas: CUDA_USE_TENSOR_CORES: yes
ggml_init_cublas: found 2 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3090, compute capability 8.6, VMM: yes
  Device 1: NVIDIA GeForce RTX 3090, compute capability 8.6, VMM: yes
whisper_backend_init: using CUDA backend
whisper_model_load:     CUDA buffer size =   487.20 MB
whisper_model_load: model size    =  487.00 MB
whisper_backend_init: using CUDA backend
whisper_init_state: kv self size  =   49.55 MB
whisper_init_state: kv cross size =   55.30 MB
whisper_init_state: compute buffer (conv)   =   20.23 MB
whisper_init_state: compute buffer (encode) =  128.14 MB
whisper_init_state: compute buffer (cross)  =    6.31 MB
whisper_init_state: compute buffer (decode) =   97.40 MB
system_info: n_threads = 20 / 24 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | METAL = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | CUDA = 1 | COREML = 0 | OPENVINO = 0 | 
main: processing '/audios/1.wav' (278351189 samples, 17396.9 sec), 2 threads, 10 processors, 5 beams + best of 5, lang = en, task = transcribe, timestamps = 1 ...
whisper_backend_init: using CUDA backend
whisper_init_state: kv self size  =   49.55 MB
whisper_init_state: kv cross size =   55.30 MB
whisper_init_state: compute buffer (conv)   =   20.23 MB
whisper_init_state: compute buffer (encode) =  128.14 MB
whisper_init_state: compute buffer (cross)  =    6.31 MB
whisper_init_state: compute buffer (decode) =   97.40 MB
whisper_backend_init: using CUDA backend
whisper_init_state: kv self size  =   49.55 MB
whisper_init_state: kv cross size =   55.30 MB
whisper_init_state: compute buffer (conv)   =   20.23 MB
whisper_init_state: compute buffer (encode) =  128.14 MB
whisper_init_state: compute buffer (cross)  =    6.31 MB
whisper_init_state: compute buffer (decode) =   97.40 MB
whisper_backend_init: using CUDA backend
whisper_init_state: kv self size  =   49.55 MB
whisper_init_state: kv cross size =   55.30 MB
whisper_init_state: compute buffer (conv)   =   20.23 MB
whisper_init_state: compute buffer (encode) =  128.14 MB
whisper_init_state: compute buffer (cross)  =    6.31 MB
whisper_init_state: compute buffer (decode) =   97.40 MB
whisper_backend_init: using CUDA backend
whisper_init_state: kv self size  =   49.55 MB
whisper_init_state: kv cross size =   55.30 MB
whisper_init_state: compute buffer (conv)   =   20.23 MB
whisper_init_state: compute buffer (encode) =  128.14 MB
whisper_init_state: compute buffer (cross)  =    6.31 MB
whisper_init_state: compute buffer (decode) =   97.40 MB
whisper_backend_init: using CUDA backend
whisper_init_state: kv self size  =   49.55 MB
whisper_init_state: kv cross size =   55.30 MB
whisper_init_state: compute buffer (conv)   =   20.23 MB
whisper_init_state: compute buffer (encode) =  128.14 MB
whisper_init_state: compute buffer (cross)  =    6.31 MB
whisper_init_state: compute buffer (decode) =   97.40 MB
whisper_backend_init: using CUDA backend
whisper_init_state: kv self size  =   49.55 MB
whisper_init_state: kv cross size =   55.30 MB
whisper_init_state: compute buffer (conv)   =   20.23 MB
whisper_init_state: compute buffer (encode) =  128.14 MB
whisper_init_state: compute buffer (cross)  =    6.31 MB
whisper_init_state: compute buffer (decode) =   97.40 MB
whisper_backend_init: using CUDA backend
whisper_init_state: kv self size  =   49.55 MB
whisper_init_state: kv cross size =   55.30 MB
whisper_init_state: compute buffer (conv)   =   20.23 MB
whisper_init_state: compute buffer (encode) =  128.14 MB
whisper_init_state: compute buffer (cross)  =    6.31 MB
whisper_init_state: compute buffer (decode) =   97.40 MB
whisper_backend_init: using CUDA backend
whisper_init_state: kv self size  =   49.55 MB
whisper_init_state: kv cross size =   55.30 MB
whisper_init_state: compute buffer (conv)   =   20.23 MB
whisper_init_state: compute buffer (encode) =  128.14 MB
whisper_init_state: compute buffer (cross)  =    6.31 MB
whisper_init_state: compute buffer (decode) =   97.40 MB
whisper_backend_init: using CUDA backend
whisper_init_state: kv self size  =   49.55 MB
whisper_init_state: kv cross size =   55.30 MB
whisper_init_state: compute buffer (conv)   =   20.23 MB
whisper_init_state: compute buffer (encode) =  128.14 MB
whisper_init_state: compute buffer (cross)  =    6.31 MB
whisper_init_state: compute buffer (decode) =   97.40 MB
GGML_ASSERT: ggml-cuda.cu:6742: ptr == (void *) (g_cuda_pool_addr[device] + g_cuda_pool_used[device])`

**Comment by ggerganov** [comment]
Hm, not sure. Does it work without Docker on that machine?

**Comment by MorphSeur** [comment]
No, I didn't tried other installations. Only, Docker CPU.

**Comment by MorphSeur** [comment]
Sometimes it starts transcription, sometimes no.
You can check in the last lines containing the timestamp.

`$ sudo docker run --runtime=nvidia --gpus 1 -it --rm \
>   -v /home/test/environments/whisper/models:/models \
>   -v /home/test/environments/whisper/audios:/audios \
>   -v /home/test/environments/whisper/outputs:/outputs \
>    cuda-app:latest "./main -t 2 -p 10 -sow -pp -m /models/ggml-small.en.bin -f /audios/1.wav -otxt -of /outputs/1.small.en.txt"
whisper_init_from_file_with_params_no_state: loading model from '/models/ggml-small.en.bin'
whisper_model_load: loading model
whisper_model_load: n_vocab       = 51864
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 768
whisper_model_load: n_audio_head  = 12
whisper_model_load: n_audio_layer = 12
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 768
whisper_model_load: n_text_head   = 12
whisper_model_load: n_text_layer  = 12
whisper_model_load: n_mels        = 80
whisper_model_load: ftype         = 1
whisper_model_load: qntvr         = 0
whisper_model_load: type          = 3 (small)
whisper_model_load: adding 1607 extra tokens
whisper_model_load: n_langs       = 99
ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   no
ggml_init_cublas: CUDA_USE_TENSOR_CORES: yes
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3090, compute capability 8.6, VMM: yes
whisper_backend_init: using CUDA backend
whisper_model_load:     CUDA buffer size =   487.20 MB
whisper_model_load: model size    =  487.00 MB
whisper_backend_init: using CUDA backend
whisper_init_state: kv self size  =   49.55 MB
whisper_init_state: kv cross size =   55.30 MB
whisper_init_state: compute buffer (conv)   =   20.23 MB
whisper_init_state: compute buffer (encode) =  128.14 MB
whisper_init_state: compute buffer (cross)  =    6.31 MB
whisper_init_state: compute buffer (decode) =   97.40 MB
system_info: n_threads = 20 / 24 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | METAL = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | CUDA = 1 | COREML = 0 | OPENVINO = 0 | 
main: processing '/audios/1.wav' (278351189 samples, 17396.9 sec), 2 threads, 10 processors, 5 beams + best of 5, lang = en, task = transcribe, timestamps = 1 ...
whisper_backend_init: using CUDA backend
whisper_init_state: kv self size  =   49.55 MB
whisper_init_state: kv cross size =   55.30 MB
whisper_init_state: compute buffer (conv)   =   20.23 MB
whisper_init_state: compute buffer (encode) =  128.14 MB
whisper_init_state: compute buffer (cross)  =    6.31 MB
whisper_init_state: compute buffer (decode) =   97.40 MB
whisper_backend_init: using CUDA backend
whisper_init_state: kv self size  =   49.55 MB
whisper_init_state: kv cross size =   55.30 MB
whisper_init_state: compute buffer (conv)   =   20.23 MB
whisper_init_state: compute buffer (encode) =  128.14 MB
whisper_init_state: compute buffer (cross)  =    6.31 MB
whisper_init_state: compute buffer (decode) =   97.40 MB
whisper_backend_init: using CUDA backend
whisper_init_state: kv self size  =   49.55 MB
whisper_init_state: kv cross size =   55.30 MB
whisper_init_state: compute buffer (conv)   =   20.23 MB
whisper_init_state: compute buffer (encode) =  128.14 MB
whisper_init_state: compute buffer (cross)  =    6.31 MB
whisper_init_state: compute buffer (decode) =   97.40 MB
whisper_backend_init: using CUDA backend
whisper_init_state: kv self size  =   49.55 MB
whisper_init_state: kv cross size =   55.30 MB
whisper_init_state: compute buffer (conv)   =   20.23 MB
whisper_init_state: compute buffer (encode) =  128.14 MB
whisper_init_state: compute buffer (cross)  =    6.31 MB
whisper_init_state: compute buffer (decode) =   97.40 MB
whisper_backend_init: using CUDA backend
whisper_init_state: kv self size  =   49.55 MB
whisper_init_state: kv cross size =   55.30 MB
whisper_init_state: compute buffer (conv)   =   20.23 MB
whisper_init_state: compute buffer (encode) =  128.14 MB
whisper_init_state: compute buffer (cross)  =    6.31 MB
whisper_init_state: compute buffer (decode) =   97.40 MB
whisper_backend_init: using CUDA backend
whisper_init_state: kv self size  =   49.55 MB
whisper_init_state: kv cross size =   55.30 MB
whisper_init_state: compute buffer (conv)   =   20.23 MB
whisper_init_state: compute buffer (encode) =  128.14 MB
whisper_init_state: compute buffer (cross)  =    6.31 MB
whisper_init_state: compute buffer (decode) =   97.40 MB
whisper_backend_init: using CUDA backend
whisper_init_state: kv self size  =   49.55 MB
whisper_init_state: kv cross size =   55.30 MB
whisper_init_state: compute buffer (conv)   =   20.23 MB
whisper_init_state: compute buffer (encode) =  128.14 MB
whisper_init_state: compute buffer (cross)  =    6.31 MB
whisper_init_state: compute buffer (decode) =   97.40 MB
whisper_backend_init: using CUDA backend
whisper_init_state: kv self size  =   49.55 MB
whisper_init_state: kv cross size =   55.30 MB
whisper_init_state: compute buffer (conv)   =   20.23 MB
whisper_init_state: compute buffer (encode) =  128.14 MB
whisper_init_state: compute buffer (cross)  =    6.31 MB
whisper_init_state: compute buffer (decode) =   97.40 MB
whisper_backend_init: using CUDA backend
whisper_init_state: kv self size  =   49.55 MB
whisper_init_state: kv cross size =   55.30 MB
whisper_init_state: compute buffer (conv)   =   20.23 MB
whisper_init_state: compute buffer (encode) =  128.14 MB
whisper_init_state: compute buffer (cross)  =    6.31 MB
whisper_init_state: compute buffer (decode) =   97.40 MB
[00:00:00.000 --> 00:00:10.000]   [BLANK_AUDIO]
[00:00:10.000 --> 00:00:20.000]   [BLANK_AUDIO]
GGML_ASSERT: ggml-cuda.cu:6742: ptr == (void *) (g_cuda_pool_addr[device] + g_cuda_pool_used[device])`

**Comment by bobqianic** [comment]
```
whisper_backend_init: using CUDA backend
whisper_init_state: kv self size = 49.55 MB
whisper_init_state: kv cross size = 55.30 MB
whisper_init_state: compute buffer (conv) = 20.23 MB
whisper_init_state: compute buffer (encode) = 128.14 MB
whisper_init_state: compute buffer (cross) = 6.31 MB
whisper_init_state: compute buffer (decode) = 97.40 MB
whisper_backend_init: using CUDA backend
whisper_init_state: kv self size = 49.55 MB
whisper_init_state: kv cross size = 55.30 MB
whisper_init_state: compute buffer (conv) = 20.23 MB
whisper_init_state: compute buffer (encode) = 128.14 MB
whisper_init_state: compute buffer (cross) = 6.31 MB
whisper_init_state: compute buffer (decode) = 97.40 MB
whisper_backend_init: using CUDA backend
whisper_init_state: kv self size = 49.55 MB
whisper_init_state: kv cross size = 55.30 MB
whisper_init_state: compute buffer (conv) = 20.23 MB
whisper_init_state: compute buffer (encode) = 128.14 MB
whisper_init_state: compute buffer (cross) = 6.31 MB
whisper_init_state: compute buffer (decode) = 97.40 MB
whisper_backend_init: using CUDA backend
whisper_init_state: kv self size = 49.55 MB
whisper_init_state: kv cross size = 55.30 MB
whisper_init_state: compute buffer (conv) = 20.23 MB
whisper_init_state: compute buffer (encode) = 128.14 MB
whisper_init_state: compute buffer (cross) = 6.31 MB
whisper_init_state: compute buffer (decode) = 97.40 MB
whisper_backend_init: using CUDA backend
whisper_init_state: kv self size = 49.55 MB
whisper_init_state: kv cross size = 55.30 MB
whisper_init_state: compute buffer (conv) = 20.23 MB
whisper_init_state: compute buffer (encode) = 128.14 MB
whisper_init_state: compute buffer (cross) = 6.31 MB
whisper_init_state: compute buffer (decode) = 97.40 MB
whisper_backend_init: using CUDA backend
whisper_init_state: kv self size = 49.55 MB
whisper_init_state: kv cross size = 55.30 MB
whisper_init_state: compute buffer (conv) = 20.23 MB
whisper_init_state: compute buffer (encode) = 128.14 MB
whisper_init_state: compute buffer (cross) = 6.31 MB
whisper_init_state: compute buffer (decode) = 97.40 MB
whisper_backend_init: using CUDA backend
whisper_init_state: kv self size = 49.55 MB
whisper_init_state: kv cross size = 55.30 MB
whisper_init_state: compute buffer (conv) = 20.23 MB
whisper_init_state: compute buffer (encode) = 128.14 MB
whisper_init_state: compute buffer (cross) = 6.31 MB
whisper_init_state: compute buffer (decode) = 97.40 MB
whisper_backend_init: using CUDA backend
whisper_init_state: kv self size = 49.55 MB
whisper_init_state: kv cross size = 55.30 MB
whisper_init_state: compute buffer (conv) = 20.23 MB
whisper_init_state: compute buffer (encode) = 128.14 MB
whisper_init_state: compute buffer (cross) = 6.31 MB
whisper_init_state: compute buffer (decode) = 97.40 MB
whisper_backend_init: using CUDA backend
whisper_init_state: kv self size = 49.55 MB
whisper_init_state: kv cross size = 55.30 MB
whisper_init_state: compute buffer (conv) = 20.23 MB
whisper_init_state: compute buffer (encode) = 128.14 MB
whisper_init_state: compute buffer (cross) = 6.31 MB
whisper_init_state: compute buffer (decode) = 97.40 MB
GGML_ASSERT: ggml-cuda.cu:6742: ptr == (void *) (g_cuda_pool_addr[device] + g_cuda_pool_used[device])`
```

Why are so many buffers being initiated? Oh, I get it, you're using `-p 10`. Try removing that and then give it another try.

**Comment by MorphSeur** [comment]
Thanks a lot!
It finally works!

`-p 10` was used in docker CPU.
_I forgot it!!_
