### ISSUE TITLE
whisper.cpp cant work with more than one gpu card

### ISSUE THREAD

**Issue by UniversalTechno** [ggerganov/whisper.cpp#1775]
whisper.cpp cant work with more than one gpu card when have machine has 2 gpu cards , whisper cpp use only one gpu card

**Comment by ggerganov** [comment]
You can start two separate instances using:

```
CUDA_VISIBLE_DEVICES=0 ./main ...
CUDA_VISIBLE_DEVICES=1 ./main ...
```

**Comment by UniversalTechno** [comment]
THANKS A LOT 
what about server can i do same or there is other methode 
CUDA_VISIBLE_DEVICES=0 ./server ...
CUDA_VISIBLE_DEVICES=1 ./server ...

**Comment by ggerganov** [comment]
You can - just need to start the server on different ports (`--port`)

**Comment by UniversalTechno** [comment]
Great many thanks for your great work  .
