### ISSUE TITLE
-v seem to be default with no way to turn off?

### ISSUE THREAD

**Issue by StuartIanNaylor** [ggerganov/whisper.cpp#178]
Is it possible just to get transcription without the 'process' info as seems like -v is the default but doesn't seem to be a way to turn off?

**Comment by ggerganov** [comment]
Yup, the `-v` option will likely be removed. You can achieve the same effect by piping `stderr` to `/dev/null`. For example:

```
./main -m ./models/ggml-base.en.bin -f ./samples/jfk.wav 2> /dev/null

[00:00:00.000 --> 00:00:11.000]   And so my fellow Americans, ask not what your country can do for you, ask what you can do for your country.
```
