### ISSUE TITLE
win 11 / linux - talk-llama voice interface is broken. Commit d6b9be2 from 19.01.2204

### ISSUE THREAD

**Issue by mirek190** [ggerganov/whisper.cpp#1796]
Under windows 11 / linux no audio output
Commit [d6b9be2](https://github.com/ggerganov/whisper.cpp/commit/d6b9be21d76b91a96bb987063b25e5b532140253) from 19.01.2204

````
.\talk-llama.exe -mw ggml-large-v3.bin -ml marcoroni-7b-v3.Q8_0.gguf -s speak.bat -ngl 99 -t 16
````
Variables $1 and $2 from speak / speak.bat are not passing proper strings 
For instance I changed under windows  speak.ps1 to
````
# Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope CurrentUser
param(
  # voice options are David or Zira
  [Parameter(Mandatory=$true)][string]$voice,
  [Parameter(Mandatory=$true)][string]$text
)

# testing variables
Add-Content -Path C:\AI_music\output.txt -Value $voice
Add-Content -Path C:\AI_music\output.txt -Value $text

Add-Type -AssemblyName System.Speech;
$speak = New-Object System.Speech.Synthesis.SpeechSynthesizer;
$speak.SelectVoice("Microsoft $voice Desktop");
$speak.Rate="0";
$speak.Speak($text);

````

to get variables $1 and $2 to a file

Output the output.txt during talking with talk-llama
````
2
'
2
'
2
'
2
'
2
'
````

Conclusion - audio interface is broken.

**Comment by mirek190** [comment]
Hello

any chance to fix it?

**Comment by ggerganov** [comment]
I don't have a Windows machine, so hoping someone else to help with this

**Comment by mirek190** [comment]
Under Linux audio also not working with talk-llama
