### ISSUE TITLE
Cheaper hardware to run bigger model 

### ISSUE THREAD

**Issue by ekorudi** [ggerganov/whisper.cpp#18]
Refer our discussion at #8  , I can run ```ggml-large.bin```, for same input audio 120 sec ( 2 minutes) in around 54 minutes on Samsung A52.

What is your suggestion for optimization to run bigger model on cheaper hardware:
1. Selecting better hardware for array manipulation (Neon?)
2. Improve algorithm 
3. Use GPU provided by hardware 
4. ... ?

Will be happy if you share the resource I can learn to achieve that goal.

**Comment by ggerganov** [comment]
As I mentioned in #8, I think some extra performance could be gained by properly implementing the SIMD routines in `ggml.c` for the Android Arm architecture:

- https://github.com/ggerganov/whisper.cpp/blob/8dd855adbc6cd448050823f2da2ee4dbdc2ae6f4/ggml.c#L303
- https://github.com/ggerganov/whisper.cpp/blob/8dd855adbc6cd448050823f2da2ee4dbdc2ae6f4/ggml.c#L476

I don't think that the current implementation is optimal - it was just something that I hacked to make it run on RPi4.

But in any case - this will probably lead to a few 10s of percent improvement at best. Not sure what is your expectation for these devices. The large model inference will always be at least an order of magnitude longer than the audio length on a phone device.

I don't know what GPUs are available available on modern mobile devices, but I don't plan on supporting them. Usually, it involves using some complex framework (e.g. CUDA, OpenCL, Metal, etc) and it take a lot of expertise and experience to utilize these efficiently.

Regarding the algorithm improvement:
The inference algorithm consists of relatively simple operations with matrices and vectors. Not much can be done to improve the algorithm, other than implementing efficiently these basic operations. The common strategies are:
  - SIMD implementation
  - cache-aware data storage
  - multi-threading
  - packing data into smaller elements (for example 32-bit float into 16-bit or 8-bit float / int) at the cost of some precision

I have an idea for reducing the memory for the large model even further that I want to experiment with at some point, but most likely it will fail. So, I don't think the algorithm can be improved in any significant way.

**Comment by ArtyomZemlyak** [comment]
An alternative solution could be to retrain a small model for a data domain, a specific task, or a specific language.

I think that you want to use a large model just because of its quality. Therefore, it is possible that it is worth considering additional training options for smaller models, but train them so that their quality is satisfactory.

But I can say that with Whisper it will not be an easy task now, since there are no official scripts for training or pre-training. But there are a couple of some written by craftsmen.

Now I'm trying a solution combined from two such scripts, but so far the quality is even worse compared to the original. On the most pre-training dataset, CER decreases, but on real examples, recognition becomes worse.

**Comment by ggerganov** [comment]
@ekorudi You might want to give a try using the latest `master` branch - it is possible that the performance is a bit better now. Let me know if there is a build issue.

**Comment by ekorudi** [comment]
Error on compile for Android 

```
$ make
/ok/whisper/arm-compiler/bin/aarch64-linux-android28-clang  -O3 -std=c11 -Wall -Wextra -Wno-unused-parameter -Wno-unused-function -pthread -mavx -mavx2 -mfma -mf16c   -c ggml.c
clang80: warning: argument unused during compilation: '-mavx' [-Wunused-command-line-argument]
clang80: warning: argument unused during compilation: '-mavx2' [-Wunused-command-line-argument]
clang80: warning: argument unused during compilation: '-mfma' [-Wunused-command-line-argument]
clang80: warning: argument unused during compilation: '-mf16c' [-Wunused-command-line-argument]
/ok/whisper/arm-compiler/bin/aarch64-linux-android28-clang++ -O3 -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wno-unused-function -pthread -c whisper.cpp
/ok/whisper/arm-compiler/bin/aarch64-linux-android28-clang++ -O3 -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wno-unused-function -pthread main.cpp whisper.o ggml.o -o main -static-libstdc++
./main -h
/system/bin/linker64: No such file or directory
Makefile:56: recipe for target 'main' failed
make: *** [main] Error 255

```

Error on compile for Linux Intel
```
$ make
cc  -O3 -std=c11 -Wall -Wextra -Wno-unused-parameter -Wno-unused-function -pthread -mavx -mavx2 -mfma -mf16c   -c ggml.c
ggml.c:189:36: error: initializer element is not constant
 const size_t CACHE_LINE_SIZE_F32 = CACHE_LINE_SIZE/sizeof(float);
                                    ^~~~~~~~~~~~~~~
Makefile:60: recipe for target 'ggml.o' failed
make: *** [ggml.o] Error 1

```

**Comment by ArtyomZemlyak** [comment]
> Error on compile for Linux Intel

Has same issue, then trying compile on server.
Solved installed gcc-9 (previos gcc-7).
