### ISSUE TITLE
I cant convert server http request to a javascript request 

### ISSUE THREAD

**Issue by UniversalTechno** [ggerganov/whisper.cpp#1808]
I tried so many methode to make a server http request using javascript but all the im getting the following errors 

Received request: output.wav
read_wav: WAV file 'whisper_server_temp_file.wav' must be 16-bit
error: failed to read WAV file 'whisper_server_temp_file.wav'
Received request: 
error: failed to open 'whisper_server_temp_file.wav' as WAV file
error: failed to read WAV file 'whisper_server_temp_file.wav'

and a model of my source code is   : 

  async function sendToCppServer(base64Data) {
    // Create a FormData object
    const formData = new FormData();
    formData.append('file', base64Data);
    formData.append('temperature', '0.0');
    formData.append('temperature_inc', '0.2');
    formData.append('response_format', 'json');

    // Make the HTTP request using fetch
    try {
      const response = await fetch('http://127.0.0.1:8080/inference', {
        method: 'POST',
        body: formData,
      });

      if (!response.ok) {
        throw new Error(`HTTP error! Status: ${response.status}`);
      }

      const data = await response.json();
      // Handle the response data as needed
      console.log('Response:', data);
    } catch (error) {
      // Handle errors
      console.error('Error:', error);
    }
  }
 
i used so many other methodes like 
 // Convert WAV buffer to Blob
    const wavBlob = new Blob([wavBuffer], { type: 'audio/wav' });

    // Append the WAV Blob to the FormData
    formData.append('file', wavBlob, 'output.wav');
    formData.append('temperature', '0.0');
    formData.append('temperature_inc', '0.2');
    formData.append('response_format', 'json');
*
but unfortunately i cant succeed 
please any help so we can add the javascript source request into the repository

**Comment by teddybear082** [comment]
I don’t know about the JavaScript part but try running the server with —convert command line argument and see how that goes

**Comment by UniversalTechno** [comment]
thanks it was an issue with the wav format sent

**Comment by aldrinjenson** [comment]
Hi @UniversalTechno , I am facing the same issue.
Could you please paste the working POST request with fetch
