### ISSUE TITLE
Input dispatching timed out 

### ISSUE THREAD

**Issue by SchweitzerGAO** [ggerganov/whisper.cpp#1828]
I am running the code of Android example in Java, but when it begins to transcribe, the main thread is stuck with the following error:
![image](https://github.com/ggerganov/whisper.cpp/assets/64410968/fba65b8f-18f7-4cac-ac58-cb284bf5b7f9)
It will be very kind of you if anyone can help me with this

**Comment by bobqianic** [comment]
cc @litongjava

**Comment by SchweitzerGAO** [comment]
Update: I run the demo independently from my own project and discovered that it is so slow to transcribe with whisper-base, which takes about 22s

**Comment by ggerganov** [comment]
Are you building in Release?

**Comment by SchweitzerGAO** [comment]
No @ggerganov  will this help solve the problem?

**Comment by ggerganov** [comment]
Building in Release compared to Debug will improve the performance significantly

**Comment by SchweitzerGAO** [comment]
Thanks and I will try
