### ISSUE TITLE
[QUESTION] Multiple GPU support

### ISSUE THREAD

**Issue by Alvarocda** [ggerganov/whisper.cpp#1846]
Hello, I would like to know if it is possible to run Whisper.cpp on a PC with multiple GPUs?

If so, when doing the transcription will it divide the processing between the GPUs or will it run the transcription process on just 1 of the GPUs? And if the process is going to run on just 1 GPU, can I define which of the GPUs it will run on?

**Comment by ggerganov** [comment]
No, only single GPU is supported at the moment. You can run multiple separate instances each on a different GPU though

**Comment by Alvarocda** [comment]
And how would this be done? I took a look at the available parameters and didn't find any parameters that define which GPU will be used to perform the transcription.

**Comment by ggerganov** [comment]
For example:

```bash
# process using GPU 0
CUDA_VISIBLE_DEVICES=0 ./main ...

# process using GPU 1
CUDA_VISIBLE_DEVICES=1 ./main ...

...
```

**Comment by Alvarocda** [comment]
Thanks a lot for the help.
