### ISSUE TITLE
talk-llama not buildable 

### ISSUE THREAD

**Issue by Exw27** [ggerganov/whisper.cpp#1880]
`egrep: warning: egrep is obsolescent; using grep -E
I whisper.cpp build info: 
I UNAME_S:  Linux
I UNAME_P:  unknown
I UNAME_M:  x86_64
I CFLAGS:   -I.              -O3 -DNDEBUG -std=c11   -fPIC -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -pthread -mavx -mavx2 -mfma -mf16c -msse3 -mssse3
I CXXFLAGS: -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -pthread -mavx -mavx2 -mfma -mf16c -msse3 -mssse3
I LDFLAGS:  
I CC:       cc (GCC) 13.2.1 20230801
I CXX:      g++ (GCC) 13.2.1 20230801

g++ -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -pthread -mavx -mavx2 -mfma -mf16c -msse3 -mssse3 examples/talk-llama/talk-llama.cpp examples/talk-llama/llama.cpp examples/common.cpp examples/common-ggml.cpp examples/common-sdl.cpp ggml.o ggml-alloc.o ggml-backend.o ggml-quants.o whisper.o -o talk-llama `sdl2-config --cflags --libs` 
examples/talk-llama/talk-llama.cpp: In function ‘int main(int, char**)’:
examples/talk-llama/talk-llama.cpp:426:19: warning: ‘int llama_eval(llama_context*, llama_token*, int32_t, int32_t)’ is deprecated: use llama_decode() instead [-Wdeprecated-declarations]
  426 |     if (llama_eval(ctx_llama, embd_inp.data(), embd_inp.size(), 0)) {
      |         ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from examples/talk-llama/talk-llama.cpp:7:
examples/talk-llama/llama.h:562:30: note: declared here
  562 |     LLAMA_API DEPRECATED(int llama_eval(
      |                              ^~~~~~~~~~
examples/talk-llama/llama.h:27:36: note: in definition of macro ‘DEPRECATED’
   27 | #    define DEPRECATED(func, hint) func __attribute__((deprecated(hint)))
      |                                    ^~~~
examples/talk-llama/talk-llama.cpp:650:39: warning: ‘int llama_eval(llama_context*, llama_token*, int32_t, int32_t)’ is deprecated: use llama_decode() instead [-Wdeprecated-declarations]
  650 |                         if (llama_eval(ctx_llama, embd.data(), embd.size(), n_past)) {
      |                             ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
examples/talk-llama/llama.h:562:30: note: declared here
  562 |     LLAMA_API DEPRECATED(int llama_eval(
      |                              ^~~~~~~~~~
examples/talk-llama/llama.h:27:36: note: in definition of macro ‘DEPRECATED’
   27 | #    define DEPRECATED(func, hint) func __attribute__((deprecated(hint)))
      |                                    ^~~~
examples/talk-llama/llama.cpp: In function ‘ggml_tensor* llm_build_kqv(ggml_context*, const llama_model&, const llama_hparams&, const llama_kv_cache&, ggml_cgraph*, ggml_tensor*, ggml_tensor*, ggml_tensor*, ggml_tensor*, int64_t, int32_t, int32_t, float, float, const llm_build_cb&, int)’:
examples/talk-llama/llama.cpp:4728:28: warning: ‘ggml_tensor* ggml_alibi(ggml_context*, ggml_tensor*, int, int, float)’ is deprecated: use ggml_soft_max_ext instead (will be removed in Mar 2024) [-Wdeprecated-declarations]
 4728 |             kq = ggml_alibi(ctx, kq, /*n_past*/ 0, n_head, max_alibi_bias);
      |                  ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from examples/talk-llama/llama.h:4,
                 from examples/talk-llama/llama.cpp:2:
./ggml.h:1500:51: note: declared here
 1500 |     GGML_DEPRECATED(GGML_API struct ggml_tensor * ggml_alibi(
      |                                                   ^~~~~~~~~~
./ggml.h:202:41: note: in definition of macro ‘GGML_DEPRECATED’
  202 | #    define GGML_DEPRECATED(func, hint) func __attribute__((deprecated(hint)))
      |                                         ^~~~
examples/talk-llama/llama.cpp:4738:50: error: cannot convert ‘float’ to ‘ggml_tensor*’
 4738 |         kq = ggml_soft_max_ext(ctx, kq, kq_mask, kq_scale);
      |                                                  ^~~~~~~~
      |                                                  |
      |                                                  float
./ggml.h:1396:35: note:   initializing argument 4 of ‘ggml_tensor* ggml_soft_max_ext(ggml_context*, ggml_tensor*, ggml_tensor*, ggml_tensor*, float, float)’
 1396 |             struct ggml_tensor  * pos,
      |             ~~~~~~~~~~~~~~~~~~~~~~^~~
examples/talk-llama/llama.cpp: In function ‘void llama_backend_init(bool)’:
examples/talk-llama/llama.cpp:11004:23: error: too few arguments to function ‘void ggml_numa_init(ggml_numa_strategy)’
11004 |         ggml_numa_init();
      |         ~~~~~~~~~~~~~~^~
./ggml.h:683:22: note: declared here
  683 |     GGML_API void    ggml_numa_init(enum ggml_numa_strategy numa); // call once for better performance on NUMA systems
      |                      ^~~~~~~~~~~~~~
make: *** [Makefile:414: talk-llama] Error 1
`

**Comment by ggerganov** [comment]
Yes, sorry I forgot to sync. Should be good now
