### ISSUE TITLE
ggml.c: error: 'SYS_getcpu' undeclared did you mean 'SYS_get_cpu'

### ISSUE THREAD

**Issue by themanyone** [ggerganov/whisper.cpp#1894]
On both projects, **whisper.cpp**, and **llama.cpp**, we get this compilation error with latest git when compiling with CUBLAS.

 `WHISPER_CUBLAS=1 make -j`

```
ggml.c: In function 'ggml_numa_init':
ggml.c:2088:26: error: 'SYS_getcpu' undeclared (first use in this function); did you mean 'SYS_get_cpu'?
 2088 |     getcpu_ret = syscall(SYS_getcpu,&current_cpu,&g_state.numa.current_node);
      |                          ^~~~~~~~~~
      |                          SYS_get_cpu
ggml.c:2088:26: note: each undeclared identifier is reported only once for each function it appears in
make: *** [Makefile:317: ggml.o] Error 1
```

The fix is very straightforward. We simply drop in `SYS_get_cpu`.

**Comment by petterreinholdtsen** [comment]
I created bull request #1897 based on your description, and hope it will be included in the master branch soon.

**Comment by ggerganov** [comment]
Hm, that's strange. We should be able to check which of the 2 is available (`SYS_getcpu` or `SYS_get_cpu`) and use the correct one

cc @bmtwl Any ideas?

**Comment by petterreinholdtsen** [comment]
[Georgi Gerganov]
> Hm, that's strange. We should be able to check which of the 2 is
> available (`SYS_getcpu` or `SYS_get_cpu`) and use the correct one

I tried tracking down if and when the define changed in glibc, without
any luck, so I can not tell which version of glibc to use as a
separator.

On the other hand, the code in
/usr/include/x86_64-linux-gnu/bits/syscall.h
look like this:

  #ifdef __NR_getcpu
  # define SYS_getcpu __NR_getcpu
  #endif

It is thus very simple to use a construct like this:

  #if defined(SYS_getcpu)
   ... use SYS_getcpu
  #elif defined(SYS_get_cpu)
   ... use SYS_get_cpu
  #endif

-- 
Happy hacking
Petter Reinholdtsen

**Comment by themanyone** [comment]
That should do it. I'm stuck using gcc-12 for acceleration, because Nvidia cuBLAS requires it for their old glibc workarounds (Nvidia's workarounds conflict with gcc-13's hot patches which [re]address the same issue, leading to conflicts).

**Comment by ggerganov** [comment]
Ok, would like to hear if @cebtenzzre agrees before merging

**Comment by bmtwl** [comment]
I tested the proposed strategy on a private branch and it worked through the permutations I tried.

`+#if defined SYS_get_cpu`
`+    getcpu_ret = syscall(SYS_get_cpu,&current_cpu,&g_state.numa.current_node);`
`+#elif defined SYS_getcpu`
`     getcpu_ret = syscall(SYS_getcpu,&current_cpu,&g_state.numa.current_node);`
`+#endif`

Has a PR been submitted for this issue, or is there still a need for one?

**Comment by petterreinholdtsen** [comment]
[bmwl]
> Has a PR been submitted for this issue, or is there still a need for
> one?

I created #1897 with my proposed solution.  Feel free to adjust it if
you want a different approach.

-- 
Happy hacking
Petter Reinholdtsen
