### ISSUE TITLE
Add support for 1.5, 2 and 3 bit quantization

### ISSUE THREAD

**Issue by bil-ash** [ggerganov/whisper.cpp#1900]
Ggml and llama.cpp has recently added support for 1.5-, 2- and 3-bit quantization. So, @ggerganov please add these quantization support to whisper.cpp as well. Will be useful for running the whisper-large models with limited RAM.

**Comment by bobqianic** [comment]
> Ggml and llama.cpp has recently added support for 1.5-, 2- and 3-bit quantization.

Whisper.cpp already supports `Q2_K` and `Q3_K`. If you give it a try, you'll notice that the quality of the results has significantly deteriorated. I can not see any reasons we need to implement `1.5bit` quantization.

**Comment by bil-ash** [comment]
Would be nice if this is added to the docs

**Comment by bil-ash** [comment]
Yeah, ran the inference on q2_k and realized that inference is horrible. So closing the issue
