### ISSUE TITLE
Add time frames

### ISSUE THREAD

**Issue by DittmerOk** [ggerganov/whisper.cpp#1919]
Tell me, in the example it is indicated
./main -m models/ggml-large-v1.bin -l ru --no-timestamps -f ~/output.wav -of output -otxt
This is to remove the time frames, but how can we make sure they still exist? If I delete --no-timestamps, then they are still not there? How can I make them exist?

**Comment by bobqianic** [comment]
In the function located in main.cpp, you'll notice that when we direct the output to a text file, we only include the textual content, excluding any special tokens. If you wish to include special tokens in the text file output, please make use of the additional option `--print-special`

**Comment by DittmerOk** [comment]
yes, thanks. it's work
