### ISSUE TITLE
CUDA on Windows

### ISSUE THREAD

**Issue by jwijffels** [ggerganov/whisper.cpp#1922]
Hello again,

I'm trying to configure the R wrapper at https://github.com/bnosac/audio.whisper to make it use CUBLAS. 
That works smoothly on Linux giving same transcription speeds as whisper.cpp with the R wrapper.
On Windows however, I see the Makefile will not work as it has Linux specific paths https://github.com/ggerganov/whisper.cpp/blob/master/Makefile#L218-L230

In order to see if this would work on windows, I've duplicated your continuous integration flow at https://github.com/ggerganov/whisper.cpp/blob/master/.github/workflows/build.yml#L253-L311 in the audio.whisper R package
and tried to compile with (as show at https://github.com/bnosac/audio.whisper/blob/cuda-windows/src/Makevars#L156-L161) where `CUDA_PATH `is `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2`

```
	NVCC         = nvcc
	PKG_CFLAGS   += -DGGML_USE_CUBLAS -I"$(CUDA_PATH)/include" 
	PKG_CPPFLAGS += -DGGML_USE_CUBLAS -I"$(CUDA_PATH)/include" 
	PKG_LIBS     += -lcuda -lcublas -lculibos -lcudart -lcublasLt -lpthread -ldl -lrt -L"$(CUDA_PATH)/lib64" -L/usr/lib/wsl/lib
	NVCCFLAGS    = --forward-unknown-to-host-compiler -arch=$(CUDA_ARCH_FLAG)
	OBJECTS_CUDA = whisper_cpp/ggml-cuda.o
```

That seems to fail. As there is no culibos nor rt in the Windows at C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.3/lib/x64 and removing these `(-lculibos  -lrt)` gives similar errors as https://forums.developer.nvidia.com/t/missing-lib-files-culibos-dl-rt-for-cublas/276707

What would be the statements to compile whisper.cpp on Windows (in casu using mingw)?

**Comment by bobqianic** [comment]
> What would be the statements to compile whisper.cpp on Windows (in casu using mingw)?

AFAIK, CUDA does not support MinGW on Windows.

https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html

**Comment by jwijffels** [comment]
Thanks for the confirmation on this. This is also what I thought.

I see in your CI at https://github.com/ggerganov/whisper.cpp/blob/master/.github/workflows/build.yml#L285-L289 you are using cmake instead of make. Which compiler does that then use on Windows?

**Comment by bobqianic** [comment]
> Which compiler does that then use on Windows?

You can see the logs in the CI. They're using Microsoft Visual C++ (MSVC)

https://github.com/ggerganov/whisper.cpp/actions/runs/8158489794/job/22300537410#step:6:9

**Comment by jwijffels** [comment]
Thanks for the help and the time taken to answer!
