### ISSUE TITLE
Compilation / distribution of a whisper.dll that 'just works' and is performant across all x86 processors, whether they support AVX2 extensions or not

### ISSUE THREAD

**Issue by RyanMetcalfeInt8** [ggerganov/whisper.cpp#1939]
Hello,

I am the lead for this project: https://github.com/intel/openvino-plugins-ai-audacity

As part of these Audacity plugins, we have a whisper transcription feature that uses whisper.cpp under the hood. For our pre-compiled distribution, we distribute whisper.dll (compiled from this project of course).

There are many users that have complained about DLL loading related issues. It turns out that the root cause in the vast majority of these cases is that the user is running on x86 platforms that do not have AVX/AVX2 instructions set extension support.

So, I wanted to ask if anyone has come up with a method to compile whisper.dll such that it is well supported across x86 platforms?

And before you ask 😄  
1. I realize I can add ```-DWHISPER_NO_AVX``` / ```-DWHISPER_NO_AVX2``` CMake options, and this would solve the distribution problem, but then it would be much less performant on machines that actually support AVX2.

2. And yeah, I suppose I could compile 2 versions of whisper.dll (one with AVX enabled, one without), and then selectively install it.. but I don't really want to go down that path.

Anyway, anyone have any ideas?

Thanks!

**Comment by ggerganov** [comment]
Hey, very cool to see `whisper.cpp` as a plugin for Audacity!

Unfortunately, we don't have a good solution to the described problem. We first discussed this last year (https://github.com/ggerganov/ggml/issues/86) and back then the proposed solution was your pt.2.

There are ways to make this work with a single binary, but I'm afraid it would require a huge change in the core library, and I'm not very interested in doing it. One of the proposals was here: https://github.com/ggerganov/whisper.cpp/pull/1261 - not sure if it would be of help, but might be worth a look

**Comment by RyanMetcalfeInt8** [comment]
Hey @ggerganov,

Thanks for the info! I'll take a look at the links that you shared -- looks like others have been thinking about this as well.

Cheers!
Ryan

**Comment by MarkR-A** [comment]
Hi Ryan, first of all thanks for all your amazing work! Do you know when, if at all, openvino ai plugins for Audacity will be compatible with Intel Xeon CPUs (in general)?

**Comment by RyanMetcalfeInt8** [comment]
Hi @MarkR-A,

You can try the new release of our Audacity plugins (https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.5.1-R2). This should support Intel Xeon CPUs, even ones that do not support AVX/AVX2 instructions. We do this by conditionally installing an AVX2-enabled version of whisper.dll, based on the detected instruction set support on the system running the installer.

Thanks,
Ryan
