### ISSUE TITLE
How to calculate token size from string?

### ISSUE THREAD

**Issue by sindresorhus** [ggerganov/whisper.cpp#1962]
I'm using the `params.initial_prompt` setting in my app, and I would like to interactively warn the user if they exceed the prompt limit. Given a string, how can I calculate the token size?

**Comment by felrock** [comment]
You could use `static std::vector<whisper_vocab::id> tokenize(const whisper_vocab & vocab, const std::string & text)` on your initial_prompt and check the length, compare it to your context size.

**Comment by sindresorhus** [comment]
I'm using Whisper.cpp's C API from Swift. But I now see that I could use `whisper_tokenize`. However, it's a bit of a waste to fill up the tokens array when I only care about the size.

So my request is to add something like this:

```c++
int whisper_token_count(struct whisper_context * ctx, const char * text) {
    const auto res = tokenize(ctx->vocab, text);
    return res.size();
}
```

**Comment by felrock** [comment]
Your request is a bit too specific imo. You can create a function like that yourself, just disregard the tokens after you've checked the size.

**Comment by sindresorhus** [comment]
Any app accepting a custom prompt will need this. Of course every app could reinvent the wheel, but I think many app developers don't even realize they have to validate the prompt. I for sure did not. Having a specific function like this makes it more discoverable that they need to.
