### ISSUE TITLE
Large model failed on a small sample (42 seconds)

### ISSUE THREAD

**Issue by RYucel** [ggerganov/whisper.cpp#197]
I just received an error on windows 10 machine with yesterday's binary file (actions section: whisper-bin-x64) first time for large model after trying to transcript this wav file: 
https://filetransfer.io/data-package/xiPWRU2L#link
`main -m ggml-model-whisper-large.bin -t 4 -otxt -f cvdt.wav -l tr`

It's around 40 seconds length but large model failed most btw all models I tried (small, medium, large). It just found first 0-3 seconds and last 1 second part. Between these sections not transcribed, while smaller models did much better. What could be the reason for this strange result for Large model?

**Comment by ggerganov** [comment]
This is similar to #68 
I have fixed it in the `sampling-fixes` branch, but I want to do some more testing before merging it to `master.

**Comment by ggerganov** [comment]
Should be fixed on `master`
