### ISSUE TITLE
Android CLBlast build crashes app with `dlopen failed: library "libGLES_mali.so" not found` message

### ISSUE THREAD

**Issue by colonist4** [ggerganov/whisper.cpp#1972]
I tried to build sample android app following [README.md](https://github.com/ggerganov/whisper.cpp/blob/master/examples/whisper.android/README.md)

Build is successful, however when i open app, it crashes with error message `dlopen failed: library "libGLES_mali.so" not found`
Is anyone can help me?

**logcat Error message**
```
FATAL EXCEPTION: main
Process: com.whispercppdemo, PID: 12865
java.lang.UnsatisfiedLinkError: dlopen failed: library "libGLES_mali.so" not found: needed by /data/app/~~T-kC1tU977YBeE20fmb45Q==/com.whispercppdemo-TrFQV3fCtmvlmsEO3tPuOg==/base.apk!/lib/arm64-v8a/libclblast.so in namespace classloader-namespace
	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
	at java.lang.System.loadLibrary(System.java:1656)
	at b4.h.<clinit>(Unknown Source:141)
	at e4.j.i(Unknown Source:44)
	at l4.a.p(Unknown Source:7)
	at u.q.U0(Unknown Source:141)
	at b5.a.g0(Unknown Source:85)
	at c3.a.f0(Unknown Source:46)
```

**Build tool versions**
- NDK : 25.2.9519653
- targetSdkVersion : 34
- device info : Galaxy S10e (Android 12)

**Detail build steps i tried**
1. Clone [CLBlast repo](https://github.com/CNugteren/CLBlast) & [OpenCL-Headers repo](https://github.com/KhronosGroup/OpenCL-Headers)
2. Pull device's `libOpenCL.so` file to `OpenCL-Headers/lib`
`adb pull /vendor/lib64/libOpenCL.so ~/OpenCL-Headers/lib/`
3. Bulid CLBlast lib with following below command
https://github.com/ggerganov/whisper.cpp/blob/725350d4ea1545d890fe41f815b851cbc57838f6/examples/whisper.android/README.md?plain=1#L24-L38
4. Modify android project's gradle.properties following
https://github.com/ggerganov/whisper.cpp/blob/725350d4ea1545d890fe41f815b851cbc57838f6/examples/whisper.android/README.md?plain=1#L51-L57
5. Remove ggml repo's linker option `--copy-dt-needed-entries` at 'CMakeLists.txt' line 202 (Because android llvm linker not supports this option and throws error)
6. Run android project on device

**Comment by colonist4** [comment]
Solved by changing soname of libOpenCL.so into 'OpenCL' before build CLBlast and ggml.

**Comment by kirri** [comment]
Hi @colonist4,

I get the exact same logcat error message: library "libGLES_mali.so" not found.
Can you please explain in more detail what you changed in order to solve this?

Thanks!

**Comment by colonist4** [comment]
@kirri 

Are you built CLBlast and ggml library yourself with pulled libOpenCL.so file from device?

If you check the SONAME of "libOpenCL.so", then it shown as "libGLES_mali.so". This is wrong part.
So you should change SONAME of libOpenCL.so before building CLBlast and ggml.

This https://stackoverflow.com/questions/18467163/is-there-any-way-to-change-the-soname-of-a-binary-directly will help you.

**Comment by minyoung-cho** [comment]
Hi @colonist4,

I get the exact same logcat error message: library "libGLES_mali.so" not found.
Can you please explain in more detail what you changed in order to solve this?

And `Solved by changing soname of libOpenCL.so into 'OpenCL' before build CLBlast and ggml.` please explan in more detail.

Thanks!

**Comment by colonist4** [comment]
@minyoung-cho

Did you built CLBlast and ggml ?
Please describe the build steps you performed, then i will point wrong step out.
