### ISSUE TITLE
Release v1.5.5 ??

### ISSUE THREAD

**Issue by Erim32** [ggerganov/whisper.cpp#2031]
Just an open issue or discussion to share visibility about the realease v1.5.5.
Last release ( v1.5.4) was 4 month ago.

Any target date or features to completed before to be able to deploy a new release ?
Maybe could you had some pre-release version ( every month or every two month ).

**Comment by ggerganov** [comment]
Will try to put v1.5.5 soon. Ping me if it is not up in a couple of days

**Comment by Erim32** [comment]
@ggerganov Ping to remind you about the v1.5.5, as requested in your previous message.

**Comment by ggerganov** [comment]
It's up now: https://github.com/ggerganov/whisper.cpp/releases/tag/v1.5.5
