### ISSUE TITLE
Large model repetitive "Thank you" message

### ISSUE THREAD

**Issue by pbochan** [ggerganov/whisper.cpp#2037]
Hello, 

I'm facing a weird behaviour of how a large model reacts to an empty inference message: it keeps generating "Thank you" caption over and over again for English (for other languages, say, Ukrainian, it generates "Дякую", for Russian "Спасибо" and so on). The medium model (and other smaller models) generates "{BLANK_AUDIO}" or "[LAUGHING]" and so on.

How can large model react to empty inference results with at least "{BLANK_AUDIO}" but not with endless "Thank you" messages?

Thanks,
P

**Comment by mechiland** [comment]
+1 on @pbochan 

I've tried Chinese on `ggml-large-v3.bin` with language set to 'auto'. The original audio is Chinese, and the output is meanlinglessly repeating: 

<img width="537" alt="image" src="https://github.com/ggerganov/whisper.cpp/assets/33785/33d8a4f6-d572-4086-a3c9-5b078a4978ed">

Feel like the model is polluted.

**Comment by pbochan** [comment]
@mechiland, thanks for a reply. Indeed, large model v1 does have way less “thank you” messages.
