### ISSUE TITLE
M1 Max, Whisper CPP 1.5.5 has increased CPU usage

### ISSUE THREAD

**Issue by Makememo** [ggerganov/whisper.cpp#2066]
- macOS Sonoma 14.4.1
- medium.en or medium

1.5.5
![image](https://github.com/ggerganov/whisper.cpp/assets/140973261/c22d7f33-69df-4c15-b604-3ab8d87ef13d)

1.5.4
![image](https://github.com/ggerganov/whisper.cpp/assets/140973261/20bbb7f6-4c17-41b2-aa5d-50fc1f64aea2)

---
1.5.5 Parameter Information
![image](https://github.com/ggerganov/whisper.cpp/assets/140973261/7f3f1e3c-bd3b-4cad-ae69-9b81c7f38bc5)

1.5.5 output information
![image](https://github.com/ggerganov/whisper.cpp/assets/140973261/9e9ff0a0-2c1e-4bc2-9a32-ac52bcb38edb)

**Comment by ggerganov** [comment]
Thanks for spotting that - seems like a regression introduced in https://github.com/ggerganov/whisper.cpp/pull/1997

Could you check if https://github.com/ggerganov/whisper.cpp/pull/2070 fixes the isssue?

**Comment by Makememo** [comment]
No problems after testing. Thank you very much.

I also tested#1997，Twice as long as the change option is not enabled.

I'll resubmit a issue.

Enable
whisper_print_timings:    total time = 223807.66 ms

Not enabled
whisper_print_timings:    total time = 108195.09 ms

**Comment by ulatekh** [comment]
Argh...sorry for introducing that. I've been consistently using suppress_regex since its inception.
