### ISSUE TITLE
Feature request - Support WhisperSpeech for voice generation with whisper model

### ISSUE THREAD

**Issue by LSXAxeller** [ggerganov/whisper.cpp#2089]
**WhisperSpeech is a text-to-speech/voice generation/voice cloning model** derived from OpenAI's Whisper model inversion. Integrating support for it into Whisper.cpp would enhance the functionality of whisper.cpp to cover all primary voice operations. can it be integrated ? 
[WhisperSpeech Repo](https://github.com/collabora/WhisperSpeech)

**Comment by przemoc** [comment]
Thank you for mentioning:

- https://github.com/collabora/WhisperSpeech

Seems interesting. But I'm not sure if Georgi wouldn't prefer to have it as a separate project, e.g. whisperspeech.cpp. :)
Having both ASR and TTS in one project would be cool for sure, but it could make the maintenance harder, and maybe some tweaked version of whisper is needed there (don't know, as I haven't investigated it).

whisperspeech.cpp could be a nice alternative to:

- https://github.com/PABannier/bark.cpp

**Comment by ggerganov** [comment]
Looks like an interesting project, but probably I won't get around to integrating it anytime soon
