### ISSUE TITLE
MSVC static runtime library

### ISSUE THREAD

**Issue by pierreguillot** [ggerganov/whisper.cpp#2109]
It would be great to be able to define the MSVC runtime library via [CMAKE_MSVC_RUNTIME_LIBRARY](https://cmake.org/cmake/help/latest/variable/CMAKE_MSVC_RUNTIME_LIBRARY.html) (or the MSVC_RUNTIME_LIBRARY property). However, this feature has only been included in CMake 3.15. Would it be possible to set this version as the minimum? Or set the minimum version to 3.5 only if it is not yet defined?

```
if(NOT DEFINED CMAKE_MINIMUM_REQUIRED_VERSION)
  cmake_minimum_required(VERSION 3.5)
endif()
```

P.S. I can create a PR if necessary.

**Comment by thewh1teagle** [comment]
I spent hours debugging why it doesn't respect setting static msvc linking. 

I tried with `set(MSVC_RUNTIME_LIBRARY, "MultiThreaded")` or `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /MT")`

Eventually the only way worked:

```cmake
if (MSVC)
    set(CompilerFlags
            CMAKE_CXX_FLAGS
            CMAKE_CXX_FLAGS_DEBUG
            CMAKE_CXX_FLAGS_RELEASE
            )
    foreach(CompilerFlag ${CompilerFlags})
    string(REPLACE "/MD" "/MT" ${CompilerFlag} "${${CompilerFlag}}")
    endforeach()
endif()
```

**Comment by altunenes** [comment]
Any hope of this? same issue on Windows. :(

**Comment by pierreguillot** [comment]
I found a much less hacky solution than replacing the `CMAKE_CXX_FLAGS`. Just set `CMP0091` policy to `NEW` and set the `MSVC_RUNTIME_LIBRARY` property of the `ggml` and `whisper` targets to `“MultiThreaded$<$<CONFIG:Debug>:Debug>”`. Here's an example:

```cmake
cmake_minimum_required(VERSION 3.18)
cmake_policy(SET CMP0091 NEW)
...
set_target_properties(ggml PROPERTIES MSVC_RUNTIME_LIBRARY “MultiThreaded$<$<CONFIG:Debug>:Debug>”)
set_target_properties(whisper PROPERTIES MSVC_RUNTIME_LIBRARY “MultiThreaded$<$<CONFIG:Debug>:Debug>”)
```

I had previously thought this approach didn't work, but I must have forgotten to define the policy 🤦. Anyway, even it seems to me that pushing the CMake version would be a good thing, this workaround is acceptable to me 🙂 so I close this issue.
