### ISSUE TITLE
Disabling WHISPER_LOG_INFO

### ISSUE THREAD

**Issue by pprobst** [ggerganov/whisper.cpp#2111]
Hello. 

As far as I know, there's no option to disable the logging done with `WHISPER_LOG_INFO`, present in `whisper.cpp`. This is a bit troublesome when debugging, as I need to comment all the `WHISPER_LOG_INFO`.

Is there an option to (cleanly) disable logging that I'm not aware of? If there is not, is it possible to request this feature? Thanks.

**Comment by bobqianic** [comment]
https://github.com/ggerganov/whisper.cpp/blob/8fac6455ffeb0a0950a84e790ddb74f7290d33c4/whisper.cpp#L131-L140

How about doing something similar to how we disable `WHISPER_LOG_DEBUG`?

```cpp
 #if defined(WHISPER_LOG) 
 #define WHISPER_LOG_INFO(...)  whisper_log_internal(GGML_LOG_LEVEL_INFO , __VA_ARGS__) 
 #else 
 #define WHISPER_LOG_INFO(...) 
 #endif 
```

**Comment by pprobst** [comment]
True. I did not notice that. It can be done. Thanks.
