### ISSUE TITLE
whisper folder and Mel_filters.npz file does not exist.

### ISSUE THREAD

**Issue by abdelazizSalah** [ggerganov/whisper.cpp#2144]
* I managed to download the small.pt model, and cloned the repo at the shown path, however
* on executing this command:
> "python3 models/convert-pt-to-ggml.py /Users/zizo/Downloads/small.pt /Users/zizo/Documents/GitHub/whisper.cpp ./models/whisper-medium" 
* I get the following error: 
> hparams: {'n_mels': 80, 'n_vocab': 51865, 'n_audio_ctx': 1500, 'n_audio_state': 768, 'n_audio_head': 12, 'n_audio_layer': 12, 'n_text_ctx': 448, 'n_text_state': 768, 'n_text_head': 12, 'n_text_layer': 12}
Traceback (most recent call last):
  File "/Users/zizo/Documents/GitHub/whisper.cpp/models/convert-pt-to-ggml.py", line 221, in <module>
    with np.load(dir_whisper / "whisper" / "assets" / "mel_filters.npz") as f:
  File "/Users/zizo/Library/Python/3.9/lib/python/site-packages/numpy/lib/npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/zizo/Documents/GitHub/whisper.cpp/whisper/assets/mel_filters.npz'

* And I have looked for the folder /whisper but I did not find it, and I did not also find the file Mel_filters.npz. 
* So do anyone have any idea how to resolve this to be able to load the model and start using the demo?

**Comment by ggerganov** [comment]
You need to clone the OpenAI Whisper repo to get the mel filter assets: https://github.com/openai/whisper/tree/main/whisper/assets

**Comment by abdelazizSalah** [comment]
it worked thanks!!
