### ISSUE TITLE
Trying to understand what Random Seed does

### ISSUE THREAD

**Issue by regstuff** [ggerganov/whisper.cpp#215]
Could anyone explain what it does? 

I know about random seed in general, but I don't understand what purpose it could serve in the context of a Whisper user. 

My main issue is the occasional loops that Whisper tends to get stuck in when there are periods of  silence in the audio. Was wondering if Random Seed could help avoid this. Right now I manually break the transcription and then restart it with a time offset.

**Comment by ggerganov** [comment]
I think you have some older version of `whisper.cpp`, because I remove the random seed at some point.
It wasn't used for anything.

The idea was to be used for the temperature fallback strategy which helps to mitigate exactly the problem that you experience, but it hasn't been implemented yet.
