### ISSUE TITLE
Not running on remote virtual windows 10 machine

### ISSUE THREAD

**Issue by RYucel** [ggerganov/whisper.cpp#217]
I tried to build and run whisper on a windows 10 virtual machine version 10.0.14393 virtualized on Windows server essentials 2016. Built without any issue on VS Studio 2022. But when command prompt called via >main -m ... There is no output even a single line shows any error or output. Models are there in same folder structure. What can be problem to look for? bench.exe also not working not. Just come out as below again without any error or output 
![image](https://user-images.githubusercontent.com/24809488/205238964-acddd8ec-3f94-4514-bd34-c4827f596527.png)

**Comment by ggerganov** [comment]
I think this is now fixed via 124c718c73f915f3e4235ae2af8841356e76177d
