### ISSUE TITLE
Removing the `whisper_pcm_to_mel_phase_vocoder*` functions

### ISSUE THREAD

**Issue by iboB** [ggerganov/whisper.cpp#2195]
The `whisper_pcm_to_mel_phase_vocoder*` functions are not used in any of the examples. It seems that they are only to be used with `whisper_full_params::speed_up = true` [which is forbidden](https://github.com/ggerganov/whisper.cpp/blob/e130b666425879af4b538f2441f741cc70b6f9d7/whisper.cpp#L5353-L5356)

Are they planned to be used in the future? If not, may I remove them? 

I'm working on a set of optimizations for the mel spectrogram calculation and it would make my life much easier if I don't have to support them too (and rely on the fact that some of the arguments which are currently provided to `log_mel_spectrogram` are known at compile time).

Should `whisper_full_params::speed_up` also be removed?

**Comment by ggerganov** [comment]
Yes, we can remove the `speed_up` functionality - it was in experimental stage since the beginning and it didn't seem to provide any value
