### ISSUE TITLE
Running inference over a large batch of audio files

### ISSUE THREAD

**Issue by vmedappa** [ggerganov/whisper.cpp#22]
Hi! Firstly, thank you so much for this incredible work!

I have been running the tiny.en models on a large number of wav files stored in a folder. I am currently parallelizing the work over a multi-core machine using GNU parallel and running the following command : 

`find input_data/eng_wav_data -name "*.wav" | parallel 'time ./main -m models/ggml-tiny.en.bin -nt -f {} -t 1 > {.}.txt'`

I found that currently the model is loaded each time we have to transcribe a wav file. Is there a way I can circumvent this and load the model only once? Any help would be appreciated. Thank you. Apologies if this issue has been resolved already

**Comment by ggerganov** [comment]
Just added a support to provide multiple input files:

```
./main -m models/ggml-tiny.en.bin file0.wav file1.wav file2.wav ...
```

All specified files will be processed with a single model load.

**Comment by ggerganov** [comment]
We now have enough options to be able to process batches of files and also splitting a long file into multiple jobs
