### ISSUE TITLE
apple M1  error 

### ISSUE THREAD

**Issue by huangshoucheng** [ggerganov/whisper.cpp#2211]
Converting PyTorch Frontend ==> MIL Ops: 100%|███████████████████████████████████████████████████████████████████████████████████████████▉| 821/822 [00:00<00:00, 9873.82 ops/s]
Running MIL frontend_pytorch pipeline: 100%|████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 148.74 passes/s]
Running MIL default pipeline: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 78/78 [00:01<00:00, 61.85 passes/s]
Running MIL backend_mlprogram pipeline: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:00<00:00, 210.95 passes/s]
done converting
/Users/cheng/whisper.cpp/models/coreml-encoder-base.en.mlmodelc/coremldata.bin
models/coreml-encoder-base.en.mlmodelc -> models/ggml-base.en-encoder.mlmodelc

The last two lines show that no base.en.bin file is generated, so when I run . /main -m models/ggml-medium.bin -f samples/jfk.wav
I get the
whisper_init_from_file_with_params_no_state: loading model from 'models/ggml-base.en.bin'
whisper_init_from_file_with_params_no_state: failed to open 'models/ggml-base.en.bin'
error: failed to initialize whisper context
Is there anyone who has the same problem as me? How can I solve it?

**Comment by chengyjonathan** [comment]
What was the solution? I'm also running into this, but i get no error message
