### ISSUE TITLE
Segmentation fault with CUDA on commit (#2206)

### ISSUE THREAD

**Issue by themanyone** [ggerganov/whisper.cpp#2230]
Steps to reproduce

`WHISPER_CUDA=1 make -j`
`./main -m ./models/ggml-medium-q5_0.bin samples/jfk.wav`

**Crash.**
whisper_init_from_file_with_params_no_state: loading model from './models/ggml-medium-q5_0.bin'
whisper_init_with_params_no_state: use gpu    = 1
whisper_init_with_params_no_state: flash attn = 0
whisper_init_with_params_no_state: gpu_device = 0
whisper_init_with_params_no_state: dtw        = 0
whisper_model_load: loading model
whisper_model_load: n_vocab       = 51865
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 1024
whisper_model_load: n_audio_head  = 16
whisper_model_load: n_audio_layer = 24
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 1024
whisper_model_load: n_text_head   = 16
whisper_model_load: n_text_layer  = 24
whisper_model_load: n_mels        = 80
whisper_model_load: ftype         = 8
whisper_model_load: qntvr         = 1
whisper_model_load: type          = 4 (medium)
whisper_model_load: adding 1608 extra tokens
whisper_model_load: n_langs       = 99
whisper_backend_init: using CUDA backend
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:   no
ggml_cuda_init: CUDA_USE_TENSOR_CORES: yes
ggml_cuda_init: found 1 CUDA devices:
  Device 0: Quadro M3000M, compute capability 5.2, VMM: yes
whisper_model_load:    CUDA0 total size =   538.59 MB
whisper_model_load: model size    =  538.59 MB
Segmentation fault (core dumped

**What works.** Versions prior to this commit:

$ `git bisect bad`
ffef323c4cfa8596cb91cf92d6f791f01a44335e is the first bad commit
commit ffef323c4cfa8596cb91cf92d6f791f01a44335e (HEAD)
Author: Borislav Stanimirov <b.stanimirov@abv.bg>
Date:   Tue Jun 4 09:32:23 2024 +0300

    whisper : add CUDA-specific computation mel spectrograms (#2206)
    
    * whisper : use polymorphic class to calculate mel spectrogram
    
    * whisper : add cuda-specific mel spectrogram calculation
    
    * whisper : conditionally compile cufftGetErrorString to avoid warnings
    
    * build : add new files to makefile
    
    * ruby : add new files to conf script
    
    * build : fix typo in makefile
    
    * whisper : suppress cub warning for deprecated C++ std in whisper-mel-cuda

**Comment by themanyone** [comment]
$ `sysinfo`
CPU: quad core Intel Core i7-2860QM (-MT MCP-)
speed/min/max: 1122/800/3600 MHz Kernel: 6.8.11-200.fc39.x86_64 x86_64
Up: 1d 9h 38m Mem: 5.77/31.28 GiB (18.4%) Storage: 1.86 TiB (21.3% used)
Procs: 354 Shell: Bash inxi: 3.3.34
VGA compatible controller: NVIDIA Corporation GM204GLM [Quadro M3000M] (rev a1)

**Comment by ggerganov** [comment]
Try latest `master` - should be fixed

**Comment by themanyone** [comment]
Nope.
`git bisect reset
git pull`
Already up to date.

**Comment by ggerganov** [comment]
Does it work with https://github.com/ggerganov/whisper.cpp/pull/2231 ?

**Comment by themanyone** [comment]
Sorry, no. It does not work with any of the later commits. I tried using `ggml-tiny.en.bin` to no avail.
I can make it work by using `-ng` flag. But that disables graphics layers and is significantly slower.

Will try to do a debug build.

Added DEBUG flag to `Makefile`
`ifdef DEBUG
    CFLAGS   := -g -I. -O0 -std=c11   -fPIC
    CXXFLAGS := -g -I. -I./examples -O0 -std=c++11 -fPIC
endif`

**Comment by ggerganov** [comment]
Based on the debug session, it seems that Async CUDA operations are not supported for some reason:

```
cudaMallocAsync(&m_hann_window, hw.len * sizeof(float), m_stream) whisper-mel-cuda.cu:206 - operation not supported
cudaMemcpyAsync(m_hann_window, hw.data, hw.len * sizeof(float), cudaMemcpyHostToDevice, m_stream) whisper-mel-cuda.cu:207 - invalid argument
cudaMallocAsync(&m_filters, f.size() * sizeof(float), m_stream) whisper-mel-cuda.cu:213 - operation not supported
cudaMemcpyAsync(m_filters, f.data(), f.size() * sizeof(float), cudaMemcpyHostToDevice, m_stream) whisper-mel-cuda.cu:214 - invalid argument
cudaMallocAsync(&m_cufft_workspace, m_cufft_workspace_size, m_stream) whisper-mel-cuda.cu:246 - operation not supported
cudaMallocAsync(&m_log_mel_temp_storage, m_log_mel_temp_storage_size, m_stream) whisper-mel-cuda.cu:264 - operation not supported
cudaMallocAsync(&cu_padded_samples, padded_samples.size() * sizeof(float), m_stream) whisper-mel-cuda.cu:289 - operation not supported
cudaMemcpyAsync(cu_padded_samples, padded_samples.data(), padded_samples.size() * sizeof(float), cudaMemcpyHostToDevice, m_stream) whisper-mel-cuda.cu:290 - invalid argument
cudaMallocAsync(&stft_in, n_frames * 400 * sizeof(float), m_stream) whisper-mel-cuda.cu:293 - operation not supported
cudaMallocAsync(&stft_out, n_frames * (400 / 2 + 1) * sizeof(cufftComplex), m_stream) whisper-mel-cuda.cu:298 - operation not supported
cufftMakePlan1d(plan, 400, CUFFT_R2C, int(n_frames), &waSize) whisper-mel-cuda.cu:305 - Driver or internal cuFFT library error
```

**Comment by ggerganov** [comment]
See if https://github.com/ggerganov/whisper.cpp/pull/2235 fixes the issue

**Comment by iboB** [comment]
Or... see if #2236 fixes it 😄

**Comment by themanyone** [comment]
Yes, `gh pr checkout 2236` fixes it 😄
