### ISSUE TITLE
unable to compile with openvino support

### ISSUE THREAD

**Issue by BBBalls** [ggerganov/whisper.cpp#2281]
I downloaded a fresh clone of the repo, and am unable to compile for openvino support. The plain `make` version compiles, and compiling with openblas support also works.

Pop_OS 22.04
OpenVino 2024.2.0

Below is the outputs

(openvino_conv_env) bbballs@pop-os:~/git/whisper.cpp$ cmake -B build -DWHISPER_OPENVINO=1
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.34.1") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- OpenMP found
-- Warning: ccache not found - consider installing it for faster compilation or disable this warning with GGML_CCACHE=OFF
-- CMAKE_SYSTEM_PROCESSOR: x86_64
-- x86 detected
-- Configuring done
-- Generating done
-- Build files have been written to: /home/bbballs/git/whisper.cpp/build

(openvino_conv_env) bbballs@pop-os:~/git/whisper.cpp$ cmake --build build -j --config Release
[  5%] Building CXX object src/CMakeFiles/whisper.openvino.dir/openvino/whisper-openvino-encoder.cpp.o
[ 15%] Building C object ggml/src/CMakeFiles/ggml.dir/ggml-alloc.c.o
[ 15%] Building C object ggml/src/CMakeFiles/ggml.dir/ggml-backend.c.o
[ 20%] Building C object ggml/src/CMakeFiles/ggml.dir/ggml.c.o
[ 25%] Building C object ggml/src/CMakeFiles/ggml.dir/ggml-quants.c.o
/home/bbballs/git/whisper.cpp_2/src/openvino/whisper-openvino-encoder.cpp:2:10: fatal error: ggml.h: No such file or directory
    2 | #include "ggml.h"
      |          ^~~~~~~~
compilation terminated.
gmake[2]: *** [src/CMakeFiles/whisper.openvino.dir/build.make:76: src/CMakeFiles/whisper.openvino.dir/openvino/whisper-openvino-encoder.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:248: src/CMakeFiles/whisper.openvino.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
[ 30%] Linking C shared library libggml.so
[ 30%] Built target ggml
gmake: *** [Makefile:136: all] Error 2

**Comment by ggerganov** [comment]
Does this patch fix the issue?

```diff
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index 84c5d29..40fb520 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -73,7 +73,7 @@ if (WHISPER_OPENVINO)
     set_property(TARGET ${TARGET} PROPERTY POSITION_INDEPENDENT_CODE ON)
     set(WHISPER_EXTRA_FLAGS ${WHISPER_EXTRA_FLAGS} -DWHISPER_USE_OPENVINO)
 
-    target_link_libraries(${TARGET} PRIVATE openvino::runtime)
+    target_link_libraries(${TARGET} PRIVATE openvino::runtime ggml)
     set_target_properties(${TARGET} PROPERTIES FOLDER "libs")
 endif()
 
```

**Comment by BBBalls** [comment]
Yes, I was able to compile with OpenVino support. Thank you.

**Comment by BBBalls** [comment]
There is still a problem. Compiling will complete, but when run there is no indication of OpenVino supprot when `main` is run. I have tried compiling with OpenVino 2023.0.0, 2024.1.0, and 2024.2.0 with the same results.

(openvino_conv_env) bbballs@pop-os:~/git/whisper.cpp_2$ ./main -m models/ggml-large-v2.bin -f samples/jfk.wav
whisper_init_from_file_with_params_no_state: loading model from 'models/ggml-large-v2.bin'
whisper_init_with_params_no_state: use gpu    = 1
whisper_init_with_params_no_state: flash attn = 0
whisper_init_with_params_no_state: gpu_device = 0
whisper_init_with_params_no_state: dtw        = 0
whisper_model_load: loading model
whisper_model_load: n_vocab       = 51865
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 1280
whisper_model_load: n_audio_head  = 20
whisper_model_load: n_audio_layer = 32
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 1280
whisper_model_load: n_text_head   = 20
whisper_model_load: n_text_layer  = 32
whisper_model_load: n_mels        = 80
whisper_model_load: ftype         = 1
whisper_model_load: qntvr         = 0
whisper_model_load: type          = 5 (large)
whisper_model_load: adding 1608 extra tokens
whisper_model_load: n_langs       = 99
whisper_model_load:      CPU total size =  3093.99 MB
whisper_model_load: model size    = 3093.99 MB
whisper_init_state: kv self size  =  251.66 MB
whisper_init_state: kv cross size =  251.66 MB
whisper_init_state: kv pad  size  =    7.86 MB
whisper_init_state: compute buffer (conv)   =   34.69 MB
whisper_init_state: compute buffer (encode) =  926.53 MB
whisper_init_state: compute buffer (cross)  =    9.25 MB
whisper_init_state: compute buffer (decode) =  213.06 MB

system_info: n_threads = 4 / 8 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | METAL = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | CUDA = 0 | COREML = 0 | OPENVINO = 0

main: processing 'samples/jfk.wav' (176000 samples, 11.0 sec), 4 threads, 1 processors, 5 beams + best of 5, lang = en, task = transcribe, timestamps = 1 ...


[00:00:00.000 --> 00:00:10.960]   And so, my fellow Americans, ask not what your country can do for you, ask what you can do for your country.


whisper_print_timings:     load time =  1053.38 ms
whisper_print_timings:     fallbacks =   0 p /   0 h
whisper_print_timings:      mel time =    16.04 ms
whisper_print_timings:   sample time =    89.06 ms /   146 runs (    0.61 ms per run)
whisper_print_timings:   encode time = 25833.51 ms /     1 runs (25833.51 ms per run)
whisper_print_timings:   decode time =   146.66 ms /     2 runs (   73.33 ms per run)
whisper_print_timings:   batchd time =  3554.59 ms /   142 runs (   25.03 ms per run)
whisper_print_timings:   prompt time =     0.00 ms /     1 runs (    0.00 ms per run)
whisper_print_timings:    total time = 30852.24 ms

**Comment by CsehAbel** [comment]
I can attest to this as well. 
It built after the fix to CMakeLists.txt. 
But once i issue 
whisper.cpp$ ./build/bin/main  -m models/ggml-large-v3.bin -f samples/jfk.wav 
i see the following OPENVINO = 0
I tried -ng and -oved CPU as well.

**Comment by ggerganov** [comment]
Please test https://github.com/ggerganov/whisper.cpp/pull/2294

**Comment by BBBalls** [comment]
I manually added the change of #2294, because it was not merged at time of testing. It does restore OpenVino support.

**Comment by CsehAbel** [comment]
It worked for me, and it is super fast now, like 2x just on the CPU with -t 20 -p 1. Instead of like 0.5x without openvino. This speedup is massive and now its a real alternative to using the OpenAI API. Thank you.
