### ISSUE TITLE
coreml question

### ISSUE THREAD

**Issue by chengyjonathan** [ggerganov/whisper.cpp#2323]
I'm able to produce the following directories, as per the instructions.

`models/coreml-encoder-base.en.mlmodelc -> models/ggml-base.en-encoder.mlmodelc`

I'm able to cmake, using

```
cmake -B build -DWHISPER_COREML=1
cmake --build build -j --config Release
```

The next instruction says

`./main -m models/ggml-base.en.bin -f samples/jfk.wav`

But I have these directories. Not ggml-base.en.bin. Is there a step I'm missing?

Thank you!

**Comment by ggerganov** [comment]
Yes, you need to run the following command to download the `base.en` model:

```bash
./models/download-ggml-model.sh base.en
```
