### ISSUE TITLE
Clarifications - Simple VAD and circular buffer in command.cpp

### ISSUE THREAD

**Issue by Cadotte** [ggerganov/whisper.cpp#2335]
We have been using the command.cpp example and it works surprisingly well. We want to clarify part of the VAD and circular buffer mechanisms, since we would like to replace the simple VAD by a more refined one (i.e. which does not consider noise as "activity").

To the best of our understanding, once the prompt has been accepted, [lines 588 to 622 of command.cpp](https://github.com/ggerganov/whisper.cpp/blob/master/examples/command/command.cpp#L588-L622) work as follows:

- The latest 2000 ms of audio is extracted from the circular buffer
- The VAD checks if the last 1000 ms of the 2000 ms have an energy above 60% of the whole
- If VAD returns true, then the latest command_ms (as defined in arguments) ms of audio is extracted from the circular buffer, which includes the 2000 ms used by the VAD to check activity

Yet, we do not understand how this can work. To our understanding, if command_ms is set to 5000, then the last 1000 will have a higher energy, but the rest of the 4000 will contain the sound before that higher energy (i.e. before any voice was detected) and would hence miss the command.

Unless we are missing something related to the circular buffer management, or the internal whisper state/context?

**Comment by ggerganov** [comment]
> The VAD checks if the last 1000 ms of the 2000 ms have an energy above 60% of the whole

Correct, but note that the function returns `false` when the VAD in the last 1000ms is higher than the total energy. Does that explain?

**Comment by ggerganov** [comment]
> the VAD detects the end of noise/voice rather than the beginning

Yes, correct

> Doesn't this logic return true for a "no noise/voice" condition though? (the last 1000ms would not be higher than 60% of the total energy, if I am not mistaken)

The "energy" in this simple VAD is defined simply as `avg(abs(PCM_t))`. So it's technically not really an energy, but the average of the signal amplitude. If you think about a pure noise waveform over time, (i.e. something like silence) than this quantity would be approximately constant for any time interval that you consider and so we expect `energy_last ~= energy_all` when there is silence. Setting `vad_thold` to less than `1.0` would allow us to detect changes. But of course, this is not a perfect solution and there could be fail cases

**Comment by Cadotte** [comment]
Thank you very much for your answers! We now have all the information we need.
