### ISSUE TITLE
Everything is good, but it stops in the middle

### ISSUE THREAD

**Issue by zpeng2022** [ggerganov/whisper.cpp#2341]
- I follow the tutorial with no problem.

- and convert the large-v2 model 
- ![image](https://github.com/user-attachments/assets/1eb14e70-ad6f-4b40-ac1e-2c0bc824318c)

- I use this command to run the model.
```
./main -t 8 -mc 0 -m models/ggml-large-v2.bin -f ./mp4s/myaudio_wav/myaudio.wav -otxt -osrt -of /Users/zzz/CLionProjects/whisper.cpp/mp4s/wav/
```
- but it stop here for multi times (I have tried multiple times) 
- 1 hour 16 minutes, it always stop here. without any error output, It just stuck here
![image](https://github.com/user-attachments/assets/3533dbbe-49b7-4429-b438-209a26f73145)
- and the gpu usage is down to zero

**Comment by zpeng2022** [comment]
well I solve it with this https://github.com/ggerganov/whisper.cpp/issues/896#issuecomment-1713723225

**Comment by zpeng2022** [comment]
well, it happens again, 7 in 10 will fail

**Comment by OmarKhaled511** [comment]
@zpeng2022, have you found any solution to this issue?
