### ISSUE TITLE
crash after `whisper_free` with EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by Josscii** [ggerganov/whisper.cpp#2347]
https://github.com/ggerganov/whisper.cpp/blob/81c999fe0a25c4ebbfef10ed8a1a96df9cfc10fd/ggml/src/ggml-metal.m#L2870

<img width="1257" alt="image" src="https://github.com/user-attachments/assets/c1e71fd0-1a94-4fdf-b726-e2d5c13b3e64">

when I call `whisper_free`, it will crash on this line with `EXC_BAD_ACCESS`

**Comment by Josscii** [comment]
https://github.com/ggerganov/ggml/commit/93098177523216865ec74bb584840cfed794987c

this seems fix it, need sync

**Comment by ggerganov** [comment]
Done

**Comment by Josscii** [comment]
Thanks, I'll test to see if it works

**Comment by Josscii** [comment]
not happening from my test, thanks again

**Comment by edisonzf2020** [comment]
When to create a new release tag
