### ISSUE TITLE
Doesn't run on Fedora 40

### ISSUE THREAD

**Issue by KTibow** [ggerganov/whisper.cpp#2374]
Fedora 40 replaced wget with wget2, and I wouldn't be surprised if more distros follow. On these distributions, the download script errors as `--show-progress` isn't an option.

**Comment by kyemacdonald** [comment]
You can fix the script by removing "--show-progress" from line 105 of the download script

**Comment by KTibow** [comment]
Yeah I went ahead and did that. I had to also remove the quiet flag and add `--progress bar` for it to render.
