### ISSUE TITLE
ggml_metal_graph_compute crashes at computeCommandEncoderWithDescriptor

### ISSUE THREAD

**Issue by lithium0003** [ggerganov/whisper.cpp#2452]
metal compute crashes at this line,
https://github.com/ggerganov/whisper.cpp/blob/2944cb72d95282378037cb0eb45c9e2b2529ff2c/ggml/src/ggml-metal.m#L3063
because ```ctx->edesc``` is autoreleased already.

In ggml_metal_init() at this line,
https://github.com/ggerganov/whisper.cpp/blob/2944cb72d95282378037cb0eb45c9e2b2529ff2c/ggml/src/ggml-metal.m#L352
```ctx->edesc``` is allocated,  MTLComputePassDescriptor.computePassDescriptor returned value shuld be copy.

```
    ctx->edesc  = [MTLComputePassDescriptor.computePassDescriptor copy];
```
this fix seems work.

Like same reason, in ggml_backend_metal_set_n_cb() comments says that ```encode_async``` set causes crash.
Capture block should be copy for another scope.
```
ctx->encode_async = [^(size_t iter) {
    } copy];
```

**Comment by ggerganov** [comment]
Yes, a patch has already been pushed in `llama.cpp`: https://github.com/ggerganov/llama.cpp/commit/5d5ab1e5cca0d6d63701a1cb85dbe26cb57d2c4e

Will sync it tomorrow

**Comment by lithium0003** [comment]
Thanks!

**Comment by ggerganov** [comment]
Should be fixed now
