### ISSUE TITLE
Can't compile with GGML_VULKAN=1

### ISSUE THREAD

**Issue by toboil-features** [ggerganov/whisper.cpp#2478]
```
ggml/src/ggml-vulkan.cpp:29:10: fatal error: ggml-vulkan-shaders.hpp: No such file or directory
   29 | #include "ggml-vulkan-shaders.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
```

make -j 4 -B GGML_VULKAN=1

The problem presents only with latest commit of whisper.cpp. Llama.cpp is fine, I can compile it easily with Vulkan support.

Also:
```
make: *** [Makefile:653: ggml/src/ggml-vulkan.o] Error 1
```

**Comment by ggerganov** [comment]
Can you test https://github.com/ggerganov/whisper.cpp/pull/2485 and see if it works?

**Comment by toboil-features** [comment]
Yes, now it compiles.
