### ISSUE TITLE
Feature Request: Split segments when editing transcript

### ISSUE THREAD

**Issue by conjon42** [ggerganov/whisper.cpp#2493]
It is possible to merge transcript segments into one when editing a transcript, but I have not found an option to split a segment, such as when two speaker are replying quickly to each other in the same section. Adding this feature would help improve readability and speaker assignment for segments.

**Comment by millionscorto** [comment]
Shouldn't you implement this yourself from the JSON output? I mean it's pretty trivial. The speaker segmentation is rudimentary at best using built in diarization. Not sure if this has anything to do with whisper.cpp
