### ISSUE TITLE
bug report: index overflow cause crash

### ISSUE THREAD

**Issue by Josscii** [ggerganov/whisper.cpp#2504]
https://github.com/ggerganov/whisper.cpp/blob/a5abfe6a90495f7bf19fe70d016ecc255e97359c/src/whisper.cpp#L7022

`j` is compared with `ns`, which seems wrong, it should less than `n`, not `ns`.

**Comment by Josscii** [comment]
I do transcribe with `turbo` model, and it sometimes crash on this line

**Comment by Josscii** [comment]
@ggerganov

**Comment by ggerganov** [comment]
Thanks for finding this. Would you like to submit a PR?

**Comment by Josscii** [comment]
I can submit a pr, but I'm don't have a good understanding of the code, I only debuged it here, I'm afraid I would break some code

**Comment by ggerganov** [comment]
The fix is correct. `ns` is the number of samples, while the `j` iterator loops over the tokens, not the samples. This check is needed to guarantee that we don't do out-of-bounds access in the `tokens` array.

**Comment by Josscii** [comment]
Thanks for your explaination, I'll submit a pr
