### ISSUE TITLE
Radio transcript

### ISSUE THREAD

**Issue by shmightworks** [ggerganov/whisper.cpp#2507]
I'm doing a fun project to transcribe radio broadcast.
I'm taking 15 minutes recordings and feeding it to WhisperCPP.
More often than not, I noticed, it passes through talking as [Music], and other times it doesn't output [Music] and the actual lyrics comes out.
I don't mind lyrics coming out in the output, but I do mind talking being skipped and outputted as [Music]

Is there something I can do to improve the results?
I'm guessing maybe where along the lines of using the prompt argument to feed in something.

Any suggestions?
Thanks.

**Comment by kth8** [comment]
Which model are you using? Maybe try a larger one for better results.

**Comment by shmightworks** [comment]
I'm just using:
https://huggingface.co/ggerganov/whisper.cpp/blob/main/ggml-base.bin
maybe I'll try ggml-medium.en.bin

**Comment by shmightworks** [comment]
After some testing, yes, using a different model, plus adding a prompt helped it a bit.
Currently using ggml-small.en.bin, with  my machine, the ggml-medium.en.bin was taking longer to transcribe than the length of the audio, so that's not going to work.
Really have no idea if and how the prompt is making a difference, but I say "there is a mix of music and talking, transcribe both", and the results seems to do a more thorough job.
