### ISSUE TITLE
How to get the probs?

### ISSUE THREAD

**Issue by soulmayon2** [ggerganov/whisper.cpp#2640]
I notice using the whisper_pcm_to_mel() + whisper_lang_auto_detect() API could get the probs for all languages in the lang_probs array, but it is too complex.  

The whisper_full_lang() API can get the detected language, is it possible  to get the probs at same time?

**Comment by ggerganov** [comment]
The probs are currently not exposed. The API could be updated to expose them by storing them in `whisper_state`.

**Comment by soulmayon2** [comment]
Thanks!
