### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [ggerganov/whisper.cpp#2672]
I would like to point out that an identifier like “[`__RUBY_WHISPER_H`](https://github.com/ggerganov/whisper.cpp/blob/7d55637f0bc8ff1b405f6f18c5c04fe39e4ad389/bindings/ruby/ext/ruby_whisper.h#L1 "Update candidate")” [does not fit](https://wiki.sei.cmu.edu/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by ggerganov** [comment]
cc @KitaitiMakoto

**Comment by KitaitiMakoto** [comment]
Thank you for reporting!
