### ISSUE TITLE
Equivalent functionality for Whisper's verbose=False

### ISSUE THREAD

**Issue by mayeaux** [ggerganov/whisper.cpp#276]
I'm the developer of https://github.com/mayeaux/generate-subtitles

Currently I use `verbose=False` with this app when using Whisper, because it gives me useful information that I can output to the frontend: `35%|███▌      | 5588/15901 [00:17<00:31, 326.60frames/s],`

I just started using whisper.cpp so I'm not sure if it's listed somewhere but I can't see it, but is there a way to set `verbose` as `False` so I can get info about the frames/second and percentages in real time? Thanks!

**Comment by ggerganov** [comment]
You can now add the `--print-progress` argument to `main` and get information about the progress in %

**Comment by mayeaux** [comment]
Thanks, I opened a ticket to implement `whisper.cpp` for my app, as mentioned in that ticket it seems an OVH server at $200/month will perform better using the CPU than a $250/month GPU cloud server from Vast.ai (which is by far the cheapest GPU cloud service). Love what you've created here thanks again.
