### ISSUE TITLE
How do I compile to a shared library?  without libc++_shared.so ?

### ISSUE THREAD

**Issue by azkadev** [ggerganov/whisper.cpp#30]
I want to experiment with using whisper into the app, but when I open it, an error occurs when the compiled library requires `libc++_shared.so`,

i use this bash to build for android target
```bash
/home/azkdev/Android/Sdk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang -pthread -O3 -std=c11 -mavx -mavx2 -mfma -mf16c -c ./ggml.c -fPIC -lstdc++
/home/azkadev/Android/Sdk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++ -pthread -O3 -std=c++11 -mavx -mavx2 -mfma -mf16c -c ./whisper.cpp -fPIC -lstdc++
/home/azkadev/Android/Sdk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++ -pthread -O3 -std=c++11 ./main.cpp -fPIC -lstdc++ whisper.o ggml.o -o ./whisper.so --shared -fPIC -lstdc++
```
I have also tried this [clang-linking-so-library-libc-shared-so](https://stackoverflow.com/questions/55184167/clang-linking-so-library-libc-shared-so), but it doesn't work

Error
![Screenshot from 2022-10-08 19-17-21](https://user-images.githubusercontent.com/82513502/194707386-67261a5f-0cac-413d-a963-7d98443abe58.png)

can you give a build command so it doesn't need libc++_shared.so? sorry i'm still a beginner in cpp

**Comment by ggerganov** [comment]
Does this work:

```java
gcc -O3 -std=c11 -pthread -mavx -mavx2 -mfma -mf16c -fPIC -c ggml.c
g++ -O3 -std=c++11 -pthread --shared -static-libstdc++ whisper.cpp ggml.o -o libwhisper.so
```

Then you can link `libwhisper.so` like this, for example:

```java
g++ main.cpp -L. -lwhisper
```

Also, I'm pretty sure you don't need the `-mavx -mavx2 -mfma -mf16c` flags for Android, so you can remove them. You might need some other flags though, not sure. Might want to check this comment:

https://github.com/ggerganov/whisper.cpp/issues/18#issuecomment-1269192184

**Comment by azkadev** [comment]
![Screenshot from 2022-10-08 20-42-32](https://user-images.githubusercontent.com/82513502/194710550-5946b7f2-2b7f-4fa0-a3fb-d76868d78f65.png)
Thank you very much, now I can convert audio to text, thanks for porting to cpp, and thanks for helping me,

**Comment by DillonHHH** [comment]
Could we get an example project for Android? I got the Whisper.so file but I'm not sure where to move on from here...

**Comment by Topping1** [comment]
@azkadev can you please give some tips on how to create a minimal application with whisper like the one you are showing? I have not much experience in C++ or android application coding.
@ggerganov I did an experiment myself compiling the code on android, using the CxxDroid compiler and it worked perfectly. On a Snapdragon 712 with 6gb Ram I get 6.5s for transcribing jfk.wav (11s) with tiny model, 16s with base model and 62s with small model. Pretty decent for a midrange chipset.

**Comment by azkadev** [comment]
I don't know tips, you can see my repo [here](https://github.com/azkadev/whisper_dart), sorry my english is bad

**Comment by azkadev** [comment]
> @azkadev can you please give some tips on how to create a minimal application with whisper like the one you are showing? I have not much experience in C++ or android application coding. @ggerganov I did an experiment myself compiling the code on android, using the CxxDroid compiler and it worked perfectly. On a Snapdragon 712 with 6gb Ram I get 6.5s for transcribing jfk.wav (11s) with tiny model, 16s with base model and 62s with small model. Pretty decent for a midrange chipset.
