### ISSUE TITLE
C API threadsafety

### ISSUE THREAD

**Issue by tazz4843** [ggerganov/whisper.cpp#32]
I can't see any docs as to threadsafety for the C API. Information here would be very helpful for me and future users. Thanks!

**Comment by ggerganov** [comment]
Good point - will add information about that.

The interface is thread-safe as long as you don't use the same `whisper_context` in more than one thread.

**Comment by tazz4843** [comment]
By "using in more than one thread", do you mean sending between threads and then using it, or using it concurrently from multiple threads? I'm writing Rust bindings for this lib, and I just want to be absolutely sure here.

**Comment by ggerganov** [comment]
It's ok to send it from one thread to another. The only limitation is to not use it concurrently from multiple threads.

**Comment by happysalada** [comment]
@tazz4843 did you ever write the rust bindings for the lib ? If yes, I'm interested in them!

**Comment by tazz4843** [comment]
I did @happysalada, and you can find them over at https://github.com/tazz4843/whisper-rs
