### ISSUE TITLE
If there is a large gap between the output result and whisper, the top 1 token is also selected

### ISSUE THREAD

**Issue by wuhongsheng** [ggerganov/whisper.cpp#321]
whisper output 
[00:00.000 --> 00:02.000] 吃飯了嗎

main output 
[00:00:00.000 --> 00:00:00.500]  (按讚)
[00:00:00.500 --> 00:00:01.200]  謝謝你

I want to know where the main difference between the two sides is in the dcoder

**Comment by ggerganov** [comment]
It is not clear what is the issue - please provide more details
