### ISSUE TITLE
cgraph->work == NULL eventually causes null pointer crash in ggml.c

### ISSUE THREAD

**Issue by RndyP** [ggerganov/whisper.cpp#344]
The eventual crash occurs here:
dst_data is NULL because params->wdata is NULL

![image](https://user-images.githubusercontent.com/78916608/209989435-c71a499a-7186-4696-bc90-f2a49682c565.png)

Cause is way up the stack where cgraph->work is zero:

![image](https://user-images.githubusercontent.com/78916608/209988877-4d22a5a6-836e-42a4-921b-276800f5b3cf.png)

This check is interesting:
![image](https://user-images.githubusercontent.com/78916608/210009318-870a7688-ce20-485b-b652-34b38f111c1f.png)

My environment is Visual Studio 2022. Crash occurs with optimizations on or disabled.
Crash occurs fairly repeatably by simply streaming room noise in whisper.
I can debug somewhat with Visual Studio when I turn off optimizations, although I have no idea what exactly the code is doing.
Let me know if you have any questions or need help. I am hoping if you look at these sections you will have an epiphany.

**Comment by RndyP** [comment]
Hmm, I got the latest version of ggml.c a couple of hours ago, and it seems this issue is fixed. I will close this tomorrow after a few more hours of testing.

**Comment by RndyP** [comment]
Problem is back now. I thought the latest version fixed this, but apparently not. I set audio_ctx to 1536, and now it's back.

**Comment by ggerganov** [comment]
The audio_ctx cannot be larger than 1500. Added checks to prevent that in the future
