### ISSUE TITLE
./whisper.cpp/whisper.h:121:81: error: unknown type name 'bool'

### ISSUE THREAD

**Issue by tazz4843** [ggerganov/whisper.cpp#35]
I'm attempting to automate rust-bindgen generation. This appears to not work, however, as it uses clang which does not implicitly `#include <stdbool.h>`. Adding `#include <stdbool.h>` to line 5 of whisper.h appears to fix this. I'm opening this issue to get feedback and others' thoughts.

**Comment by ggerganov** [comment]
I've added the header as suggested.

I am no sure if it is a good practice to use `bool` in C-style interfaces, but I really prefer it in terms of code readability.
In case it turns out that it causes some sort of incompatibilities, we will switch it to `int`.

**Comment by tazz4843** [comment]
This issue appears to have been the last major blocker to Rust bindings. I have published the ergonomic Rust wrapper at https://crates.io/crates/whisper-rs, if you're curious. Thanks for making this lib!
