### ISSUE TITLE
SIGFPE on certain audio files

### ISSUE THREAD

**Issue by tazz4843** [ggerganov/whisper.cpp#39]
Hey there! I'm testing out whisper.cpp to see if it would be suitable for production use. However I'm running into a SIGFPE on certain audio files: namely those that do not produce any output from the model. Because of the way my system is set up, I'm unable to provide any test files that can reproduce this bug.

However, I was able to build the library with debug symbols and trigger the exception. It seems to be a divide-by-zero error on line 2349 of whisper.cpp:

https://github.com/ggerganov/whisper.cpp/blob/8d9435825143fffddaaf648fac2d87bcc5738db0/whisper.cpp#L2349

The GDB output is as follows:
```
Thread 21 "scripty_stt_ser" received signal SIGFPE, Arithmetic exception.
[Switching to Thread 0x7ffff7085700 (LWP 3869)]
0x0000555555599123 in whisper_full (ctx=0x5555556f6a80, params=..., samples=<optimized out>, n_samples=<optimized out>) at whisper.cpp:2349
2349            int progress_cur = (100*seek)/whisper_n_len(ctx);
```
Unfortunately, despite compiling with debug symbols (`-g` flag), `bt` gave no extra info beyond that:
```
(gdb) bt
#0  0x0000555555599123 in whisper_full (ctx=0x5555556f6a80, params=..., samples=<optimized out>, n_samples=<optimized out>) at whisper.cpp:2349
#1  0x0000555555593cf6 in whisper_rs::whisper_ctx::WhisperContext::full (self=<optimized out>, params=..., data=...) at src/whisper_ctx.rs:390
```

Let me know if there's anything else I can do to help!

**Comment by ggerganov** [comment]
Very likely that the length of the audio is 0.
The function `whisper_n_len` returns the length of the spectrogram and it will be 0 if the audio is empty.

There should be a check for division by zero.

When using `-g` you also want to avoid using `-O3` in order to not get `<optimized out>`

**Comment by tazz4843** [comment]
I'm willing to try out implementing this, how would you want the division by zero check to be handled? ie. should it throw an error or should it just silently skip?

**Comment by ggerganov** [comment]
Right after computing the mel spectrogram, check if the length is less than 100 (i.e. 1 second) and if yes - return 0:

https://github.com/ggerganov/whisper.cpp/blob/8d9435825143fffddaaf648fac2d87bcc5738db0/whisper.cpp#L2315-L2320

Add short comment with explanation that we do not process audio less than 1 second
