### ISSUE TITLE
Getting an error "The Application as unable to start correctly" on a particular Windows machine

### ISSUE THREAD

**Issue by matale** [ggerganov/whisper.cpp#392]
The error is a pop up dialog that reads "The application was unable to start correctly (0xc0000142). Click OK to close the application." 

I am able to get it working on my laptop but not on another mini PC, the only thing I can think of is this PC has a Celeron processor, would this be an issue? (Inter Celeron N5105 2GHz)

I am using the binaries from the 1.0.4 releases here ([whisper-bin-x64.zip](https://github.com/ggerganov/whisper.cpp/releases/download/1.0.4/whisper-bin-x64.zip))

**Comment by Topping1** [comment]
@matale as far as I know the current implementation requires a CPU with AVX and AVX2 support. It seems that the Intel Celeron N5105 does not support those extensions. I think you can modify the build files to remove those compiler flags BUT the program will run very slow. Hope this helps.
