### ISSUE TITLE
Medium.en accuracy discrepancy

### ISSUE THREAD

**Issue by jlopp** [ggerganov/whisper.cpp#393]
I have a 15 minute presentation I'm transcribing to test performance and accuracy of whisper.cpp.

When I run it with the small.en or the large models, it does a great job handling punctuation and breaking up sentences / paragraphs with line breaks.

When I run with the medium.en model, the output is noticeably different and worse. It no longer inserts commas into sentences and it no longer has ANY line breaks. It's like something about the model is no longer to detect pauses from the speaker.

When I run it with the full medium model, this behavior does not occur and the commas / line breaks match what I see in the small.en and large models.

**Comment by Topping1** [comment]
I have similar problems with some french and german audio transcriptions with the Medium model. Usually switching to Small or Base models fixes the problems (at the cost of some transcription accuracy).

**Comment by ggerganov** [comment]
@jlopp 
My understanding is that this is not an issue with `medium.en` specifically, but rather a consequence of the auto-regressive nature of Whisper in general - it can "fall" into different modes of transcription: long sentences, short sentences, no punctuation, etc.

There are many factors that play role in this and it's hard to control everything, so it seems random.
Some recordings will be transcribed in one way, others in different way.

Something you can try is to use the `--prompt` argument of `main` to "push" the model into certain behaviour.
For example, [here](https://github.com/ggerganov/whisper.cpp/discussions/348#discussioncomment-4559682) I demonstrate how to force the model to not use punctuation - which is the inverse of what you want.

Maybe you can try something like this:

```./main -m models/ggml-medium.en.bin samples/gb0.wav -t 8 --prompt "Hello, this is the first sentence. And this is the second one. A little pause ... and we are back."```

**Comment by jlopp** [comment]
Ah, good to know. Thanks!
