### ISSUE TITLE
Trying to run this on Raspberry Pi 3 A+, simply getting "Killed"

### ISSUE THREAD

**Issue by WhereAmO** [ggerganov/whisper.cpp#395]
I have a Pi here that I'm trying to run this on, but sadly every time I run any command to test it out on the sample .wav it just gets killed.

![uhoh](https://user-images.githubusercontent.com/81683771/211431397-32e81d29-2ef1-4fdf-8d63-107fc6c6c1e9.png)

Any help would be appreciated! If you need any info, please do ask!

**Comment by j-f1** [comment]
Maybe an out of memory error?

**Comment by WhereAmO** [comment]
That sounds about right, is there any way to reduce the memory usage any further?

**Comment by j-f1** [comment]
I would say to use a smaller model but you’re already doing that. Maybe try running it under GDB to see if you can get more info on the crash?

**Comment by WhereAmO** [comment]
I tried this out on a different OS that is supposed to use less memory, and I managed to run this just fine, so turns out it was just a memory issue!

**Comment by ggerganov** [comment]
@WhereAmO
Just for my information: it is still running on the RPi3, but just on a different OS, right?

**Comment by WhereAmO** [comment]
Mhm, I just swapped over to Lite version of the Raspberry Pi OS, didn't use any other Pi. Works fine now!
