### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by yujinqiu** [ggerganov/whisper.cpp#4]
Hi @ggerganov 
whisper.cpp look promising, thank you for you work. 
I know there is timestamp limitation in the README currently. 
Is it possible to include timestamp  in the future?   that will be useful when generate subtitle. 
Or can  whisper.cpp support stream mode with steaming audio.

**Comment by ggerganov** [comment]
Hi, timestamps are available now - give it a try and let me know if you notice something wrong.

I plan to add a real-time speech-to-text from microphone using SDL2 Audio. My hope is to get at-least the `small` model to run in real-time on a regular machine, but we'll see.

**Comment by CHERTS** [comment]
> Hi, timestamps are available now - give it a try and let me know if you notice something wrong.
> 
> I plan to add a real-time speech-to-text from microphone using SDL2 Audio. My hope is to get atleast the `small` model to run in real-time on a regular machine, but we'll see.

It would be just great! I'm looking forward to it! Thank you!
