### ISSUE TITLE
Assertion `sum > 0.0f' failed

### ISSUE THREAD

**Issue by delneg** [ggerganov/whisper.cpp#400]
ggml.c:6242: ggml_compute_forward_flash_attn_f16: Assertion `sum > 0.0f' failed.

Happened in runtime, no clue why it did

**Comment by ggerganov** [comment]
Is it reproducible on latest `master`? 4ef3398e8fe0c426de038b8c3816c6791a34a5ae

**Comment by delneg** [comment]
> Is it reproducible on latest `master`? [4ef3398](https://github.com/ggerganov/whisper.cpp/commit/4ef3398e8fe0c426de038b8c3816c6791a34a5ae)

Unfortunately, I can't check because go binding won't compile on that commit.
I'm using 5e9f33596fe360c435e76f4682f20c1079fcc5cd

**Comment by delneg** [comment]
Scratch that, It was an issues with my build, not the project.
I'll check again on the latest commit
