### ISSUE TITLE
Is there a way to utilize this in Node.js?

### ISSUE THREAD

**Issue by gajus** [ggerganov/whisper.cpp#417]

**Comment by gajus** [comment]
Discovered immediately after posting this https://www.npmjs.com/package/whisper.cpp

**Comment by Mike-Bell** [comment]
You can also build your own bindings via [Node-API](https://nodejs.org/api/n-api.html). It's more work than just consuming some generated WASM, but I've worked through it, and the performance should be better (more directly comparable to the C++ implementation).
