### ISSUE TITLE
Language auto-detect "auto" flag does not work using the stream tool

### ISSUE THREAD

**Issue by bdrelling** [ggerganov/whisper.cpp#445]
Attempting to use the `--language auto` option to enable auto-detect with the multi-language model throws an error for the `stream` tool.

**Command**

```sh
./stream -m ./models/ggml-base.bin --threads 8 --step 500 --length 5000 --language auto
```

**Error**

```
whisper_lang_id: unknown language 'auto'
error: unknown language 'auto'
```

**Comment by gourcetools** [comment]
Same here, how to make this workproperly?
```
whisper_lang_id: unknown language 'auto'
error: unknown language 'auto'

usage: ./stream [options]

```

**Comment by AeroXi** [comment]
same

**Comment by pannous** [comment]
you can hack one line in stream.cpp as in https://github.com/ggerganov/whisper.cpp/pull/501#pullrequestreview-1376780021

**Comment by gourcetools** [comment]
> you can hack one line in stream.cpp as in [#501 (review)](https://github.com/ggerganov/whisper.cpp/pull/501#pullrequestreview-1376780021)

This works. Thanks
