### ISSUE TITLE
emcmake cmake .. && make -j

### ISSUE THREAD

**Issue by silvacarl2** [ggerganov/whisper.cpp#448]
attempting to run: emcmake cmake .. && make -j

but keeps giiving this error:

configure: cmake .. -DCMAKE_TOOLCHAIN_FILE=/usr/share/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR=/usr/bin/node;--experimental-wasm-threads
CMake Error: The current CMakeCache.txt directory /mnt/d/Dropbox/Developer-Tools/whisper/whisper.cpp-tests/whisper.cpp/build-em/CMakeCache.txt is different than the directory /home/silvacarl/Dropbox/Developer-Tools/whisper/whisper.cpp-tests/whisper.cpp/build-em where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
CMake Error: The source "/mnt/d/Dropbox/Developer-Tools/whisper/whisper.cpp-tests/whisper.cpp/CMakeLists.txt" does not match the source "/home/silvacarl/Dropbox/Developer-Tools/whisper/whisper.cpp-tests/whisper.cpp/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
emcmake: error: 'cmake .. -DCMAKE_TOOLCHAIN_FILE=/usr/share/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR=/usr/bin/node;--experimental-wasm-threads' failed (returned 1)

**Comment by silvacarl2** [comment]
cancel that, fixed.

**Comment by jake1271** [comment]
Hi, I'm getting the same issue.
Could you tell us what you did to resolve the issue?
thanks!
