### ISSUE TITLE
node --experimental-wasm-threads --experimental-wasm-simd ../tests/test-whisper.js issue

### ISSUE THREAD

**Issue by silvacarl2** [ggerganov/whisper.cpp#449]
trying to run: node --experimental-wasm-threads --experimental-wasm-simd ../tests/test-whisper.js

but get:

failed to asynchronously prepare wasm: CompileError: WebAssembly.instantiate(): Compiling function #62 failed: i32x4.splat found empty stack @+5977

**Comment by ggerganov** [comment]
Try to update `node`. It works with `v18.12.1`

**Comment by sapoepsilon** [comment]
Just to add this, it didn't work on node ```v20.9.0```, I had to downgrade to `v18.12.1`
