### ISSUE TITLE
add duration to transcribe 

### ISSUE THREAD

**Issue by eazyliving** [ggerganov/whisper.cpp#463]
In addition to --offset-t I'd love to have an option to limit the duration the transcription is done.

smth like

--offset-t 10000 -duration 30000

would start at second 10 and transcribe 30 seconds of audio, stopping at second 40.

I try to create smth like distributed transcription for podcasts. Some episodes having more than an hour (that goes up to 9h easily) is hard to transcribe in one got on one machine. Cutting that audio, distributing parts and then calculating the resulting transcipt may be possible, but not having to cut the audio beforehand would make things way easier.

**Comment by pmoreiramcosta** [comment]
Hey! The main example seems to have this ([see here](https://github.com/ggerganov/whisper.cpp/blob/master/examples/main/main.cpp#L154) and [here](https://github.com/ggerganov/whisper.cpp/blob/master/examples/main/main.cpp#L649)). Have you tried it?

**Comment by eazyliving** [comment]
Oh bloody...

Sorry! And thanks. Must have been drunk.
