### ISSUE TITLE
Does OpenBLAS Windows builds from v1.2.0 run on all CPUs (with and without AVX2)?

### ISSUE THREAD

**Issue by niksedk** [ggerganov/whisper.cpp#469]
Does OpenBLAS Windows 64-bit build from v1.2.0 run on all 64-bit CPUs - both with and without AVX2?
(32-bit version on 32-bit OS)

Also, v1.2.0 runs very well, all files get processed now - nice and stable release :)
(probably mostly due to https://github.com/ggerganov/whisper.cpp/commit/291980369c1d3cba5d85f78b77b8f944b821d1cc)

**Comment by ggerganov** [comment]
I actually recently realised that `whisper.cpp` only needs AVX. AVX2 is not required. I need to update the build to reflect that.
But on your question - it should work on all 64-bit CPUs with AVX. I think 32-bit will not work - not sure

**Comment by niksedk** [comment]
thx :)

**Comment by Purfview** [comment]
> it should work on all 64-bit CPUs with AVX

It doesn't work with AVX CPU. Is there ETA for the fixed build?
Now I use @niksedk's "SSE2" build, I wonder how much it's slower than AVX...

**Comment by ggerganov** [comment]
It should work on all CPUs with AVX + FMA + F2C instruction sets

**Comment by Purfview** [comment]
> It should work on all CPUs with AVX + FMA + F2C instruction sets

Ah, my CPU doesn't have FMA (dunno what F2C is). Is there possibility of a compile without FMA but with AVX?
Btw,"SSE2" version runs 3 times slower than OpanAI's Python implementation.
