### ISSUE TITLE
is it possible to run ggml C/C++ whisper model on tflite micro framework?

### ISSUE THREAD

**Issue by nyadla-sys** [ggerganov/whisper.cpp#47]
is it possible to run ggml C/C++ whisper model on tflite micro framework?

https://github.com/tensorflow/tflite-micro

**Comment by richardburleigh** [comment]
Someone already converted the PyTorch models to tflite ([usefulsensors/openai-whisper](https://github.com/usefulsensors/openai-whisper))

**Comment by nyadla-sys** [comment]
@richardburleigh 
Running inference and evaluating is challenge with the converted tflite files

**Comment by ggerganov** [comment]
8-bit weights will be added natively some time in the future, but not a priority now
