### ISSUE TITLE
Add function to clear model words

### ISSUE THREAD

**Issue by tazz4843** [ggerganov/whisper.cpp#48]
Hi there! I'm trying to save compute resources by reusing `WhisperContext` objects in a STT server instance, but if no words were detected in the audio, it will cause whatever words were found in the last transcription that had words detected to be spit out again. This is a major issue, and I'd like a way to prevent this. The easiest way I can think of is adding a function to clear the words stored in the model. I considered adding such a feature to my app, but I realized this could cause serious overhead and introduce user privacy risks from storing many sentences compared to just clearing the words from the model itself. Thanks!

**Comment by ggerganov** [comment]
Before extending the interface of `whisper.cpp` can you confirm that setting `params.no_context = true;` fixes the repetition:

https://github.com/ggerganov/whisper.cpp/blob/b2f1600aa380e3ec5dc0de6194e38f27245c2a6a/whisper.h#L169

**Comment by tazz4843** [comment]
Setting `params.no_context = true` does not fix the repetition, or cause any noticeable change in output.

**Comment by ggerganov** [comment]
I think the latest change should resolve your problem - give it a try

**Comment by tazz4843** [comment]
It does fix the issue, thanks!
