### ISSUE TITLE
Failed to initialize whisper context

### ISSUE THREAD

**Issue by SLong97** [ggerganov/whisper.cpp#483]
Hi, I downloaded the x64 executable from here https://github.com/ggerganov/whisper.cpp/actions/runs/3517978497

When I try to run the transcription command, I get this error.
```
$ ./main -m models/ggml-tiny.bin -f audio/WAV-CLIP-The-Big-Tech-Show_Dropbox-CEO.wav
whisper_model_load: loading model from 'models/ggml-tiny.bin'
whisper_model_load: failed to open 'models/ggml-tiny.bin'
whisper_init: failed to load model from 'models/ggml-tiny.bin'
error: failed to initialize whisper context
```

Any help in resolving this issue would be greatly appreciated.

**Comment by sandrohanea** [comment]
Hello @SLong97 ,
I just tested it, and it works as expected as long as you download the model and add it to the `models` directory.

You can download that specific model from: https://huggingface.co/datasets/ggerganov/whisper.cpp/blob/main/ggml-tiny.bin

**Comment by SLong97** [comment]
> Hello @SLong97 , I just tested it, and it works as expected as long as you download the model and add it to the `models` directory.
> 
> You can download that specific model from: https://huggingface.co/datasets/ggerganov/whisper.cpp/blob/main/ggml-tiny.bin

That's what I was doing already, which resulted in this issue im facing now.

**Comment by SLong97** [comment]
It was a small problem in the end, had the model in the right folder, but did'nt have the folder in the right place.
