### ISSUE TITLE
4x slower on Windows compared to linux

### ISSUE THREAD

**Issue by aviks** [ggerganov/whisper.cpp#493]
I find that the inference is about 4x slower in windows, compared to linux, on the same intel i5 machine. The `whisper_full_parallel` takes 31 seconds on linux, but 119 seconds on windows, with the `base.en` model, and n_processors=1

The windows binary is cross compiled from a linux host with GCC/mingw. Both the windows and linux binaries are compiled with a default invocation of cmake, with no changes to the default build config. 

My code looks something like this: 

```
    ctx = whisper_init_from_file(path_to_model_file )
    wparams = whisper_full_default_params(WHISPER_SAMPLING_GREEDY)
    whisper_full_parallel(ctx, wparams, data, length(data), 1)
    n_segments = whisper_full_n_segments(ctx)
```

Any ideas on why this might be, or suggestions on how I might go about debugging it? 

PS: The code above is Julia, but that's a very thin wrapper around the C api. I can see the progress print outs slow down considerably, so it's all within the single C method call.

**Comment by RndyP** [comment]
Do you have AVX enabled on Windows? Is this Visual C++ compiler?

**Comment by aviks** [comment]
> Do you have AVX enabled on Windows? Is this Visual C++ compiler?

Not VC, I cross compile, using GCC. I can see that the compiler was invoked with `-mavx2` etc.

**Comment by aviks** [comment]
OK, so I happened to have run this timing when my laptop was on battery power (I know, I know, but I thought I was just considering relative times) 

On battery, on my machine, the windows process seems to be heavily throttled. The Linux (WSL) process is NOT throttled. When on AC power, the linux timing stays the same, and the windows timing is pretty close as well. 

Sorry for the noise. TIL about aggressive throttling of some processes on my laptop.

**Comment by RndyP** [comment]
Hehe, my laptop is waaay slower on battery.
