### ISSUE TITLE
I got too many repetitions. Is there a way to redo only a segment of the audio?

### ISSUE THREAD

**Issue by laravelpro** [ggerganov/whisper.cpp#496]
I got too many repetitions. Can you show me how to fix this?

Is there a way to redo only a segment of the audio? And then output to the same file?

**Comment by nxtreaming** [comment]
I wrote a simple utility to fix this issue.

https://github.com/nxtreaming/intellitext/blob/main/SubtitleFix/SubtitleFix.cpp

**Comment by indokid9999** [comment]
@laravelpro
You can use the  -ot and -d options to redo a short section of a large wav file.
 -ot N,     --offset-t N        [0      ] time offset in milliseconds
 -d  N,     --duration N        [0      ] duration of audio to process in milliseconds

The following example will process  1 minute of audio beginning at  30:00 of the wav file. It will even  put the correct timing in the output file(srt etc). You will have to import it into your original srt file which you should backup  before you redo the the short section. Try it first without the -osrt option.

main -m model/ggml-base.bin -l fr -f long_audio.wav -osrt  -ot 1800000 -d 60000

**Comment by ggerganov** [comment]
@laravelpro 
See answer by @indokid9999 

Repetitions will be resolved eventually - there are several other issues about this
