### ISSUE TITLE
What's the build process for Windows?

### ISSUE THREAD

**Issue by athu16** [ggerganov/whisper.cpp#51]
I tried running "make" and got this error:
```
process_begin: CreateProcess(NULL, uname -s, ...) failed.
process_begin: CreateProcess(NULL, uname -p, ...) failed.
process_begin: CreateProcess(NULL, uname -m, ...) failed.
cc  -O3 -std=c11   -Wall -Wextra -Wno-unused-parameter -Wno-unused-function   -c ggml.c
process_begin: CreateProcess(NULL, cc -O3 -std=c11 -Wall -Wextra -Wno-unused-parameter -Wno-unused-function -c ggml.c, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [ggml.o] Error 2
```
Could someone guide me through building this program on Windows? Are there pre-built binaries available? I have Visual Studio 2022 and MinGW installed.

**Comment by DaniruKun** [comment]
Honestly it works just fine under WSL2, just make sure that you have the necessary dependencies like SDL2

**Comment by anubhav712** [comment]
> I tried running "make" and got this error:
> 
> ```
> process_begin: CreateProcess(NULL, uname -s, ...) failed.
> process_begin: CreateProcess(NULL, uname -p, ...) failed.
> process_begin: CreateProcess(NULL, uname -m, ...) failed.
> cc  -O3 -std=c11   -Wall -Wextra -Wno-unused-parameter -Wno-unused-function   -c ggml.c
> process_begin: CreateProcess(NULL, cc -O3 -std=c11 -Wall -Wextra -Wno-unused-parameter -Wno-unused-function -c ggml.c, ...) failed.
> make (e=2): The system cannot find the file specified.
> make: *** [ggml.o] Error 2
> ```
> 
> Could someone guide me through building this program on Windows? Are there pre-built binaries available? I have Visual Studio 2022 and MinGW installed.

You need to make a small change in "MakeFIle"  ggml.c is not generating .o file due to windows
change the line 58 starting to GCC
and it should do fine . able to run now 
![image](https://user-images.githubusercontent.com/1998286/195979752-414e35db-e031-456f-a324-01263683bf48.png)

**Comment by athu16** [comment]
Thanks! I got past that point, but now it can't find pthread.h which seems to not support Windows.
`ggml.c:21:21: fatal error: pthread.h: No such file or directory
 #include <pthread.h>`
How do I get past this point?

**Comment by anubhav712** [comment]
Yes , Choose the binary according to your system from official Git link [https://github.com/niXman/mingw-builds-binaries/releases](url) . 

Thread issue , bug should now be closed
