### ISSUE TITLE
Spanish model

### ISSUE THREAD

**Issue by leonardorame** [ggerganov/whisper.cpp#510]
Hi, I see the only available models are:

tiny.en tiny base.en base small.en small medium.en medium large-v1 large

Can anyone help me to generate the ggml-base multilingual or spanish model?

**Comment by leonardorame** [comment]
Easy, just do `./download-ggml-model.sh small` (to download the small multilingual model).

**Comment by ManuXD32** [comment]
> Easy, just do `./download-ggml-model.sh small` (to download the small multilingual model).

But It still translates the audio to english, is there a way so the text is just transcribed and written in spanish and not translates?

**Comment by panagiotidi** [comment]
Try to use `--language es` when invoking

**Comment by George-P-1** [comment]
In addition to `--language es` which indicates the input audio language, also use `--task transcribe` which instructs whisper to convert Spanish audio to Spanish text. If you wanna translate to English text then you can specify `--task translate` instead.
