### ISSUE TITLE
Text fragments sometimes start with line break

### ISSUE THREAD

**Issue by peterk** [ggerganov/whisper.cpp#513]
Thank you for your great work in creating whisper.cpp! Running version 1.2.0. Using these settings when transcribing the [GWB demo file](https://upload.wikimedia.org/wikipedia/commons/1/1f/George_W_Bush_Columbia_FINAL.ogg).

`main -m ggml-medium.bin -p 2 -mc 500 -l en -f gwb.wav `

Terminal output:

```
[00:00:17.000 --> 00:00:23.000]   A short time later, debris was seen falling from the skies above Texas.
[00:00:23.000 --> 00:00:29.000]  
 The Columbia is lost. There are no survivors.
[00:00:29.000 --> 00:00:32.000]   On board was a crew of seven.
```

Every now and then I see transcription fragments starting with line breaks but I find it is difficult to get consistent test results. Is this a bug that could be dependent on the number of processors (-p parameter)?

**Comment by ggerganov** [comment]
Hi thanks!
This is unexpected - I don't see a possible reason for this. Do you observe it without the `-p` parameter?

**Comment by peterk** [comment]
I will try to find a test scenario that is consistent so I suggest this is closed until it is repeatable. Went through the code but can not see any obvious reason where this could happen.
