### ISSUE TITLE
Generated subtitles are too long 

### ISSUE THREAD

**Issue by R4ZZ3** [ggerganov/whisper.cpp#52]
Hi and first of all thanks for creating this implementation.

I am trying to create a new version out of this one https://huggingface.co/spaces/Finnish-NLP/Whisper-ASR-youtube-subtitles

I have this now working locally but now I spotted that generated subtitles are way too long.
On the right this cpp implementation. Original pytorch implementation (small model) on the left.
Is it a "feature" of this implementation or what is going on here?
![image](https://user-images.githubusercontent.com/25264037/195977600-b30e9801-6d0a-4820-aca8-d50a111b4942.png)

**Comment by ggerganov** [comment]
There isn't any logic that I added for determining the length of the segments. They are whatever the model produces.

I have a few guess of what could be causing the difference that you observe:

- Currently `whisper.cpp` performs the GREEDY strategy for sampling the tokens. This is the most simple strategy - always picking the most likely token after the inference. You can try disabling the beam search strategy in the PyTorch implementation and see if this results in longer segments too. If the answer is yes, it means that we need to implement the beam search strategy in `whisper.cpp` to resolve this.

- Another possible explanation is that [my computation of the Mel spectrogram](https://github.com/ggerganov/whisper.cpp/blob/master/whisper.cpp#L1956-L1966) is slightly different compared to the [PyTorch implementation](https://github.com/openai/whisper/blob/main/whisper/audio.py#L92-L124). I've tried running it on the same audio sample and the results are not identical. It's possible that this difference propagates through the network and leads to the observed differences. This is possible to resolve by matching the 2 implementations.

- The third explanation is that `whisper.cpp` does not produce identical results to the original implementation - it's just not possible (or very hard) to achieve the exact same results when working with floating point numbers. So all the rounding errors during the computation could eventually lead to a different result.

I think I've seen reports by some people that the original implementation also sometime produces very long segments. So it could be just a matter of chance - not much we can do here.

Additionally, I have tried adding logic for forcing the segments to not become very long by forcing a timestamp token to be sampled when the segment becomes long. In general it helps, but sometimes I observed errors and decided to not include it.

Hope this helps.

**Comment by pateljoel** [comment]
I too have this issue the subtitles are far too long with the C++ version of Whisper, @Topping1 I played with this and is there a way to get the text to be shorter?

**Comment by pateljoel** [comment]
@ggerganov I've tried the above and it doesn't make a difference, the text is still the same length.

**Comment by R4ZZ3** [comment]
Just fetched the updates and recompiled.
Seems promising! Small hickup at the end but it is perfectly ok!
Great job @ggerganov!

![image](https://user-images.githubusercontent.com/25264037/196539800-2bba0624-cddc-4fe1-9db3-7b7288a7212b.png)
