### ISSUE TITLE
ggml_new_tensor_impl: not enough space in the scratch memory

### ISSUE THREAD

**Issue by divideconcept** [ggerganov/whisper.cpp#529]
I'm using whisper.cpp as a C++ library in macOS 12.6 arm (macbook air M1), with the base and small multilingual models.

I'm processing audio chunks ranging from 3 to 20 seconds or so.

Sometime I randomly get this error (crashing my application):
ggml_new_tensor_impl: not enough space in the scratch memory
which points to this:
https://github.com/ggerganov/whisper.cpp/blob/373043cabecc1d456d99debe8ebe2d2801f30c2b/ggml.c#L1654

However I have no idea what I can do to help with this issue ?

**Comment by ggerganov** [comment]
Are you using the latest `master` branch?
There was a bugfix yesterday: #520

**Comment by divideconcept** [comment]
I couldn't repro the crash after using the latest master branch, so I'd say it's fixed.
Also the random behavior was consistant with an uninitialized variable.
