### ISSUE TITLE
Newbie question: How to create a libwhisper.so library so I can used it via ffi in Flutter

### ISSUE THREAD

**Issue by LiveRock** [ggerganov/whisper.cpp#541]
Newbie question: How to create a libwhisper.so library so I can used it via ffi in Flutter

The instructions works great to create the main executable in my Mac Book Pro M1 and the examples run well.
I want to use it in a Flutter app but will need it as a 'shared library' .so file.

How do I do it?

Thanks

**Comment by ggerganov** [comment]
`make libwhisper.so` should produce a shared library

**Comment by LiveRock** [comment]
When I followed the instructions, I only get a main executable file.
I tried another method but got a .dylib instead of .so

**Comment by LiveRock** [comment]
Thanks, it did create a so file.

**Comment by Prateek0001** [comment]
Hey i want to use whisper cpp which uses gpu in flutter project for ios using dart binding , can someone help ?

**Comment by steve3p0** [comment]
Did you ever get this to work?  I want to use it for Windows.

**Comment by fareesh** [comment]
> `make libwhisper.so` should produce a shared library

Is there a new approach now? I don't see  this in the Makefile anymore

`$(LIB_WHISPER): $(OBJ_WHISPER) $(LIB_GGML)
	$(CXX) $(CXXFLAGS) -shared -fPIC -o $@ $^ $(LDFLAGS)
`

**Comment by mukunthan007** [comment]
@fareesh Have you found any solution to build libwhisper.so file ?.

I can see multiple .so files in build/src directory but it's a linked file.

**Comment by mukunthan007** [comment]
@fareesh Found a solution to create a .so file
cmake \  
  -DCMAKE_TOOLCHAIN_FILE= .android_sdk/ndk/25.2.xxxxxx/build/cmake/android.toolchain.cmake  
  -DANDROID_ABI=arm64-v8a \       
  -DANDROID_PLATFORM=android-24 \ 
  -DBUILD_SHARED_LIBS=ON \   
  -B build-android

Then, Build command
cmake --build build-android --target whisper

Then search libwhisper.so file by
find . -name "libwhisper.*"
