### ISSUE TITLE
[crash] SIGABRT !isnan(x) > ggml_compute_forward_gelu_f32 > ggml.c

### ISSUE THREAD

**Issue by venkr** [ggerganov/whisper.cpp#545]
Looks like an isnan check in `ggml_compute_forward_gelu_f32` is failing sometimes, here's a stack trace:
```
ggml_compute_forward.cold.80(ggml.c:4225)
ggml_compute_forward_gelu_f32(ggml.c:4225)
ggml_compute_forward_gelu(ggml.c:4239)
ggml_compute_forward(ggml.c:6649)
ggml_graph_compute(ggml.c:7535)
whisper_encode(whisper.cpp:1702)
whisper_full(whisper.cpp:3607)
Whisper.transcribe(WhisperBridge.swift:96)
```

Will try to see if I can collect more logs on what causes this.

**Comment by ggerganov** [comment]
Please provide the commit hash that you are using too

**Comment by venkr** [comment]
We're using `whisper.spm` commit [d5c6d](https://github.com/ggerganov/whisper.spm/commit/d5c6d5c8a39703153472055c13902defc7177d22) - so I'm guessing that's likely `b2083c`

**Comment by ggerganov** [comment]
Ok, if you are using language auto-detect functionality, then most likely the cause is the following bug which was fixed recently: fb4d0d470ff4accb66d185e31e194807c1b9b437

I'll push a new version soon

**Comment by venkr** [comment]
Ah okay cool, I thought it was the source of the scratch memory OOM, but didn't realize it could cause this too.
Thanks!

**Comment by ggerganov** [comment]
Feel free to reopen if the issue persists
