### ISSUE TITLE
Is it possible to load a custom fine-tuned checkpoint from this port?

### ISSUE THREAD

**Issue by 10-zin** [ggerganov/whisper.cpp#547]
Let's say the checkpoint is from the hugging-face training script. I want to transcribe using one of their checkpoints with this port.

**Comment by ggerganov** [comment]
See if the "Fine-tuned models" section has any useful info:

https://github.com/ggerganov/whisper.cpp/tree/master/models#fine-tuned-models

**Comment by 10-zin** [comment]
awesome!! @ggerganov I checked that and it works!

However, It is quite slow for the fine-tuned versions in comparison to the standard ones from openai.
Any idea why this could be the case?

**Comment by ggerganov** [comment]
Try adding `--no-fallback` parameter
