### ISSUE TITLE
Unicode/Encoding Issue with Japanese Text

### ISSUE THREAD

**Issue by ChristopherFritz** [ggerganov/whisper.cpp#55]
I'm trying running Japanese audio files through whisper.cpp, and the output is returning some "corrupted" output.

Here is the output from whisper and whisper.cpp for comparison:

|Command|Output|
|--|--|
|whisper output.wav --model large --language Japanese|さくらちゃん運動神経もすっごくいいし、バトンもうまいんだけど|
|./main -m models/ggml-large.bin -l ja -f output.wav|さくらちゃん運動神��もすっごくいいし、バトンもうまいんだけど。|

The expected 「神経も」 portion is the following in hex:

0xE7A59E 0xE7B58C 0xE38282

The "corrupted" 「神��も」 portion is:

0xE7A59E 0xEFBFBD 0xEEBFBD 0xE38282

------

Note: I had to comment out a few lines from whisper.cpp around line 2300 for "make" to compile.  I do not know if this would impact it.

```
                    .beam_search = {
                        //.n_past = 0,
                        //.beam_width = 10,
                        //.n_best = 5,
                    },
```

**Comment by tazz4843** [comment]
This sounds like a duplicate of #25.

**Comment by ChristopherFritz** [comment]
I completely failed to see that one when I checked!  Looks like it is indeed the same issue.
