### ISSUE TITLE
Audio Buffer Format

### ISSUE THREAD

**Issue by cerupcat** [ggerganov/whisper.cpp#565]
Does whisper.cpp do any downsampling of audio or do we have to provide it 16000hz audio as Floats? I'm trying to get things working on iOS, but the input sample rate doesn't match 16k hz and I'm not sure if that's the reason it's not recognizing in words.

**Comment by ggerganov** [comment]
You have to provide 16 kHz PCM. `whisper.cpp` does not perform resampling. If the audio is not 16 kHz, it will not be transcribed correctly

**Comment by cristalwen** [comment]
> You have to provide 16 kHz PCM. `whisper.cpp` does not perform resampling. If the audio is not 16 kHz, it will not be transcribed correctly

If I want to run a file with any sampling rate, how should I modify it?

**Comment by cristalwen** [comment]
> You have to provide 16 kHz PCM. `whisper.cpp` does not perform resampling. If the audio is not 16 kHz, it will not be transcribed correctly

If I want to run a file with any sampling rate, how should I modify it?
