### ISSUE TITLE
example whisper.wasm is different than example

### ISSUE THREAD

**Issue by DavidGOrtega** [ggerganov/whisper.cpp#577]
The example at https://whisper.ggerganov.com/ differs from the repo.
There is no threads in the repo example so the `index-tmpl.html` and `emscripten.cpp` should be different

Found in index-tmpl.html at https://whisper.ggerganov.com/
```js 
Module.full_default(instance, audio, document.getElementById('language').value, nthreads, translate)
```

vs 

```js
Module.full_default(instance, audio, document.getElementById('language').value, translate)
```

```cpp
emscripten::function("full_default", emscripten::optional_override([](size_t index, const emscripten::val & audio, const std::string & lang, bool translate) {
```

**Comment by ggerganov** [comment]
The current live version at https://whisper.ggerganov.com/ is built from the [4-bit](https://github.com/ggerganov/whisper.cpp/pull/540) branch. The changes are there, but not yet on master

**Comment by DavidGOrtega** [comment]
Awesome work! 🙏
