### ISSUE TITLE
What is the audio length in the stream?

### ISSUE THREAD

**Issue by G2G2G2G** [ggerganov/whisper.cpp#578]
```
./stream -m ./models/ggml-base.en.bin -t 8 --step 500 --length 5000
```
in the --help it says
>            --length N      [10000  ] audio length in milliseconds

I thought is the max length of a segment?  but it is not that
the length to run the stream? (I know it isn't that)
is it the time allowed to process it?

**Comment by ggerganov** [comment]
It's the length of each segment.
Each transcribed line by the `stream` example is a segment and it corresponds to `--length` ms of audio.

**Comment by G2G2G2G** [comment]
ohh ok the segment of voice that turns into 1 line of text?
