### ISSUE TITLE
Zero-pad the audio, not the spectrogram

### ISSUE THREAD

**Issue by ggerganov** [ggerganov/whisper.cpp#579]
Makes sense - hopefully will reduce hallucinations

https://github.com/openai/whisper/discussions/838#discussioncomment-5222689

**Comment by lunixbochs** [comment]
I'm pretty sure zero-padding audio samples and padding with null spectrogram frames has almost the exact same on the input features to the model.

If their hypothesis is correct, it may be worth playing with other kinds of padding, but my experience has been that whisper will hallucinate during uniform noise as well.

**Comment by lunixbochs** [comment]
(Removed previous incorrect assumption about the featurization).

As long as you don't change the featurization, it looks like you can just switch your padding to `-1.5` if it's more convenient to keep padding at the spectrogram level.

**Comment by meakbiyik** [comment]
Oh this might be a game-changer, I wasn't able to find a way to reduce them so far.

**Comment by albino1** [comment]
This was merged into Whisper as of [20230307](https://github.com/openai/whisper/commit/26807ec6d3cd9d3ce153d143dc840ea312dc1fad), is there a chance we'll see it in whisper.cpp soon?
