### ISSUE TITLE
Polyglot feature

### ISSUE THREAD

**Issue by DavidGOrtega** [ggerganov/whisper.cpp#584]
Could be plausible to adjust the language detector to support a polyglot conversation? 
The idea is to be able to adjust the language detector prior to the net forward and forwarding the input in many batches.

**Comment by DavidGOrtega** [comment]
related to #536

**Comment by DavidGOrtega** [comment]
While I love the idea I feel that this enhancement might be out of the scope of the project itself.
Im using this library in conjunction of vlad.js to do exactly this and works pretty well. 
I would rather prefer this project to focus on speed and memory management instead of solving this easy to solve issues aside the project.

Please close it if you feel the same @ggerganov

**Comment by ggerganov** [comment]
The `whisper_lang_auto_detect()` call allows to "probe" different parts of the audio for the language:

https://github.com/ggerganov/whisper.cpp/blob/09e90680072d8ecdf02eaf21c393218385d2c616/whisper.h#L224-L236

Regarding the VAD - yes, a general purpose VAD is not trivial to implement and is out of the scope of this project.

**Comment by DavidGOrtega** [comment]
> The `whisper_lang_auto_detect()` call allows to "probe" different parts of the audio for the language:

I have tried @ggerganov doing a multi language and stays with the very first language detected. Im using the `4-bit` branch
