### ISSUE TITLE
Decoder randomly goes crazy. Makes it extremely slow

### ISSUE THREAD

**Issue by scottmas** [ggerganov/whisper.cpp#588]
Some audio files randomly take forever to transcribe on my M1 built of today’s main branch. My benchmark for small.en shows a fast encoding speed of ~800ms.

<details>
<summary>Full benchmark</summary>
{0:59}~/projects/whisper.cpp:master ✗ ➭ ./bench -m models/ggml-small.en.bin             
whisper_init_from_file_no_state: loading model from 'models/ggml-small.en.bin'
whisper_model_load: loading model
whisper_model_load: n_vocab       = 51864
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 768
whisper_model_load: n_audio_head  = 12
whisper_model_load: n_audio_layer = 12
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 768
whisper_model_load: n_text_head   = 12
whisper_model_load: n_text_layer  = 12
whisper_model_load: n_mels        = 80
whisper_model_load: f16           = 1
whisper_model_load: type          = 3
whisper_model_load: mem required  =  603.00 MB (+   16.00 MB per decoder)
whisper_model_load: adding 1607 extra tokens
whisper_model_load: model ctx     =  464.56 MB
whisper_model_load: model size    =  464.44 MB
whisper_init_state: kv self size  =   15.75 MB
whisper_init_state: kv cross size =   52.73 MB

system_info: n_threads = 4 / 10 | AVX = 0 | AVX2 = 0 | AVX512 = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | F16C = 0 | FP16_VA = 1 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 0 | VSX = 0 | 

whisper_print_timings:     load time =   178.54 ms
whisper_print_timings:     fallbacks =   0 p /   0 h
whisper_print_timings:      mel time =     0.00 ms
whisper_print_timings:   sample time =     0.00 ms /     1 runs (    0.00 ms per run)
whisper_print_timings:   encode time =   782.57 ms /     1 runs (  782.57 ms per run)
whisper_print_timings:   decode time =     0.00 ms /     1 runs (    0.00 ms per run)
whisper_print_timings:    total time =   973.71 ms
</details>

But when I do a simple transcription of a simple 2 second audio file, I randomly can see decode times of ~20 seconds. 

```bash
whisper_print_timings:     load time =   176.71 ms
whisper_print_timings:     fallbacks =   3 p /   0 h
whisper_print_timings:      mel time =     4.35 ms
whisper_print_timings:   sample time =  1990.16 ms /  2878 runs (    0.69 ms per run)
whisper_print_timings:   encode time =   767.62 ms /     1 runs (  767.62 ms per run)
whisper_print_timings:   decode time = 22531.08 ms /  2866 runs (    7.86 ms per run)
whisper_print_timings:    total time = 25493.16 ms
```

I haven't been able to detect a pattern to when and why this happens but the answer likely lies in the recent changes to the decoder. Long files. Short files. Clear speech files. Ambiguous noises files. It just seems to randomly happen although perhaps more commonly on audio with ambiguous speech samples. Any insight or additional info I can give you?

**Comment by dennislysenko** [comment]
I can corroborate this roughly, albeit with nowhere near as good of data as you. I had the same audio file take 90 seconds and 277 seconds in different runs, on iOS 15. Unable to confirm if this is on the decoder or elsewhere.

v1.2.1, commit `af005d5` in our case.

**Comment by dennislysenko** [comment]
@scottmas it might help to attach the 2 sec audio file you're using for those benchmarks, so that @ggerganov has a known reference to compare against your example timings

**Comment by ggerganov** [comment]
Can you confirm that adding `-nf` resolves the issue?

**Comment by dennislysenko** [comment]
@ggerganov I see in my examples that specifying `params.temperature_inc = 0` indeed causes it to run much faster on files with ambiguous audio/silence. 

Are there any issues you think it might cause if I use no-fallback mode?

**Comment by ggerganov** [comment]
The fall back generally improves transcription quality. But currently, the evaluation in `whisper.cpp` is suboptimal.
I plan to disable this option by default until more efficient implementation is available
