### ISSUE TITLE
There seems to be no Autodetect language ?

### ISSUE THREAD

**Issue by anubhav712** [ggerganov/whisper.cpp#59]
Language other than English needs to be specified , it doesn't auto detect the language , is it due to missing multilingual support ?

**Comment by anubhav712** [comment]
Language other than English needs to be specified , it doesn't auto detect the language , is it  due to missing multilingual support ?

**Comment by ggerganov** [comment]
Here is a quick sketch for implementing this:
- add language "auto" that can be passed to `language` parameter https://github.com/ggerganov/whisper.cpp/blob/b7c85d1ea6533fff53dd977ad6f531e19d8ff95f/whisper.h#L228
- in `whisper_full()`, add auto-detect logic if `params.language == "auto"`, probably somewhere at the start:
https://github.com/ggerganov/whisper.cpp/blob/b7c85d1ea6533fff53dd977ad6f531e19d8ff95f/whisper.cpp#L2601-L2602
- the auto-detect logic should run the encoder on the first 30s audio `whisper_encode()`
- after that, it should run the decoder once `whisper_decode()` and sample the highest probability language token

Maybe we can add a standalone function in `whisper.h` that detects the language and can be used for arbitrary sound position. Something like:

```c
const char * whisper_lang_auto_detect(struct whisper_context * ctx, int t_offset, int t_length);
```

**Comment by hrehfeld** [comment]
Thank you for implementing this! :heart:
