### ISSUE TITLE
Problem compiling to arm64 architecture

### ISSUE THREAD

**Issue by psquizzle** [ggerganov/whisper.cpp#590]
I am trying to integrate this into a react-native app, I am compiling for iOS and getting the following error.

Undefined symbols for architecture arm64
┌─ Symbol: _ggml_add
└─ Referenced from: whisper_encode_internal(whisper_context&, whisper_state&, int, int) in libreact-native-jsi-template.a(whisper.o)

[RUN_FASTLANE]
❌  ld: symbol(s) not found for architecture arm64

[RUN_FASTLANE]
❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)

Any ideas on how to proceed?

**Comment by psquizzle** [comment]
Ok, problem solved, I thought it was something to do with the compiler settings but ggml.c wasn't linking properly

**Comment by voicyio** [comment]
> Ok, problem solved, I thought it was something to do with the compiler settings but ggml.c wasn't linking properly

how did you solve this problem?
clang: error: linker command failed with exit code 1
