### ISSUE TITLE
Hosting the ggml models in the cloud

### ISSUE THREAD

**Issue by ggerganov** [ggerganov/whisper.cpp#6]
Currently, I am hosting the `ggml` Whisper model files on my Linode server.
However, it has a limited network bandwidth per month and as more people start using `whisper.cpp` it won't be enough.

What are some good options for hosting ~10GB of data?

The only requirement is to be able to `wget`/`curl` the files directly - i.e. Google Drive and alike are not an option.

**Comment by ArtyomZemlyak** [comment]
I think you can try huggingface. 
Its just a good tool for models sharing. For example i tried load [tiny model](https://huggingface.co/artzemliak/whisper-tiny-test-for-load).

And you can load models as you want:
```sh
wget https://huggingface.co/artzemliak/whisper-tiny-test-for-load/resolve/main/tiny.pt
````
Or clone repo with LFS support.
