### ISSUE TITLE
Building 1.2.1 for Windows using mingw yields error: Undefined reference to read_wav...

### ISSUE THREAD

**Issue by zorlack** [ggerganov/whisper.cpp#606]
I'm following the instructions in #168 but with version `1.2.1` I can no longer compile successfully:

I start in a fresh Debian container and I prep it by doing: 
```
apt-get update -y
apt-get install git curl build-essential g++-mingw-w64-x86-64-posix gcc-mingw-w64-x86-64-posix -y
git clone -b v1.2.1  https://github.com/ggerganov/whisper.cpp.git
```

Now I go to do the build
```
root@3fc79d49a589:/# cd whisper.cpp
root@3fc79d49a589:/whisper.cpp# mkdir bin-windows
root@3fc79d49a589:/whisper.cpp# mkdir bin-windows/models
root@3fc79d49a589:/whisper.cpp# cp ./models/download-ggml-model.sh bin-windows/models
root@3fc79d49a589:/whisper.cpp# x86_64-w64-mingw32-gcc-posix -I. -O3 -std=c11 -mfma -mf16c -mavx -mavx2 -c ggml.c -o bin-windows/ggml.o
root@3fc79d49a589:/whisper.cpp# x86_64-w64-mingw32-g++-posix -I. -I./examples -O3 -std=c++11 -lwinpthread -c whisper.cpp -o bin-windows/whisper.o
root@3fc79d49a589:/whisper.cpp# x86_64-w64-mingw32-g++-posix -I. -I./examples -O3 -std=c++11 -static-libgcc -static-libstdc++ -lwinpthread examples/main/main.cpp bin-windows/ggml.o bin-windows/whisper.o -o bin-windows/main
/usr/bin/x86_64-w64-mingw32-ld: /tmp/ccaSbP9g.o:main.cpp:(.text.startup+0x6a4): undefined reference to `read_wav(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<float, std::allocator<float> >&, std::vector<std::vector<float, std::allocator<float> >, std::allocator<std::vector<float, std::allocator<float> > > >&, bool)'
collect2: error: ld returned 1 exit status
```

I'm not sure what's happening here. Seems like it doesn't see a reference, but I'm not sure what's changed.

This process works just fine for `v1.2.0`

Thanks very much!

**Comment by lijihhh** [comment]
There's a new file in "examples" named "common.cpp" in this version.
You need to build this file also.
`x86_64-w64-mingw32-g++-posix -I. -I./examples -O3 -std=c++11 -lwinpthread -c examples/common.cpp -o common.o`
And add the "common.o" to build "main.cpp".
`x86_64-w64-mingw32-g++-posix -I. -I./examples -O3 -std=c++11 -static-libgcc -static-libstdc++ -lwinpthread examples/main/main.cpp common.o whisper.o ggml.o -o main`

**Comment by zorlack** [comment]
Thank you! @lijihhh you're exactly right.

**Comment by lijihhh** [comment]
Which cpu are you using？My E5 cpu can't print any results either. But it works correctly on my i3 PC.

**Comment by abdoOmar01** [comment]
I'm using an i7-4700MQ

**Comment by jfariasf87** [comment]
I'm getting the same error when building on Ubuntu 22.04 on WSL2:

`..
/usr/bin/x86_64-w64-mingw32-ld: bin-windows/ggml.o:ggml.c:(.rdata+0x4988): undefined reference to `ggml_vec_dot_q6_K_q8_K'
/usr/bin/x86_64-w64-mingw32-ld: bin-windows/ggml.o:ggml.c:(.rdata+0x49c0): undefined reference to `quantize_row_q8_K'
collect2: error: ld returned 1 exit status
`
