### ISSUE TITLE
How to ggml-ify other fine-tuned whisper models?

### ISSUE THREAD

**Issue by haqatak** [ggerganov/whisper.cpp#616]
Hi, I would love to use this model https://huggingface.co/pere/whisper-NST2.
I tried point it at the  pytorch_model.bin file, but I receive an error:
Traceback (most recent call last):
  File "convert-pt-to-ggml.py", line 209, in <module>
    hparams = checkpoint["dims"]
KeyError: 'dims'

Can someone point me in the right direction?
thanks :)

**Comment by haqatak** [comment]
Perfect, that worked
thanks for the swift reply :D

**Comment by jasontitus** [comment]
For some reason my fine tuning (following that tutorial) doesn't seem to create a vocab.json file in the checkpoint folders.  Is there a step that generates that file that I could have missed?  It is expected by the conversion script.

Also, I'm assuming that the checkpoint directories are the final product of training.  Perhaps I am missing a finalization step somewhere?
