### ISSUE TITLE
/whisper.cpp/whisper.cpp:2305:17: internal compiler error: in reshape_init_class, at cp/decl.c:6465

### ISSUE THREAD

**Issue by cornpo** [ggerganov/whisper.cpp#62]
Fully stumped. Only did `make`. cpp (Ubuntu 11.2.0-19ubuntu1) 11.2.0

`whisper.cpp: In function ‘whisper_full_params whisper_full_default_params(whisper_decode_strategy)’:
whisper.cpp:2305:17: internal compiler error: in reshape_init_class, at cp/decl.c:6465
 2305 |                 };
      |                 ^
0x7f415aaa6d8f __libc_start_call_main
	../sysdeps/nptl/libc_start_call_main.h:58
0x7f415aaa6e3f __libc_start_main_impl
	../csu/libc-start.c:392
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <file:///usr/share/doc/gcc-11/README.Bugs> for instructions.`

**Comment by ggerganov** [comment]
Looks like a compiler bug. Just pushed a workaround - give it a try

**Comment by cornpo** [comment]
It compiles now. Thanks alot!
