### ISSUE TITLE
Add `params.initial_prompt` to set an initial prompt string

### ISSUE THREAD

**Issue by sindresorhus** [ggerganov/whisper.cpp#637]
It would be useful if the API had an `initial_prompt` parameter to set a string as the initial prompt. The OpenAI docs recommend always setting it to fix punctation, so it's quite a common need: https://platform.openai.com/docs/guides/speech-to-text/prompting

I'm aware I could already do something like [this](https://github.com/rock3125/whisper.cpp/commit/cd0ae21ac0436a595023074b86a8bfe7cc7f4797#diff-2d3599a9fad195f2c3c60bd06691bc1815325b3560b5feda41a91fa71194e805R468-R482), but I don't think it makes sense for everyone to re-implement that logic.

**Comment by jhen0409** [comment]
Agree, that option will be very useful!

I did the same in https://github.com/mybigday/whisper.rn/pull/8, I think it can be built directly into the whisper.cpp. Maybe I will try to send a PR later.

**Comment by User1231300** [comment]
I also would appreciate this
