### ISSUE TITLE
Txt output not saving timestamps

### ISSUE THREAD

**Issue by HLasse** [ggerganov/whisper.cpp#644]
When used with the `-otxt` flag the timestamps are not saved to the .txt despite being printed in stdout. `-osrt` and `-ovst` work fine.

**Example:**
Running `./main -m models/ggml-medium.bin -f samples/jfk.wav -otxt`

Results in the following output:
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/23191638/227020791-b88eb7d0-6d4f-4ea4-ae95-cbb5f4d66b07.png">

And this .txt file:
<img width="885" alt="image" src="https://user-images.githubusercontent.com/23191638/227021141-0cf4d21e-ed45-4a1e-aba1-7331f8a92121.png">

Whereas running `./main -m models/ggml-medium.bin -f samples/jfk.wav -osrt` produces timestamps in .srt format

<img width="893" alt="image" src="https://user-images.githubusercontent.com/23191638/227021299-d308b3e6-3c98-4e73-a48a-47e36a5a7362.png">

**Comment by ggerganov** [comment]
This is the intended behaviour for `-otxt`. You can either use one of the other formats or add a new format that fits your requirements

**Comment by HLasse** [comment]
I see, thanks. Ended up using `tee` to direct the output to a file as well `./main -m models/ggml-medium.bin -f samples/jfk.wav | tee jfk.txt`
