### ISSUE TITLE
Not working on MacOS (ARM)

### ISSUE THREAD

**Issue by undefdev** [ggerganov/whisper.cpp#66]
Hi, I've been trying to get this to work a few times, but it always fails with an illegal hardware instruction error.

E.g. for `./main -m models/ggml-small.bin -f samples/jfk.wav` I get the following output:
```
whisper_model_load: loading model from 'models/ggml-small.bin'
whisper_model_load: n_vocab       = 51865
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 768
whisper_model_load: n_audio_head  = 12
whisper_model_load: n_audio_layer = 12
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 768
whisper_model_load: n_text_head   = 12
whisper_model_load: n_text_layer  = 12
whisper_model_load: n_mels        = 80
whisper_model_load: f16           = 1
whisper_model_load: type          = 3
whisper_model_load: mem_required  = 1048.00 MB
whisper_model_load: adding 1608 extra tokens
whisper_model_load: ggml ctx size = 533.05 MB
fish: Job 1, './main -m models/ggml-small.b...' terminated by signal SIGILL (Illegal instruction)
```

I've tried other models as well, but the result is always the same.

**Comment by ggerganov** [comment]
That is interesting. What device are you using?

What is the output of:

```bash
make clean
make
```

**Comment by undefdev** [comment]
I'm using a MacBook Pro with M1 Max.

output of `make clean`:
```
rm -f *.o main libwhisper.a
```
output of `make`:
```
cc  -O3 -std=c11   -Wall -Wextra -Wno-unused-parameter -Wno-unused-function -pthread -mavx -mavx2 -mfma -mf16c   -c ggml.c
c++ -O3 -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wno-unused-function -pthread -c whisper.cpp
c++ -O3 -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wno-unused-function -pthread main.cpp whisper.o ggml.o -o main 
./main -h

usage: ./main [options] file0.wav file1.wav ...

options:
  -h,       --help           show this help message and exit
  -s SEED,  --seed SEED      RNG seed (default: -1)
  -t N,     --threads N      number of threads to use during computation (default: 4)
  -o N,     --offset N       offset in milliseconds (default: 0)
  -v,       --verbose        verbose output
            --translate      translate from source language to english
  -otxt,    --output-txt     output result in a text file
  -ovtt,    --output-vtt     output result in a vtt file
  -osrt,    --output-srt     output result in a srt file
  -ps,      --print_special  print special tokens
  -nt,      --no_timestamps  do not print timestamps
  -l LANG,  --language LANG  spoken language (default: en)
  -m FNAME, --model FNAME    model path (default: models/ggml-base.en.bin)
  -f FNAME, --file FNAME     input WAV file path
  ```

**Comment by ggerganov** [comment]
Ok, I see the problem - the Makefile incorrectly thinks that this is x86 architecture and adds AVX flags: `-mavx -mavx2 -mfma -mf16c`

To fix this, I need to know the output of the following commands:

```
uname -s
uname -p
uname -m
```

**Comment by undefdev** [comment]
Interesting... `uname -mps` gives me:
```
Darwin x86_64 i386
```

**Comment by ggerganov** [comment]
That's unexpected.

In the meantime, if you just want to give `whisper.cpp` a try, you should be able to compile it properly like this:

```java
cc  -O3 -std=c11   -Wall -Wextra -Wno-unused-parameter -Wno-unused-function -pthread -DGGML_USE_ACCELERATE   -c ggml.c
c++ -O3 -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wno-unused-function -pthread -c whisper.cpp
c++ -O3 -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wno-unused-function -pthread main.cpp whisper.o ggml.o -o main  -framework Accelerate
```

This is what I use on my MacBook M1 Pro and it works.

If you figure out why `uname` reports this as `x86_64` please let me know, so I can somehow update the Makefile to support M1 Max.

**Comment by undefdev** [comment]
`uname -v` gives me `Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000` however... Apparently I'm not the first having this problem

https://github.com/Homebrew/discussions/discussions/2226
https://apple.stackexchange.com/questions/420452/running-uname-m-gives-x86-64-on-m1-mac-mini

I have also checked, and terminal is not running in rosetta.

**Comment by abelbabel** [comment]
On FreeBSD we have `sysctl` ... is there something equivalent on Mac OS - it's somehow one familiy ...

```
$ sysctl -n hw.machine_arch
amd64
```

**Comment by undefdev** [comment]
There is `sysctl`, but it works somewhat differently. So your oids aren't supported on Mac it seems.

Particularly useful queries are:
```
$ sysctl -n hw.optional.arm64
1
$ sysctl -n machdep.cpu.brand_string
Apple M1 Max
```

Some other interesting fields I've found:
```
machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 PCLMULQDQ DTSE64 MON DSCPL VMX EST TM2 SSSE3 CX16 TPR PDCM SSE4.1 SSE4.2 AES SEGLIM64
```
or
```
$ sysctl -a | grep arm
hw.optional.arm.FEAT_FlagM: 1
hw.optional.arm.FEAT_FlagM2: 1
hw.optional.arm.FEAT_FHM: 1
hw.optional.arm.FEAT_DotProd: 1
hw.optional.arm.FEAT_SHA3: 1
hw.optional.arm.FEAT_RDM: 1
hw.optional.arm.FEAT_LSE: 1
hw.optional.arm.FEAT_SHA256: 1
hw.optional.arm.FEAT_SHA512: 1
hw.optional.arm.FEAT_SHA1: 1
hw.optional.arm.FEAT_AES: 1
hw.optional.arm.FEAT_PMULL: 1
hw.optional.arm.FEAT_SPECRES: 0
hw.optional.arm.FEAT_SB: 1
hw.optional.arm.FEAT_FRINTTS: 1
hw.optional.arm.FEAT_LRCPC: 1
hw.optional.arm.FEAT_LRCPC2: 1
hw.optional.arm.FEAT_FCMA: 1
hw.optional.arm.FEAT_JSCVT: 1
hw.optional.arm.FEAT_PAuth: 1
hw.optional.arm.FEAT_PAuth2: 0
hw.optional.arm.FEAT_FPAC: 0
hw.optional.arm.FEAT_DPB: 1
hw.optional.arm.FEAT_DPB2: 1
hw.optional.arm.FEAT_BF16: 0
hw.optional.arm.FEAT_I8MM: 0
hw.optional.arm.FEAT_ECV: 1
hw.optional.arm.FEAT_LSE2: 1
hw.optional.arm.FEAT_CSV2: 1
hw.optional.arm.FEAT_CSV3: 1
hw.optional.arm.FEAT_FP16: 1
hw.optional.arm.FEAT_SSBS: 1
hw.optional.arm.FEAT_BTI: 0
hw.optional.armv8_1_atomics: 1
hw.optional.armv8_2_fhm: 1
hw.optional.armv8_2_sha512: 1
hw.optional.armv8_2_sha3: 1
hw.optional.armv8_3_compnum: 1
hw.optional.armv8_crc32: 1
hw.optional.armv8_gpi: 1
hw.optional.arm64: 1
```

**Comment by ggerganov** [comment]
@undefdev 
I pushed a branch that uses `sysctl -n hw.optional.arm64`.
Can you give it a try and see if it works:

```
git checkout make-mac-os-arm
```

**Comment by Vimy** [comment]
I got the same error when I was using terminal in Rosetta mode. Maybe that's it?

**Comment by undefdev** [comment]
@Vimy No, apparently it was an old homebrew installation that caused the issue. I hadn't reinstalled it since it gained m1 support.

@ggerganov I tried it, and it worked, albeit it was about 4x slower than when I just hardcoded `UNAME_P := arm` and
`UNAME_M := arm64`. It seems like you commented out the `ifeq ($(SYSCTL_M),1)` case, but if i put it back in it won't work.

In the meantime I also fixed my wrong arch output by reinstalling homebrew. Now the performance is also a lot better!
Before, 5 seconds of audio took about 20 seconds to transcribe. Now it's only a bit longer than one second!
So fixing the terminal is definitely worth it.

I think it's probably best to check sysctl and give a warning linking to this issue, if there's a contradicting output.
Otherwise I think it's easier to just overwrite the UNAME variables.
The code in the pull request I made should do that.

**Comment by ggerganov** [comment]
@undefdev 
Thanks for the investigation! I like the proposed change and have merged it into upstream.

**Comment by xyx361100238** [comment]
I was use whisper in macbook pro same system set:Darwin i386  x86_64
It works in ./main -m models/ggml-base.en.bin -f samples/jfk.wav 
But not work in ./stream -m models/ggml-base.en.bin -t 8 --step 500 --length 5000
Tips:

> adeMacBook-Pro:whisper.cpp-master a$ ./stream -m models/ggml-base.en.bin -t 8 --step 500 --length 5000
audio_sdl_init: found 2 capture devices:
audio_sdl_init:    - Capture device #0: 'Built-in Microphone'
audio_sdl_init:    - Capture device #1: 'BlackHole 2ch'
audio_sdl_init: attempt to open default capture device ...
audio_sdl_init: obtained spec for input device (SDL Id = 2):
audio_sdl_init:     - sample rate:       16000
audio_sdl_init:     - format:            33056 (required: 33056)
audio_sdl_init:     - channels:          1 (required: 1)
audio_sdl_init:     - samples per frame: 1024
whisper_model_load: loading model from 'models/ggml-base.en.bin'
whisper_model_load: n_vocab       = 51864
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 512
whisper_model_load: n_audio_head  = 8
whisper_model_load: n_audio_layer = 6
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 512
whisper_model_load: n_text_head   = 8
whisper_model_load: n_text_layer  = 6
whisper_model_load: n_mels        = 80
whisper_model_load: f16           = 1
whisper_model_load: type          = 2
whisper_model_load: mem_required  = 377.00 MB
whisper_model_load: adding 1607 extra tokens
whisper_model_load: ggml ctx size = 163.43 MB
whisper_model_load: memory size =    22.83 MB 
whisper_model_load: model size  =   140.54 MB
main: processing 8000 samples (step = 0.5 sec / len = 5.0 sec), 8 threads, lang = en, task = transcribe, timestamps = 0 ...

no content!

**Comment by xyx361100238** [comment]
@undefdev  do you can use ./stream?

**Comment by undefdev** [comment]
@xyx361100238 Yes, but it was too slow before fixing my terminal. So you probably need to fix this first (assuming you also have an ARM Mac).

So make sure you don't have rosetta enabled (check box not ticked):
<img width="333" alt="image" src="https://user-images.githubusercontent.com/13840966/196886155-2f5b3960-a6fa-4ca1-b656-b60e114dc321.png">

And if that's not it you can check if you have a m1 compatible homebrew.
If you have a m1 compatible homebrew, the folder `/opt/homebrew/` should exist.
Otherwise uninstall homebrew and reinstall it. Be aware that this means you will also have to reinstall all your homebrew packages, but imo it's worth it. Many things are faster now.

**Comment by xyx361100238** [comment]
@undefdev    yes，It's just  too slow！
it works well in M1 pro， thx！

**Comment by michael-prosper** [comment]
> @xyx361100238 Yes, but it was too slow before fixing my terminal. So you probably need to fix this first (assuming you also have an ARM Mac).
> 
> So make sure you don't have rosetta enabled (check box not ticked): <img alt="image" width="333" src="https://user-images.githubusercontent.com/13840966/196886155-2f5b3960-a6fa-4ca1-b656-b60e114dc321.png">
> 
> And if that's not it you can check if you have a m1 compatible homebrew. If you have a m1 compatible homebrew, the folder `/opt/homebrew/` should exist. Otherwise uninstall homebrew and reinstall it. Be aware that this means you will also have to reinstall all your homebrew packages, but imo it's worth it. Many things are faster now.

Sometimes it's useful to know why that would have happened - having a "Rosetta" terminal is a common workaround a lot of people suggest for various different things. I know early on when the M1s were released, Solana, React, and I'm sure other tools complained about ARM and so our go to "no think" workaround was to use a Rosetta Terminal, which prefixes command with x86 arch.

**Comment by etrnal1** [comment]
@undefdev item 选项不能点Rosetta 打开，否则第二张图就U _namep 显示为x86,m2 电脑正常显示应为arm ,执行make clean 在执行make 编辑即可成功
`make`
`make clean`


<img width="253" alt="Snipaste_2023-03-13_03-10-04" src="https://user-images.githubusercontent.com/23565695/224567292-446342b0-b1c6-4acb-ae08-<img width="942" alt="Snipaste_2023-03-13_03-11-00" src="https://user-images.githubusercontent.com/23565695/224567303-8b8b5a6e-0f88-443b-9990-08f0e8d4e9b0.png">dd04ada0bd79.png">

**Comment by Birch-san** [comment]
beware: the `uname` that ships with macOS, returns for `uname -p` a different result to the `uname` distributed by GNU coreutils.  
`arm` and `arm64` respectively.

https://github.com/Lightning-AI/lightning/pull/13992#issuecomment-1204157830

**Comment by alisonzhu** [comment]
> @undefdev item 选项不能点Rosetta 打开，否则第二张图就U _namep 显示为x86,m2 电脑正常显示应为arm ,执行make clean 在执行make 编辑即可成功
> 
> <img alt="Snipaste_2023-03-13_03-10-04" width="253" src="https://user-images.githubusercontent.com/23565695/224567711-ea968376-ccfd-41b4-afcb-d87f26e1b424.png">
> 
> `make clean` `make`
> 
> <img width="253" alt="Snipaste_2023-03-13_03-10-04" src="https://user-images.githubusercontent.com/23565695/224567292-446342b0-b1c6-4acb-ae08-<img alt="Snipaste_2023-03-13_03-11-00" width="942" src="https://user-images.githubusercontent.com/23565695/224567303-8b8b5a6e-0f88-443b-9990-08f0e8d4e9b0.png">dd04ada0bd79.png">

thank you

**Comment by PinkD** [comment]
Because the `uname` contains two architectures. We need to use `arch` command to force it to use arm64 instead of x86_64.

```
$ file `which uname`
/usr/bin/uname: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64e:Mach-O 64-bit executable arm64e]
/usr/bin/uname (for architecture x86_64):	Mach-O 64-bit executable x86_64
/usr/bin/uname (for architecture arm64e):	Mach-O 64-bit executable arm64e
```

```
$ uname -mps
Darwin x86_64 i386
$ arch -arm64 uname -mps
Darwin arm64 arm
```

So all you need to do to compile an arm64 executable is to add `arch -arm64` in front of `make` like this:

```
$ make -j8
$ file ./main
main: Mach-O 64-bit executable x86_64
$ arch -arm64 make -j8
$ file ./main
main: Mach-O 64-bit executable arm64
```

May this help you guys.

**Comment by Sternbach-Software** [comment]
> @xyx361100238 Yes, but it was too slow before fixing my terminal. So you probably need to fix this first (assuming you also have an ARM Mac).
> 
> So make sure you don't have rosetta enabled (check box not ticked): <img alt="image" width="333" src="https://user-images.githubusercontent.com/13840966/196886155-2f5b3960-a6fa-4ca1-b656-b60e114dc321.png">
> 
> And if that's not it you can check if you have a m1 compatible homebrew. If you have a m1 compatible homebrew, the folder `/opt/homebrew/` should exist. Otherwise uninstall homebrew and reinstall it. Be aware that this means you will also have to reinstall all your homebrew packages, but imo it's worth it. Many things are faster now.

Had to restart after this.

**Comment by shanebo** [comment]
> That's unexpected.
> 
> In the meantime, if you just want to give `whisper.cpp` a try, you should be able to compile it properly like this:
> 
> ```java
> cc  -O3 -std=c11   -Wall -Wextra -Wno-unused-parameter -Wno-unused-function -pthread -DGGML_USE_ACCELERATE   -c ggml.c
> c++ -O3 -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wno-unused-function -pthread -c whisper.cpp
> c++ -O3 -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wno-unused-function -pthread main.cpp whisper.o ggml.o -o main  -framework Accelerate
> ```
> 
> This is what I use on my MacBook M1 Pro and it works.
> 
> If you figure out why `uname` reports this as `x86_64` please let me know, so I can somehow update the Makefile to support M1 Max.

When I run that command I get `clang: error: no such file or directory: 'main.cpp'`

**Comment by thewh1teagle** [comment]
@ggerganov 
I get the same error when trying to run `x86_64` (`universal`) `whisper` on `m1`.
I prefer to ship only single architecture to `MacOS` as `m1` supports running `x86_64`.
Does whisper support running `x86_64` on `M1`? other program works for me, but when I tried [github.com/thewh1teagle/vibe/releases/download/v0.0.4/vibe_0.0.4_x64.dmg](https://github.com/thewh1teagle/vibe/releases/download/v0.0.4/vibe_0.0.4_x64.dmg)
it throws Ilegal insructions

**Comment by ggerganov** [comment]
There is no point in using `x86_64` builds on M1 - it will be very slow and requires some sort of emulation layer
