### ISSUE TITLE
GGML_ASSERT: \whisper.cpp\ggml.c:3904: !ggml_is_transposed(a)

### ISSUE THREAD

**Issue by ANMahmood** [ggerganov/whisper.cpp#661]
Trying to simply compile and run talk.exe on Windows 10.
Also, I checked out the talk.llama branch but msbuild produced errors. Is there a shortcut way to test talk.llama ?

.\whisper.cpp> cmake -S . -B ./build -A x64 -DCMAKE_BUILD_TYPE=Release -DWHISPER_SUPPORT_SDL2=ON -DWHISPER_BUILD_EXAMPLES=ON -DWHISPER_BUILD_TESTS=ON -DWHISPER_PERF=ON

.\whisper.cpp> msbuild ALL_BUILD.vcxproj -t:build -p:configuration=Release -p:platform=x64

cp ./sdl2/SDL2-2.26.0/lib/x64/SDL2.dll build/bin/Release

.\whisper.cpp> .\build\bin\Release\talk.exe -p Santa -mw .\models\ggml-base.en.bin

whisper_init_from_file_no_state: loading model from '.\models\ggml-base.en.bin'
whisper_model_load: loading model
whisper_model_load: n_vocab       = 51864
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 512
whisper_model_load: n_audio_head  = 8
whisper_model_load: n_audio_layer = 6
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 512
whisper_model_load: n_text_head   = 8
whisper_model_load: n_text_layer  = 6
whisper_model_load: n_mels        = 80
whisper_model_load: f16           = 1
whisper_model_load: type          = 2
whisper_model_load: mem required  =  215.00 MB (+    6.00 MB per decoder)
whisper_model_load: adding 1607 extra tokens
whisper_model_load: model ctx     =  140.60 MB
whisper_model_load: model size    =  140.54 MB
whisper_init_state: kv self size  =    5.25 MB
whisper_init_state: kv cross size =   17.58 MB
gpt2_model_load: loading model from 'models/ggml-gpt-2-117M.bin'
gpt2_model_load: n_vocab = 50257
gpt2_model_load: n_ctx   = 1024
gpt2_model_load: n_embd  = 768
gpt2_model_load: n_head  = 12
gpt2_model_load: n_layer = 12
gpt2_model_load: f16     = 1
gpt2_model_load: ggml ctx size = 311.12 MB
gpt2_model_load: memory size =    72.00 MB, n_mem = 12288
gpt2_model_load: model size  =   239.08 MB
gpt-2: model loaded in 217 ms

SDL_main: processing, 4 threads, lang = en, task = transcribe, timestamps = 0 ...

init: found 3 capture devices:
init:    - Capture device #0: 'Microphone Array (Realtek(R) Audio)'
init:    - Capture device #1: 'Microphone (USB Audio Device)'
init:    - Capture device #2: 'Microphone (Webcam 250)'
init: attempt to open default capture device ...
init: obtained spec for input device (SDL Id = 2):
init:     - sample rate:       16000
init:     - format:            33056 (required: 33056)
init:     - channels:          1 (required: 1)
init:     - samples per frame: 1024
gpt-2: prompt:
========================

This is a dialogue between Santa (A) and a person (B). The dialogue so far is:

B: Hello Santa, how are you?
A: I'm fine, thank you.
{1}
Here is how Santa (A) continues the dialogue:

A:
========================

SDL_main: Speech detected! Processing ...
SDL_main: Heard nothing, skipping ...
SDL_main: Speech detected! Processing ...
SDL_main: Heard '←[1mHello?←[0m', (t = 3501 ms)
GGML_ASSERT: \whisper.cpp\ggml.c:3904: !ggml_is_transposed(a)

**Comment by includedhj** [comment]
same question

**Comment by ggerganov** [comment]
Should be fixed now
