### ISSUE TITLE
Is it possible to integrate in macOS app?

### ISSUE THREAD

**Issue by pradeepb28** [ggerganov/whisper.cpp#662]
Hello, is it possible to integrate in macOS app? I couldn't find steps how to integrate whisper so I am asking here. Thank you.

**Comment by vricosti** [comment]
there is already a MacOS fork written in Swift: https://github.com/vade/OpenAI-Whisper-CoreML

**Comment by ggerganov** [comment]
- https://github.com/ggerganov/whisper.cpp/tree/master/examples/whisper.swiftui
- https://github.com/ggerganov/whisper.cpp/tree/master/examples/whisper.objc

**Comment by jacobjiangwei** [comment]
@ggerganov  could you let me know how to integrate the whisper.cpp into the swiftui xcode project? I tried to drag whole whisper.cpp folder, or package.swift, or even add it as a module, none of it works like the demo UI app.

How did you add the dependency there?

**Comment by thehwang** [comment]
I built something exactly for this use case using whisper.cpp + SFSpeechRecognizer — open source: github.com/thehwang/Scripta. Might be relevant to your discussion.
