### ISSUE TITLE
android build failed after recent commit ：/ggml.c:816:28: error: initializing 'const int8x8_t' (vector of 8 'int8_t' values) with an expression of incompatible type 'int'

### ISSUE THREAD

**Issue by vfishv** [ggerganov/whisper.cpp#666]
android build failed after recent update  

/ggml.c:816:28: error: initializing 'const int8x8_t' (vector of 8 'int8_t' values) with an expression of incompatible type 'int'

 build pass only for arm64-v8a

**Comment by zeitsmatt** [comment]
Is there a clearer explanation for 'build pass only for arm64-v8a'?  I'm still seeing this issue and the comments I'm seeing on the web are to modify the build files.
