### ISSUE TITLE
llama_model_load: invalid model file './models/ggml-small.en.bin' (too old, regenerate your model files!)

### ISSUE THREAD

**Issue by parkerqian** [ggerganov/whisper.cpp#679]
I just download the model of ggml-small.en.bin

and run the command like this 
./talk-llama -mw ./models/for-tests-ggml-small.bin -ml ./models/ggml-small.en.bin -p "Georgi" -t 8
the error message :
llama_model_load: invalid model file './models/ggml-small.en.bin' (too old, regenerate your model files!)
![11](https://user-images.githubusercontent.com/4987818/228263999-68ecd1e5-0148-49d4-9e97-5d65279bb520.png)

**Comment by danielcbit** [comment]
I believe you are using the incorrect model files. You need to follow the steps from this other project https://github.com/ggerganov/llama.cpp and apply to the LLAMA model downloaded(https://github.com/facebookresearch/llama/pull/73/files) from Facebook.

It also took me a while to figure out what needed to be done and some trial and error.
