### ISSUE TITLE
need assisstance for deploying the TTS in the speak.sh 

### ISSUE THREAD

**Issue by shiyuasuka** [ggerganov/whisper.cpp#683]
# Eleven Labs
#
#wd=$(dirname $0)
#script=$wd/eleven-labs.py
#python3 $script $1 "$2" >/dev/null 2>&1
#ffplay -autoexit -nodisp -loglevel quiet -hide_banner -i ./audio.mp3 >/dev/null 2>&1 

I uncomment this part of code and it did not use the TTS voice

**Comment by DGdev91** [comment]
That's just an example, there wasn't really a eleven-labs.py file.
I made one, see pull request #728 

To use the Eleven Labs TTS you have to register to beta.elevenlabs.io and get an api key, then install the elevenlabs unofficial pip package and paste your apy key in my eleven-labs.py script in examples/talk/eleven-labs.py (i put the same script also in examples/talk-llama/eleven-labs.py but it seems to pick "talk" folder anyway)
