### ISSUE TITLE
Compilation error: 'common.h' file not found when building talk-llama example

### ISSUE THREAD

**Issue by gaceladri** [ggerganov/whisper.cpp#703]
Hello,

I'm trying to compile the `talk-llama` example, but I'm encountering an error related to the `common.h` header file not being found. Here is the output I get when running `make talk-llama`:

```
cd examples/talk-llama
make talk-llama
c++ talk-llama.cpp -o talk-llama
talk-llama.cpp:4:10: fatal error: 'common.h' file not found
#include "common.h"
^~~~~~~~~~
1 error generated.
make: *** [talk-llama] Error 1
```

I understand that `common.h` is located in the parent folder, but it seems that the Makefile or the example code does not handle the include path correctly. Could you please provide guidance on how to properly compile the `talk-llama` example with the correct include paths, or update the example/Makefile to fix the issue?

Thank you!

**Comment by horacex** [comment]
try go back to the folder of whisper.cpp to run
`make talk-llama`
