### ISSUE TITLE
Backport the performance improvement from llama.cpp

### ISSUE THREAD

**Issue by kovaacs** [ggerganov/whisper.cpp#709]
It would be very cool if the performance improvements from https://github.com/ggerganov/llama.cpp/pull/613 could be backported to this repo.

I couldn't find an issue for this, if there is one, I'm happy to close this.

**Comment by edwios** [comment]
Related. https://github.com/ggerganov/whisper.cpp/issues/702

**Comment by ggerganov** [comment]
Just updated `ggml` and the performance should be much better.
I observe > x2 overall improvement on Apple Silicon

No need to generate new models - everything should just work
