### ISSUE TITLE
Non-Deterministic output

### ISSUE THREAD

**Issue by SMUsamaShah** [ggerganov/whisper.cpp#734]
I realized that every single run on an audio can give a different result. Sometimes it get's some words wrong, sometimes other words wrong. I thought adding `initial prompt` via `--prompt` would fix the all the wrong words. Initial prompt does influence the style of output and effect some words but again this behaviour is non-deterministic. 

e.g. in one run it didn't even transcribe a large chunk of audio which had some inaudible part while in another run it correctly tagged that part as inaudible and completed the rest.

Is there a way to make it get the random seed on each run and re-use it? If we can provide a seed, it should help fine tuning the output by modifying just the initial prompt (similar to Stable Diffusion).

**Comment by misutoneko** [comment]
The original Whisper has this note:
"Setting temperature to 0 will make the outputs mostly deterministic, but a small amount of variability may remain."

So...force t_cur to zero? Looks like there's no command line switch for this.

**Comment by ggerganov** [comment]
You can use the `--no-fallback` option to effectively set `t_cur` to 0 and disable the non-deterministic fallbacks
