### ISSUE TITLE
[Feature Request]Support  openai/whisper "--initial_prompt" flag

### ISSUE THREAD

**Issue by yujinqiu** [ggerganov/whisper.cpp#74]
Hi, 
From this [disscussion](https://github.com/openai/whisper/discussions/277#discussioncomment-3832154), we know that openai/whisper support `--initial_prompt` to support  zh-Hans and zh-Hant.  
I think it will be better if whisper.cpp can also support this feature.

**Comment by ggerganov** [comment]
Closing this in favor of #90
