### ISSUE TITLE
the ggml conversion script is broken

### ISSUE THREAD

**Issue by llimllib** [ggerganov/whisper.cpp#741]
In https://github.com/openai/whisper/pull/1044/, whisper removed `vocab.json` which the [conversion script relies on](https://github.com/ggerganov/whisper.cpp/blob/0a2d1210bcb98978214bbf4e100922a413afd39d/models/convert-pt-to-ggml.py#L237).

Reverting the whisper repository back to `ad3250a` with `git switch --detach ad3250a` seems to fix the issue.

**Comment by ivan-gorin** [comment]
I've created a merge request #725  that fixes this issue (and my issue #724 which is the same )

**Comment by llimllib** [comment]
Ah, thanks!
