### ISSUE TITLE
Any way to convert all codes to java language

### ISSUE THREAD

**Issue by michoael** [ggerganov/whisper.cpp#743]
I don't use c/c++
I want use java only with libraries without any another languages.

How i can do this?

**Comment by franalbani** [comment]
What do you mean by "convert all codes to java"?

Literally taken, that is a huge task for a human to do and I'm not aware of any automatic way to do it. Even if possible, it most likely be to slow to be useful.

A reasonable approach would be to write a Java binding (maybe somebody is already making it).

Another to call `whisper.cpp` as an external process.

**Comment by ggerganov** [comment]
I don't think Java can be easily supported.
Your best chance is using the C-style API

**Comment by michoael** [comment]
I know it's not easy but i think not impossible

I want change to jave to use on android devices

I know i can use cpp on android, but i can't understand how edit it create my i want

**Comment by franalbani** [comment]
The question of "converting" C++ to Java is too generic and unrelated to this project. You may have more luck in a Java community.

**Comment by michoael** [comment]
Okay, but i want add whisper in my project android

What exactly i need add from this project to my project

I know how add cpp side by side with java on android studio

But what exactly need add on it

I use vosk before this time to now

I can created with vosk
Listening on Real time from mic or internal device
Listing from file real time and save to srt file 

But vosk have only 20 languages, can't listen with music, and not have translation. 

So i need change to whisper 

I want know what coding should be get, i important only to android 

I read something to use it but i can't understand all words 

I think 
Whisper.h it's header, so important to add on my project, and folder jna on android example 

What i need more, i hope help me to add it on my project
