### ISSUE TITLE
Error building android project from examples

### ISSUE THREAD

**Issue by ashwin696** [ggerganov/whisper.cpp#765]
I'm new to android and I tried the android examples and build the project but getting error:
Details:
OS - Ubuntu 20.04
Android studio - v2022.2.1.18
let me know if need any other details. Thanks

> Task :app:buildNdkBuildRelease[arm64-v8a]
C/C++: /home/jordan/git_repos/whisper.cpp/examples/whisper.android/app/src/main/jni/whisper/../../../../../../..//ggml.c:3067:75: warning: implicitly declaring library function 'aligned_alloc' with type 'void *(unsigned long, unsigned long)' [-Wimplicit-function-declaration]
C/C++:         /*.mem_buffer         =*/ params.mem_buffer ? params.mem_buffer : GGML_ALIGNED_MALLOC(mem_size),
C/C++:                                                                           ^
C/C++: /home/jordan/git_repos/whisper.cpp/examples/whisper.android/app/src/main/jni/whisper/../../../../../../..//ggml.c:121:36: note: expanded from macro 'GGML_ALIGNED_MALLOC'
C/C++: #define GGML_ALIGNED_MALLOC(size)  aligned_alloc(GGML_MEM_ALIGN, size)
C/C++:                                    ^
C/C++: /home/jordan/git_repos/whisper.cpp/examples/whisper.android/app/src/main/jni/whisper/../../../../../../..//ggml.c:3067:75: note: include the header <stdlib.h> or explicitly provide a declaration for 'aligned_alloc'
C/C++: /home/jordan/git_repos/whisper.cpp/examples/whisper.android/app/src/main/jni/whisper/../../../../../../..//ggml.c:121:36: note: expanded from macro 'GGML_ALIGNED_MALLOC'
C/C++: #define GGML_ALIGNED_MALLOC(size)  aligned_alloc(GGML_MEM_ALIGN, size)
C/C++:                                    ^
C/C++: 1 warning generated.
C/C++: /home/jordan/git_repos/whisper.cpp/examples/whisper.android/app/src/main/jni/whisper/jni.c:235:1: warning: non-void function does not return a value [-Wreturn-type]
C/C++: }
C/C++: ^
C/C++: /home/jordan/git_repos/whisper.cpp/examples/whisper.android/app/src/main/jni/whisper/jni.c:243:1: warning: non-void function does not return a value [-Wreturn-type]
C/C++: }
C/C++: ^
C/C++: 2 warnings generated.
C/C++: ld: error: undefined symbol: aligned_alloc
C/C++: >>> referenced by ggml.c:3067 (src/main/jni/whisper/../../../../../../../ggml.c:3067)
C/C++: >>>               /home/jordan/git_repos/whisper.cpp/examples/whisper.android/app/build/intermediates/cxx/Release/642o6s5e/obj/local/arm64-v8a/objs/whisper//home/jordan/git_repos/whisper.cpp/examples/whisper.android/app/src/main/jni/whisper/__/__/__/__/__/__/__//ggml.o:(ggml_init)
C/C++: clang++: error: linker command failed with exit code 1 (use -v to see invocation)
C/C++: make: *** [/home/jordan/Android/Sdk/ndk/25.1.8937393/build/core/build-binary.mk:657: /home/jordan/git_repos/whisper.cpp/examples/whisper.android/app/build/intermediates/cxx/Release/642o6s5e/obj/local/arm64-v8a/libwhisper.so] Error 1

> Task :app:buildNdkBuildRelease[arm64-v8a] FAILED
ld: error: undefined symbol: aligned_alloc
>>> referenced by ggml.c:3067 (src/main/jni/whisper/../../../../../../../ggml.c:3067)
>>>               /home/jordan/git_repos/whisper.cpp/examples/whisper.android/app/build/intermediates/cxx/Release/642o6s5e/obj/local/arm64-v8a/objs/whisper//home/jordan/git_repos/whisper.cpp/examples/whisper.android/app/src/main/jni/whisper/__/__/__/__/__/__/__//ggml.o:(ggml_init)

**Comment by lsCoding666** [comment]
minsdk version>=28

**Comment by ashwin696** [comment]
> minsdk version>=28
Thank you. That worked
