### ISSUE TITLE
Core ML model does not seem to be working in iOS app

### ISSUE THREAD

**Issue by ahsanzia341** [ggerganov/whisper.cpp#778]
I was able to integrate the coreml model in the app and the log says, "Core ML Model Loaded" (please see the attached screenshot for reference) but when I am running the transcription using the function whisper_full, I am not seeing any difference in speed as I am seeing on my terminal. I have transcribed for a 40 secs audio. Below are the runs I gave for the transcriptions.
<img width="798" alt="Screenshot 2023-04-17 at 12 56 45 AM" src="https://user-images.githubusercontent.com/26021017/232435173-fe70f41d-1e2b-4853-bfe4-5c056c7f2f8e.png">
<img width="806" alt="Screenshot 2023-04-17 at 12 56 33 AM" src="https://user-images.githubusercontent.com/26021017/232435188-e3031266-cf57-4564-aac3-c10ce7aa7024.png">

This screenshot is when the Core ML Model got loaded.
<img width="803" alt="Screenshot 2023-04-17 at 12 56 24 AM" src="https://user-images.githubusercontent.com/26021017/232435182-48f6f255-c61e-4bfb-b57b-fa922bdf804d.png">

Any help would be appreciated.

**Comment by ggerganov** [comment]
How much is the `encode time, ms per run` without `WHISPER_COREML`?
Check only the first run, as in this screenshot:

![image](https://user-images.githubusercontent.com/1991296/232439326-f477bca1-40b6-4a8b-aba7-9751d057fd2a.png)

**Comment by ahsanzia341** [comment]
Here are the details without coreml.
<img width="880" alt="Screenshot 2023-04-17 at 2 26 12 PM" src="https://user-images.githubusercontent.com/26021017/232443286-4b0ed5c0-07f0-4364-a5dc-643715f53fd3.png">

**Comment by ahsanzia341** [comment]
Ok I just checked the difference in speed is there. It is taking 160 secs to encode this audio without coreml in the app. Actually, when I ran the same audio in the terminal, the difference is far greater. Here are the results.

First run:
<img width="576" alt="Screenshot 2023-04-17 at 2 33 10 PM" src="https://user-images.githubusercontent.com/26021017/232445130-99aa583d-6307-45b0-a504-2d6556d9c895.png">

Second run:
<img width="571" alt="Screenshot 2023-04-17 at 2 33 01 PM" src="https://user-images.githubusercontent.com/26021017/232445265-ba446dca-e6aa-46dd-b85b-42f76c2f898e.png">

**Comment by yousifa** [comment]
How did you enable coreml? Is it a build flag?

**Comment by ahsanzia341** [comment]
> How did you enable coreml? Is it a build flag?

Yes, I had to add it in the .h file to get it working in the iOS app.

**Comment by yousifa** [comment]
> > How did you enable coreml? Is it a build flag?
> 
> Yes, I had to add it in the .h file to get it working in the iOS app.

Yep, figured it out. Have to include the files under /coreml in the app as well!

**Comment by andforce** [comment]
@ahsanzia341 
Hi, could you show some code that how used CorlML on iOS?
thanks very munch~
