### ISSUE TITLE
Generated subtitle rewinds repeatedly to 00:00:00.000 timestamp

### ISSUE THREAD

**Issue by patarapolw** [ggerganov/whisper.cpp#79]
Also, only VTT output is correctly produced. SRT is broken and looks just like TXT. Perhaps TXT isn't broken, though.

![generated VTT](https://user-images.githubusercontent.com/21255931/197386433-d05d213e-2f21-411d-b855-eb2b299e53cb.png)

![MPC player](https://user-images.githubusercontent.com/21255931/197386452-146cf887-392c-4e10-a67d-7b3f7465e49b.png)

It's on WSL2 (Ubuntu) on Windows 11.

```bash
#!/usr/bin/env bash
 
workdir=$HOME/Projects/whisper.cpp
$workdir/main -l ja -m $workdir/models/ggml-medium.bin -otxt -ovtt -osrt $@
```

**Comment by ggerganov** [comment]
Thanks for noticing - should be fixed now

**Comment by patarapolw** [comment]
`*.srt` is OK now; as well as timing as far as I have seen.
