### ISSUE TITLE
Can't build stream example on Windows

### ISSUE THREAD

**Issue by dgm3333** [ggerganov/whisper.cpp#792]
This is a follow-on from [Can't build stream example](https://github.com/ggerganov/whisper.cpp/issues/696) which was unfortunately closed a couple of days before I noticed it.

I also can't figure out how to build stream - Although I'm not sure if this is an SDL issue or whisper.cpp?
I'm attempting to build on win10 with AMDx64 chipset.
I don't think it's relevant to the current issue but the whisper cmake output is stating "-- x86 detected" as below.
The detailed steps I've tried are as below:-

I have cloned SDL from here: https://github.com/libsdl-org/SDL
By default this uses the main branch. I built this using:
`mkdir build && cd build && cmake .. && cmake --build . --config Release`

This builds SDL3. Tried again after setting the git branch to SDL2. ran:-
`cmake .. && cmake --build . --config Release`

This appears to build SDL2 correctly:-

SDL2.vcxproj -> C:\Users\dgm55\source\repos\SDL\build\Release\SDL2.dll
SDL2-static.vcxproj -> C:\Users\dgm55\source\repos\SDL\build\Release\SDL2-static.lib
SDL2_test.vcxproj -> C:\Users\dgm55\source\repos\SDL\build\Release\SDL2_test.lib
SDL2main.vcxproj -> C:\Users\dgm55\source\repos\SDL\build\Release\SDL2main.lib

Then from the whisper.cpp dir tried
`mkdir build && cd build && cmake -DWHISPER_BUILD_EXAMPLES=1 -DWHISPER_SUPPORT_SDL2=1 ..`
This failed to find SDL so I tried:
`cmake -DWHISPER_BUILD_EXAMPLES=1 -DWHISPER_SUPPORT_SDL2=1 -DCMAKE_PREFIX_PATH=C:\Users\dgm55\source\repos\SDL\cmake -DCMAKE_PREFIX_PATH=C:\Users\dgm55\source\repos\SDL\build ..`

This progressed a bit more, but failed to find sdlfind.cmake (see BUILDERROR1 below) so I manually copied this from sdl/cmake/sdlfind.cmake to the sdl/build directory
This progresses further, but still fails to build (see BUILDERROR2 below)
At this point I'm stuck...

BUILDERROR1

`cmake  -DWHISPER_BUILD_EXAMPLES=1 -DWHISPER_SUPPORT_SDL2=1 ..`
-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.19043.
CMake Warning (dev) at CMakeLists.txt:5 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- CMAKE_SYSTEM_PROCESSOR: AMD64
-- x86 detected
CMake Error at C:/Users/dgm55/source/repos/SDL/build/SDL2Config.cmake:58 (include):
  include could not find requested file:

    C:/Users/dgm55/source/repos/SDL/build/sdlfind.cmake
Call Stack (most recent call first):
  examples/CMakeLists.txt:9 (find_package)

-- SDL2_INCLUDE_DIRS = C:/Users/dgm55/source/repos/SDL/include;C:/Users/dgm55/source/repos/SDL/include/SDL2
-- SDL2_LIBRARIES = SDL2::SDL2
-- Configuring incomplete, errors occurred!

BUILDERROR2

cmake ..
-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.19043.
CMake Warning (dev) at CMakeLists.txt:5 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- CMAKE_SYSTEM_PROCESSOR: AMD64
-- x86 detected
-- SDL2_INCLUDE_DIRS = C:/Users/dgm55/source/repos/SDL/include;C:/Users/dgm55/source/repos/SDL/include/SDL2
-- SDL2_LIBRARIES = SDL2::SDL2
-- Configuring done
CMake Error at examples/CMakeLists.txt:43 (target_link_libraries):
  Target "common-sdl" links to:

    SDL2::SDL2

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

CMake Error at examples/talk/CMakeLists.txt:15 (target_link_libraries):
  Target "talk" links to:

    SDL2::SDL2

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

CMake Error at examples/talk-llama/CMakeLists.txt:13 (target_link_libraries):
  Target "talk-llama" links to:

    SDL2::SDL2

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by dgm3333** [comment]
Oh I forgot to say with the basic make command I also get an error - although main and bench compile fine with
`make .`

`C:\repos\whisper.cpp>make stream`
/bin/sh: line 1: cc: command not found
/bin/sh: line 1: head: command not found
/bin/sh: line 1: head: command not found
I whisper.cpp build info:
I UNAME_S:  MSYS_NT-10.0-19043
I UNAME_P:  unknown
I UNAME_M:  x86_64
I CFLAGS:   -I.              -O3 -DNDEBUG -std=c11   -fPIC -mfma -mf16c -mavx -mavx2
I CXXFLAGS: -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC
I LDFLAGS:
I CC:
I CXX:

cc  -I.              -O3 -DNDEBUG -std=c11   -fPIC -mfma -mf16c -mavx -mavx2   -c ggml.c -o ggml.o
make: cc: No such file or directory
make: *** [Makefile:197: ggml.o] Error 127

**Comment by docloulou** [comment]
what was the solution please ?

**Comment by juampe** [comment]
Same problem using CMAKE_PREFIX_PATH and WHISPER_SDL2

```
PS C:\Users\juamp\Develop\whisper.cpp\build> cmake .. -DWHISPER_CUBLAS=1 -DWHISPER_BUILD_EXAMPLES=1 -DWHISPER_SDL2=1 -DSDL2_DIR="C:\Users\juamp\Develop\SDL\build" -DCMAKE_PREFIX_PATH="C:\Users\juamp\Develop\SDL\cmake"
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- cuBLAS found
-- CMAKE_SYSTEM_PROCESSOR: AMD64
-- x86 detected
-- GGML CUDA sources found, configuring CUDA architecture
-- SDL2_INCLUDE_DIRS = C:/Users/juamp/Develop/SDL/include;C:/Users/juamp/Develop/SDL/include/SDL2
-- SDL2_LIBRARIES = SDL2::SDL2
-- Configuring done (3.0s)
CMake Error at examples/CMakeLists.txt:47 (target_link_libraries):
  Target "common-sdl" links to:

    SDL2::SDL2

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.



CMake Error at examples/talk-llama/CMakeLists.txt:13 (target_link_libraries):
  Target "talk-llama" links to:

    SDL2::SDL2

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.



-- Generating done (1.5s)
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**Comment by WorkLearn123** [comment]
> Same problem using CMAKE_PREFIX_PATH and WHISPER_SDL2
> 
> ```
> PS C:\Users\juamp\Develop\whisper.cpp\build> cmake .. -DWHISPER_CUBLAS=1 -DWHISPER_BUILD_EXAMPLES=1 -DWHISPER_SDL2=1 -DSDL2_DIR="C:\Users\juamp\Develop\SDL\build" -DCMAKE_PREFIX_PATH="C:\Users\juamp\Develop\SDL\cmake"
> CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
>   Compatibility with CMake < 3.5 will be removed from a future version of
>   CMake.
> 
>   Update the VERSION argument <min> value or use a ...<max> suffix to tell
>   CMake that the project does not need compatibility with older versions.
> 
> 
> -- cuBLAS found
> -- CMAKE_SYSTEM_PROCESSOR: AMD64
> -- x86 detected
> -- GGML CUDA sources found, configuring CUDA architecture
> -- SDL2_INCLUDE_DIRS = C:/Users/juamp/Develop/SDL/include;C:/Users/juamp/Develop/SDL/include/SDL2
> -- SDL2_LIBRARIES = SDL2::SDL2
> -- Configuring done (3.0s)
> CMake Error at examples/CMakeLists.txt:47 (target_link_libraries):
>   Target "common-sdl" links to:
> 
>     SDL2::SDL2
> 
>   but the target was not found.  Possible reasons include:
> 
>     * There is a typo in the target name.
>     * A find_package call is missing for an IMPORTED target.
>     * An ALIAS target is missing.
> 
> 
> 
> CMake Error at examples/talk-llama/CMakeLists.txt:13 (target_link_libraries):
>   Target "talk-llama" links to:
> 
>     SDL2::SDL2
> 
>   but the target was not found.  Possible reasons include:
> 
>     * There is a typo in the target name.
>     * A find_package call is missing for an IMPORTED target.
>     * An ALIAS target is missing.
> 
> 
> 
> -- Generating done (1.5s)
> CMake Generate step failed.  Build files cannot be regenerated correctly.
> ```

**How to solve this problem? I hope to know it.**

**Comment by nigue3025** [comment]
> Solved I build SDL2 an installed in C:/Program Files/SDL2/, sure you can download a precompiled package
> 
> ```
> PS C:\Users\juamp\Develop\SDL\build> cmake --build c:/Users/juamp/Develop/SDL/build --config Release --target install -j 14 --
> ```
> 
> Then configure again wiht the new path
> 
> ```
> PS C:\Users\juamp\Develop\whisper.cpp\build> cmake .. -DWHISPER_CUBLAS=1 -DWHISPER_BUILD_EXAMPLES=1 -DWHISPER_SDL2=1 -DSDL2_DIR="C:/Program Files/SDL2" -DCMAKE_PREFIX_PATH=" C:/Program Files/SDL2/cmake"               
> CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
>   Compatibility with CMake < 3.5 will be removed from a future version of
>   CMake.
> 
>   Update the VERSION argument <min> value or use a ...<max> suffix to tell
>   CMake that the project does not need compatibility with older versions.
> 
> 
> -- cuBLAS found
> -- CMAKE_SYSTEM_PROCESSOR: AMD64
> -- x86 detected
> -- GGML CUDA sources found, configuring CUDA architecture
> -- SDL2_INCLUDE_DIRS = C:/Program Files/SDL2/include;C:/Program Files/SDL2/include/SDL2
> -- SDL2_LIBRARIES = SDL2::SDL2main;SDL2::SDL2
> -- Configuring done (1.8s)
> -- Generating done (0.6s)
> -- Build files have been written to: C:/Users/juamp/Develop/whisper.cpp/build
> PS C:\Users\juamp\Develop\whisper.cpp\build> 
> ```

Cool! Same problem also solved by this solution!
