### ISSUE TITLE
Start Android with some problem.

### ISSUE THREAD

**Issue by lightwind** [ggerganov/whisper.cpp#796]
Start the android project, follow the documentation steps, but compiling the project encounters the following problem:
![image](https://user-images.githubusercontent.com/25144040/232951600-550f8457-66fc-4b41-920e-60f1537c578a.png)

**Comment by Zolliner** [comment]
I encountered the same problem, how did you solve it?

**Comment by Zolliner** [comment]
解决了，原来不能把安卓项目文件夹移到其他目录，因为需要用到whisper.cpp项目里的一些文件
