### ISSUE TITLE
Increasing memory usage over time with CoreML

### ISSUE THREAD

**Issue by neurostar** [ggerganov/whisper.cpp#797]
There is an increasing memory usage with CoreML, not with CPU version.
Tested with multiple audio samples and model size in M2 Air.
for medium size model, starting 2.44 GB after ~40min audio transcription 3.3GB with CoreML.
There was no significant change in compiled main for CPU.

**Comment by ggerganov** [comment]
This is not expected - can anyone else confirm this?

**Comment by neurostar** [comment]
<img width="731" alt="ml_mem" src="https://user-images.githubusercontent.com/55060/236697023-a1be67e0-1db6-40a8-9c49-ae2ed02bf1a7.png">

I'm not sure that why there is no additional reports about it.
To double check, using current master, re-compile freshly re-generate ml encoder.
With a 52 min sample audio file, measure memory usage every minutes using top.
There is clear trend of increasing memory usage over time with CoreML

**Comment by ggerganov** [comment]
@neurostar 

I think this buffer here is the problem:

https://github.com/ggerganov/whisper.cpp/blob/14bee39b290f81381a259c53a169ffac8fcce987/coreml/whisper-encoder.mm#L43-L50

It is never deallocated. My Objective-C is rudimentary, so I am no 100% sure if this works, but can you give it a try:

https://github.com/ggerganov/whisper.cpp/commit/b671ee0f2a16fee1a3fb4dec6cb3f20203f5f41c

Checkout the `fix-coreml-leak` branch and run the same test.

**Comment by neurostar** [comment]
@ggerganov 

Thank you so much for quick fix.
I had to comment out [outCoreML release]; since I got segfault.
With just two lines ( [outMA release];  [inMultiArray release];) , It fixed memory leak. 
There is no change in memory usage with CoreML.

**Comment by ggerganov** [comment]
Should be fixed now on `master` via #899
