### ISSUE TITLE
Runtime CoreML switch

### ISSUE THREAD

**Issue by dennislysenko** [ggerganov/whisper.cpp#803]
Currently, CoreML is enabled/disabled based on a compile time switch, meaning it can't be configured at whisper-init-time.

I'm working with someone on an application where we may need an option to toggle CoreML at whisper-init-time.

It seems straightforward enough to implement, we can do it on a fork, but we can make this as a PR here so that others can benefit from it, if needed. Would have the benefit of making it easier to maintain our side with future changes from upstream as well. @ggerganov - thoughts?

**Comment by Canis-UK** [comment]
I implemented part of this in PR #812 which allows a Core ML build to transcribe with or without the Core ML model, falling back to the regular one if it's unavailable — you'd just need to add a flag to skip loading the Core ML model in `whisper_init_state()`.

**Comment by ggerganov** [comment]
Yes, I will add this option for the next release in a few days. Not sure if I will use the proposal in #812 - might do some extra refactoring of the encode functions. Will see
