### ISSUE TITLE
whisper.swift can not get transcription

### ISSUE THREAD

**Issue by illusion77** [ggerganov/whisper.cpp#819]
It did not display transcription after the 'Done'

<img width="1343" alt="image" src="https://user-images.githubusercontent.com/43769288/233865298-aecc96e1-b0fd-4120-a54f-8153f8c9ed7f.png">

And this is console print

<img width="1224" alt="image" src="https://user-images.githubusercontent.com/43769288/233865724-17c268e8-8732-4950-893a-092d4814fb05.png">

As you can see there is no transcription was printed after the 'About to run whisper_full'

I can only know the getTranscription() already return empty transcription
```swift
func getTranscription() -> String {
    var transcription = ""
    for i in 0..<whisper_full_n_segments(context) {
        transcription += String.init(cString: whisper_full_get_segment_text(context, i))
    }
    return transcription
}
```

Anybody knows this error? I didn't even change any code.

**Comment by sorgfresser** [comment]
Silly me but I'm experiencing a somewhat similar issue. To be more precise `whisper_full_n_segments` is 0 in a case where it shouldn't be. How did you fix it?

**Comment by sorgfresser** [comment]
Thanks a lot!

**Comment by illusion77** [comment]
> Thanks a lot!

Can you run it normally now? My speed is very slow, and the result are all '[SOUND] [SOUND] ...'
I don't know why, if you know how to solve this, could we discuss it?

**Comment by includedhj** [comment]
use release

**Comment by illusion77** [comment]
> use release

Yes, I knew that it appears [SOUND] [SOUND]... because the metadata of wav file is wrong, it has to be mono 16k, and slow speed due to I didn't use release mode, thank for your reply
