### ISSUE TITLE
bark.cpp

### ISSUE THREAD

**Issue by jmtatsch** [ggerganov/whisper.cpp#823]
This new bark model looks quite promising https://github.com/suno-ai/bark
@ggerganov Any chance you will make a bark.cpp? 
Then speech recognition, text generation and text-to-speech would be democratized 😍

**Comment by noe** [comment]
This is already under discussion at https://github.com/ggerganov/ggml/issues/59

**Comment by maxbrito500** [comment]
Great. I was going to propose the same thing. It would be a perfect match.

**Comment by Zibri** [comment]
UP!  I agree.. bark.cpp is needed!

**Comment by jmtatsch** [comment]
bark.cpp is there https://github.com/PABannier/bark.cpp
