### ISSUE TITLE
Yet another attempt to fix endless transcribe loop from OpenAI

### ISSUE THREAD

**Issue by clyang** [ggerganov/whisper.cpp#831]
Just notice that OpenAI has merged a fix that might reduce endless transcribe loop issue. Really hope Whisper.cpp can apply the same fix in the near future. Thank you.

references:
https://github.com/openai/whisper/commit/b0022b3283232b2b9f19262360cd80ec9975aeb4
https://github.com/openai/whisper/commit/c09a7ae299c4c34c5839a76380ae407e7d785914

**Comment by ggerganov** [comment]
I believe we've had this logic in `whisper.cpp` for a while now:

https://github.com/ggerganov/whisper.cpp/blob/c23588cc4b2c4be4ba3634a21c7f2b302c5f370e/whisper.cpp#L3514-L3524
