### ISSUE TITLE
Add benchmark tool

### ISSUE THREAD

**Issue by ggerganov** [ggerganov/whisper.cpp#84]
We need a more deterministic way to benchmark the performance, so I'm thinking about adding a tool that runs just the Encoder part of the transformer on random noise input. This has the advantage that one does not require any audio data to run and the number of operations is fixed (as opposed to when running the Decoder).

**Comment by ArtyomZemlyak** [comment]
Very good idea for testing performance directly of speed up only computation part. 

But in some cases steel need check overal model performance - if quality of model somehow dropped, then its can run slowly (bc decoder trying get good answer). But it depends on decoder type, parameters of decoder... 

Therefore good idea!
