### ISSUE TITLE
wav file must be 16 kHz

### ISSUE THREAD

**Issue by tbswork1** [ggerganov/whisper.cpp#847]
Tested with some wav files and got error like

```
read_wav: WAV file '../msg.wav' must be 16 kHz
```

**Comment by ggerganov** [comment]
Yes, you need to convert your audio files to to 16 kHz WAV

**Comment by tbswork1** [comment]
@ggerganov 
Is it a limitation of the original Whisper project? Also, is WAV the only supported format, e.g. mp3 not supported?

**Comment by ggerganov** [comment]
This C++ implementation support only WAV format to avoid any 3rd party dependencies.
Whisper runs with raw PCM audio. The user of the library is responsible to convert the audio to PCM and pass it to Whisper.
