### ISSUE TITLE
Issue with make stream and CUDA

### ISSUE THREAD

**Issue by 06opoTeHb** [ggerganov/whisper.cpp#850]
Successfully build with:
sudo apt-get install libsdl2-dev
make clean
WHISPER_CUBLAS=1 make -j
than
tried to build stream, but got error:

whisper.cpp$ make stream
I whisper.cpp build info: 
I UNAME_S:  Linux
I UNAME_P:  x86_64
I UNAME_M:  x86_64
I CFLAGS:   -I.              -O3 -DNDEBUG -std=c11   -fPIC -pthread -mf16c -mavx -msse3
I CXXFLAGS: -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -pthread
I LDFLAGS:  
I CC:       cc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
I CXX:      g++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0

g++ -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -pthread examples/stream/stream.cpp examples/common.cpp examples/common-ggml.cpp examples/common-sdl.cpp ggml.o whisper.o -o stream `sdl2-config --cflags --libs` 
/usr/bin/ld: ggml.o: in function `ggml_compute_forward_mul_mat_q_f32':
ggml.c:(.text+0x2c65): undefined reference to `ggml_cuda_pool_malloc'
/usr/bin/ld: ggml.c:(.text+0x2c85): undefined reference to `ggml_cuda_pool_malloc'
/usr/bin/ld: ggml.c:(.text+0x2cb1): undefined reference to `ggml_cuda_pool_malloc'
/usr/bin/ld: ggml.c:(.text+0x2cdb): undefined reference to `ggml_cuda_pool_malloc'
/usr/bin/ld: ggml.c:(.text+0x2ce5): undefined reference to `ggml_get_dequantize_row_q_cuda'
/usr/bin/ld: ggml.c:(.text+0x2d63): undefined reference to `g_cudaStream2'
/usr/bin/ld: ggml.c:(.text+0x2d93): undefined reference to `ggml_cuda_h2d_tensor_2d'
/usr/bin/ld: ggml.c:(.text+0x2db5): undefined reference to `cudaGetLastError'
/usr/bin/ld: ggml.c:(.text+0x2dc4): undefined reference to `g_cudaEvent'
/usr/bin/ld: ggml.c:(.text+0x2dcf): undefined reference to `cudaEventRecord'
/usr/bin/ld: ggml.c:(.text+0x2dee): undefined reference to `g_cudaStream'
/usr/bin/ld: ggml.c:(.text+0x2df6): undefined reference to `ggml_cuda_h2d_tensor_2d'
/usr/bin/ld: ggml.c:(.text+0x2e05): undefined reference to `g_cudaEvent'
/usr/bin/ld: ggml.c:(.text+0x2e11): undefined reference to `g_cudaStream'
/usr/bin/ld: ggml.c:(.text+0x2e19): undefined reference to `cudaStreamWaitEvent'
/usr/bin/ld: ggml.c:(.text+0x2e5c): undefined reference to `g_cublasH'
/usr/bin/ld: ggml.c:(.text+0x2e73): undefined reference to `cublasSgemm_v2'
/usr/bin/ld: ggml.c:(.text+0x2e96): undefined reference to `g_cudaStream'
/usr/bin/ld: ggml.c:(.text+0x2e9e): undefined reference to `cudaMemcpyAsync'
/usr/bin/ld: ggml.c:(.text+0x2ee8): undefined reference to `g_cudaStream'
/usr/bin/ld: ggml.c:(.text+0x2ef0): undefined reference to `cudaStreamSynchronize'
/usr/bin/ld: ggml.c:(.text+0x2f08): undefined reference to `ggml_cuda_pool_free'
/usr/bin/ld: ggml.c:(.text+0x2f1a): undefined reference to `ggml_cuda_pool_free'
/usr/bin/ld: ggml.c:(.text+0x2f2a): undefined reference to `ggml_cuda_pool_free'
/usr/bin/ld: ggml.c:(.text+0x2f3a): undefined reference to `ggml_cuda_pool_free'
/usr/bin/ld: ggml.c:(.text+0x2f7c): undefined reference to `cudaGetErrorString'
/usr/bin/ld: ggml.c:(.text+0x309e): undefined reference to `cudaGetErrorString'
/usr/bin/ld: ggml.c:(.text+0x30f8): undefined reference to `cudaGetErrorString'
/usr/bin/ld: ggml.c:(.text+0x311c): undefined reference to `cudaGetErrorString'
/usr/bin/ld: ggml.c:(.text+0x3141): undefined reference to `cudaGetErrorString'
/usr/bin/ld: ggml.o:ggml.c:(.text+0x3166): more undefined references to `cudaGetErrorString' follow
/usr/bin/ld: ggml.o: in function `ggml_compute_forward_mul_mat_f16_f32':
ggml.c:(.text+0x59a0): undefined reference to `ggml_cuda_pool_malloc'
/usr/bin/ld: ggml.c:(.text+0x59bf): undefined reference to `ggml_cuda_pool_malloc'
/usr/bin/ld: ggml.c:(.text+0x59e2): undefined reference to `ggml_cuda_pool_malloc'
/usr/bin/ld: ggml.c:(.text+0x5a46): undefined reference to `g_cudaStream'
/usr/bin/ld: ggml.c:(.text+0x5b0d): undefined reference to `ggml_cuda_h2d_tensor_2d'
/usr/bin/ld: ggml.c:(.text+0x5bc3): undefined reference to `cudaMemcpyAsync'
/usr/bin/ld: ggml.c:(.text+0x5c13): undefined reference to `g_cublasH'
/usr/bin/ld: ggml.c:(.text+0x5c1b): undefined reference to `cublasGemmEx'
/usr/bin/ld: ggml.c:(.text+0x5c46): undefined reference to `cudaMemcpyAsync'
/usr/bin/ld: ggml.c:(.text+0x5cdb): undefined reference to `cudaStreamSynchronize'
/usr/bin/ld: ggml.c:(.text+0x5cf3): undefined reference to `ggml_cuda_pool_free'
/usr/bin/ld: ggml.c:(.text+0x5d00): undefined reference to `ggml_cuda_pool_free'
/usr/bin/ld: ggml.c:(.text+0x5d0d): undefined reference to `ggml_cuda_pool_free'
/usr/bin/ld: ggml.c:(.text+0x5e26): undefined reference to `cudaGetErrorString'
/usr/bin/ld: ggml.c:(.text+0x5e69): undefined reference to `cudaGetErrorString'
/usr/bin/ld: ggml.c:(.text+0x5e8b): undefined reference to `g_cudaStream'
/usr/bin/ld: ggml.c:(.text+0x5e9e): undefined reference to `cudaGetErrorString'
/usr/bin/ld: ggml.c:(.text+0x5ef5): undefined reference to `cudaGetErrorString'
/usr/bin/ld: ggml.o: in function `ggml_init':
ggml.c:(.text+0xce5a): undefined reference to `ggml_init_cublas'
/usr/bin/ld: ggml.o: in function `ggml_compute_forward':
ggml.c:(.text+0x10fb1): undefined reference to `ggml_cuda_pool_malloc'
/usr/bin/ld: ggml.c:(.text+0x10fd6): undefined reference to `ggml_cuda_pool_malloc'
/usr/bin/ld: ggml.c:(.text+0x10ffd): undefined reference to `ggml_cuda_pool_malloc'
/usr/bin/ld: ggml.c:(.text+0x1102d): undefined reference to `g_cudaStream'
/usr/bin/ld: ggml.c:(.text+0x110a6): undefined reference to `ggml_cuda_h2d_tensor_2d'
/usr/bin/ld: ggml.c:(.text+0x110c7): undefined reference to `ggml_cuda_h2d_tensor_2d'
/usr/bin/ld: ggml.c:(.text+0x11116): undefined reference to `g_cublasH'
/usr/bin/ld: ggml.c:(.text+0x1111e): undefined reference to `cublasSgemm_v2'
/usr/bin/ld: ggml.c:(.text+0x1114f): undefined reference to `cudaMemcpyAsync'
/usr/bin/ld: ggml.c:(.text+0x1119b): undefined reference to `cudaStreamSynchronize'
/usr/bin/ld: ggml.c:(.text+0x111b6): undefined reference to `ggml_cuda_pool_free'
/usr/bin/ld: ggml.c:(.text+0x111c6): undefined reference to `ggml_cuda_pool_free'
/usr/bin/ld: ggml.c:(.text+0x111d6): undefined reference to `ggml_cuda_pool_free'
/usr/bin/ld: ggml.c:(.text+0x1120a): undefined reference to `cudaGetErrorString'
/usr/bin/ld: ggml.c:(.text+0x11282): undefined reference to `cudaGetErrorString'
/usr/bin/ld: ggml.c:(.text+0x112a1): undefined reference to `cudaGetErrorString'
/usr/bin/ld: ggml.c:(.text+0x112bf): undefined reference to `g_cudaStream'
/usr/bin/ld: ggml.c:(.text+0x112cb): undefined reference to `cudaGetErrorString'
collect2: error: ld returned 1 exit status
make: *** [Makefile:268: stream] Error 1

thanks a lot in advance for help

**Comment by ggerganov** [comment]
Use:

```bash
make clean
WHISPER_CUBLAS=1 make -j stream
```

**Comment by 06opoTeHb** [comment]
Thanks for advice. Worked like a charm.
