### ISSUE TITLE
"failed to load Core ML model"

### ISSUE THREAD

**Issue by cjheath** [ggerganov/whisper.cpp#865]
uname -a:
`Darwin hostname.local 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:58 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6020 arm64`

Xcode Version 14.3 (14E222b)

Whisper.cpp commit 05bef0f0e9bac95df37a866033dd27b6a057effd

Followed the procedure for generating CoreML models, with the base model. Output file is present in models/for-tests-ggml-base.en.bin

Running `./main --language auto -m models/for-tests-ggml-base.en.bin -f -` (with valid WAV file on stdin) ends in the messages:
```
whisper_init_state: loading Core ML model from 'models/for-tests-ggml-base.en-encoder.mlmodelc'
whisper_init_state: first run on a device may take a while ...
whisper_init_state: failed to load Core ML model from 'models/for-tests-ggml-base.en-encoder.mlmodelc'
error: failed to initialize whisper context
```

I've looked into the code a little, but I don't know how the https://github.com/wangchou/callCoreMLFromCpp adapter  works or how to extract a better error code/message from it.

**Comment by cybersandwich** [comment]
Are you intending to use the test base en model? If you followed the steps it should run the base model fine with the coreML. 

If you plan on just using the base model, you dont need to explicitly put the model in the command. You can do: `./main -f <wavfile.wav>`.

**Comment by ggerganov** [comment]
The `models/for-tests-ggml-base.en.bin` file is an empty model used just for tests.
Use `models/ggml-base.en.bin` instead

**Comment by cjheath** [comment]
See https://github.com/ggerganov/whisper.cpp/pull/874
wget failed, so I started to convert the files myself - but some of the steps aren documented.

**Comment by KitaitiMakoto** [comment]
You also need Core ML model:

```
% ls ./models/ | grep mlmodel
ggml-base-encoder.mlmodelc
```

Then specify `base` model (ggml-base.bin):

```
% ./build/bin/whisper-cli -m ./models/ggml-base.bin -f ./samples/jfk.wav
(snip)
whisper_init_state: loading Core ML model from './models/ggml-base-encoder.mlmodelc'
whisper_init_state: first run on a device may take a while ...
whisper_init_state: Core ML model loaded
whisper_init_state: compute buffer (conv)   =    5.62 MB
whisper_init_state: compute buffer (cross)  =   13.88 MB
whisper_init_state: compute buffer (decode) =   97.29 MB

system_info: n_threads = 4 / 8 | WHISPER : COREML = 1 | OPENVINO = 0 | Metal : EMBED_LIBRARY = 1 | CPU : NEON = 1 | ARM_FMA = 1 | FP16_VA = 1 | MATMUL_INT8 = 1 | DOTPROD = 1 | ACCELERATE = 1 | REPACK = 1 |
(snip)
```

Core ML is used (COREML = 1).

If you don't have Core ML model, you can make it by following steps in [README](https://github.com/ggml-org/whisper.cpp?tab=readme-ov-file#core-ml-support).
