### ISSUE TITLE
What is the different between "ggml-base.large.bin". and "ggml-base.large-v1.bin"?

### ISSUE THREAD

**Issue by realcarlos** [ggerganov/whisper.cpp#894]
and does it support using ANE on iOS? a little bit slow to transcribe on my iPhone 14 Pro Max.

**Comment by realcarlos** [comment]
and I wonder what is the difference between using ggml-small.bin and ggml-small.en.bin ,if user speaks English.

**Comment by albino1** [comment]
`large` is v2 and `large-v1` is v1.  See this issue about problems using the v2 model:

https://github.com/ggerganov/whisper.cpp/issues/675

**Comment by jensdraht1999** [comment]
@realcarlos Can we close this issue?
