### ISSUE TITLE
fix memory leak has introduced a segmentation fault in stream while using coreml

### ISSUE THREAD

**Issue by dev-mush** [ggerganov/whisper.cpp#904]
The changes introduced in this pr https://github.com/ggerganov/whisper.cpp/pull/899 are causing segmentation fault crashes when executing ./stream. 

I've inspected the code a little, and my safe bet is that the program is attempting to release possibily nil objects, I don't see any other big changes from the previous version that could justify the segfault... but am not touching c++/objc code since ages so might be wrong.

**Comment by multispecies-lab** [comment]
Same issue here...

**Comment by ggerganov** [comment]
Should be fixed now
