### ISSUE TITLE
talk-llama does not seem to support models in new quantization format

### ISSUE THREAD

**Issue by jmtatsch** [ggerganov/whisper.cpp#922]
```
./talk-llama -ml models/wizard-vicuna-13B.ggml.q5_1.bin
whisper_init_from_file_no_state: loading model from 'models/ggml-base.en.bin'
whisper_model_load: loading model
whisper_model_load: n_vocab       = 51864
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 512
whisper_model_load: n_audio_head  = 8
whisper_model_load: n_audio_layer = 6
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 512
whisper_model_load: n_text_head   = 8
whisper_model_load: n_text_layer  = 6
whisper_model_load: n_mels        = 80
whisper_model_load: ftype         = 1
whisper_model_load: type          = 2
whisper_model_load: mem required  =  310.00 MB (+    6.00 MB per decoder)
whisper_model_load: adding 1607 extra tokens
whisper_model_load: model ctx     =  140.60 MB
whisper_model_load: model size    =  140.54 MB
whisper_init_state: kv self size  =    5.25 MB
whisper_init_state: kv cross size =   17.58 MB
llama.cpp: loading model from models/wizard-vicuna-13B.ggml.q5_1.bin
error loading model: unknown (magic, version) combination: 67676a74, 00000002; is this really a GGML file?
llama_init_from_file: failed to load model

main: processing, 4 threads, lang = en, task = transcribe, timestamps = 0 ...

init: found 2 capture devices:
init:    - Capture device #0: 'MacBook Pro-Mikrofon'
init:    - Capture device #1: 'Microsoft Teams Audio'
init: attempt to open default capture device ...
init: obtained spec for input device (SDL Id = 2):
init:     - sample rate:       16000
init:     - format:            33056 (required: 33056)
init:     - channels:          1 (required: 1)
init:     - samples per frame: 1024
[1]    66006 segmentation fault  ./talk-llama -ml models/wizard-vicuna-13B.ggml.q5_1.bin
```

**Comment by ggerganov** [comment]
Should work now

**Comment by jmtatsch** [comment]
Did a clean checkout and it fails building:

```
make talk-llama
I whisper.cpp build info: 
I UNAME_S:  Darwin
I UNAME_P:  arm
I UNAME_M:  arm64
I CFLAGS:   -I.              -O3 -DNDEBUG -std=c11   -fPIC -pthread -DGGML_USE_ACCELERATE
I CXXFLAGS: -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -pthread
I LDFLAGS:   -framework Accelerate
I CC:       Apple clang version 12.0.5 (clang-1205.0.22.9)
I CXX:      Apple clang version 12.0.5 (clang-1205.0.22.9)

cc  -I.              -O3 -DNDEBUG -std=c11   -fPIC -pthread -DGGML_USE_ACCELERATE   -c ggml.c -o ggml.o
c++ -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -pthread -c whisper.cpp -o whisper.o
c++ -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -pthread examples/talk-llama/talk-llama.cpp examples/talk-llama/llama.cpp examples/common.cpp examples/common-ggml.cpp examples/common-sdl.cpp ggml.o whisper.o -o talk-llama `sdl2-config --cflags --libs`  -framework Accelerate
examples/talk-llama/llama.cpp:485:22: error: use of undeclared identifier 'GGML_TYPE_Q4_2'
                case GGML_TYPE_Q4_2:
                     ^
examples/talk-llama/llama.cpp:561:18: error: use of undeclared identifier 'GGML_TYPE_Q4_2'
            case GGML_TYPE_Q4_2:
                 ^
examples/talk-llama/llama.cpp:1888:56: error: use of undeclared identifier 'GGML_TYPE_Q4_2'
        case LLAMA_FTYPE_MOSTLY_Q4_2: quantized_type = GGML_TYPE_Q4_2; break;
                                                       ^
3 errors generated.
make: *** [talk-llama] Error 1
```

**Comment by ggerganov** [comment]
Try again, think it works now

**Comment by jmtatsch** [comment]
Works now. Thanks for the quick fix!

**Comment by reverse-2020** [comment]
i have met  the same problem ,which model in llama.cpp worked well , but when i use talk-llama, error happend -> error loading model: unknown (magic, version) combination: 67676a74, 00000003,  can u tell me how to fix it ? i have update both whisper.cpp&llama.cpp , by the way , the llama model is Chinese-LLaMA-Alpaca

**Comment by jasontitus** [comment]
I'm seeing 'unrecognized tensor type 14' when I try to load llama models (30B Q4_0 in this case) quantized with current code.  Works fine with the Q4_0 model quantized with the June 6th version of the code.  Current llama code seems to load and process the quantized model fine.

----
llama.cpp: loading model from ../llama.cpp/models/30B/ggml-model-q4_0.bin
error loading model: unrecognized tensor type 14

llama_init_from_file: failed to load model

----

**Comment by dereklll** [comment]
> I'm seeing 'unrecognized tensor type 14' when I try to load llama models (30B Q4_0 in this case) quantized with current code. Works fine with the Q4_0 model quantized with the June 6th version of the code. Current llama code seems to load and process the quantized model fine.
> 
> llama.cpp: loading model from ../llama.cpp/models/30B/ggml-model-q4_0.bin error loading model: unrecognized tensor type 14
> 
> llama_init_from_file: failed to load model

same problem.

**Comment by dereklll** [comment]
> > I'm seeing 'unrecognized tensor type 14' when I try to load llama models (30B Q4_0 in this case) quantized with current code. Works fine with the Q4_0 model quantized with the June 6th version of the code. Current llama code seems to load and process the quantized model fine.
> > llama.cpp: loading model from ../llama.cpp/models/30B/ggml-model-q4_0.bin error loading model: unrecognized tensor type 14
> > llama_init_from_file: failed to load model
> 
> same problem.

I have solved this problem.
![image](https://github.com/ggerganov/whisper.cpp/assets/42927959/10bfc5e3-8c36-4f2e-ace3-152c4f1491ff)
