### ISSUE TITLE
large-v1 model support in CoreML

### ISSUE THREAD

**Issue by abCods** [ggerganov/whisper.cpp#925]
Hi @ggerganov

First of all,  thank you for your amazing work with `Whisper.cpp`. I have been especially taking advantage of your work around the CoreML support for the Apple Silicon. It is truly a cost effective solution.

In my case, I have been using the multilingual model including the `large` and `large-v1`. Over the period of time the data suggests that `large-v1` is better off for the multilingual case as it offers better performance and it is less prone to the odd issue of repetitions in the transcriptions ( as the multilingual recordings are more prone to it. )

When it comes to the CoreML, the `models/download-coreml-model.sh` has the option of `large-v1` model.
[models=( "tiny.en" "tiny" "base.en" "base" "small.en" "small" "medium.en" "medium" "large-v1" "large" )](https://github.com/ggerganov/whisper.cpp/blob/a5defbc1b98bea0f070331ce1e8b62d947b0443d/models/download-coreml-model.sh#LL22C85-L22C93)

But the `models/convert-whisper-to-coreml.py` doesn't offer the further support on it.
[parser.add_argument("--model", type=str, help="model to convert (e.g. tiny, tiny.en, base, base.en, small, small.en, medium, medium.en, large)", required=True)
](https://github.com/ggerganov/whisper.cpp/blob/a5defbc1b98bea0f070331ce1e8b62d947b0443d/models/convert-whisper-to-coreml.py#L299)

Am I missing something here or is the `large-v1` isn't supported yet? If so, I would be happy to contribute here.

Thanks

**Comment by ggerganov** [comment]
Yes, please add `large-v1` support - I just missed that

**Comment by abCods** [comment]
#926

**Comment by eugenepyvovarov** [comment]
@abCods how fast does the large-v1 model compiles into cormel format for you? I have it running for hours, when I do force stop as suggested in other threads - I just get an error that it is not completed. hence can't compile it yet.

**Comment by abCods** [comment]
@eugenepyvovarov 

On an M2 mini machine, it takes about a couple of seconds for me.

It shouldn't even take minutes, let alone hours. I am sure there must must be an issue with dependency either missing or crashing.

**Comment by eugenepyvovarov** [comment]
@abCods it really takes seconds on base/small models, but as I go to bigger ones it takes more time - medium already going some time, waiting until it is done..

**Comment by abCods** [comment]
> @abCods it really takes seconds on base/small models, but as I go to bigger ones it takes more time - medium already going some time, waiting until it is done..

What are your machine's specs?

**Comment by abCods** [comment]
> > > @abCods it really takes seconds on base/small models, but as I go to bigger ones it takes more time - medium already going some time, waiting until it is done..
> > 
> > What are your machine's specs?
> 
> M1 Ultra / 128GB

I'll get my hands on one of these and share my experience.
