### ISSUE TITLE
download-ggml-model.sh - wget and realpath are not available on macOS by default

### ISSUE THREAD

**Issue by andypayne** [ggerganov/whisper.cpp#93]
The wget and realpath tools are not available on macOS by default, so models/download-ggml-model.sh does not run on macOS without installing wget and working around the absence of realpath. I have modified the script to work on both macOS and linux. I will submit a pull request.

**Comment by andypayne** [comment]
I've submitted a pull request:  https://github.com/ggerganov/whisper.cpp/pull/94

**Comment by ggerganov** [comment]
Thanks for the contribution!
