### ISSUE TITLE
System Crash on Fedora 38, UM690 (AMD Ryzen 9 6900HX) with -t >= 6 

### ISSUE THREAD

**Issue by ajstarks** [ggerganov/whisper.cpp#934]
Fedora Linux (6.2.15-300.fc38.x86_64), UM690 (AMD Ryzen 9 6900HX)

I can reliably cause a system crash to reboot by transcribing a 3 min audio clip using the default model (ggml-base.en.bin), with a thread count of 6. I've built with ClBlast. There are no issues if I use the default thread count of 4.

**Comment by tazz4843** [comment]
This sounds like more of a hardware issue, give prime95 a shot with >= 6 threads?
