### ISSUE TITLE
100x slowdown on Windows vs macOS

### ISSUE THREAD

**Issue by venkr** [ggerganov/whisper.cpp#936]
Hey - just wanted to check if I was doing this right, as I've tried `whisper.cpp` on an M2 Macbook Pro, and also on a Windows Surface 5 laptop - and I've found close to a 100x slowdown on the JFK sample.

Here are the traces:
Windows:
`./main.exe -f ..\..\..\samples\jfk.wav -m ..\..\..\models\ggml-base.en.bin`

whisper_print_timings:     load time =   555.54 ms
whisper_print_timings:     fallbacks =   0 p /   0 h
whisper_print_timings:      mel time =  1046.80 ms
whisper_print_timings:   sample time =   124.91 ms /    27 runs (    4.63 ms per run)
whisper_print_timings:   encode time = 35476.98 ms /     1 runs (35476.98 ms per run)
whisper_print_timings:   decode time =  2374.36 ms /    27 runs (   87.94 ms per run)
whisper_print_timings:    total time = 39730.49 ms

macOS:
`./main samples/jfk.wav -m models/ggml-base.en.bin`
whisper_print_timings:     load time =    94.64 ms
whisper_print_timings:     fallbacks =   0 p /   0 h
whisper_print_timings:      mel time =    51.58 ms
whisper_print_timings:   sample time =    11.33 ms /    27 runs (    0.42 ms per run)
whisper_print_timings:   encode time =    65.68 ms /     1 runs (   65.68 ms per run)
whisper_print_timings:   decode time =    71.34 ms /    27 runs (    2.64 ms per run)
whisper_print_timings:    total time =   402.46 ms

On Windows, I ran the following steps:
- `./models/download-ggml-model.sh base.en`
- `cmake -S . -B ./build`
- Open `build/whisper.cpp.sln` in Visual Studio 2022 and run `Build Solution`
- Run `./main.exe -f ..\..\..\samples\jfk.wav -m ..\..\..\models\ggml-base.en.bin`

Is there anything different I could do to get better performance on Windows?

**Comment by venkr** [comment]
Looks like there's some automatic throttling at play, it's 2x faster (only ~50x slower than macOS!) when plugged in:

whisper_print_timings:     load time =   416.59 ms
whisper_print_timings:     fallbacks =   0 p /   0 h
whisper_print_timings:      mel time =   821.72 ms
whisper_print_timings:   sample time =    59.23 ms /    27 runs (    2.19 ms per run)
whisper_print_timings:   encode time = 16046.74 ms /     1 runs (16046.74 ms per run)
whisper_print_timings:   decode time =   658.34 ms /    27 runs (   24.38 ms per run)
whisper_print_timings:    total time = 18098.11 ms

**Comment by nalbion** [comment]
The bottleneck seems to be `ggml_compute_forward_mul_mat_f16_f32()` for `GGML_TASK_COMPUTE` which frequently takes longer than 100ms to execute (particularly nodes #75, 159 and 243), but only the 1st time `ggml_graph_compute()` is called. The first time this is called it processes **268 nodes** and takes **over 3 seconds** to run on my laptop, but then I see it being called again with 66 nodes (200ms) and then 27 more times with 368 nodes, but each of those calls only takes about 10ms.

On my Dell laptop I get a total time of 4000 to 9000 ms for `jfk.wav` and `ggml-base.en.bin`
If I build with CUBLAS that comes down to 3000 to 5000 ms. 

Noob question - if I have an Nvidia GPU, are cuBLAS, CLBlast, OpenBLAS
