### ISSUE TITLE
Error occurs when running cmake of java binding

### ISSUE THREAD

**Issue by Epresin** [ggerganov/whisper.cpp#945]
When running the script given by java binding, there seems to be something wrong with cmake. I don’t understand c++ at all. The following is my error report. My cmake version is 3.26.4  ,Is there a way to solve it?

`Lenovo@Epresin MINGW64 ~/Desktop/test2
$ git clone https://github.com/ggerganov/whisper.cpp.git
Cloning into 'whisper.cpp'...
remote: Enumerating objects: 3695, done.
remote: Counting objects: 100% (1587/1587), done.
remote: Compressing objects: 100% (425/425), done.
remote: Total 3695 (delta 1313), reused 1246 (delta 1149), pack-reused 2108
Receiving objects: 100% (3695/3695), 6.63 MiB | 8.16 MiB/s, done.
Resolving deltas: 100% (2317/2317), done.

Lenovo@Epresin MINGW64 ~/Desktop/test2
$ cd whisper.cpp/bindings/java

Lenovo@Epresin MINGW64 ~/Desktop/test2/whisper.cpp/bindings/java (master)
$ mkdir build

Lenovo@Epresin MINGW64 ~/Desktop/test2/whisper.cpp/bindings/java (master)
$ pushd build
~/Desktop/test2/whisper.cpp/bindings/java/build ~/Desktop/test2/whisper.cpp/bindings/java

Lenovo@Epresin MINGW64 ~/Desktop/test2/whisper.cpp/bindings/java/build (master)
$ cmake ..
-- Building for: NMake Makefiles
CMake Error at CMakeLists.txt:3 (project):
  Running

   'nmake' '-?'

  failed with:

   系统找不到指定的文件。(Meaning: The system cannot find the file specified)

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
`

**Comment by Epresin** [comment]
I tried to specify the compiler path, and the related error disappeared, but there is still a problem

`C:\Users\Lenovo\Desktop\test2\whisper.cpp\bindings\java\build>cmake -D CMAKE_C_COMPILER=C:/MinGW/mingw64/bin/gcc -D CMAKE_CXX_COMPILER=C:/MinGW/mingw64/bin/g++ ..
-- Building for: NMake Makefiles
CMake Error at CMakeLists.txt:3 (project):
  Running

   'nmake' '-?'

  failed with:

   系统找不到指定的文件。


-- Configuring incomplete, errors occurred!`

**Comment by Epresin** [comment]
@nalbion

**Comment by nalbion** [comment]
In https://github.com/ggerganov/whisper.cpp/pull/944 I've removed the need for cmake in the java bindings
