### ISSUE TITLE
How to build the Java bindings and execute the Example code in readme with CoreML support 

### ISSUE THREAD

**Issue by RageshAntony** [ggerganov/whisper.cpp#963]

**Comment by Epresin** [comment]
I followed the instructions in the README, but encountered an error when running ./gradlew build. I would like to know if there will be a way in the future to directly set it as a dependency library using Maven or Gradle scripts? @nalbion

**Comment by nalbion** [comment]
Can you post the build error that you're getting @Epresin ? 

I would like to deploy the jar to Maven Central. For now, you can download `whispercpp.jar` from the [CI build](https://github.com/ggerganov/whisper.cpp/actions/runs/5106982961#artifacts)

It will attempt to load `darwin-x86-64/libwhisper.dynlib` from the classpath or one of:

- `jna.library.path` 
- `jna.platform.library`
- `~/Library/Frameworks`
- `/Library/Frameworks`
- `/System/Library/Frameworks`

**Comment by Epresin** [comment]
> Can you post the build error that you're getting @Epresin ?
> 
> I would like to deploy the jar to Maven Central. For now, you can download from the [CI build](https://github.com/ggerganov/whisper.cpp/actions/runs/5106982961#artifacts)`whispercpp.jar`
> 
> It will attempt to load from the classpath or one of:`darwin-x86-64/libwhisper.dynlib`
> 
> * `jna.library.path`
> * `jna.platform.library`
> * `~/Library/Frameworks`
> * `/Library/Frameworks`
> * `/System/Library/Frameworks`

This is my log,
https://paste.ubuntu.com/p/b76FCyNsgZ/

**Comment by nalbion** [comment]
@Epresin those logs look like you're trying to build on Windows. The windows build expects to find `whisper.dll` at `build\generated\resources\main\win32-x86-64`. After building the library I run the following from `bindings\java`:

```
copy /y ..\..\build\bin\Release\whisper.dll build\generated\resources\main\win32-x86-64\whisper.dll
```

**Comment by breandan** [comment]
I encountered a few errors trying to use whisper.cpp with CoreML support on `Mac OS X 13.3.1 aarch64` and JVM `17.0.1`.

* `permission denied: ./gradlew`, this can be fixed with `chmod +x gradlew`
*  `Execution failed for task ':javadoc'`, this can be fixed by adding `enabled = false` to the `javadoc { ... }` section of the `build.gradle` file.
* `Native library (darwin-aarch64/libwhisper.dylib) not found in resource path`, not sure how to get past this error.

I saw there was a Makefile instruction for building the `libwhisper.so` file, but I'm not sure how to build `libwhisper.dylib`.

**Comment by nalbion** [comment]
`./gradlew javadoc` works on Windows and Ubuntu - what error do you get @breandan ?

To build `libwhisper.dylib` you would need to run:

```bash
cd build 
cmake -DBUILD_SHARED_LIBS=1 -DWHISPER_COREML=1 ..
make -j
```

**Comment by RageshAntony** [comment]
@nalbion 

I get this error when following your instruction above

rageshantonyd@gnz-pc build % make -j

[ 50%] Building CXX object CMakeFiles/whisper_java.dir/src/main/cpp/whisper_java.cpp.o

In file included from /Users/rageshantonyd/Documents/whisper/whisper.cpp/bindings/java/src/main/cpp/whisper_java.cpp:2:
/Users/rageshantonyd/Documents/whisper/whisper.cpp/bindings/java/src/main/cpp/whisper_java.h:8:1: warning: empty struct has size 0 in C, size 1 in C++ [-Wextern-c-compat]

struct whisper_java_params {
^
/Users/rageshantonyd/Documents/whisper/whisper.cpp/bindings/java/src/main/cpp/whisper_java.cpp:7:1: error: declaration of anonymous struct must be a definition

struct void whisper_java_default_params(enum whisper_sampling_strategy strategy) {
^
/Users/rageshantonyd/Documents/whisper/whisper.cpp/bindings/java/src/main/cpp/whisper_java.cpp:33:2: error: expected unqualified-id
}

**Comment by nalbion** [comment]
`src/main/cpp` no longer exists in the master branch. Initially I started implementing using JNI, but switched to JNA. 

Pull the latest version from `master`, use `cmake` & `make` to compile the whisper shared lib, and then use `./gradlew publishToMavenLocal` to build the java bindings

**Comment by RageshAntony** [comment]
@nalbion 

Thanks. Executed the sample program with Charm

I able to run after I made some changes in the sample java code in the Readme because it seems like older version because the params shown as incompatible 

please check the sample code for java bindings

**Comment by RageshAntony** [comment]
@nalbion 

And, if I use the generated **whispercpp-1.4.0.jar** in a new standalone project in a another mac system, then where I need to put the libwhisper.dylib ?

Just in project root folder in enough ? Or it can be packed along with the Jar ?

**Comment by RageshAntony** [comment]
@nalbion 

I am getting this error when using the whispercpp-1.4.0.jar in another project 

java.lang.NoClassDefFoundError: com/sun/jna/Library

**Comment by nalbion** [comment]
The shared lib needs to be in `jna.library.path` - see notes to Esprin above. I'll update the README.

If you're using a GPU, you may need to copy the cublas, cublasLt and cudart (or as appropriate) libraries into java.library.path
