### ISSUE TITLE
Porting weight compressed whisper.tflite (size ~40MB) on https://github.com/ggerganov/whisper.cpp

### ISSUE THREAD

**Issue by nyadla-sys** [ggerganov/whisper.cpp#98]
@ggerganov 
Could you please use the [whisper.tflite](https://github.com/usefulsensors/openai-whisper/blob/main/models/whisper.tflite)(total model size ~40MB) to run on https://github.com/ggerganov/whisper.cpp

This will help to use lot less memory than original pytorch model

**Comment by ggerganov** [comment]
For this to work, we need to have 8-bit support in `ggml` which is currently not high-priority task.
Closing this issue in favor of similar request #104
